import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { inspectEngineInput, type EngineInputPreflightReport } from "./engineInputPreflight";
import { parseEngineScenarioSnapshot, type EngineScenarioSnapshotV1 } from "../scenarioSnapshot";
import { compareCompactPlanning, compareOperationalMetrics } from "./replayOperationalMetrics";
export type ReplayEngine = "v3" | "v4" | "orc"; export type ReplayEngineSelection = ReplayEngine | "all";
export interface ReplayOptions { engine?: ReplayEngineSelection; repeat?: number; timeLimitMs?: number; output?: string | null; failFast?: boolean; preflightOnly?: boolean; allowPreflightErrors?: boolean; includeCompactPlanning?: boolean; compactPlanningOutput?: string | null; workerEnv?: Record<string,string|undefined> }
export interface ReplayExecutionSummary { engine: ReplayEngine; repetition: number; executionStatus: "completed" | "timeout" | "error" | "preflight_blocked"; runtimeMs: number; errorCode?: string | null; errorMessage?: string | null; status?: string | null; plannedTasks?: number | null; unplannedTasks?: number | null; hardFeasible?: boolean | null; complete?: boolean | null; outputHash?: string | null; usedEngine?: string | null; fallbackReason?: string | null; falseGates?: string[]; makespan?: number | null; talentIdle?: number | null; visibleMainFlowIdle?: number | null; largestMainFlowGap?: number | null; workerStartupMs?: number; engineExecutionMs?: number; totalRuntimeMs?: number; operationalMetrics?: any; replayWarnings?: string[]; compactPlanningIncluded?: boolean; compactPlanningPath?: string | null; operationalMetricsMs?: number }
export interface ReplayReport { snapshot: Pick<EngineScenarioSnapshotV1, "exportVersion" | "planId" | "inputHash" | "counts">; preflight: EngineInputPreflightReport; options: { engines: ReplayEngine[]; repeat: number; timeLimitMs: number | null; failFast: boolean }; executions: ReplayExecutionSummary[]; deterministic: boolean | null; completed: boolean; timedOutExecutions: number; failedExecutions: number; comparisonVersion?: "REPLAY_OPERATIONAL_COMPARISON_V1"; comparisons?: any[] }
export const enginesFor = (selection: ReplayEngineSelection = "all"): ReplayEngine[] => selection === "all" ? ["v3", "v4", "orc"] : [selection];
function calcDeterministic(executions: ReplayExecutionSummary[]): boolean | null { let sawPair=false; for (const engine of ["v3","v4","orc"] as ReplayEngine[]) { const hashes = executions.filter(e=>e.engine===engine && e.executionStatus==="completed" && e.outputHash).map(e=>e.outputHash); if (hashes.length >= 2) { sawPair=true; if (new Set(hashes).size > 1) return false; } } return sawPair ? true : null; }
async function runChild(snapshotPath: string, engine: ReplayEngine, repetition: number, timeLimitMs: number | null, env?: Record<string,string|undefined>): Promise<ReplayExecutionSummary & { compactPlanning?: any[] }> {
  const started = performance.now(); const worker = fileURLToPath(new URL("./replayEngineWorker.ts", import.meta.url));
  return await new Promise((resolve) => { const child = spawn(process.execPath, ["--import", "tsx", worker, snapshotPath, engine, String(repetition)], { stdio: ["ignore","pipe","pipe"], env: { ...process.env, ...env } }); let out="", err="", done=false; const finish=(summary: ReplayExecutionSummary)=>{ if(done) return; done=true; clearTimeout(timer); resolve(summary); }; child.stdout.on("data", d => { out += d; if (out.length > 1_000_000) out = out.slice(-1_000_000); }); child.stderr.on("data", d => { err += d; if (err.length > 20_000) err = err.slice(-20_000); }); const timer = timeLimitMs && timeLimitMs > 0 ? setTimeout(() => { child.kill("SIGTERM"); setTimeout(()=> { if (!child.killed) child.kill("SIGKILL"); }, 500).unref(); finish({ engine, repetition, executionStatus: "timeout", runtimeMs: Math.round(performance.now()-started), errorCode: "TIMEOUT", errorMessage: `Timed out after ${timeLimitMs} ms`, status: null, plannedTasks: null, unplannedTasks: null, hardFeasible: null, complete: null, outputHash: null }); }, timeLimitMs) : undefined as any; child.on("exit", code => { if (done) return; const runtimeMs = Math.round(performance.now()-started); if (code === 0) { try { const parsed = JSON.parse(out); finish({ ...parsed.summary, runtimeMs, workerStartupMs: parsed.workerStartupMs, engineExecutionMs: parsed.engineExecutionMs, totalRuntimeMs: parsed.totalRuntimeMs, compactPlanning: parsed.compact?.compactPlanning }); } catch (e) { finish({ engine, repetition, executionStatus: "error", runtimeMs, errorCode: "INVALID_WORKER_OUTPUT", errorMessage: e instanceof Error ? e.message : String(e) }); } } else finish({ engine, repetition, executionStatus: "error", runtimeMs, errorCode: `WORKER_EXIT_${code}`, errorMessage: err.trim() || `Worker exited with code ${code}` }); }); });
}
export async function replayEngineScenario(snapshot: EngineScenarioSnapshotV1, options: ReplayOptions = {}, snapshotPath?: string): Promise<ReplayReport> { const repeat = Math.max(1, Math.floor(options.repeat ?? 1)); const engines = enginesFor(options.engine); const preflight = inspectEngineInput(snapshot.engineInput); const executions: ReplayExecutionSummary[] = []; const failFast = !!options.failFast; const timeLimitMs = Number.isFinite(Number(options.timeLimitMs)) ? Number(options.timeLimitMs) : null; const snap = { exportVersion: snapshot.exportVersion, planId: snapshot.planId, inputHash: snapshot.inputHash, counts: snapshot.counts };
  if (!preflight.valid && !options.allowPreflightErrors) { for (const engine of engines) for (let r=1;r<=repeat;r++) executions.push({ engine, repetition: r, executionStatus: "preflight_blocked", runtimeMs: 0, errorCode: "PREFLIGHT_ERRORS", errorMessage: "Preflight errors block replay by default." }); return { snapshot: snap, preflight, options: { engines, repeat, timeLimitMs, failFast }, executions, deterministic: null, completed: false, timedOutExecutions: 0, failedExecutions: executions.length }; }
  if (options.preflightOnly) return { snapshot: snap, preflight, options: { engines, repeat, timeLimitMs, failFast }, executions, deterministic: null, completed: true, timedOutExecutions: 0, failedExecutions: 0 };
  let path = snapshotPath; if (!path) { const dir = mkdtempSync(join(tmpdir(), "engine-replay-")); path = join(dir, "snapshot.json"); writeFileSync(path, JSON.stringify(snapshot)); }
  let aborted = false;
  for (const engine of engines) { if (aborted) break; for (let r=1;r<=repeat;r++) { console.error(`[${engine} ${r}/${repeat}] started`); const s = await runChild(path, engine, r, timeLimitMs, options.workerEnv); executions.push(s); console.error(`[${engine} ${r}/${repeat}] ${s.executionStatus}${s.executionStatus === "timeout" && timeLimitMs ? ` after ${timeLimitMs} ms` : ` in ${s.runtimeMs} ms`}`); if (failFast && s.executionStatus !== "completed") { aborted = true; break; } } }
  const compactByRun: Record<string, any[]> = {};
  for (const e of executions as any[]) { if (Array.isArray(e.compactPlanning)) { compactByRun[`${e.engine}:${e.repetition}`] = e.compactPlanning; if (options.includeCompactPlanning) e.compactPlanningIncluded = true; else delete e.compactPlanning; } }
  if (options.compactPlanningOutput) writeFileSync(options.compactPlanningOutput, JSON.stringify({ version: "REPLAY_COMPACT_PLANNING_V1", planningByExecution: compactByRun }, null, 2)+"\n");
  for (const e of executions) { e.compactPlanningPath = options.compactPlanningOutput ?? null; if (!options.includeCompactPlanning) e.compactPlanningIncluded = false; }
  const firstCompleted=(engine:ReplayEngine)=>executions.find(e=>e.engine===engine&&e.executionStatus==="completed"&&e.repetition===1) as any;
  const comparisons:any[]=[];
  for (const [baseline,candidate] of [["v3","v4"],["v4","orc"],["v3","orc"]] as any[]) { const b=firstCompleted(baseline), c=firstCompleted(candidate); if(b&&c) comparisons.push({ baselineEngine: baseline, candidateEngine: candidate, metrics: compareOperationalMetrics(b.operationalMetrics,c.operationalMetrics) }); }
  const v4=firstCompleted("v4"), orc=firstCompleted("orc");
  if (v4&&orc&&Array.isArray(compactByRun["v4:1"])&&Array.isArray(compactByRun["orc:1"])) { const eq=compareCompactPlanning(compactByRun["v4:1"], compactByRun["orc:1"]); comparisons.push({ baselineEngine:"v4", candidateEngine:"orc", planningEquivalence: eq }); if (String(orc.usedEngine)==="v4_fallback" && !eq.equivalentPlanning) orc.replayWarnings=[...(orc.replayWarnings??[]),"ORC_FALLBACK_OUTPUT_NOT_EQUIVALENT_TO_V4"]; }
  const timedOutExecutions = executions.filter(e=>e.executionStatus==="timeout").length, failedExecutions = executions.filter(e=>e.executionStatus==="error"||e.executionStatus==="preflight_blocked").length; return { snapshot: snap, preflight, options: { engines, repeat, timeLimitMs, failFast }, executions, deterministic: calcDeterministic(executions), completed: timedOutExecutions===0 && failedExecutions===0, timedOutExecutions, failedExecutions, comparisonVersion: "REPLAY_OPERATIONAL_COMPARISON_V1", comparisons } }
export function parseReplayArgs(argv: string[]): { file: string; options: ReplayOptions } { const args=[...argv]; const file=args.shift(); if(!file) throw new Error("Usage: replayEngineScenario <snapshot.json> [--engine v3|v4|orc|all] [--repeat N] [--output report.json] [--time-limit-ms N] [--preflight-only] [--fail-fast] [--allow-preflight-errors]"); const options: ReplayOptions={engine:"all", repeat:1}; for(let i=0;i<args.length;i++){ const a=args[i], v=args[i+1]; if(a==="--engine"){options.engine=v as ReplayEngineSelection;i++;} else if(a==="--repeat"){options.repeat=Number(v);i++;} else if(a==="--output"){options.output=v;i++;} else if(a==="--time-limit-ms"){options.timeLimitMs=Number(v);i++;} else if(a==="--preflight-only") options.preflightOnly=true; else if(a==="--fail-fast") options.failFast=true; else if(a==="--allow-preflight-errors") options.allowPreflightErrors=true; else if(a==="--include-compact-planning") options.includeCompactPlanning=true; else if(a==="--compact-planning-output"){options.compactPlanningOutput=v;i++;} else throw new Error(`Unknown replay option: ${a}`); } if(!["v3","v4","orc","all"].includes(String(options.engine))) throw new Error(`Invalid --engine: ${options.engine}`); return {file, options}; }
if (import.meta.url === `file://${process.argv[1]}`) { try { const {file, options}=parseReplayArgs(process.argv.slice(2)); const snapshot=parseEngineScenarioSnapshot(readFileSync(file)); const pre=inspectEngineInput(snapshot.engineInput); console.error(`[preflight] ${pre.valid ? "valid" : "invalid"} — ${pre.facts.tasks} tasks, ${pre.facts.contestants} contestants, ${pre.facts.spaces} spaces`); const report=await replayEngineScenario(snapshot, options, file); const json=JSON.stringify(report,null,2); if(options.output) writeFileSync(options.output, `${json}\n`); else console.log(json); if(report.deterministic===false) process.exitCode=2; } catch(e) { console.error(e instanceof Error ? e.message : String(e)); process.exitCode=1; } }
