import { createHash } from "node:crypto";
import type { EngineInput } from "../types";

export type OperationalKind = "productive" | "contestant_meal" | "synthetic" | "unknown";
export interface CompactPlanningTask { taskId:number; startPlanned:string|null; endPlanned:string|null; spaceId:number|null; zoneId:number|null; contestantId:number|null; templateId:number|null; templateName?:string|null; assignedResourceIds:number[]; operationalKind:OperationalKind }
export interface ReplayOperationalMetricsV1 { plannedTaskCount:number; unplannedTaskCount:number; productiveTaskCount:number; contestantMealTaskCount:number; syntheticTaskCount:number; earliestStartMinute:number|null; latestEndMinute:number|null; makespanMinutes:number|null; totalContestantIdleMinutes:number; maximumContestantIdleMinutes:number; contestantsWithIdle:number; totalContestantSpanMinutes:number; maximumContestantSpanMinutes:number; contestantSummaries:Array<{contestantId:number; firstStart:number; lastEnd:number; spanMinutes:number; idleMinutes:number; taskCount:number; largestGapMinutes:number}>; mainZoneProductiveTaskCount:number; mainZoneProductiveMinutes:number; mainZoneFirstStartMinute:number|null; mainZoneLastEndMinute:number|null; mainZoneVisibleIdleMinutes:number; mainZoneLargestGapMinutes:number; mainZoneGapCount:number; mainZoneGapIntervals:Array<{start:number; end:number; durationMinutes:number; previousTaskIds:number[]; nextTaskIds:number[]}>; templateChangesByZoneId:Record<string,{changes:number; limit:number|null; excess:number}>; totalTemplateChanges:number; zonesExceedingTemplateChangeLimit:string[]; hardOverlapCount:number; contestantOverlapCount:number; spaceOverlapCount:number; resourceOverlapCount:number; dependencyViolationCount:number; availabilityViolationCount:number; protectedTaskMutationCount:number; scheduledOutsidePlanWindowCount:number }
export interface ReplayOperationalEvaluation { operationalMetrics:ReplayOperationalMetricsV1; compactPlanning:CompactPlanningTask[]; replayWarnings:string[]; operationalMetricsMs:number }
export const toOptionalNumber = (v:unknown): number|null => { if (v == null || v === "") return null; if (typeof v === "number") return Number.isFinite(v) ? v : null; if (typeof v === "string") { const s=v.trim(); if (!s) return null; const n=Number(s); return Number.isFinite(n) ? n : null; } return null; };
export function parseHHMMToMinutes(v:unknown): number|null { if (typeof v !== "string") return null; const m=/^(\d{2}):(\d{2})$/.exec(v.trim()); if(!m) return null; const h=Number(m[1]), min=Number(m[2]); if(!Number.isInteger(h)||!Number.isInteger(min)||h<0||h>23||min<0||min>59) return null; return h*60+min; }
const n=(v:unknown):number|null=>{ const x=Number(v); return Number.isFinite(x)?x:null; };
const arr=(v:unknown):any[]=>Array.isArray(v)?v:[];
const idSet=(a:number[])=>[...new Set(a.filter(Number.isFinite))].sort((x,y)=>x-y);
function kind(input:EngineInput,t:any):OperationalKind { const role=String(t?.operationalRole??""); const name=String(t?.templateName??"").toLowerCase(); if(role.includes("placeholder") || role.includes("transport") || t?.breakKind === "space_meal" || t?.contestantId == null && role.includes("meal")) return "synthetic"; if(role === "meal_break_placeholder" && t?.contestantId != null) return "contestant_meal"; if(t?.breakKind === "itinerant_meal" || (input.mealTaskTemplateId != null && Number(t?.templateId)===Number(input.mealTaskTemplateId)) || (input.mealTaskTemplateName && name===input.mealTaskTemplateName.toLowerCase())) return t?.contestantId != null ? "contestant_meal" : "synthetic"; return "productive"; }
export function normalizeReplayPlanning(input:EngineInput, output:any): { compactPlanning:CompactPlanningTask[]; unplannedTaskIds:number[]; replayWarnings:string[] } { const byId=new Map(input.tasks.map(t=>[Number(t.id),t])); const planned=arr(output?.plannedTasks ?? output?.schedule); const warnings:string[]=[]; const compactPlanning=planned.map((p:any) => { const taskId=Number(p.taskId ?? p.id); const base=byId.get(taskId); if(!base) warnings.push(`MISSING_INPUT_TASK:${taskId}`); const spaceId=n(p.spaceId ?? p.assignedSpace ?? base?.spaceId); const zoneId=n(p.zoneId ?? (spaceId!=null ? (input.zoneIdBySpaceId as any)?.[spaceId] : null) ?? base?.zoneId); const c:CompactPlanningTask={ taskId, startPlanned:p.startPlanned ?? p.start ?? base?.startPlanned ?? null, endPlanned:p.endPlanned ?? p.end ?? base?.endPlanned ?? null, spaceId, zoneId, contestantId:n(p.contestantId ?? base?.contestantId), templateId:n(p.templateId ?? base?.templateId), templateName:p.templateName ?? base?.templateName ?? null, assignedResourceIds:idSet(arr(p.assignedResourceIds ?? p.assignedResources ?? base?.assignedResourceIds).map(Number)), operationalKind: kind(input, {...base,...p}) }; if(c.startPlanned==null||c.endPlanned==null) warnings.push(`MISSING_TIME:${taskId}`); return c; }).filter(t=>Number.isFinite(t.taskId)); const unplannedTaskIds=arr(output?.unplanned).map((u:any)=>Number(u.taskId ?? u.id)).filter(Number.isFinite); return {compactPlanning, unplannedTaskIds, replayWarnings:warnings}; }
const overlap=(a:any,b:any)=>a.start < b.end && b.start < a.end;
const intervals=(tasks:CompactPlanningTask[])=>tasks.map(t=>({task:t,start:parseHHMMToMinutes(t.startPlanned),end:parseHHMMToMinutes(t.endPlanned)})).filter((x):x is any=>x.start!=null&&x.end!=null&&x.end>=x.start);
function countOverlaps(rows:any[], key:(t:CompactPlanningTask)=>number|null, capacity=1){ let c=0; const groups=new Map<number,any[]>(); for(const r of rows){ const k=key(r.task); if(k!=null) groups.set(k,[...(groups.get(k)||[]),r]); } for(const g of groups.values()) for(let i=0;i<g.length;i++) for(let j=i+1;j<g.length;j++) if(overlap(g[i],g[j])) c++; return c; }
export function evaluateReplayOperationalMetrics(input:EngineInput, output:any): ReplayOperationalEvaluation { const started=performance.now(); const {compactPlanning,unplannedTaskIds,replayWarnings}=normalizeReplayPlanning(input,output); const rows=intervals(compactPlanning); const starts=rows.map(r=>r.start), ends=rows.map(r=>r.end); const earliestStartMinute=starts.length?Math.min(...starts):null, latestEndMinute=ends.length?Math.max(...ends):null; const prod=compactPlanning.filter(t=>t.operationalKind==="productive"), meals=compactPlanning.filter(t=>t.operationalKind==="contestant_meal"), synth=compactPlanning.filter(t=>t.operationalKind==="synthetic");
 const contestantSummaries:any[]=[]; for(const cid of idSet(compactPlanning.map(t=>t.contestantId as number))){ const cr=intervals(compactPlanning.filter(t=>t.contestantId===cid && t.operationalKind!=="synthetic")).sort((a,b)=>a.start-b.start||a.end-b.end); if(!cr.length) continue; let idle=0, largest=0; for(let i=1;i<cr.length;i++){ const gap=Math.max(0,cr[i].start-cr[i-1].end); idle+=gap; largest=Math.max(largest,gap); } const first=cr[0].start,last=Math.max(...cr.map(r=>r.end)); contestantSummaries.push({contestantId:cid, firstStart:first, lastEnd:last, spanMinutes:last-first, idleMinutes:idle, taskCount:cr.length, largestGapMinutes:largest}); }
 const mainZone=Number(input.optimizerMainZoneId); const mainSpaceIds=new Set(arr((input.spaceIdsByZoneId as any)?.[mainZone]).map(Number)); const mainRows=intervals(prod.filter(t=>t.zoneId===mainZone || (t.spaceId!=null && mainSpaceIds.has(t.spaceId)))).sort((a,b)=>a.start-b.start||a.end-b.end); const blocks:any[]=[]; for(const r of mainRows){ if(!blocks.length||r.start>blocks[blocks.length-1].end) blocks.push({start:r.start,end:r.end,taskIds:[r.task.taskId]}); else { const b=blocks[blocks.length-1]; b.end=Math.max(b.end,r.end); b.taskIds.push(r.task.taskId); } } const gaps:any[]=[]; for(let i=1;i<blocks.length;i++) if(blocks[i].start>blocks[i-1].end) gaps.push({start:blocks[i-1].end,end:blocks[i].start,durationMinutes:blocks[i].start-blocks[i-1].end,previousTaskIds:blocks[i-1].taskIds.slice(0,5),nextTaskIds:blocks[i].taskIds.slice(0,5)});
 const templateChangesByZoneId:Record<string,any>={}; for(const zid of idSet(prod.map(t=>t.zoneId as number))){ const zr=intervals(prod.filter(t=>t.zoneId===zid)).sort((a,b)=>a.start-b.start||a.end-b.end); let changes=0, prev:any=undefined; for(const r of zr){ const cur=r.task.templateId ?? r.task.templateName ?? null; if(prev!==undefined && cur!==prev) changes++; prev=cur; } const limit=toOptionalNumber((input.maxTemplateChangesByZoneId as any)?.[zid]); templateChangesByZoneId[String(zid)]={changes,limit,excess:limit==null?0:Math.max(0,changes-limit)}; }
 const contestantOverlapCount=countOverlaps(rows.filter((r:any)=>r.task.operationalKind!=="synthetic"),t=>t.contestantId); const spaceOverlapCount=countOverlaps(rows.filter((r:any)=>r.task.operationalKind==="productive"),t=>t.spaceId); let resourceOverlapCount=0; const resGroups=new Map<number,any[]>(); for(const r of rows) for(const rid of r.task.assignedResourceIds) resGroups.set(rid,[...(resGroups.get(rid)||[]),r]); for(const g of resGroups.values()) for(let i=0;i<g.length;i++) for(let j=i+1;j<g.length;j++) if(overlap(g[i],g[j])) resourceOverlapCount++;
 const byTask=new Map(rows.map((r:any)=>[r.task.taskId,r])); let dependencyViolationCount=0, availabilityViolationCount=0, protectedTaskMutationCount=0, scheduledOutsidePlanWindowCount=0; for(const r of rows){ const base=input.tasks.find(t=>Number(t.id)===r.task.taskId) as any; for(const dep of arr(base?.dependsOnTaskIds).concat(base?.dependsOnTaskId!=null?[base.dependsOnTaskId]:[])){ const dr=byTask.get(Number(dep)) as any; if(dr && dr.end>r.start) dependencyViolationCount++; } const av=r.task.contestantId!=null ? (input.contestantAvailabilityById as any)?.[r.task.contestantId] : null; const as=parseHHMMToMinutes(av?.start), ae=parseHHMMToMinutes(av?.end); if((as!=null&&r.start<as)||(ae!=null&&r.end>ae)) availabilityViolationCount++; const ws=parseHHMMToMinutes(input.workDay?.start), we=parseHHMMToMinutes(input.workDay?.end); if((ws!=null&&r.start<ws)||(we!=null&&r.end>we)) scheduledOutsidePlanWindowCount++; if(base && (base.status==="in_progress"||base.status==="done"||base.seedSource==="protected_existing_planning") && ((base.startPlanned&&base.startPlanned!==r.task.startPlanned)||(base.endPlanned&&base.endPlanned!==r.task.endPlanned)||(base.spaceId!=null&&Number(base.spaceId)!==r.task.spaceId))) protectedTaskMutationCount++; }
 const totalTemplateChanges=Object.values(templateChangesByZoneId).reduce((s:any,z:any)=>s+z.changes,0); const metrics:ReplayOperationalMetricsV1={ plannedTaskCount:compactPlanning.length, unplannedTaskCount:unplannedTaskIds.length, productiveTaskCount:prod.length, contestantMealTaskCount:meals.length, syntheticTaskCount:synth.length, earliestStartMinute, latestEndMinute, makespanMinutes:earliestStartMinute==null||latestEndMinute==null?null:latestEndMinute-earliestStartMinute, totalContestantIdleMinutes:contestantSummaries.reduce((s,x)=>s+x.idleMinutes,0), maximumContestantIdleMinutes:Math.max(0,...contestantSummaries.map(x=>x.idleMinutes)), contestantsWithIdle:contestantSummaries.filter(x=>x.idleMinutes>0).length, totalContestantSpanMinutes:contestantSummaries.reduce((s,x)=>s+x.spanMinutes,0), maximumContestantSpanMinutes:Math.max(0,...contestantSummaries.map(x=>x.spanMinutes)), contestantSummaries, mainZoneProductiveTaskCount:mainRows.length, mainZoneProductiveMinutes:blocks.reduce((s,b)=>s+b.end-b.start,0), mainZoneFirstStartMinute:blocks.length?blocks[0].start:null, mainZoneLastEndMinute:blocks.length?blocks[blocks.length-1].end:null, mainZoneVisibleIdleMinutes:gaps.reduce((s,g)=>s+g.durationMinutes,0), mainZoneLargestGapMinutes:Math.max(0,...gaps.map(g=>g.durationMinutes)), mainZoneGapCount:gaps.length, mainZoneGapIntervals:gaps, templateChangesByZoneId, totalTemplateChanges, zonesExceedingTemplateChangeLimit:Object.entries(templateChangesByZoneId).filter(([,z]:any)=>z.excess>0).map(([z])=>z), hardOverlapCount:contestantOverlapCount+spaceOverlapCount+resourceOverlapCount, contestantOverlapCount, spaceOverlapCount, resourceOverlapCount, dependencyViolationCount, availabilityViolationCount, protectedTaskMutationCount, scheduledOutsidePlanWindowCount };
 return { operationalMetrics:metrics, compactPlanning, replayWarnings, operationalMetricsMs:Math.round(performance.now()-started) }; }
export const compactPlanningHash=(p:CompactPlanningTask[])=>createHash("sha256").update(JSON.stringify(p.map(t=>({taskId:t.taskId,startPlanned:t.startPlanned,endPlanned:t.endPlanned,spaceId:t.spaceId,zoneId:t.zoneId,contestantId:t.contestantId,templateId:t.templateId,assignedResourceIds:t.assignedResourceIds,operationalKind:t.operationalKind})).sort((a,b)=>a.taskId-b.taskId))).digest("hex");
export function compareCompactPlanning(a:CompactPlanningTask[],b:CompactPlanningTask[]){ const bm=new Map(b.map(t=>[t.taskId,t])); const changed:number[]=[]; let timingChangedTaskCount=0, assignmentChangedTaskCount=0; for(const x of a){ const y=bm.get(x.taskId); if(!y){changed.push(x.taskId); continue;} const timing=x.startPlanned!==y.startPlanned||x.endPlanned!==y.endPlanned; const assign=x.spaceId!==y.spaceId||JSON.stringify(x.assignedResourceIds)!==JSON.stringify(y.assignedResourceIds); if(timing||assign) changed.push(x.taskId); if(timing) timingChangedTaskCount++; if(assign) assignmentChangedTaskCount++; } for(const y of b) if(!a.some(x=>x.taskId===y.taskId)) changed.push(y.taskId); return { equivalentPlanning:changed.length===0, changedTaskCount:idSet(changed).length, changedTaskIds:idSet(changed).slice(0,50), timingChangedTaskCount, assignmentChangedTaskCount, metadataOnlyDifferent: changed.length===0 && compactPlanningHash(a)===compactPlanningHash(b) }; }
export type Direction="lower_is_better"|"higher_is_better";
const dirs:Record<string,Direction>={plannedTaskCount:"higher_is_better", unplannedTaskCount:"lower_is_better"};
export function compareOperationalMetrics(b:any,c:any){ const keys=["makespanMinutes","totalContestantIdleMinutes","maximumContestantIdleMinutes","totalContestantSpanMinutes","mainZoneVisibleIdleMinutes","mainZoneLargestGapMinutes","mainZoneGapCount","totalTemplateChanges","hardOverlapCount","dependencyViolationCount","availabilityViolationCount","plannedTaskCount","unplannedTaskCount"]; const out:any={}; for(const k of keys){ const direction=dirs[k]??"lower_is_better"; const bv=toOptionalNumber(b?.[k]), cv=toOptionalNumber(c?.[k]); const delta=bv==null||cv==null?null:cv-bv; let assessment:any="unavailable"; if(delta===0) assessment="equal"; else if(delta!=null) assessment=(direction==="lower_is_better" ? delta<0 : delta>0) ? "improved" : "worsened"; out[k]={baselineValue:bv,candidateValue:cv,delta,direction,assessment}; } return out; }
