import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import type { EngineInput, EngineOutput } from "../types";
import { generatePlanV3 } from "../v3";
import { generatePlanV4 } from "../v4";
import { runORCActivePlanner } from "../orc/active/orcActivePlanner";
import { canonicalizeForEngineScenario, cloneEngineScenarioValue, parseEngineScenarioSnapshot, type EngineScenarioSnapshotV1 } from "../scenarioSnapshot";
export type ReplayEngine = "v3" | "v4" | "orc"; export type ReplayEngineSelection = ReplayEngine | "all";
export interface ReplayOptions { engine?: ReplayEngineSelection; repeat?: number; timeLimitMs?: number; output?: string | null }
export interface ReplayExecutionSummary { engine: ReplayEngine; runtimeMs: number; status: string; plannedTasks: number; unplannedTasks: number; hardFeasible: boolean | null; complete: boolean | null; outputHash: string; usedEngine?: string | null; fallbackReason?: string | null; falseGates?: string[]; makespan?: number | null; talentIdle?: number | null; visibleMainFlowIdle?: number | null; largestMainFlowGap?: number | null }
export interface ReplayReport { snapshot: Pick<EngineScenarioSnapshotV1, "exportVersion" | "planId" | "inputHash" | "counts">; executions: ReplayExecutionSummary[]; deterministic: boolean }
function hashOutput(value: unknown): string { return createHash("sha256").update(JSON.stringify(canonicalizeForEngineScenario(value))).digest("hex"); }
const enginesFor = (selection: ReplayEngineSelection = "all"): ReplayEngine[] => selection === "all" ? ["v3", "v4", "orc"] : [selection];
function asArray(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function num(value: unknown): number | null { const n = Number(value); return Number.isFinite(n) ? n : null; }
function compactOutput(engine: ReplayEngine, result: any) { const output: EngineOutput = engine === "v4" || engine === "orc" ? result.output : result; const diagnostics = engine === "v4" || engine === "orc" ? result.diagnostics : output.v3Meta ?? {}; const gates = diagnostics?.gates && typeof diagnostics.gates === "object" ? Object.entries(diagnostics.gates).filter(([, v]) => v === false).map(([k]) => k) : []; return { output: { feasible: output?.feasible ?? null, complete: output?.complete ?? null, plannedTasks: asArray(output?.plannedTasks).map((p: any) => ({ taskId: p.taskId, startPlanned: p.startPlanned, endPlanned: p.endPlanned, assignedResources: p.assignedResources ?? [] })), unplanned: asArray((output as any)?.unplanned).map((u: any) => ({ taskId: u.taskId ?? u.id, reason: u.reason ?? null })) }, diagnostics: { status: diagnostics?.status ?? (output?.feasible ? "success" : "infeasible"), usedEngine: diagnostics?.usedEngine ?? null, fallbackReason: diagnostics?.fallbackReason ?? null, falseGates: gates, makespan: diagnostics?.quality?.makespan ?? diagnostics?.OPQM?.makespan ?? diagnostics?.opqm?.makespan ?? null, talentIdle: diagnostics?.quality?.talentIdle ?? diagnostics?.OPQM?.talentIdle ?? diagnostics?.opqm?.talentIdle ?? null, visibleMainFlowIdle: diagnostics?.OPQM?.visibleMainFlowIdle ?? diagnostics?.opqm?.visibleMainFlowIdle ?? null, largestMainFlowGap: diagnostics?.OPQM?.largestMainFlowGap ?? diagnostics?.opqm?.largestMainFlowGap ?? null } }; }
function runOne(engine: ReplayEngine, input: EngineInput): { summary: ReplayExecutionSummary; compact: unknown } { const started = performance.now(); const result = engine === "v3" ? generatePlanV3(input as any) : engine === "v4" ? generatePlanV4(input) : runORCActivePlanner(input); const runtimeMs = Math.round(performance.now() - started); const compact = compactOutput(engine, result); const output = (compact as any).output; const d = (compact as any).diagnostics; return { compact, summary: { engine, runtimeMs, status: String(d.status ?? "unknown"), plannedTasks: asArray(output.plannedTasks).length, unplannedTasks: asArray(output.unplanned).length, hardFeasible: typeof output.feasible === "boolean" ? output.feasible : null, complete: typeof output.complete === "boolean" ? output.complete : null, outputHash: hashOutput(compact), usedEngine: d.usedEngine, fallbackReason: d.fallbackReason, falseGates: d.falseGates, makespan: num(d.makespan), talentIdle: num(d.talentIdle), visibleMainFlowIdle: num(d.visibleMainFlowIdle), largestMainFlowGap: num(d.largestMainFlowGap) } }; }
export function replayEngineScenario(snapshot: EngineScenarioSnapshotV1, options: ReplayOptions = {}): ReplayReport { const repeat = Math.max(1, Math.floor(options.repeat ?? 1)); const executions: ReplayExecutionSummary[] = []; let deterministic = true; for (const engine of enginesFor(options.engine)) { let firstHash: string | null = null; for (let i = 0; i < repeat; i++) { const { summary } = runOne(engine, cloneEngineScenarioValue(snapshot.engineInput)); executions.push(summary); if (firstHash && firstHash !== summary.outputHash) deterministic = false; firstHash ??= summary.outputHash; } } return { snapshot: { exportVersion: snapshot.exportVersion, planId: snapshot.planId, inputHash: snapshot.inputHash, counts: snapshot.counts }, executions, deterministic }; }
export function parseReplayArgs(argv: string[]): { file: string; options: ReplayOptions } { const args = [...argv]; const file = args.shift(); if (!file) throw new Error("Usage: replayEngineScenario <snapshot.json> [--engine v3|v4|orc|all] [--repeat N] [--output report.json] [--time-limit-ms N]"); const options: ReplayOptions = { engine: "all", repeat: 1 }; for (let i = 0; i < args.length; i++) { const a = args[i]; const v = args[i + 1]; if (a === "--engine") { options.engine = v as ReplayEngineSelection; i++; } else if (a === "--repeat") { options.repeat = Number(v); i++; } else if (a === "--output") { options.output = v; i++; } else if (a === "--time-limit-ms") { options.timeLimitMs = Number(v); i++; } else throw new Error(`Unknown replay option: ${a}`); } if (!["v3", "v4", "orc", "all"].includes(String(options.engine))) throw new Error(`Invalid --engine: ${options.engine}`); return { file, options }; }
if (import.meta.url === `file://${process.argv[1]}`) { try { const { file, options } = parseReplayArgs(process.argv.slice(2)); const snapshot = parseEngineScenarioSnapshot(readFileSync(file)); const report = replayEngineScenario(snapshot, options); const json = JSON.stringify(report, null, 2); if (options.output) writeFileSync(options.output, `${json}\n`); console.log(json); if (!report.deterministic) process.exitCode = 2; } catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; } }
