import type { OperationalState } from "../contracts";
import { isMacroPlaceholderTask } from "./macroProductionWaveTaskClassifier";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null};
const subject=(t:any)=>t?.contestantId??t?.contestant_id??t?.talentId??t?.talent_id??t?.participantId??t?.participant_id??t?.itinerantTeamId??t?.itinerant_team_id??null;
const push=(m:Record<string,any[]>,k:any,v:any)=>{ if(k!=null)(m[String(k)]??=[]).push(v); };
export function buildMacroProductionWaveFixedCalendar(args:{operationalState:OperationalState; scopeTaskIds:number[]; candidateId:string; mainZoneTarget:any}){
 const state=args.operationalState; const scope=new Set(args.scopeTaskIds); const locks=new Set((state.locks??[]).map((l:any)=>l.taskId)); const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t]));
 const fixedIntervalsByResourceId:Record<string,any[]>={}, fixedIntervalsBySpaceId:Record<string,any[]>={}, fixedIntervalsBySubjectId:Record<string,any[]>={}; const fixedMainFlowIntervals:any[]=[]; const protectedTaskIds:number[]=[], movableTaskIds:number[]=[], fixedTaskIds:number[]=[];
 for(const e of state.planning??[]){ const task:any=tasks.get((e as any).taskId); const id=(e as any).taskId; const s=toMin((e as any).startPlanned), end=toMin((e as any).endPlanned); if(s==null||end==null||end<=s) continue;
  const protectedStatus=["done","in_progress"].includes(String(task?.status)); const locked=locks.has(id); const inScope=scope.has(id); const placeholder=isMacroPlaceholderTask(e)||isMacroPlaceholderTask(task); const fixed=!inScope||protectedStatus||locked;
  if(inScope&&!fixed&&!placeholder) movableTaskIds.push(id); if(fixed){ fixedTaskIds.push(id); if(protectedStatus||locked) protectedTaskIds.push(id); }
  if(!fixed) continue; const interval={candidateId:args.candidateId,taskId:id,start:s,end, startPlanned:(e as any).startPlanned,endPlanned:(e as any).endPlanned,spaceId:(e as any).spaceId??null,resourceIds:[...((e as any).assignedResourceIds??[])],subjectId:subject(task),protectedStatus,locked,readOnly:true};
  for(const r of interval.resourceIds) push(fixedIntervalsByResourceId,r,interval); if(interval.spaceId!=null && (!placeholder || (e as any).spaceBlocksProduction===true || (e as any).blocksSpace===true)) push(fixedIntervalsBySpaceId,interval.spaceId,interval); if(interval.subjectId!=null) push(fixedIntervalsBySubjectId,interval.subjectId,interval);
  const mainSpaces=args.mainZoneTarget?.mainSpaceIds??[]; if(interval.spaceId!=null&&mainSpaces.includes(interval.spaceId)) fixedMainFlowIntervals.push(interval);
 }
 const sort=(m:Record<string,any[]>)=>Object.values(m).forEach(xs=>xs.sort((a,b)=>a.start-b.start||a.end-b.end)); sort(fixedIntervalsByResourceId); sort(fixedIntervalsBySpaceId); sort(fixedIntervalsBySubjectId); fixedMainFlowIntervals.sort((a,b)=>a.start-b.start||a.end-b.end);
 return {fixedIntervalsByResourceId,fixedIntervalsBySpaceId,fixedIntervalsBySubjectId,fixedMainFlowIntervals,protectedTaskIds:[...new Set(protectedTaskIds)],movableTaskIds:[...new Set(movableTaskIds)],fixedTaskIds:[...new Set(fixedTaskIds)],summary:{fixedTaskCount:new Set(fixedTaskIds).size,movableTaskCount:new Set(movableTaskIds).size,protectedTaskCount:new Set(protectedTaskIds).size,fixedResourceIdCount:Object.keys(fixedIntervalsByResourceId).length,fixedSpaceIdCount:Object.keys(fixedIntervalsBySpaceId).length,fixedSubjectIdCount:Object.keys(fixedIntervalsBySubjectId).length,readOnly:true},readOnly:true};
}
export function findFixedOverlap(fixedCalendar:any,a:any,task:any){ const s=toMin(a.startPlanned), e=toMin(a.endPlanned); if(s==null||e==null)return null; const checks:any[]=[]; for(const r of a.resourceIds??[]) checks.push(["context-fixed-resource-blocker","RESOURCE",r,fixedCalendar.fixedIntervalsByResourceId?.[String(r)]??[]]); if(a.spaceId!=null) checks.push(["context-fixed-space-blocker","SPACE",a.spaceId,fixedCalendar.fixedIntervalsBySpaceId?.[String(a.spaceId)]??[]]); const sid=subject(task); if(sid!=null) checks.push(["context-fixed-subject-blocker","SUBJECT",sid,fixedCalendar.fixedIntervalsBySubjectId?.[String(sid)]??[]]); for(const [reason,kind,id,xs] of checks) for(const f of xs) if(s< f.end && e> f.start) return {reason,kind,id,fixed:f,proposedStart:s,proposedEnd:e}; return null; }
