import type { OperationalState } from "../contracts";
import { findFixedOverlap } from "./macroProductionWaveFixedCalendar";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}; const hh=(x:number)=>`${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`;
const subject=(t:any)=>t?.contestantId??t?.contestant_id??t?.talentId??t?.talent_id??t?.participantId??t?.participant_id??t?.itinerantTeamId??t?.itinerant_team_id??null;
export function buildMacroProductionWaveLanes(args:{operationalState:OperationalState; taskClassification:any; mainTaskIds:number[]; prerequisiteTaskIds:number[]; resourceIds:number[]; startMinute:number}){
 const state=args.operationalState; const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const entries=new Map((state.planning??[]).map((e:any)=>[e.taskId,{...e,a:toMin(e.startPlanned),b:toMin(e.endPlanned),task:tasks.get(e.taskId)}]));
 const mainFlowLane:any[]=[]; const assignments:any[]=[]; const endByTask=new Map<number,number>(); const resCursor=new Map<number,number>(); const spaceCursor=new Map<number,number>(); const subjCursor=new Map<any,number>();
 const place=(id:number,lane:string,notBefore:number)=>{const e:any=entries.get(id); if(!e||e.a==null||e.b==null)return null; const dur=e.b-e.a; const rs=e.assignedResourceIds??[]; const sid=subject(e.task); let s=Math.max(notBefore,...rs.map((r:number)=>resCursor.get(r)??args.startMinute),e.spaceId!=null?(spaceCursor.get(e.spaceId)??args.startMinute):args.startMinute,sid!=null?(subjCursor.get(sid)??args.startMinute):args.startMinute); const out={taskId:id,startPlanned:hh(s),endPlanned:hh(s+dur),spaceId:e.spaceId??null,resourceIds:[...rs],lane}; assignments.push(out); endByTask.set(id,s+dur); for(const r of rs)resCursor.set(r,s+dur); if(e.spaceId!=null)spaceCursor.set(e.spaceId,s+dur); if(sid!=null)subjCursor.set(sid,s+dur); if(lane==="mainFlowLane")mainFlowLane.push(out); return out;};
 for(const mid of args.mainTaskIds){ const prereqs=(args.taskClassification.upstreamPrerequisiteTaskIdsByMainTask?.[mid]??[]).filter((id:number)=>args.prerequisiteTaskIds.includes(id)); for(const pid of prereqs) if(!endByTask.has(pid)) place(pid,`resourceLane:${(entries.get(pid) as any)?.assignedResourceIds?.[0]??"none"}`,args.startMinute); place(mid,"mainFlowLane",Math.max(args.startMinute,...prereqs.map((id:number)=>endByTask.get(id)??args.startMinute))); }
 const resourceLanesByResourceId:any={}; const spaceLanesBySpaceId:any={}; const subjectLanesBySubjectId:any={}; for(const a of assignments){ for(const r of a.resourceIds??[]) (resourceLanesByResourceId[r]??=[]).push(a); if(a.spaceId!=null)(spaceLanesBySpaceId[a.spaceId]??=[]).push(a); const sid=subject((entries.get(a.taskId) as any)?.task); if(sid!=null)(subjectLanesBySubjectId[sid]??=[]).push(a); }
 return {assignments, lanePlan:{mainFlowLane,resourceLanesByResourceId,spaceLanesBySpaceId,subjectLanesBySubjectId,parallelLaneCount:Object.keys(resourceLanesByResourceId).length,readOnly:true}};
}

export function buildContextAwareMacroProductionWaveLanes(args:{operationalState:OperationalState; taskClassification:any; scope:any; fixedCalendar:any; productionWavePolicy:any; startMinute:number; mainZoneTarget:any}){
 const state=args.operationalState; const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const entries=new Map((state.planning??[]).map((e:any)=>[e.taskId,{...e,a:toMin(e.startPlanned),b:toMin(e.endPlanned),task:tasks.get(e.taskId)}]));
 const movable=new Set(args.fixedCalendar?.movableTaskIds??[...args.scope.mainTaskIds,...args.scope.prerequisiteTaskIds]); const assignments:any[]=[]; const blockers:any[]=[]; const placed:any[]=[]; const ws=toMin(state.workDay?.start)??0, we=toMin(state.workDay?.end)??24*60;
 const ownOverlap=(a:any,s:number,e:number)=>placed.find((p:any)=>s<p.e&&e>p.s&&(((a.assignedResourceIds??[]).some((r:number)=>(p.resourceIds??[]).includes(r)))||(a.spaceId!=null&&a.spaceId===p.spaceId)||(subject(a.task)!=null&&subject(a.task)===p.subjectId)));
 const first=(entry:any,notBefore:number,lane:string)=>{ const dur=entry.b-entry.a; for(let s=Math.max(ws,notBefore); s+dur<=we; s+=5){ const a={taskId:entry.taskId,startPlanned:hh(s),endPlanned:hh(s+dur),spaceId:entry.spaceId??null,resourceIds:[...(entry.assignedResourceIds??[])],lane}; const fixed=findFixedOverlap(args.fixedCalendar,a,entry.task); const own=ownOverlap(entry,s,s+dur); if(!fixed&&!own){ placed.push({...a,s,e:s+dur,subjectId:subject(entry.task)}); assignments.push(a); return a; } if(fixed&&s===Math.max(ws,notBefore)) blockers.push({candidateId:`candidate:macro-production-wave-day-shape:${args.scope.scopeId}`,scopeId:args.scope.scopeId,movedTaskId:entry.taskId,fixedBlockingTaskId:fixed.fixed.taskId,resourceId:fixed.kind==='RESOURCE'?fixed.id:null,spaceId:fixed.kind==='SPACE'?fixed.id:null,subjectId:fixed.kind==='SUBJECT'?fixed.id:null,reason:fixed.reason,proposedStart:hh(s),proposedEnd:hh(s+dur),fixedBlockerStart:fixed.fixed.startPlanned,fixedBlockerEnd:fixed.fixed.endPlanned,readOnly:true}); } blockers.push({candidateId:`candidate:macro-production-wave-day-shape:${args.scope.scopeId}`,scopeId:args.scope.scopeId,movedTaskId:entry.taskId,reason:"outside-work-day",proposedStart:hh(Math.max(ws,notBefore)),proposedEnd:hh(Math.max(ws,notBefore)+dur),allowedWindow:{start:state.workDay?.start??null,end:state.workDay?.end??null},readOnly:true}); return null; };
 const endByTask=new Map<number,number>(); for(const mid of args.scope.mainTaskIds){ const prereqs=(args.taskClassification.upstreamPrerequisiteTaskIdsByMainTask?.[mid]??[]).filter((id:number)=>args.scope.prerequisiteTaskIds.includes(id)); for(const pid of prereqs) if(movable.has(pid)&&!endByTask.has(pid)){const e:any=entries.get(pid); const a=e&&first(e,args.startMinute,`resourceLane:${e?.assignedResourceIds?.[0]??'none'}`); if(a)endByTask.set(pid,toMin(a.endPlanned)!);} if(movable.has(mid)){const e:any=entries.get(mid); const a=e&&first(e,Math.max(args.startMinute,...prereqs.map((id:number)=>endByTask.get(id)??args.startMinute)),"mainFlowLane"); if(a)endByTask.set(mid,toMin(a.endPlanned)!);} }
 const lanePlan=buildMacroProductionWaveLanes({operationalState:state,taskClassification:args.taskClassification,mainTaskIds:[],prerequisiteTaskIds:[],resourceIds:[],startMinute:args.startMinute}).lanePlan; lanePlan.mainFlowLane=assignments.filter(a=>a.lane==='mainFlowLane'); lanePlan.resourceLanesByResourceId={}; lanePlan.spaceLanesBySpaceId={}; lanePlan.subjectLanesBySubjectId={}; for(const a of assignments){ for(const r of a.resourceIds??[]) (lanePlan.resourceLanesByResourceId[r]??=[]).push(a); if(a.spaceId!=null)(lanePlan.spaceLanesBySpaceId[a.spaceId]??=[]).push(a); const sid=subject((entries.get(a.taskId) as any)?.task); if(sid!=null)(lanePlan.subjectLanesBySubjectId[sid]??=[]).push(a); } lanePlan.parallelLaneCount=Object.keys(lanePlan.resourceLanesByResourceId).length;
 return {assignments,lanePlan,contextBlockers: blockers,contextAwarePlacementAccepted:assignments.length>0&&blockers.length===0,contextAwarePlacementRejected:blockers.length>0,readOnly:true};
}
