import test from "node:test";
import assert from "node:assert/strict";
import { buildMacroProductionWaveScopeOptions } from "./macroProductionWaveScopePlanner";
import { classifyMacroProductionWaveTasks } from "./macroProductionWaveTaskClassifier";
import { resolveProductionWavePolicy } from "./productionWavePolicy";

const state=(extra:any={})=>({id:"s",workDay:{start:"09:00",end:"18:00"},constraints:{optimizer:{mainFlowSpaceId:900,productionWavePolicy:{runtime:{macroDayShapeMaxMovedTasks:30}}}},tasks:[{id:1,status:"pending"},{id:2,status:"pending",dependsOnTaskIds:[1]},{id:3,status:"pending"},{id:4,status:"pending",dependsOnTaskIds:[3]}],planning:[{taskId:1,startPlanned:"08:30",endPlanned:"08:45",spaceId:701,assignedResourceIds:[1],countsAsWork:true},{taskId:2,startPlanned:"09:00",endPlanned:"09:30",spaceId:900,assignedResourceIds:[1],countsAsWork:true},{taskId:3,startPlanned:"10:00",endPlanned:"10:15",spaceId:701,assignedResourceIds:[1],countsAsWork:true},{taskId:4,startPlanned:"10:30",endPlanned:"11:00",spaceId:900,assignedResourceIds:[1],countsAsWork:true}],...extra});

test("gap-next-main-only leaves compatible prerequisites in place",()=>{const st=state(); const c=classifyMacroProductionWaveTasks({operationalState:st as any,mainZoneTarget:{configured:true,mainSpaceIds:[900],mainZoneIds:[]}}); const opts=buildMacroProductionWaveScopeOptions({operationalState:st as any,taskClassification:c,productionWavePolicy:resolveProductionWavePolicy(st),mainZoneTarget:{configured:true,mainSpaceIds:[900],mainZoneIds:[]},gap:{start:9*60,end:9*60}}); const one=opts[0]; assert.equal(one.scopeId,"gap-next-main-only"); assert.deepEqual(one.leftInPlaceCompatiblePrerequisiteTaskIds,[1]); assert.deepEqual(one.prerequisiteTaskIds,[]); assert.equal(one.fitsPolicyLimits,true);});

test("progressive scope reports full scope too large without hiding mini scopes",()=>{const tasks:any[]=[]; const planning:any[]=[]; for(let i=1;i<=36;i++){tasks.push({id:i,status:"pending"}); planning.push({taskId:i,startPlanned:`${String(9+Math.floor(i/4)).padStart(2,"0")}:00`,endPlanned:`${String(9+Math.floor(i/4)).padStart(2,"0")}:10`,spaceId:900,assignedResourceIds:[1],countsAsWork:true});} const st=state({tasks,planning,constraints:{optimizer:{mainFlowSpaceId:900,productionWavePolicy:{runtime:{macroDayShapeMaxMovedTasks:5}}}}}); const c=classifyMacroProductionWaveTasks({operationalState:st as any,mainZoneTarget:{configured:true,mainSpaceIds:[900],mainZoneIds:[]}}); const opts=buildMacroProductionWaveScopeOptions({operationalState:st as any,taskClassification:c,productionWavePolicy:resolveProductionWavePolicy(st),mainZoneTarget:{configured:true,mainSpaceIds:[900],mainZoneIds:[]},gap:{start:9*60,end:9*60}}); assert.ok(opts.length>1); assert.equal(opts[0].fitsPolicyLimits,true); assert.equal(opts.at(-1)?.rejectionReason,"macro-day-shape-scope-too-large");});
