import type { OperationalState } from "../contracts";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}; const uniq=(xs:number[])=>[...new Set(xs.filter(Number.isFinite))].sort((a,b)=>a-b);
const deps=(t:any)=>uniq([...(t?.dependsOnTaskIds??[]),...(t?.dependsOnTaskId!=null?[t.dependsOnTaskId]:[])]); const subject=(t:any)=>t?.contestantId??t?.contestant_id??t?.talentId??t?.talent_id??t?.participantId??t?.participant_id??t?.itinerantTeamId??t?.itinerant_team_id??null;
export function preflightMacroProductionWaveDayShapeCandidate(args:{operationalState:OperationalState; assignments:any[]; policy:any; candidateId:string}){
 const state=args.operationalState; const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const base=new Map((state.planning??[]).map((e:any)=>[e.taskId,e])); const ws=toMin(state.workDay?.start)??0, we=toMin(state.workDay?.end)??24*60; const locked=new Set((state.locks??[]).map((l:any)=>l.taskId)); const details:any[]=[];
 const maxMoved=args.policy.values.runtime.macroDayShapeMaxMovedTasks; const moved=args.assignments.filter(a=>{const e:any=base.get(a.taskId); return e&& (e.startPlanned!==a.startPlanned||e.endPlanned!==a.endPlanned||e.spaceId!==a.spaceId)});
 if(moved.length>maxMoved) details.push({candidateId:args.candidateId,reason:"macro-day-shape-scope-too-large",violatedConstraint:"SCOPE_LIMIT",affectedTaskIds:moved.map(a=>a.taskId),limit:maxMoved,actual:moved.length,readOnly:true});
 const intervals:any[]=[]; for(const a of args.assignments){ const s=toMin(a.startPlanned), e=toMin(a.endPlanned); const task:any=tasks.get(a.taskId); if(s==null||e==null||e<=s) details.push({candidateId:args.candidateId,reason:"invalid-duration",violatedConstraint:"POSITIVE_DURATION",affectedTaskIds:[a.taskId],proposedStart:a.startPlanned,proposedEnd:a.endPlanned,lane:a.lane??null,readOnly:true}); if(s!=null&&e!=null&&(s<ws||e>we)) details.push({candidateId:args.candidateId,reason:"outside-work-day",violatedConstraint:"WORK_DAY",affectedTaskIds:[a.taskId],taskId:a.taskId,proposedStart:a.startPlanned,proposedEnd:a.endPlanned,allowedWindow:{start:state.workDay?.start??null,end:state.workDay?.end??null},lane:a.lane??null,readOnly:true}); if(["done","in_progress"].includes(String(task?.status))||locked.has(a.taskId)) details.push({candidateId:args.candidateId,reason:locked.has(a.taskId)?"locked-task":"protected-status",violatedConstraint:locked.has(a.taskId)?"LOCK":"PROTECTED_STATUS",affectedTaskIds:[a.taskId],readOnly:true}); const sid=subject(task); const w=sid!=null?(state.availability?.contestantAvailabilityById??{})[sid]:null; const aw=toMin(w?.start), bw=toMin(w?.end); if(sid!=null&&aw!=null&&bw!=null&&s!=null&&e!=null&&(s<aw||e>bw)) details.push({candidateId:args.candidateId,reason:"availability",violatedConstraint:"SUBJECT_AVAILABILITY",affectedTaskIds:[a.taskId],proposedStart:a.startPlanned,proposedEnd:a.endPlanned,allowedWindow:w,lane:a.lane??null,readOnly:true}); if(a.spaceId==null) details.push({candidateId:args.candidateId,reason:"invalid-assigned-space",violatedConstraint:"ASSIGNED_SPACE",affectedTaskIds:[a.taskId],readOnly:true}); intervals.push({...a,s,e,task}); }
 const byTask=new Map(intervals.map(i=>[i.taskId,i])); for(const i of intervals){ for(const pid of deps(i.task)){ const p:any=byTask.get(pid); const old:any=base.get(pid); const pend=p?.e??toMin(old?.endPlanned); if(pend!=null&&i.s!=null&&pend>i.s) details.push({candidateId:args.candidateId,reason:"direct-dependency-broken",violatedConstraint:"DIRECT_DEPENDENCY",affectedTaskIds:[pid,i.taskId],proposedStart:i.startPlanned,dependencyEnd:p?.endPlanned??old?.endPlanned,dependencyTaskId:pid,readOnly:true}); }}
 const check=(key:string, items:any[], constraint:string)=>{ for(let i=1;i<items.length;i++){const p=items[i-1], c=items[i]; if(p.e>c.s) details.push({candidateId:args.candidateId,reason:`${key}-overlap`,violatedConstraint:constraint,affectedTaskIds:[p.taskId,c.taskId],conflict:{previous:p.taskId,next:c.taskId},readOnly:true}); }};
 const groups=(fn:(i:any)=>any[])=>{const m=new Map<any,any[]>(); for(const i of intervals) for(const k of fn(i)) if(k!=null)m.set(k,[...(m.get(k)??[]),i]); return m}; for(const [,xs] of groups(i=>i.resourceIds??[])) check("resource",xs.sort((a,b)=>a.s-b.s),"RESOURCE_OVERLAP"); for(const [,xs] of groups(i=>[i.spaceId])) check("space",xs.sort((a,b)=>a.s-b.s),"SPACE_OVERLAP"); for(const [,xs] of groups(i=>[subject(i.task)])) check("subject",xs.sort((a,b)=>a.s-b.s),"SUBJECT_OVERLAP");
 return {accepted:details.length===0, rejectedCandidateDetails:details, checkedAssignmentCount:args.assignments.length, movedTaskIds:moved.map(a=>a.taskId), readOnly:true};
}
