import type { OperationalState } from "../contracts";
type Rec=Record<string,any>; const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}; const hh=(x:number)=>`${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`; const ids=(xs:any[])=>[...new Set(xs.map(Number).filter(Number.isFinite))].sort((a,b)=>a-b); const PROT=new Set(["done","in_progress"]);
export type MacroMainZoneDependencyAwareVariantType="pull-dependency-ready-main-zone-block"|"pull-prerequisite-chain-then-main-zone-block"|"dependency-preserving-split-main-zone-block"|"dependency-blocked-diagnostic-only";
export interface MacroMainZoneDependencyChainAnalysis extends Rec{readOnly:true;recommendedVariantType:MacroMainZoneDependencyAwareVariantType}
const depIds=(t:any)=>ids([...(Array.isArray(t?.dependsOnTaskIds)?t.dependsOnTaskIds:[]),t?.dependsOnTaskId]);
const minDelay=(t:any,p:number)=>{const map=t?.dependencyMinDelayMinutesByTaskId??t?.minDelayMinutesByDependencyTaskId??{}; const v=Number(map?.[p]??t?.dependencyMinDelayMinutes??0); return Number.isFinite(v)?Math.max(0,v):0};
export function analyzeMacroMainZoneDependencyChain(args:{operationalState:OperationalState;candidateMainZoneBlock:any[];dependencyGraph?:Rec|null;taskRoles?:Rec|null;locks?:any[]|null;protectedTaskIds?:number[]|null;mainZoneTarget?:Rec|null;targetGap:{start?:string;end?:string;a?:number;b?:number};mealSemantics?:Rec|null;resourceAvailability?:Rec|null;spaceAvailability?:Rec|null;candidateStart?:string|number|null;}):MacroMainZoneDependencyChainAnalysis{
 const state=args.operationalState, tasks=new Map((state.tasks??[]).map((t:any)=>[Number(t.id),t])), plan=new Map((state.planning??[]).map((e:any)=>[Number(e.taskId),{...e,a:toMin(e.startPlanned),b:toMin(e.endPlanned)}]));
 const targetIds=ids((args.candidateMainZoneBlock??[]).map((e:any)=>e.taskId)), targetSet=new Set(targetIds), locks=new Set([...(args.locks??state.locks??[]).map((l:any)=>Number(l.taskId)),...(args.protectedTaskIds??[]).map(Number)].filter(Number.isFinite));
 const directPre=ids(targetIds.flatMap(id=>depIds(tasks.get(id))).filter(id=>!targetSet.has(id))); const rev=new Map<number,number[]>(); for(const t of state.tasks??[]) for(const d of depIds(t)) rev.set(d,[...(rev.get(d)??[]),Number(t.id)]);
 const walk=(seeds:number[],next:(id:number)=>number[])=>{const out=new Set<number>(), q=[...seeds].sort((a,b)=>a-b); while(q.length){const id=q.shift()!; for(const n of next(id).sort((a,b)=>a-b)) if(!out.has(n)&&!targetSet.has(n)){out.add(n);q.push(n)}} return ids([...out])};
 const transPre=walk(directPre,id=>depIds(tasks.get(id))), directDep=ids(targetIds.flatMap(id=>rev.get(id)??[])), transDep=walk(directDep,id=>rev.get(id)??[]), allPre=ids([...directPre,...transPre]);
 const targetStart=typeof args.candidateStart==="number"?args.candidateStart:toMin(typeof args.candidateStart==="string"?args.candidateStart:null)??args.targetGap.a??toMin(args.targetGap.start)??0, targetEnd=args.targetGap.b??toMin(args.targetGap.end)??targetStart;
 let latest=targetStart; const broken:any[]=[], unsafe:number[]=[], movable:any[]=[], unmovable:number[]=[], lockBlocked:number[]=[], progDone:number[]=[];
 for(const depId of allPre){const pe=plan.get(depId), depTask=tasks.get(depId), dependents=targetIds.filter(id=>depIds(tasks.get(id)).includes(depId)), delay=Math.max(0,...dependents.map(id=>minDelay(tasks.get(id),depId))), required=(pe?.b??targetStart)+delay; latest=Math.max(latest,required); if(required>targetStart){unsafe.push(depId,...dependents); for(const id of dependents) broken.push({prerequisiteTaskId:depId,dependentTaskId:id,prerequisiteEnd:pe?.endPlanned??null,dependentCandidateStart:hh(targetStart),minDelayMinutes:delay,violatedConstraint:"DIRECT_DEPENDENCY_BROKEN"})} if(locks.has(depId)){lockBlocked.push(depId);unmovable.push(depId)} if(PROT.has(String(depTask?.status))){progDone.push(depId);unmovable.push(depId)} if(!locks.has(depId)&&!PROT.has(String(depTask?.status))) movable.push({taskIds:[depId],prerequisiteTaskIds:[depId],totalDurationMinutes:pe?.a!=null&&pe?.b!=null?pe.b-pe.a:null,readOnly:true})}
 const dur=(id:number)=>{const e=plan.get(id);return e?.a!=null&&e?.b!=null?e.b-e.a:0}; const safe:any[]=[]; let cur=latest; const sub:number[]=[]; for(const id of targetIds){const d=dur(id); if(cur+d<=targetEnd){sub.push(id);cur+=d;if(sub.length>=1)safe.push({taskIds:[...sub],start:hh(latest),end:hh(cur),durationMinutes:cur-latest,readOnly:true})}}
 const warnings=[...new Set([...(lockBlocked.length?["macro-main-zone-locked-prerequisite"]:[]),...(progDone.length?["macro-main-zone-in-progress-or-done-prerequisite"]:[]),...(latest>targetEnd?["macro-main-zone-prerequisite-chain-does-not-fit"]:[])])];
 return {readOnly:true,targetMainZoneTaskIds:targetIds,directPrerequisiteTaskIds:directPre,transitivePrerequisiteTaskIds:transPre,directDependentTaskIds:directDep,transitiveDependentTaskIds:transDep,prerequisitesAlreadySatisfiedBeforeTargetStart:allPre.every(id=>(plan.get(id)?.b??0)<=targetStart),latestPrerequisiteEndBeforeCandidateStart:hh(Math.max(targetStart,latest)),earliestDependencySafeStart:hh(latest),dependencySafeSubBlocks:safe.sort((a,b)=>b.durationMinutes-a.durationMinutes||a.taskIds[0]-b.taskIds[0]),dependencyUnsafeTaskIds:ids(unsafe),dependencyBrokenPairs:broken.sort((a,b)=>a.prerequisiteTaskId-b.prerequisiteTaskId||a.dependentTaskId-b.dependentTaskId),movablePrerequisiteChains:movable.sort((a,b)=>a.taskIds[0]-b.taskIds[0]),unmovablePrerequisiteTaskIds:ids(unmovable),lockBlockedDependencyTaskIds:ids(lockBlocked),inProgressOrDoneDependencyTaskIds:ids(progDone),dependencyAnalysisWarnings:warnings,recommendedVariantType:latest<=targetEnd?"pull-dependency-ready-main-zone-block":safe.length?"dependency-preserving-split-main-zone-block":"dependency-blocked-diagnostic-only"};
}
