import type { OperationalState } from "../contracts";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null};
const uniq=(xs:number[])=>[...new Set(xs.filter(Number.isFinite))].sort((a,b)=>a-b);
const placeholderRoles=new Set(["transport_arrival","transport_departure","meal_break_placeholder","global_break_placeholder","non_operational_placeholder"]);
const deps=(t:any)=>uniq([...(t?.dependsOnTaskIds??[]),...(t?.dependsOnTaskId!=null?[t.dependsOnTaskId]:[])]);
export const isMacroPlaceholderTask=(entry:any)=>entry?.countsAsWork===false||placeholderRoles.has(String(entry?.operationalRole??entry?.task?.operationalRole??""));
export function classifyMacroProductionWaveTasks(args:{operationalState:OperationalState; mainZoneTarget:any; currentPlanning?:any[]}){
 const state=args.operationalState; const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const mainSpaces=new Set((args.mainZoneTarget?.mainSpaceIds??[]).map(Number)); const mainZones=new Set((args.mainZoneTarget?.mainZoneIds??[]).map(Number));
 const planning=(args.currentPlanning??state.planning??[]).map((e:any)=>({...e,a:toMin(e.startPlanned),b:toMin(e.endPlanned),task:tasks.get(e.taskId)})).filter((e:any)=>e.a!=null&&e.b!=null).sort((a:any,b:any)=>a.a-b.a||a.b-b.b);
 const byId=new Map(planning.map((e:any)=>[e.taskId,e])); const mainFlowTaskIds:number[]=[]; const placeholderTaskIds:number[]=[]; const excludedTaskIds:number[]=[]; const countsForMainFlowIgnoredTaskIds:number[]=[]; const mainFlowTasksIncluded:any[]=[]; const mainFlowTasksExcluded:any[]=[];
 for(const e of planning){ const inSpace=e.spaceId!=null&&mainSpaces.has(Number(e.spaceId)); const inZone=e.zoneId!=null&&mainZones.has(Number(e.zoneId)); const prod=!isMacroPlaceholderTask(e); const include=prod&&(inSpace||inZone); if(isMacroPlaceholderTask(e)) placeholderTaskIds.push(e.taskId); if(include){mainFlowTaskIds.push(e.taskId); mainFlowTasksIncluded.push({taskId:e.taskId,spaceId:e.spaceId??null,zoneId:e.zoneId??null,source:inSpace?"main_space":"main_zone",readOnly:true});} else {excludedTaskIds.push(e.taskId); mainFlowTasksExcluded.push({taskId:e.taskId,spaceId:e.spaceId??null,zoneId:e.zoneId??null,countsForMainFlow:e.countsForMainFlow===true,reason:!prod?"placeholder_or_non_productive":e.countsForMainFlow===true?"counts_for_main_flow_outside_main_target":"outside_main_target",readOnly:true}); if(e.countsForMainFlow===true) countsForMainFlowIgnoredTaskIds.push(e.taskId); }}
 const mainSet=new Set(mainFlowTaskIds); const upstreamPrerequisiteTaskIdsByMainTask:Record<number,number[]>={}; for(const id of mainFlowTaskIds){ upstreamPrerequisiteTaskIdsByMainTask[id]=deps(tasks.get(id)).filter(pid=>byId.has(pid)&&!mainSet.has(pid)); }
 const prereqSet=new Set(Object.values(upstreamPrerequisiteTaskIdsByMainTask).flat()); const mainFlowTaskIdsByResource:Record<number,number[]>={}; for(const id of mainFlowTaskIds){ const e:any=byId.get(id); for(const r of e?.assignedResourceIds??[]) (mainFlowTaskIdsByResource[r]??=[]).push(id); }
 const resourceSupportTaskIds=planning.filter((e:any)=>!mainSet.has(e.taskId)&&!prereqSet.has(e.taskId)&&!isMacroPlaceholderTask(e)&&(e.assignedResourceIds??[]).length).map((e:any)=>e.taskId);
 const nonBlockingSupportTaskIds=planning.filter((e:any)=>!mainSet.has(e.taskId)&&!prereqSet.has(e.taskId)&&!isMacroPlaceholderTask(e)&&!(e.assignedResourceIds??[]).length).map((e:any)=>e.taskId);
 return {mainFlowClassificationSource:args.mainZoneTarget?.configured?"resolveORCMainZoneTarget.main_space_or_zone_strict":"strict_no_config", mainFlowTaskIds:uniq(mainFlowTaskIds), mainFlowTaskIdsByResource, upstreamPrerequisiteTaskIdsByMainTask, resourceSupportTaskIds:uniq(resourceSupportTaskIds), nonBlockingSupportTaskIds:uniq(nonBlockingSupportTaskIds), placeholderTaskIds:uniq(placeholderTaskIds), excludedTaskIds:uniq(excludedTaskIds), mainFlowTasksIncluded, mainFlowTasksExcluded, countsForMainFlowIgnoredTaskIds:uniq(countsForMainFlowIgnoredTaskIds), warnings:mainFlowTaskIds.length?[]:["main_flow_tasks_not_detected_strict"], readOnly:true};
}
