import test from "node:test";
import assert from "node:assert/strict";
import { analyzeMacroMainZoneDependencyChain } from "./macroMainZoneDependencyChainAnalyzer";

const base = (over:any={}) => ({ tasks:[{id:1,status:"pending"},{id:2,status:"pending",dependsOnTaskIds:[1]},{id:3,status:"pending",dependsOnTaskIds:[2]},{id:4,status:"pending",dependsOnTaskIds:[3]}], planning:[{taskId:1,startPlanned:"12:05",endPlanned:"12:50",assignedResourceIds:[10],spaceId:2},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1},{taskId:4,startPlanned:"15:20",endPlanned:"15:50",assignedResourceIds:[10],spaceId:1}], locks:[], ...over } as any);
const block = (s=base()) => s.planning.filter((e:any)=>[2,3].includes(e.taskId)).map((e:any)=>({...e,a:14*60+20,b:e.taskId===2?14*60+50:15*60+20}));

test("detecta prerequisitos directos",()=>{ const a=analyzeMacroMainZoneDependencyChain({operationalState:base(),candidateMainZoneBlock:block(),targetGap:{a:725,b:860},candidateStart:725}); assert.deepEqual(a.directPrerequisiteTaskIds,[1]); });
test("detecta prerequisitos transitivos",()=>{ const a=analyzeMacroMainZoneDependencyChain({operationalState:base(),candidateMainZoneBlock:[block()[1]],targetGap:{a:725,b:860},candidateStart:725}); assert.deepEqual(a.transitivePrerequisiteTaskIds,[1]); });
test("calcula earliest dependency-safe start",()=>{ const a=analyzeMacroMainZoneDependencyChain({operationalState:base(),candidateMainZoneBlock:[block()[0]],targetGap:{a:725,b:860},candidateStart:725}); assert.equal(a.earliestDependencySafeStart,"12:50"); });
test("marca bloque unsafe si prerequisito acabaría después del dependiente",()=>{ const a=analyzeMacroMainZoneDependencyChain({operationalState:base(),candidateMainZoneBlock:[block()[0]],targetGap:{a:725,b:860},candidateStart:725}); assert.deepEqual(a.dependencyUnsafeTaskIds,[1,2]); assert.equal(a.dependencyBrokenPairs[0].violatedConstraint,"DIRECT_DEPENDENCY_BROKEN"); });
test("permite sub-bloque dependency-safe",()=>{ const a=analyzeMacroMainZoneDependencyChain({operationalState:base(),candidateMainZoneBlock:block(),targetGap:{a:725,b:860},candidateStart:725}); assert.ok(a.dependencySafeSubBlocks.length>=1); });
test("respeta done/in_progress/locked dependencies",()=>{ const st=base({tasks:[{id:1,status:"done"},{id:2,status:"pending",dependsOnTaskIds:[1]}],planning:[{taskId:1,startPlanned:"12:05",endPlanned:"12:50",assignedResourceIds:[10],spaceId:2},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1}],locks:[{taskId:1,lockType:"full"}]}); const a=analyzeMacroMainZoneDependencyChain({operationalState:st,candidateMainZoneBlock:[st.planning[1]],targetGap:{a:725,b:860},candidateStart:725}); assert.deepEqual(a.lockBlockedDependencyTaskIds,[1]); assert.deepEqual(a.inProgressOrDoneDependencyTaskIds,[1]); });
test("determinismo",()=>{ const args={operationalState:base(),candidateMainZoneBlock:block(),targetGap:{a:725,b:860},candidateStart:725}; assert.equal(JSON.stringify(analyzeMacroMainZoneDependencyChain(args)),JSON.stringify(analyzeMacroMainZoneDependencyChain(args))); });
