import test from "node:test";
import assert from "node:assert/strict";
import { buildMacroMainZoneBlockRelayoutCandidates } from "./macroMainZoneBlockRelayoutCandidateBuilder";

const state = (extra:any={}) => ({ id:"s", planId:1, workDay:{start:"09:00",end:"18:00"}, tasks:[1,2,3,4,5,6,7].map(id=>({id,status:"pending"})), resources:[{id:10,typeName:"Coach"},{id:11,typeName:"Coach"}], spaces:{exclusiveById:{1:true},capacityById:{1:1}}, locks:[], constraints:{mealMode:"flexible_meal_window",optimizer:{mainFlowSpaceId:1,mainZoneMaxCoachSwitchesPerDay:4}}, availability:{workDay:{start:"09:00",end:"18:00"},mealWindow:{start:"13:00",end:"16:30"},globalHardBreaks:[],protectedBreaks:[]}, planning:[{taskId:1,startPlanned:"11:30",endPlanned:"12:05",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}], cognitive:{opportunities:[],searchSpaces:[],candidates:[],candidateStates:[],simulatedStates:[],validationResults:[],operationalValues:[],commitDecisions:[],evidence:[],metadata:{}}, ...extra } as any);
const blueprint:any = { candidateReadiness:{recommendedCandidateFamily:"macro_main_zone_block_relayout"}, mainZoneBlockBlueprint:{currentMainZoneVisibleGaps:[{start:"12:05",end:"14:20",gapMinutes:135}]}, mealBlueprint:{productiveWorkAllowedInsideMealWindow:true} };

test("Generates pull-next-main-zone-block candidate",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,1); assert.equal(r.candidates[0].metadata.variantType,"pull-dependency-ready-main-zone-block"); assert.equal(r.candidates[0].assignments.length,2); });
test("Preserves assignedSpace and assignedResources",()=>{ const c=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}).candidates[0] as any; assert.equal(c.assignments[0].assignedSpace,1); assert.deepEqual(c.assignments[0].assignedResources,[10]); });
test("Does not treat flexible meal window as hard stop",()=>{ const c=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}).candidates[0] as any; assert.equal(c.metadata.mealWindowTreatedAsHardStop,false); assert.equal(c.metadata.usesFlexibleMealWindowAsProductiveTime,true); });
test("Rejects or blocks if real hard break covers target window",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({availability:{workDay:{start:"09:00",end:"18:00"},protectedBreaks:[{start:"12:30",end:"13:00",kind:"global",code:"BREAK"}],globalHardBreaks:[{start:"12:30",end:"13:00"}],mealWindow:{start:"13:00",end:"16:30"}}}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,0); assert.ok(r.summary.candidateGenerationBlockers.includes("macro-main-zone-crosses-hard-break") || r.candidates.length===0); });
test("Detects support resource displacement variant",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({tasks:[1,2,3,4].map(id=>({id,status:"pending"})), planning:[...state().planning,{taskId:4,startPlanned:"12:10",endPlanned:"12:40",assignedResourceIds:[10],spaceId:2,operationalRole:"productive_task"}]}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates[0].metadata.variantType,"pull-dependency-ready-main-zone-block"); assert.ok(Array.isArray(r.candidates[0].metadata.movedSupportTaskIds)); });
test("Respects max moved tasks",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({constraints:{optimizer:{mainFlowSpaceId:1,macroMainZoneMaxMovedTasksPerCandidate:1,macroMainZoneBlockMinTasks:1}}}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.ok(r.candidates[0].assignments.length<=1); });
test("Respects coach switch policy",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({constraints:{optimizer:{mainFlowSpaceId:1,mainZoneMaxCoachSwitchesPerDay:0}}, planning:[state().planning[0],{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[11],spaceId:1,operationalRole:"productive_task"}]}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,0); });
test("Does not move done/in_progress/locked tasks",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({tasks:[{id:1},{id:2,status:"done"},{id:3,status:"in_progress"}], locks:[{taskId:2,lockType:"full"}]}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,0); });
test("Deterministic ordering",()=>{ const a=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}); const b=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(JSON.stringify(a.candidates), JSON.stringify(b.candidates)); });

test("ID240 no desplaza prerequisito detrás de dependiente y genera dependency-ready",()=>{ const st=state({tasks:[{id:1,status:"pending"},{id:2,status:"pending",dependsOnTaskIds:[4]},{id:3,status:"pending"},{id:4,status:"pending"}], planning:[state().planning[0],{taskId:4,startPlanned:"12:05",endPlanned:"12:50",assignedResourceIds:[10],spaceId:2,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}]}); const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:st,productionWavePlanner:blueprint,baseHardFeasible:true}); assert.ok(r.summary.dependencyAnalysisAvailable); assert.ok(r.candidates.some(c=>c.metadata.variantType==="pull-dependency-ready-main-zone-block")); const c=r.candidates.find(c=>c.metadata.variantType==="pull-dependency-ready-main-zone-block")!; assert.equal(c.assignments[0].startPlanned,"12:50"); assert.ok(!c.assignments.some(a=>a.taskId===4)); });

test("ID240 genera pull-prerequisite-chain-then-main-zone-block si cabe",()=>{ const st=state({tasks:[{id:1,status:"pending"},{id:2,status:"pending",dependsOnTaskIds:[4]},{id:3,status:"pending"},{id:4,status:"pending"}], planning:[state().planning[0],{taskId:4,startPlanned:"13:30",endPlanned:"13:45",assignedResourceIds:[11],spaceId:2,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}]}); const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:st,productionWavePlanner:blueprint,baseHardFeasible:true}); assert.ok(r.candidates.some(c=>c.metadata.variantType==="pull-prerequisite-chain-then-main-zone-block")); });

test("ID240 genera blockers si no hay ventana dependency-safe",()=>{ const st=state({tasks:[{id:1,status:"pending"},{id:2,status:"pending",dependsOnTaskIds:[4]},{id:3,status:"pending"},{id:4,status:"pending"}], planning:[state().planning[0],{taskId:4,startPlanned:"14:00",endPlanned:"14:15",assignedResourceIds:[11],spaceId:2,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"15:20",endPlanned:"16:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}]}); const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:st,productionWavePlanner:blueprint,baseHardFeasible:true}); assert.ok((r.summary.dependencyBlockedReasons as string[]).includes("macro-main-zone-prerequisite-chain-does-not-fit") || r.summary.dependencyBlockedCandidateCount>=0); });

test("ID242 genera suffix compaction antes que split y usa cursor por tarea",()=>{ const st=state({ constraints:{optimizer:{mainFlowSpaceId:1,macroMainZoneBlockMaxTasks:2,macroMainZoneBlockMinTasks:1,macroMainZoneSuffixMinGlobalIdleReductionMinutes:1}}, tasks:[{id:1,status:"pending"},{id:2,status:"pending"},{id:3,status:"pending",dependsOnTaskIds:[8]},{id:4,status:"pending"},{id:5,status:"pending"},{id:8,status:"pending"}], planning:[state().planning[0],{taskId:8,startPlanned:"12:20",endPlanned:"13:00",assignedResourceIds:[11],spaceId:2,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:4,startPlanned:"15:20",endPlanned:"15:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:5,startPlanned:"15:50",endPlanned:"16:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}] }); const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:st,productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates[0].metadata.variantType,"dependency-safe-main-zone-suffix-compaction"); assert.equal((r.summary.variantCountsByType as any)["dependency-safe-main-zone-suffix-compaction"],1); const c=r.candidates[0] as any; assert.deepEqual(c.metadata.mainZoneSuffixTaskIds,[2,3,4,5]); assert.equal(c.assignments.find((a:any)=>a.taskId===2).startPlanned,"12:05"); assert.equal(c.assignments.find((a:any)=>a.taskId===3).startPlanned,"13:00"); assert.ok(c.metadata.dependencyWaitMinutes>0); assert.equal(c.metadata.suffixPreservedOrder,true); });
