import test from "node:test";
import assert from "node:assert/strict";
import { buildMacroMainZoneBlockRelayoutCandidates } from "./macroMainZoneBlockRelayoutCandidateBuilder";

const state = (extra:any={}) => ({ id:"s", planId:1, workDay:{start:"09:00",end:"18:00"}, tasks:[1,2,3,4,5,6,7].map(id=>({id,status:"pending"})), resources:[{id:10,typeName:"Coach"},{id:11,typeName:"Coach"}], spaces:{exclusiveById:{1:true},capacityById:{1:1}}, locks:[], constraints:{mealMode:"flexible_meal_window",optimizer:{mainFlowSpaceId:1,mainZoneMaxCoachSwitchesPerDay:4}}, availability:{workDay:{start:"09:00",end:"18:00"},mealWindow:{start:"13:00",end:"16:30"},globalHardBreaks:[],protectedBreaks:[]}, planning:[{taskId:1,startPlanned:"11:30",endPlanned:"12:05",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}], cognitive:{opportunities:[],searchSpaces:[],candidates:[],candidateStates:[],simulatedStates:[],validationResults:[],operationalValues:[],commitDecisions:[],evidence:[],metadata:{}}, ...extra } as any);
const blueprint:any = { candidateReadiness:{recommendedCandidateFamily:"macro_main_zone_block_relayout"}, mainZoneBlockBlueprint:{currentMainZoneVisibleGaps:[{start:"12:05",end:"14:20",gapMinutes:135}]}, mealBlueprint:{productiveWorkAllowedInsideMealWindow:true} };

test("Generates pull-next-main-zone-block candidate",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,1); assert.equal(r.candidates[0].metadata.variantType,"pull-next-main-zone-block-into-gap"); assert.equal(r.candidates[0].assignments.length,2); });
test("Preserves assignedSpace and assignedResources",()=>{ const c=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}).candidates[0] as any; assert.equal(c.assignments[0].assignedSpace,1); assert.deepEqual(c.assignments[0].assignedResources,[10]); });
test("Does not treat flexible meal window as hard stop",()=>{ const c=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}).candidates[0] as any; assert.equal(c.metadata.mealWindowTreatedAsHardStop,false); assert.equal(c.metadata.usesFlexibleMealWindowAsProductiveTime,true); });
test("Rejects or blocks if real hard break covers target window",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({availability:{workDay:{start:"09:00",end:"18:00"},protectedBreaks:[{start:"12:30",end:"13:00",kind:"global",code:"BREAK"}],globalHardBreaks:[{start:"12:30",end:"13:00"}],mealWindow:{start:"13:00",end:"16:30"}}}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,0); assert.ok(r.summary.candidateGenerationBlockers.includes("macro-main-zone-crosses-hard-break")); });
test("Detects support resource displacement variant",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({tasks:[1,2,3,4].map(id=>({id,status:"pending"})), planning:[...state().planning,{taskId:4,startPlanned:"12:10",endPlanned:"12:40",assignedResourceIds:[10],spaceId:2,operationalRole:"productive_task"}]}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates[0].metadata.variantType,"pull-next-main-zone-block-with-resource-block-displacement"); assert.ok((r.candidates[0].metadata.movedSupportTaskIds as number[]).includes(4)); });
test("Respects max moved tasks",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({constraints:{optimizer:{mainFlowSpaceId:1,macroMainZoneMaxMovedTasksPerCandidate:1,macroMainZoneBlockMinTasks:1}}}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.ok(r.candidates[0].assignments.length<=1); });
test("Respects coach switch policy",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({constraints:{optimizer:{mainFlowSpaceId:1,mainZoneMaxCoachSwitchesPerDay:0}}, planning:[state().planning[0],{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[11],spaceId:1,operationalRole:"productive_task"}]}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,0); });
test("Does not move done/in_progress/locked tasks",()=>{ const r=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state({tasks:[{id:1},{id:2,status:"done"},{id:3,status:"in_progress"}], locks:[{taskId:2,lockType:"full"}]}),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(r.candidates.length,0); });
test("Deterministic ordering",()=>{ const a=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}); const b=buildMacroMainZoneBlockRelayoutCandidates({operationalState:state(),productionWavePlanner:blueprint,baseHardFeasible:true}); assert.equal(JSON.stringify(a.candidates), JSON.stringify(b.candidates)); });
