import type { Candidate, OperationalState } from "../contracts";
import { resolveORCMainZoneTarget } from "../state/mainZoneTargetResolver";
import { resolveProductionWavePolicy } from "./productionWavePolicy";
import { analyzeProductionWaveBlocks } from "./productionWaveCoachBlockAnalyzer";
import { rankProductionWaveSubjects } from "./productionWaveTalentPriority";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}; const hh=(x:number)=>`${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`; const uniq=(xs:number[])=>[...new Set(xs.filter(Number.isFinite))].sort((a,b)=>a-b);
const protectedStatus=new Set(["done","in_progress"]); const deps=(t:any)=>uniq([...(t?.dependsOnTaskIds??[]),...(t?.dependsOnTaskId!=null?[t.dependsOnTaskId]:[])]);
function gaps(entries:any[]){return entries.slice(1).reduce((s:any[],e:any,i:number)=>{const p=entries[i]; if(e.a>p.b)s.push(e.a-p.b); return s;},[])}
function resourceIdle(entries:any[],r:number){const xs=entries.filter(e=>(e.assignedResourceIds??[]).includes(r)).sort((a,b)=>a.a-b.a); return gaps(xs).reduce((a,b)=>a+b,0)}
function talentWait(entries:any[], tasks:Map<number,any>){const m=new Map<number,any[]>(); for(const e of entries){const sid=tasks.get(e.taskId)?.contestantId; if(sid!=null)m.set(sid,[...(m.get(sid)??[]),e]);} return [...m.values()].reduce((sum,es)=>sum+gaps(es.sort((a,b)=>a.a-b.a)).reduce((a,b)=>a+b,0),0)}
function material(entries:any[], assignments:any[]){const by=new Map(assignments.map(a=>[a.taskId,a])); return entries.map(e=>{const a=by.get(e.taskId); return a?{...e,startPlanned:a.startPlanned,endPlanned:a.endPlanned,a:toMin(a.startPlanned),b:toMin(a.endPlanned),spaceId:a.spaceId??e.spaceId,assignedResourceIds:a.resourceIds}:e;}).sort((a,b)=>a.a-b.a||a.b-b.b)}
export function buildMacroProductionWaveDayShapeCandidates(args:{ operationalState?:OperationalState|null; productionConceptAlignment?:Record<string,any>|null; createdAt?:string|null }) {
 const state=args.operationalState; const policy=resolveProductionWavePolicy(state??{}); const candidates:Candidate[]=[]; const rejections:any[]=[]; if(!state) return {candidates, evidence:[], summary:summary(policy,null,null,candidates,rejections,"operational_state_missing")};
 const target=resolveORCMainZoneTarget(state as any); if(!target.configured) return {candidates,evidence:[],summary:summary(policy,null,null,candidates,rejections,"main_flow_not_configured")};
 const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const entries=(state.planning??[]).map((e:any)=>({...e,a:toMin(e.startPlanned),b:toMin(e.endPlanned),task:tasks.get(e.taskId)})).filter((e:any)=>e.a!=null&&e.b!=null).sort((a:any,b:any)=>a.a-b.a||a.b-b.b);
 const analysis=analyzeProductionWaveBlocks({operationalState:state,productionWavePolicy:policy,mainZoneTarget:target,currentPlanning:state.planning}); const priority=rankProductionWaveSubjects({operationalState:state,analysis,baselinePlanning:state.planning});
 if(!analysis.candidateMainFlowBlocks.length){ rejections.push({candidateId:"candidate:macro-production-wave-day-shape:1",reason:"no-main-flow-resource-blocks",readOnly:true}); return {candidates,evidence:[],summary:summary(policy,analysis,priority,candidates,rejections,"no_candidate_built")}; }
 const locked=new Set((state.locks??[]).map((l:any)=>l.taskId)); const byId=new Map(entries.map((e:any)=>[e.taskId,e])); const orderedSubject=new Map(priority.orderedSubjects.map((s:any,i:number)=>[s.subjectId,i]));
 const blocks=analysis.candidateMainFlowBlocks.slice(0,policy.values.coachBlocks.preferredMainFlowCoachBlocks+2).sort((a,b)=>b.score-a.score||a.resourceId-b.resourceId);
 const seqIds:number[]=[]; for(const block of blocks){ const mains=block.mainTaskIds.map(id=>byId.get(id)).filter(Boolean).sort((a:any,b:any)=>(orderedSubject.get(a.task?.contestantId)??999)-(orderedSubject.get(b.task?.contestantId)??999)||a.a-b.a); for(const main of mains){ for(const pid of (analysis.prerequisiteTasksByMainTask[main.taskId]??[])) if(!seqIds.includes(pid)) seqIds.push(pid); if(!seqIds.includes(main.taskId)) seqIds.push(main.taskId); }}
 const movable=seqIds.map(id=>byId.get(id)).filter((e:any)=>e&&!protectedStatus.has(String(e.task?.status))&&!locked.has(e.taskId)); if(movable.length<2){ rejections.push({candidateId:"candidate:macro-production-wave-day-shape:1",reason:"insufficient-movable-wave-tasks",movedTaskIds:movable.map((e:any)=>e.taskId),readOnly:true}); return {candidates,evidence:[],summary:summary(policy,analysis,priority,candidates,rejections,"candidate_invalid")}; }
 const first=analysis.mainFlowTasks[0]; let cursor=first?.a ?? toMin(state.workDay?.start) ?? 8*60; const mealStart=toMin(analysis.mealWindow?.start), mealEnd=toMin(analysis.mealWindow?.end); const assignments:any[]=[]; const scheduled=new Map<number,{s:number;e:number}>();
 for(const e of movable){ const dur=e.b-e.a; const sid=e.task?.contestantId; const win=sid!=null?(state.availability?.contestantAvailabilityById??{})[sid]:null; const ws=toMin(win?.start), we=toMin(win?.end); if(ws!=null) cursor=Math.max(cursor,ws); if(policy.values.meal.treatFlexibleMealAsHardStop && mealStart!=null&&mealEnd!=null && cursor<mealEnd&&cursor+dur>mealStart) cursor=mealEnd; const prereqEnd=Math.max(0,...deps(e.task).map(id=>scheduled.get(id)?.e ?? byId.get(id)?.b ?? 0)); cursor=Math.max(cursor,prereqEnd); if(we!=null && cursor+dur>we){ rejections.push({candidateId:"candidate:macro-production-wave-day-shape:1",reason:"availability",taskId:e.taskId,window:win,readOnly:true}); continue; } assignments.push({taskId:e.taskId,startPlanned:hh(cursor),endPlanned:hh(cursor+dur),spaceId:e.spaceId??null,resourceIds:[...(e.assignedResourceIds??[])]}); scheduled.set(e.taskId,{s:cursor,e:cursor+dur}); cursor+=dur; }
 if(assignments.length<2){ rejections.push({candidateId:"candidate:macro-production-wave-day-shape:1",reason:"no-feasible-assignments",readOnly:true}); return {candidates,evidence:[],summary:summary(policy,analysis,priority,candidates,rejections,"candidate_invalid")}; }
 const beforeMain=analysis.mainFlowTasks; const after=material(entries,assignments); const afterMain=after.filter(e=>analysis.mainFlowTasks.some((m:any)=>m.taskId===e.taskId)); const mainIdleBefore=gaps(beforeMain).reduce((a,b)=>a+b,0), mainIdleAfter=gaps(afterMain).reduce((a,b)=>a+b,0); const criticalIds=analysis.resourceCriticality.slice(0,4).map(r=>r.resourceId); const beforeRes=Object.fromEntries(criticalIds.map(r=>[r,resourceIdle(entries,r)])); const afterRes=Object.fromEntries(criticalIds.map(r=>[r,resourceIdle(after,r)])); const beforeWait=talentWait(entries,tasks), afterWait=talentWait(after,tasks);
 const moved=assignments.filter(a=>{const e=byId.get(a.taskId)!; return e.startPlanned!==a.startPlanned||e.endPlanned!==a.endPlanned;}).map(a=>a.taskId); const improves=mainIdleAfter<mainIdleBefore || criticalIds.some(r=>(afterRes as any)[r]<(beforeRes as any)[r]) || afterWait<beforeWait;
 if(!improves){ rejections.push({candidateId:"candidate:macro-production-wave-day-shape:1",reason:"no_improvement_operational_value",mainFlowIdleBefore:mainIdleBefore,mainFlowIdleAfter:mainIdleAfter,criticalResourceIdleBefore:beforeRes,criticalResourceIdleAfter:afterRes,readOnly:true}); }
 const candidate:Candidate={id:"candidate:macro-production-wave-day-shape:1",state:{status:"draft",evidenceIds:["evidence:macro-production-wave-day-shape:1"],metadata:{}},assignments,operationalValues:[],evidenceIds:["evidence:macro-production-wave-day-shape:1"],metadata:{strategy:"MACRO_PRODUCTION_WAVE_DAY_SHAPE",family:"macro-production-wave-day-shape",variantType:"coach-aligned-main-flow-block",planningInfluence:"candidate-transformations",executesTransformations:true,mainFlowBlockPlan:blocks,coachBlockPlan:analysis.coachLikeResourceBlocks,talentPriorityOrder:priority.orderedSubjects,prerequisitePlacementPlan:analysis.prerequisiteTasksByMainTask,mealUsagePlan:{mealWindow:analysis.mealWindow,flexible:policy.values.meal.allowFlexibleMealWindowProductiveWork,treatAsHardStop:policy.values.meal.treatFlexibleMealAsHardStop},movedTaskIds:moved,mainFlowTasksMoved:moved.filter(id=>analysis.mainFlowTasks.some((e:any)=>e.taskId===id)),prerequisiteTasksMoved:moved.filter(id=>Object.values(analysis.prerequisiteTasksByMainTask).flat().includes(id)),resourceBlocksCompacted:criticalIds,expectedMainFlowIdleBefore:mainIdleBefore,expectedMainFlowIdleAfter:mainIdleAfter,expectedResourceIdleBefore:beforeRes,expectedResourceIdleAfter:afterRes,expectedTalentWaitBefore:beforeWait,expectedTalentWaitAfter:afterWait,configurationUsed:policy.values,evidenceRefs:["productionWaveBlockAnalysis","talentPriority"],targetGapMinutesBefore:Math.max(0,...gaps(beforeMain)),expectedTargetGapMinutesAfter:Math.max(0,...gaps(afterMain)),movedMainZoneTaskIds:moved.filter(id=>analysis.mainFlowTasks.some((e:any)=>e.taskId===id)),affectedResourceIds:criticalIds,affectedSpaceIds:uniq(assignments.map(a=>a.spaceId).filter((x:any)=>x!=null)),confidence:0.72,rejectionReasons:improves?[]:["no_improvement_operational_value"]}};
 candidates.push(candidate); return {candidates,evidence:[],summary:summary(policy,analysis,priority,candidates,rejections,candidates.length?"candidates_generated":"no_candidate_built")};
}
function summary(policy:any,analysis:any,priority:any,candidates:Candidate[],rejections:any[],reason:string){ const md:any=candidates[0]?.metadata??{}; return {contractVersion:"ORC-MACRO-PRODUCTION-WAVE-DAY-SHAPE-ID250",executed:true,reason,candidateCount:candidates.length,candidateIds:candidates.map(c=>c.id),selectedAsCommit:false,selectedCandidateId:null,selectedSimulatedStateId:null,rejectionReasons:rejections.map(r=>r.reason),rejectedCandidateDetails:rejections,mainFlowIdleBefore:md.expectedMainFlowIdleBefore??null,mainFlowIdleAfter:md.expectedMainFlowIdleAfter??null,largestGapBefore:md.targetGapMinutesBefore??null,largestGapAfter:md.expectedTargetGapMinutesAfter??null,criticalResourceIdleBefore:md.expectedResourceIdleBefore??{},criticalResourceIdleAfter:md.expectedResourceIdleAfter??{},talentWaitBefore:md.expectedTalentWaitBefore??null,talentWaitAfter:md.expectedTalentWaitAfter??null,coachBlockPlan:analysis?.coachLikeResourceBlocks??[],talentPriorityOrder:priority?.orderedSubjects??[],mainFlowBlockPlan:md.mainFlowBlockPlan??analysis?.candidateMainFlowBlocks??[],prerequisitePlacementPlan:md.prerequisitePlacementPlan??analysis?.prerequisiteTasksByMainTask??{},mealUsagePlan:md.mealUsagePlan??{mealWindow:analysis?.mealWindow??null,flexible:policy.values.meal.allowFlexibleMealWindowProductiveWork,treatAsHardStop:policy.values.meal.treatFlexibleMealAsHardStop},configurationUsed:policy.values,explanation:candidates.length?`Intentó construir una jornada macro agrupando recursos críticos/coaches ${analysis?.coachLikeResourceBlocks?.map((b:any)=>b.resourceId).join(", ")}, colocando prerequisitos inmediatamente antes de tareas de flujo principal, priorizando talentos ${priority?.orderedSubjects?.map((s:any)=>s.subjectId).join(", ")}, y usando la comida como ${policy.values.meal.treatFlexibleMealAsHardStop?"parada dura":"ventana flexible"}. ${rejections.length?`Restricciones/rechazos: ${[...new Set(rejections.map(r=>r.reason))].join(", ")}.`:"El candidato queda para simulación, validación y evaluación OperationalValue."}`:`No se pudo construir candidato macro day-shape: ${reason}.`,readOnly:true}; }
