import type { OperationalState } from "../contracts";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}; const hh=(x:number)=>`${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`;
const subject=(t:any)=>t?.contestantId??t?.contestant_id??t?.talentId??t?.talent_id??t?.participantId??t?.participant_id??t?.itinerantTeamId??t?.itinerant_team_id??null;
export function buildMacroProductionWaveLanes(args:{operationalState:OperationalState; taskClassification:any; mainTaskIds:number[]; prerequisiteTaskIds:number[]; resourceIds:number[]; startMinute:number}){
 const state=args.operationalState; const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const entries=new Map((state.planning??[]).map((e:any)=>[e.taskId,{...e,a:toMin(e.startPlanned),b:toMin(e.endPlanned),task:tasks.get(e.taskId)}]));
 const mainFlowLane:any[]=[]; const assignments:any[]=[]; const endByTask=new Map<number,number>(); const resCursor=new Map<number,number>(); const spaceCursor=new Map<number,number>(); const subjCursor=new Map<any,number>();
 const place=(id:number,lane:string,notBefore:number)=>{const e:any=entries.get(id); if(!e||e.a==null||e.b==null)return null; const dur=e.b-e.a; const rs=e.assignedResourceIds??[]; const sid=subject(e.task); let s=Math.max(notBefore,...rs.map((r:number)=>resCursor.get(r)??args.startMinute),e.spaceId!=null?(spaceCursor.get(e.spaceId)??args.startMinute):args.startMinute,sid!=null?(subjCursor.get(sid)??args.startMinute):args.startMinute); const out={taskId:id,startPlanned:hh(s),endPlanned:hh(s+dur),spaceId:e.spaceId??null,resourceIds:[...rs],lane}; assignments.push(out); endByTask.set(id,s+dur); for(const r of rs)resCursor.set(r,s+dur); if(e.spaceId!=null)spaceCursor.set(e.spaceId,s+dur); if(sid!=null)subjCursor.set(sid,s+dur); if(lane==="mainFlowLane")mainFlowLane.push(out); return out;};
 for(const mid of args.mainTaskIds){ const prereqs=(args.taskClassification.upstreamPrerequisiteTaskIdsByMainTask?.[mid]??[]).filter((id:number)=>args.prerequisiteTaskIds.includes(id)); for(const pid of prereqs) if(!endByTask.has(pid)) place(pid,`resourceLane:${(entries.get(pid) as any)?.assignedResourceIds?.[0]??"none"}`,args.startMinute); place(mid,"mainFlowLane",Math.max(args.startMinute,...prereqs.map((id:number)=>endByTask.get(id)??args.startMinute))); }
 const resourceLanesByResourceId:any={}; const spaceLanesBySpaceId:any={}; const subjectLanesBySubjectId:any={}; for(const a of assignments){ for(const r of a.resourceIds??[]) (resourceLanesByResourceId[r]??=[]).push(a); if(a.spaceId!=null)(spaceLanesBySpaceId[a.spaceId]??=[]).push(a); const sid=subject((entries.get(a.taskId) as any)?.task); if(sid!=null)(subjectLanesBySubjectId[sid]??=[]).push(a); }
 return {assignments, lanePlan:{mainFlowLane,resourceLanesByResourceId,spaceLanesBySpaceId,subjectLanesBySubjectId,parallelLaneCount:Object.keys(resourceLanesByResourceId).length,readOnly:true}};
}
