import type { Candidate, CandidateState, OperationalState } from "../contracts";
import { resolveORCMainZoneTarget } from "../state/mainZoneTargetResolver";
import { resolveProductionWavePolicy } from "./productionWavePolicy";
import { buildProductionWaveDependencyClosure } from "./productionWaveDependencyClosure";

type Rec = Record<string, any>;
const m = (t?: string | null) => { const p=String(t??"").split(":").map(Number); return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null; };
const hh = (x:number) => `${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`;
const uniq = (xs:number[]) => [...new Set(xs.filter(Number.isFinite))].sort((a,b)=>a-b);
const PROTECTED = new Set(["done","in_progress"]);
const isWork = (e:any) => e.countsAsWork !== false && !["transport_arrival","transport_departure","meal_break_placeholder","global_break_placeholder","non_operational_placeholder"].includes(e.operationalRole);
function entries(state: OperationalState) { const tasks=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); return (state.planning??[]).map((e:any)=>({...e,a:m(e.startPlanned),b:m(e.endPlanned),task:tasks.get(e.taskId)})).filter(e=>e.a!=null&&e.b!=null).sort((x,y)=>x.a-y.a||x.b-y.b||x.taskId-y.taskId); }
function deps(task:any){ return uniq([...(task?.dependsOnTaskIds??[]), ...(task?.dependsOnTaskId!=null?[task.dependsOnTaskId]:[])]); }
function blocked(e:any,state:OperationalState){ return PROTECTED.has(String(e?.task?.status)) || (state.locks??[]).some((l:any)=>l.taskId===e.taskId); }
function gaps(main:any[]) { return main.slice(1).flatMap((e,i)=> e.a>main[i].b ? [{ id:`production-wave-gap:${main[i].taskId}:${e.taskId}:${main[i].b}-${e.a}`, a:main[i].b,b:e.a,minutes:e.a-main[i].b,previous:main[i],next:e }] : []); }
function overlap(a:number,b:number,c:number,d:number){ return a<d&&c<b; }
function noOverlap(start:number,dur:number,e:any,all:any[],moved:Set<number>){ let s=start; for(;;){ const hit=all.find(x=>!moved.has(x.taskId)&&isWork(x)&&overlap(s,s+dur,x.a,x.b)&&((x.spaceId!=null&&x.spaceId===e.spaceId)||(x.assignedResourceIds??[]).some((r:number)=>(e.assignedResourceIds??[]).includes(r)))); if(!hit) return s; s=hit.b; } }
export function buildProductionWaveDependencyBundleCandidates(args:{ operationalState?:OperationalState|null; productionConceptAlignment?:Rec|null; createdAt?:string|null }) {
 const state=args.operationalState; const policy=resolveProductionWavePolicy(state??{}); const candidates:Candidate[]=[]; const opportunities:any[]=[]; const rejections:Rec[]=[];
 if(!state) return { candidates, opportunities, summary: summary(policy, candidates, opportunities, rejections, "operational_state_missing") };
 const target=resolveORCMainZoneTarget(state as any); if(!target.configured) return { candidates, opportunities, summary: summary(policy, candidates, opportunities, rejections, "main_flow_not_configured") };
 const es=entries(state), byId=new Map(es.map(e=>[e.taskId,e])); const main=es.filter(e=>isWork(e)&&((e.spaceId!=null&&target.mainSpaceIds.includes(e.spaceId))||(e.zoneId!=null&&target.mainZoneIds.includes(e.zoneId))));
 for(const gap of gaps(main).filter(g=>g.minutes>policy.values.mainFlow.maxVisibleIdleMinutes)){
   const direct=deps(gap.next.task).map(id=>byId.get(id)).filter(Boolean);
   const initialTaskIds=uniq([gap.next.taskId, ...direct.map((e:any)=>e.taskId)]);
   const closure=buildProductionWaveDependencyClosure({ operationalState:state, initialTaskIds, mainTaskIds:[gap.next.taskId], maxBundleSearchDepth:policy.values.runtime.maxBundleSearchDepth, maxDependencyBundleSize:policy.values.runtime.maxDependencyBundleSize });
   const bundle=closure.includedTaskIds.map(id=>byId.get(id)).filter(Boolean);
   const prereq=closure.prerequisiteTaskIds.map(id=>byId.get(id)).filter(Boolean);
   const blockingDependencyTaskIds=uniq(prereq.map((e:any)=>e.taskId)); const blockingResourceIds=uniq(bundle.flatMap((e:any)=>e.assignedResourceIds??[]));
   opportunities.push({ kind:"PRODUCTION_WAVE_GAP", subtype:"dependency_bundle_required", id:gap.id, gapStart:hh(gap.a), gapEnd:hh(gap.b), gapMinutes:gap.minutes, previousMainTaskId:gap.previous.taskId, nextMainTaskId:gap.next.taskId, blockingDependencyTaskIds, blockingResourceIds, estimatedBundleSize:bundle.length, estimatedOperationalImpact:gap.minutes, dependencyClosureComplete:closure.dependencyClosureComplete, brokenDependencyPairs:closure.brokenDependencyPairs, readOnly:true });
   const nextCandidateId=`candidate:production-wave-dependency-bundle:${candidates.length+rejections.length+1}`;
   if(!closure.dependencyClosureComplete){ rejections.push({ candidateId:nextCandidateId, reason:"dependency_closure_incomplete", detailReasons:closure.hardBlockers, blockedDependencyPairs:closure.brokenDependencyPairs, missingDependencyTaskIds:closure.missingDependencyTaskIds, dependencyClosureComplete:false }); continue; }
   const bad=bundle.find((e:any)=>blocked(e,state)); if(bad){ rejections.push({ candidateId:nextCandidateId, reason: PROTECTED.has(String(bad.task?.status))?"protected_prerequisite":"LOCK_VIOLATION", taskId:bad.taskId, dependencyClosureComplete:false }); continue; }
   const ordered=[...prereq.sort((a:any,b:any)=>a.a-b.a||a.taskId-b.taskId), gap.next]; const moved=new Set(ordered.map((e:any)=>e.taskId)); let cursor=gap.a; const assignments:any[]=[]; const movementTrace:any[]=[];
   for(const e of ordered){ const dur=e.b-e.a; const start=noOverlap(cursor,dur,e,es,moved); const role=closure.dependencyRoleByTaskId[String(e.taskId)]??(e.taskId===gap.next.taskId?"main":"prerequisite"); assignments.push({ taskId:e.taskId, startPlanned:hh(start), endPlanned:hh(start+dur), spaceId:e.spaceId??null, resourceIds:[...(e.assignedResourceIds??[])] }); movementTrace.push({ taskId:e.taskId, previousStart:e.startPlanned, previousEnd:e.endPlanned, proposedStart:hh(start), proposedEnd:hh(start+dur), reason: role==="main"?"close_main_flow_gap_after_prerequisites":"move_prerequisite_before_dependent_main_task", dependencyRole:role, dependencyDepth:closure.dependencyDepthByTaskId[String(e.taskId)]??0, sourceGapId:gap.id, readOnly:true }); cursor=start+dur; }
   const after=Math.max(0, (assignments.find(a=>a.taskId===gap.next.taskId)?.startPlanned ? m(assignments.find(a=>a.taskId===gap.next.taskId)?.startPlanned)! - gap.a : gap.minutes));
   candidates.push({ id:`candidate:production-wave-dependency-bundle:${candidates.length+1}`, state:{status:"draft",evidenceIds:[`evidence:production-wave-dependency-bundle:${candidates.length+1}`],metadata:{}}, assignments, operationalValues:[], evidenceIds:[`evidence:production-wave-dependency-bundle:${candidates.length+1}`], metadata:{ strategy:"PRODUCTION_WAVE_DEPENDENCY_BUNDLE", family:"macro-production-wave-dependency-bundle", type:"dependency-bundle", variantType:"pull-prerequisites-and-main-task", planningInfluence:"candidate-transformations", executesTransformations:true, readOnly:false, sourceOpportunityId:gap.id, movementTrace, targetGapStart:hh(gap.a), targetGapEnd:hh(gap.b), targetGapMinutesBefore:gap.minutes, expectedTargetGapMinutesAfter:after, expectedVisibleMainZoneIdleReductionMinutes:Math.max(0,gap.minutes-after), movedTaskIds:ordered.map(e=>e.taskId), movedMainZoneTaskIds:closure.mainTaskIds, movedPrerequisiteTaskIds:closure.prerequisiteTaskIds, movedSupportTaskIds:closure.supportTaskIds, movedResourceBlockerTaskIds:closure.resourceBlockerTaskIds, blockingDependencyTaskIds, blockingResourceIds, dependencyClosureComplete:true, blockedDependencyPairs:[], missingDependencyTaskIds:[], productionWavePolicy:policy.values } });
 }
 return { candidates: candidates.slice(0, policy.values.runtime.macroPlannerCandidateBudget), opportunities, summary: summary(policy, candidates, opportunities, rejections, candidates.length?"candidates_generated":"no_dependency_bundle_candidate") };
}
function summary(policy:any,candidates:Candidate[],opportunities:any[],rejections:Rec[],reason:string){ const blockedDependencyPairs=rejections.flatMap(r=>Array.isArray(r.blockedDependencyPairs)?r.blockedDependencyPairs:[]); const missingDependencyTaskIds=uniq(rejections.flatMap(r=>Array.isArray(r.missingDependencyTaskIds)?r.missingDependencyTaskIds:[])); return { contractVersion:"ORC-PRODUCTION-WAVE-DEPENDENCY-BUNDLE-ID246", executed:true, reason, candidateCount:candidates.length, candidateIds:candidates.map(c=>c.id), opportunitiesDetected:opportunities.length, opportunities, selectedAsCommit:false, selectedCandidateId:null, selectedSimulatedStateId:null, rejectedCandidateIds:rejections.map(r=>r.candidateId), rejectionReasons:rejections.map(r=>r.reason), rejectedCandidateDetails:rejections, blockedDependencyPairs, missingDependencyTaskIds, dependencyClosureComplete:rejections.length?false:(candidates.length?true:null), policyUsed:policy.values, explanation: rejections.length?`El ORC intentó cerrar huecos del flujo principal moviendo prerequisitos junto con el bloque dependiente, pero rechazó candidatos por: ${uniq(rejections.map(r=>String(r.reason)) as any).join(", ")}. ${blockedDependencyPairs.length?`Dependencias bloqueadas: ${blockedDependencyPairs.map((p:any)=>`${p.taskId}->${p.dependsOnTaskId} (${p.reason})`).join(", ")}.`:""} ${missingDependencyTaskIds.length?`Dependencias faltantes o protegidas: ${missingDependencyTaskIds.join(", ")}.`:""} Por eso se conserva la mejor solución anterior.`:"El ORC generó candidatos dependency-bundle para adelantar prerequisitos y el siguiente bloque del flujo principal mediante simulación y validación.", readOnly:true }; }
export function applyProductionWaveDependencyBundleCandidate(state:OperationalState,candidate:Candidate): CandidateState { return { id:`candidate-state:${candidate.id}`, candidateId:candidate.id, strategy:"PRODUCTION_WAVE_DEPENDENCY_BUNDLE", originOpportunity:String(candidate.metadata.sourceOpportunityId??"PRODUCTION_WAVE_GAP"), plannedTransformations:[{kind:"MOVE_CHAIN",reason:"production_wave_dependency_bundle"}], estimatedImpact:{ movementTrace:Array.isArray(candidate.metadata.movementTrace)?candidate.metadata.movementTrace:[], readOnly:true }, estimatedCost:{ movedTaskCount:candidate.assignments.length, readOnly:true }, confidence:0.8, sourceAssignments:candidate.assignments }; }
