import test from "node:test";
import assert from "node:assert/strict";
import { buildProductionWavePlannerBlueprint } from "./productionWavePlannerBlueprint";

const base = (extra:any={}) => ({
  id:"s", planId:1, workDay:{start:"09:00",end:"18:00"},
  tasks:[{id:1,contestantId:1},{id:2,contestantId:1},{id:3,contestantId:1},{id:4,contestantId:2},{id:5,contestantId:2},{id:6,contestantId:2}],
  resources:[{id:101,typeName:"Coach"},{id:102,typeName:"Coach"}],
  spaces:{parentById:{},nameById:{10:"Main"},capacityById:{},concurrencyById:{},exclusiveById:{},priorityById:{},zoneIdBySpaceId:{}},
  availability:{workDay:{start:"09:00",end:"18:00"},meal:null,mealWindow:{start:"13:00",end:"16:30"},actualMeal:null,globalHardBreaks:[],protectedBreaks:[],contestantAvailabilityById:{}},
  dependencies:[], locks:[], constraints:{mealMode:"flexible_meal_window",optimizer:{mainFlowSpaceId:10}}, operationalMetrics:{}, cognitive:{opportunities:[],searchSpaces:[],candidates:[],candidateStates:[],simulatedStates:[],validationResults:[],operationalValues:[],commitDecisions:[],evidence:[],metadata:{}}, source:"EngineInput", schemaVersion:"ORC-SPEC-01",
  planning:[
    {taskId:1,startPlanned:"09:00",endPlanned:"09:15",assignedResourceIds:[],operationalRole:"transport_arrival",countsAsWork:false},
    {taskId:2,startPlanned:"12:00",endPlanned:"12:05",assignedResourceIds:[101],spaceId:10,operationalRole:"productive_task"},
    {taskId:4,startPlanned:"09:05",endPlanned:"09:20",assignedResourceIds:[],operationalRole:"transport_arrival",countsAsWork:false},
    {taskId:5,startPlanned:"14:20",endPlanned:"15:20",assignedResourceIds:[102],spaceId:10,operationalRole:"productive_task"},
    {taskId:3,startPlanned:"17:00",endPlanned:"17:15",assignedResourceIds:[],operationalRole:"transport_departure",countsAsWork:false},
    {taskId:6,startPlanned:"17:10",endPlanned:"17:25",assignedResourceIds:[],operationalRole:"transport_departure",countsAsWork:false},
  ], ...extra
} as any);
const align = { verdict:"conceptually_misaligned", macroPlannerRequired:true, visibleMainZoneGaps:[{start:"12:05",end:"14:20",gapMinutes:135,previousTaskId:2,nextTaskId:5}], readOnly:true };

test("genera blueprint v4-43-like", () => { const b:any=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:align, planningSource:"selected-orc-simulation", selectedSimulatedStateId:"sim"}); assert.equal(b.executed,true); assert.equal(b.blueprintGenerated,true); assert.ok(["blueprint_ready","blueprint_partial"].includes(b.blueprintVerdict)); assert.equal(b.candidateReadiness.recommendedCandidateFamily,"macro_main_zone_block_relayout"); assert.equal(b.macroPlannerRequired,true); assert.equal(b.doesNotMutatePlanning,true); });
test("no trata comida flexible como parón global", () => { const b:any=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:align}); assert.equal(b.mealBlueprint.productiveWorkAllowedInsideMealWindow,true); assert.equal(b.mealBlueprint.candidateFamilyRecommendation,"macro_meal_rotation"); assert.equal(b.mealBlueprint.actualGlobalBreaks.length,0); });
test("propone bloques de coach configurables", () => { const s=base({constraints:{mealMode:"flexible_meal_window",optimizer:{mainFlowSpaceId:10,mainZoneMaxCoachSwitchesPerDay:4}}}); const b:any=buildProductionWavePlannerBlueprint({operationalState:s, productionConceptAlignment:align}); assert.ok(b.mainZoneBlockBlueprint.recommendedCoachSwitchCount<=4); assert.deepEqual(b.candidateReadiness.missingConfig.includes("mainZoneCoachSwitchPolicy"),false); });
test("política de coach usa defaultProfile sin missing crítico", () => { const b:any=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:align}); assert.equal(b.warnings.includes("main_zone_coach_switch_policy_missing"), false); assert.equal(b.candidateReadiness.missingConfig.includes("mainZoneCoachSwitchPolicy"), false); assert.ok(b.productionWavePolicy.defaultedFields.includes("coachBlocks.preferredMainFlowCoachBlocks")); assert.equal(b.blueprintVerdict,"blueprint_ready"); });
test("detecta balance de recursos críticos", () => { const s=base({constraints:{optimizer:{mainFlowSpaceId:10,mainZoneMaxCoachSwitchesPerDay:4,releasePolicy:{enabled:true},maxComparableResourceSpanImbalanceMinutes:30,comparableWorkloadToleranceMinutes:200}}, planning:[...base().planning, {taskId:7,startPlanned:"09:30",endPlanned:"10:00",assignedResourceIds:[101],spaceId:10,operationalRole:"productive_task"},{taskId:8,startPlanned:"17:30",endPlanned:"18:00",assignedResourceIds:[101],spaceId:10,operationalRole:"productive_task"},{taskId:9,startPlanned:"14:00",endPlanned:"15:00",assignedResourceIds:[102],spaceId:10,operationalRole:"productive_task"}]}); const b:any=buildProductionWavePlannerBlueprint({operationalState:s, productionConceptAlignment:{...align,visibleMainZoneGaps:[]}}); assert.ok(b.criticalResourceBlueprint.spanImbalanceIssues.length>0); assert.equal(b.criticalResourceBlueprint.candidateFamilyRecommendation,"macro_coach_block_balance"); });
test("propone call-time shift", () => { const b:any=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:{}}); assert.ok(b.talentFlowBlueprint.callTimeShiftRecommendations.length>0); });
test("propone release wave si hay política", () => { const s=base({constraints:{optimizer:{mainFlowSpaceId:10,releasePolicy:{enabled:true},maxLastTaskToDepartureWaitMinutes:30}}}); const b:any=buildProductionWavePlannerBlueprint({operationalState:s, productionConceptAlignment:{}}); assert.ok(b.talentFlowBlueprint.releaseShiftRecommendations.length>0); });
test("si falta release policy, usa default explícito y no bloquea", () => { const b:any=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:{}}); assert.equal(b.talentFlowBlueprint.missingReleasePolicy,false); assert.equal(b.candidateReadiness.missingConfig.includes("releasePolicy"), false); assert.ok(b.productionWavePolicy.defaultedFields.includes("release.maxLastTaskToDepartureWaitMinutes")); });
test("start later sólo si procede", () => { const noMainGap={...align,visibleMainZoneGaps:[]}; const b:any=buildProductionWavePlannerBlueprint({operationalState:base({planning:base().planning.filter((e:any)=>e.taskId!==5)}), productionConceptAlignment:noMainGap}); assert.equal(b.startLaterBlueprint.startLaterRecommended,true); const c:any=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:align}); assert.equal(c.startLaterBlueprint.startLaterRecommended,false); assert.equal(c.candidateReadiness.recommendedCandidateFamily,"macro_main_zone_block_relayout"); });
test("determinismo", () => { const a=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:align}); const b=buildProductionWavePlannerBlueprint({operationalState:base(), productionConceptAlignment:align}); assert.equal(JSON.stringify(a), JSON.stringify(b)); });
