import type { OperationalState } from "../contracts";
import type { ProductionWaveBlockAnalysis } from "./productionWaveCoachBlockAnalyzer";
const toMin=(t?:string|null)=>{const p=String(t??"").split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null};
export const resolveProductionWaveSubjectIdentity=(task:any)=>{ const fields=["contestantId","contestant_id","talentId","talent_id","participantId","participant_id","itinerantTeamId","itinerant_team_id"]; for(const f of fields){ const v=task?.[f]; if(v!==undefined&&v!==null&&v!=="") return {subjectId:v, source:f}; } return {subjectId:null, source:null}; };
export function rankProductionWaveSubjects(args:{ operationalState: OperationalState; analysis: ProductionWaveBlockAnalysis; baselinePlanning?: any[] }) {
 const state=args.operationalState; const byTask=new Map((state.tasks??[]).map((t:any)=>[t.id,t])); const main=new Set(args.analysis.mainFlowTasks.map((e:any)=>e.taskId)); const critical=new Set(args.analysis.resourceCriticality.slice(0,4).map(r=>r.resourceId));
 const bySubject=new Map<any,any>(); const sourceSet=new Set<string>(); const tasksWithoutSubjectId:number[]=[]; for(const t of state.tasks??[]){ const id=resolveProductionWaveSubjectIdentity(t); if(id.subjectId!=null){ sourceSet.add(String(id.source)); const x=bySubject.get(id.subjectId)??{subjectId:id.subjectId, taskIds:[], sources:new Set<string>()}; x.taskIds.push(t.id); x.sources.add(id.source); bySubject.set(id.subjectId,x); } else tasksWithoutSubjectId.push(t.id); }
 const pressureById=new Map(args.analysis.talentAvailabilityPressure.map((p:any)=>[p.subjectId,p])); const pressure=[...bySubject.values()].map((x:any)=>pressureById.get(x.subjectId)??{subjectId:x.subjectId,availableMinutes:null,taskIds:x.taskIds,score:0});
 const items=pressure.map(p=>{ const entries=(args.baselinePlanning??state.planning??[]).filter((e:any)=>p.taskIds.includes(e.taskId)); const w=(state.availability?.contestantAvailabilityById??{})[p.subjectId]; const ws=toMin(w?.start), we=toMin(w?.end); const dur=entries.reduce((s:any,e:any)=>s+(toMin(e.endPlanned)!-toMin(e.startPlanned)!),0); const mainCount=entries.filter((e:any)=>main.has(e.taskId)).length; const criticalCount=entries.filter((e:any)=>(e.assignedResourceIds??[]).some((r:number)=>critical.has(r))).length; const depCount=entries.reduce((s:any,e:any)=>s+((byTask.get(e.taskId) as any)?.dependsOnTaskIds?.length??0),0); const factors={ narrowWindow: p.availableMinutes==null?0:Math.max(0,720-p.availableMinutes), earlyDeparture: we==null?0:Math.max(0,18*60-we), lateArrival: ws==null?0:Math.max(0,ws-8*60), taskCount: entries.length*10, pendingDuration: dur/5, mainFlow: mainCount*40, criticalResources: criticalCount*30, dependencies: depCount*15, impossibleLaterRisk:(we!=null&&entries.some((e:any)=>toMin(e.endPlanned)!>we-30)?50:0), stability: -entries.length };
 const score=Object.values(factors).reduce((a:any,b:any)=>a+b,0); return { subjectId:p.subjectId, score, factors, taskIds:p.taskIds, explanation:`Prioridad ${score}: ventana ${w?.start??"?"}-${w?.end??"?"}, ${mainCount} tareas main flow, ${criticalCount} tareas con recursos críticos.` }; });
 const orderedSubjects=items.sort((a,b)=>b.score-a.score||String(a.subjectId).localeCompare(String(b.subjectId))); return { orderedSubjects, talentPriorityOrder:orderedSubjects, scoreBySubjectId:Object.fromEntries(items.map(i=>[i.subjectId,i.factors])), subjectIdentitySource:[...sourceSet].sort(), subjectsDetected:orderedSubjects.map(s=>s.subjectId), tasksWithoutSubjectId, subjectIdentityWarnings:orderedSubjects.length?[]:["subject_identity_unavailable"], talentPriorityUnavailable:orderedSubjects.length===0, talentPriorityUnavailableReason:orderedSubjects.length===0?"no supported subject identity fields found on tasks":null, explanation:"Ordena talentos por presión de disponibilidad, dependencias, flujo principal, recursos críticos y coste de estabilidad.", readOnly:true };
}
