import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { buildInitialConstructionMap } from "./initialConstructionMap";

const uniq=(a:number[])=>[...new Set(a.filter(Number.isFinite))].sort((x,y)=>x-y);
const dur=(t:any)=>Number(t?.durationOverrideMin??t?.durationMin??t?.durationMinutes??t?.duration??0)||0;

export interface InitialConstructionResidualContext { readonly basePartialPlanId:string|null; readonly baseBranchId:string|null; readonly provisionalAssignments:readonly any[]; readonly provisionallyAssignedTaskIds:readonly number[]; readonly residualPendingTaskIds:readonly number[]; readonly residualProductiveTaskIds:readonly number[]; readonly provisionallySatisfiedDependencyTaskIds:readonly number[]; readonly provisionalOccupancyByContestant:Readonly<Record<string,number>>; readonly provisionalOccupancyBySpace:Readonly<Record<string,number>>; readonly provisionalOccupancyByResource:Readonly<Record<string,number>>; readonly provisionalOccupancyByPlanResourceItem:Readonly<Record<string,number>>; readonly provisionalDemandReservationByResourceItem:Readonly<Record<string,number>>; readonly resourceReservationIdentityAudit:Readonly<Record<string,unknown>>; readonly residualMainFlowTaskIds:readonly number[]; readonly residualMainFlowAnchorEligibleTaskIds:readonly number[]; readonly firstAnchorTaskId:number|null; readonly firstClosureTaskIds:readonly number[]; readonly fingerprint:string; readonly readOnly:true; }

export function buildInitialConstructionResidualContext(args:{originInput:EngineInput; originOperationalState:OperationalState; stage2:any}):InitialConstructionResidualContext{
  const assignments=[...(args.stage2?.selectedAssignments??[])].map((a:any)=>({...a,resourceIds:[...(a.resourceIds??a.assignedResourceIds??[])].sort((x:number,y:number)=>x-y)})).sort((a,b)=>a.taskId-b.taskId);
  const assigned=uniq(assignments.map((a:any)=>Number(a.taskId)));
  const tasks=[...(args.originInput.tasks??[])].sort((a:any,b:any)=>a.id-b.id);
  const byId=new Map(tasks.map((t:any)=>[t.id,t]));
  const map:any=buildInitialConstructionMap({input:args.originInput,state:args.originOperationalState,planningMode:"INITIAL_CONSTRUCTION",provisionalAssignments:assignments,provisionallyAssignedTaskIds:assigned});
  const occC:Record<string,number>={}, occS:Record<string,number>={}, occR:Record<string,number>={}, demandR:Record<string,number>={};
  const catalog=(map as any).inputCatalog??{}; const planResourceById=catalog.planResourceItemById??{}; const missing:number[]=[], ambiguous:number[]=[], namespaceConfusion:number[]=[];
  for(const a of assignments){ const t:any=byId.get(a.taskId); const m=dur(t); if(t?.contestantId!=null) occC[String(t.contestantId)]=(occC[String(t.contestantId)]??0)+m; if(a.spaceId!=null) occS[String(a.spaceId)]=(occS[String(a.spaceId)]??0)+m; for(const r of a.resourceIds??[]){ occR[String(r)]=(occR[String(r)]??0)+m; const item=planResourceById[String(r)]??planResourceById[Number(r)]; if(!item){ missing.push(Number(r)); continue; } const logical=Number(item.resourceItemId); if(!Number.isFinite(logical)){ ambiguous.push(Number(r)); continue; } demandR[String(logical)]=(demandR[String(logical)]??0)+m; if(logical===Number(r)) namespaceConfusion.push(Number(r)); } }
  const resourceReservationIdentityAudit={version:"RESOURCE-RESERVATION-IDENTITY-AUDIT-V1",missingPlanResourceItemIds:uniq(missing).slice(0,10),ambiguousPlanResourceItemIds:uniq(ambiguous).slice(0,10),namespaceCollisionPlanResourceItemIds:uniq(namespaceConfusion).slice(0,10),physicalPlanResourceItemIds:Object.keys(occR).map(Number).sort((a,b)=>a-b).slice(0,10),logicalResourceItemIds:Object.keys(demandR).map(Number).sort((a,b)=>a-b).slice(0,10),confusedNamespace:false,readOnly:true};
  const payload={v:"INITIAL-CONSTRUCTION-RESIDUAL-CONTEXT-V1",basePartialPlanId:args.stage2?.selectedPartialPlanId??null,baseBranchId:args.stage2?.selectedBranchId??null,assigned,residualPendingTaskIds:map.pendingTaskCount,main:map.mainFlowPressure?.mainFlowAnchorEligibleTaskIds,occC,occS,occR};
  return deepFreeze({basePartialPlanId:args.stage2?.selectedPartialPlanId??null,baseBranchId:args.stage2?.selectedBranchId??null,provisionalAssignments:assignments,provisionallyAssignedTaskIds:assigned,residualPendingTaskIds:uniq(((map as any).classification?.pendingTasks??[]).map((t:any)=>t.id)),residualProductiveTaskIds:uniq(((map as any).classification?.productiveTasks??[]).map((t:any)=>t.id)),provisionallySatisfiedDependencyTaskIds:assigned,provisionalOccupancyByContestant:occC,provisionalOccupancyBySpace:occS,provisionalOccupancyByResource:occR,provisionalOccupancyByPlanResourceItem:occR,provisionalDemandReservationByResourceItem:demandR,resourceReservationIdentityAudit,residualMainFlowTaskIds:map.mainFlowPressure?.mainFlowProductiveTaskIds??[],residualMainFlowAnchorEligibleTaskIds:map.mainFlowPressure?.mainFlowAnchorEligibleTaskIds??[],firstAnchorTaskId:args.stage2?.selectedAnchorTaskId??null,firstClosureTaskIds:args.stage2?.closureTaskIds??assigned,fingerprint:createHash("sha256").update(stableStringify(payload)).digest("hex"),readOnly:true});
}
