import type { EngineInput, TaskInput } from "../../types";
import type { OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { resolveORCMainFlowConfig } from "../state/mainFlowConfigResolver";
import { resolveORCPlanningEntryOperationalRoleMetadata } from "../state/nonWorkTaskClassifier";
import { resolveORCTransportContract } from "../state/transportContractResolver";
import type { ORCPlanningMode } from "../active/resolveORCPlanningMode";
const min=(s?:string|null)=>{ if(!s||!/^[0-9]{2}:[0-9]{2}$/.test(s)) return null; const [h,m]=s.split(":").map(Number); return h*60+m; };
const dur=(t:any)=>Number(t.durationOverrideMin ?? t.durationMin ?? t.durationMinutes ?? t.duration ?? 0) || 0;
const uniq=(a:number[])=>[...new Set(a.filter(Number.isFinite))].sort((x,y)=>x-y);
const ids=(v:any)=>Array.isArray(v)?v.map(Number).filter(Number.isFinite): v!=null?[Number(v)].filter(Number.isFinite):[];
export function taskPrerequisiteIds(task:TaskInput,tasks:TaskInput[]){ const direct=ids(task.dependsOnTaskIds).concat(ids(task.dependsOnTaskId)); for(const tid of ids(task.dependsOnTemplateIds).concat(ids(task.dependsOnTemplateId))){ for(const other of tasks){ if(other.id===task.id||other.templateId!==tid) continue; const sameC=task.contestantId!=null&&task.contestantId===other.contestantId; const sameT=task.itinerantTeamId!=null&&task.itinerantTeamId===other.itinerantTeamId; if(sameC||sameT) direct.push(other.id); } } return uniq(direct); }
function closure(start:number, adj:Map<number,number[]>){ const seen=new Set<number>(), stack=[...(adj.get(start)??[])]; while(stack.length){ const n=stack.pop()!; if(seen.has(n)) continue; seen.add(n); stack.push(...(adj.get(n)??[])); } return uniq([...seen]); }
export function buildInitialConstructionMap(args:{input:EngineInput; state:OperationalState; planningMode:ORCPlanningMode}){ const {input,state,planningMode}=args; const tasks=[...(input.tasks??[])].sort((a,b)=>a.id-b.id); const byId=new Map(tasks.map(t=>[t.id,t])); const prereq=new Map<number,number[]>(), dep=new Map<number,number[]>(); const blockers:any[]=[]; let directEdge=0, templateEdge=0; for(const t of tasks){ const ps=taskPrerequisiteIds(t,tasks); prereq.set(t.id,ps); for(const p of ids(t.dependsOnTaskIds).concat(ids(t.dependsOnTaskId))) if(!byId.has(p)) blockers.push({kind:"missing_dependency",taskId:t.id,prerequisiteTaskId:p}); for(const tid of ids(t.dependsOnTemplateIds).concat(ids(t.dependsOnTemplateId))) { const matches=tasks.filter(o=>o.id!==t.id&&o.templateId===tid&&((t.contestantId!=null&&t.contestantId===o.contestantId)||(t.itinerantTeamId!=null&&t.itinerantTeamId===o.itinerantTeamId))); if(!matches.length) blockers.push({kind:"unresolved_template_dependency",taskId:t.id,templateId:tid}); else templateEdge+=matches.length; } for(const p of ps){ if(p===t.id) blockers.push({kind:"self_dependency",taskId:t.id}); dep.set(p,uniq([...(dep.get(p)??[]),t.id])); directEdge++; } }
 const cycles:number[][]=[]; for(const t of tasks){ const c=closure(t.id,prereq); if(c.includes(t.id)){ cycles.push([t.id]); blockers.push({kind:"dependency_cycle",taskId:t.id}); } }
 const transport=resolveORCTransportContract(input as any); const meal=(input.actualMeal??input.mealWindow??input.meal) as any; const role=(t:any)=>resolveORCPlanningEntryOperationalRoleMetadata({task:t,mealWindow:meal,transportContract:transport}); const pending=tasks.filter(t=>t.status!=="done"&&t.status!=="in_progress"&&!state.locks.some(l=>Number(l.taskId)===t.id)); const productive=pending.filter(t=>role(t).countsAsWork);
 const main=resolveORCMainFlowConfig(input); const mainFlowTaskIds=uniq(tasks.filter(t=>main.configured&&(t.spaceId===main.mainFlowId||t.zoneId===main.mainFlowId||t.countsForMainFlow===true)).map(t=>t.id));
 const contestantPressure=uniq(tasks.map(t=>Number(t.contestantId)).filter(Number.isFinite)).map(cid=>{ const ts=productive.filter(t=>t.contestantId===cid); const av=(input.contestantAvailabilityById??{})[cid]; const avMin=min(av?.start)!=null&&min(av?.end)!=null ? (min(av!.end)!-min(av!.start)!) : null; const req=ts.reduce((s,t)=>s+dur(t),0); const slack=avMin==null?null:avMin-req; return {contestantId:cid,pendingProductiveTaskCount:ts.length,pendingProductiveMinutes:req,totalRequiredMinutes:req,effectiveAvailabilityStart:av?.start??null,effectiveAvailabilityEnd:av?.end??null,effectiveAvailableMinutes:avMin,protectedMinutes:0,earliestArrival:av?.start??null,latestDeparture:av?.end??null,directDependencyCount:ts.reduce((s,t)=>s+(prereq.get(t.id)?.length??0),0),transitiveDependencyCount:ts.reduce((s,t)=>s+closure(t.id,prereq).length,0),mainFlowTaskCount:ts.filter(t=>mainFlowTaskIds.includes(t.id)).length,scarceResourceTaskCount:0,fixedWindowTaskCount:ts.filter(t=>t.fixedWindowStart||t.fixedWindowEnd).length,workloadRatio:avMin?req/avMin:null,slackMinutes:slack,alternativeWindowEstimate:avMin,riskFlags:[...(slack!=null&&slack<60?["low_slack"]:[]),...(avMin==null?["missing_availability"]:[])],explanation:`Contestant ${cid} requires ${req} minutes before placement.`,readOnly:true}; }).sort((a,b)=>(a.slackMinutes??999999)-(b.slackMinutes??999999)||b.pendingProductiveMinutes-a.pendingProductiveMinutes||a.contestantId-b.contestantId);
 const resourcePressure=uniq(tasks.flatMap(t=>[...ids(t.resourceRequirements?.byItem&&Object.keys(t.resourceRequirements.byItem)),...((t.resourceRequirements?.anyOf??[]).flatMap((g:any)=>ids(g.resourceItemIds))),...(t.assignedResourceIds??[])] as any)).map(rid=>{ const fixed=productive.filter(t=>(t.resourceRequirements?.byItem&&Object.keys(t.resourceRequirements.byItem).map(Number).includes(rid))); const alt=productive.filter(t=>(t.resourceRequirements?.anyOf??[]).some((g:any)=>ids(g.resourceItemIds).includes(rid))); return {resourceId:rid,fixedRequiredTaskCount:fixed.length,alternativeRequiredTaskCount:alt.length,requiredMinutes:fixed.reduce((s,t)=>s+dur(t),0)+alt.reduce((s,t)=>s+dur(t)/(Math.max(1,(t.resourceRequirements?.anyOf??[]).find((g:any)=>ids(g.resourceItemIds).includes(rid))?.resourceItemIds?.length??1)),0),availableMinutes:null,demandRatio:null,uniqueConsumerCount:uniq([...fixed,...alt].map(t=>t.id)).length,mainFlowConsumerCount:uniq([...fixed,...alt].filter(t=>mainFlowTaskIds.includes(t.id)).map(t=>t.id)).length,dependencyChainConsumerCount:0,alternativeResourceCount:alt.length,scarcity:alt.length?1/Math.max(1,alt.length):fixed.length>0?1:0,riskFlags:fixed.length+alt.length>1?["shared_demand"]:[],explanation:"Pressure from pre-placement requirements; ANY_OF demand is fractional and unassigned.",readOnly:true}; }).sort((a,b)=>b.scarcity-a.scarcity||b.requiredMinutes-a.requiredMinutes||a.resourceId-b.resourceId);
 const spacePressure=uniq(tasks.flatMap(t=>[Number(t.spaceId),Number(t.zoneId)]).filter(Number.isFinite)).map(sid=>{ const ts=productive.filter(t=>t.spaceId===sid||t.zoneId===sid); const families=uniq(ts.map(t=>t.templateId)); const limit=(input.maxTemplateChangesByZoneId??{})[sid]??null; return {spaceId:sid,pendingTaskCount:ts.length,pendingProductiveMinutes:ts.reduce((s,t)=>s+dur(t),0),effectiveCapacity:(input.spaceCapacityById??{})[sid]??(input.spaceConcurrencyById??{})[sid]??1,exclusivity:(input.spaceIsExclusiveById??{})[sid]??true,mainFlowMembership:main.mainFlowId===sid,dependentTaskCount:ts.reduce((s,t)=>s+(dep.get(t.id)?.length??0),0),setupFamilyCount:families.length,configuredMaxChanges:limit,estimatedMinimumChanges:Math.max(0,families.length-1),structuralSlack:limit==null?null:limit-Math.max(0,families.length-1),riskFlags:limit!=null&&families.length-1>limit?["change_limit_pressure"]:[],explanation:`Space/zone ${sid} has ${ts.length} pending productive tasks and ${families.length} setup families.`,readOnly:true}; }).sort((a,b)=>b.pendingProductiveMinutes-a.pendingProductiveMinutes||a.spaceId-b.spaceId);
 const dependencyGraph={nodes:tasks.map(t=>({taskId:t.id,directPrerequisiteTaskIds:prereq.get(t.id)??[],transitivePrerequisiteTaskIds:closure(t.id,prereq),directDependentTaskIds:dep.get(t.id)??[],transitiveDependentTaskIds:closure(t.id,dep),prerequisiteDepth:closure(t.id,prereq).length,downstreamDepth:closure(t.id,dep).length,prerequisiteDurationMinutes:closure(t.id,prereq).reduce((s,id)=>s+dur(byId.get(id)),0),chainDurationMinutes:dur(t)+closure(t.id,prereq).reduce((s,id)=>s+dur(byId.get(id)),0)+closure(t.id,dep).reduce((s,id)=>s+dur(byId.get(id)),0),dependentCount:dep.get(t.id)?.length??0,unlockCount:closure(t.id,dep).length,rootTaskIds:[],leafTaskIds:[],readOnly:true})),directDependencyEdgeCount:directEdge,resolvedTemplateDependencyEdgeCount:templateEdge,unresolvedDependencyCount:blockers.filter(b=>String(b.kind).includes("dependency")).length,dependencyCycleCount:cycles.length,blockers,readOnly:true};
 const bottleneckRegions:any[]=[]; const add=(r:any)=>bottleneckRegions.push({...r,readOnly:true}); contestantPressure.slice(0,3).filter(c=>c.pendingProductiveTaskCount&&((c.slackMinutes??999999)<120||(c.workloadRatio??0)>0.7||c.mainFlowTaskCount>0)).forEach(c=>add({id:`critical_contestant:${c.contestantId}`,kind:"critical_contestant",relatedTaskIds:productive.filter(t=>t.contestantId===c.contestantId).map(t=>t.id),relatedContestantIds:[c.contestantId],relatedResourceIds:[],relatedSpaceIds:[],relatedTeamIds:[],hardRisk:(c.slackMinutes??999)>0?false:true,futureInfeasibilityRisk:(c.slackMinutes??999999)<60,mainFlowImpact:c.mainFlowTaskCount>0,structuralImpact:false,freedomLossRisk:(c.slackMinutes??999999)<120,confidence:c.slackMinutes==null?0.55:0.85,explanation:c.explanation,evidenceRefs:[`contestant:${c.contestantId}`]})); resourcePressure.slice(0,3).filter(r=>r.uniqueConsumerCount>0).forEach(r=>add({id:`critical_resource:${r.resourceId}`,kind:"critical_resource",relatedTaskIds:productive.filter(t=>(t.resourceRequirements?.byItem&&Object.keys(t.resourceRequirements.byItem).map(Number).includes(r.resourceId))||(t.resourceRequirements?.anyOf??[]).some((g:any)=>ids(g.resourceItemIds).includes(r.resourceId))).map(t=>t.id),relatedContestantIds:[],relatedResourceIds:[r.resourceId],relatedSpaceIds:[],relatedTeamIds:[],hardRisk:false,futureInfeasibilityRisk:r.scarcity>=1,mainFlowImpact:r.mainFlowConsumerCount>0,structuralImpact:false,freedomLossRisk:r.alternativeResourceCount<2,confidence:0.75,explanation:r.explanation,evidenceRefs:[`resource:${r.resourceId}`]})); if(main.configured&&mainFlowTaskIds.length)add({id:"main_flow_feed",kind:"main_flow_feed",relatedTaskIds:mainFlowTaskIds,relatedContestantIds:uniq(tasks.filter(t=>mainFlowTaskIds.includes(t.id)).map(t=>Number(t.contestantId)).filter(Number.isFinite)),relatedResourceIds:[],relatedSpaceIds:[main.mainFlowId],relatedTeamIds:[],hardRisk:false,futureInfeasibilityRisk:false,mainFlowImpact:true,structuralImpact:false,freedomLossRisk:true,confidence:0.8,explanation:"Configured main flow tasks feed continuity.",evidenceRefs:["mainFlow"]});
 const map={version:"INITIAL-CONSTRUCTION-MAP-V1",planningMode,stateId:state.id,taskCount:tasks.length,pendingTaskCount:pending.length,protectedTaskCount:tasks.length-pending.length,originPlanningCount:state.planning.length,dependencyGraph,contestantPressure,resourcePressure,spacePressure,itinerantTeamPressure:[],mainFlowPressure:{mainFlowConfigured:main.configured,mainFlowPriorityLevel:input.optimizerMainZonePriorityLevel??null,mainFlowTaskIds,mainFlowProductiveTaskIds:mainFlowTaskIds.filter(id=>productive.some(t=>t.id===id)),totalMainFlowMinutes:productive.filter(t=>mainFlowTaskIds.includes(t.id)).reduce((s,t)=>s+dur(t),0),mainFlowContestantIds:uniq(tasks.filter(t=>mainFlowTaskIds.includes(t.id)).map(t=>Number(t.contestantId)).filter(Number.isFinite)),mainFlowPrerequisiteTaskIds:uniq(mainFlowTaskIds.flatMap(id=>closure(id,prereq))),mainFlowResourceIds:[],mainFlowDependencyChains:mainFlowTaskIds.map(id=>({taskId:id,prerequisiteTaskIds:closure(id,prereq)})),unresolvedMainFlowBlockers:blockers.filter(b=>mainFlowTaskIds.includes(b.taskId)),readOnly:true},structuralPressure:{maxTemplateChangesByZoneId:input.maxTemplateChangesByZoneId??{},groupingZoneIds:input.groupingZoneIds??[],readOnly:true},bottleneckRegions,blockers,deterministic:stableStringify({tasks:tasks.map(t=>t.id),bottleneckRegions:bottleneckRegions.map(r=>r.id)}).length>0,readOnly:true}; return deepFreeze(map) as any; }
