import type { TimeWindow } from "../../types";
import type { OperationalState } from "../contracts";
import { resolveORCMealSemantics } from "../state/mealSemanticsResolver";
import { resolveORCPlanningEntryOperationalRoleMetadata } from "../state/nonWorkTaskClassifier";
import { resolveORCMainZoneTarget } from "../state/mainZoneTargetResolver";
import { resolveORCTransportContract } from "../state/transportContractResolver";

export const ORC_PRODUCTION_CONCEPT_ALIGNMENT_CONTRACT_VERSION_ID235 = "ORC-PRODUCTION-CONCEPT-ALIGNMENT-ID235" as const;

type Verdict = "aligned" | "partially_aligned" | "conceptually_misaligned" | "insufficient_data";
type RootCauseCode = "greedy_early_start_baseline" | "call_time_not_linked_to_first_productive_task" | "departure_not_linked_to_last_required_task" | "meal_window_over_blocking_suspected" | "flexible_meal_window_treated_as_global_stop" | "main_zone_visible_idle" | "main_zone_coach_blocks_not_balanced" | "main_zone_coach_switch_policy_missing" | "main_zone_single_resource_span_dominates" | "critical_resource_span_imbalance" | "critical_resource_idle_still_high" | "macro_day_shape_missing" | "local_optimization_cannot_fix_macro_shape" | "release_policy_not_configured";

export interface ProductionConceptRootCause { code: RootCauseCode; severity: "info" | "warning" | "critical"; affectedTaskIds: number[]; affectedResourceIds: number[]; affectedContestantIds: number[]; affectedSpaceIds: number[]; timeWindows: TimeWindow[]; humanMessage: string; recommendedNextCapability: string; readOnly: true; }
export interface ProductionConceptAlignmentAudit { contractVersion: typeof ORC_PRODUCTION_CONCEPT_ALIGNMENT_CONTRACT_VERSION_ID235; executed: boolean; readOnly: true; verdict: Verdict; score: number; warnings: string[]; rootCauses: ProductionConceptRootCause[]; macroPlannerRequired: boolean; planningSource: string | null; selectedSimulatedStateId: string | null; finalSelectedCandidateFamily: string | null; mainZoneConfigured: boolean; mainZoneTargetKind: string; mainSpaceIds: number[]; mainZoneIds: number[]; visibleMainZoneGaps: Array<TimeWindow & { gapMinutes: number; previousTaskId: number | null; nextTaskId: number | null; classification: string }>; largestVisibleMainZoneGapMinutes: number; totalVisibleMainZoneIdleMinutes: number; gapsBeforeMealWindow: number; gapsInsideFlexibleMealWindow: number; gapsAfterMealWindow: number; gapsCoveredByActualHardBreak: number; gapsIncorrectlyIgnoredBecauseMealWindow: number; mainZoneVisibleContinuityVerdict: string; criticalResourceDaySpans: Record<string, number>; criticalResourceWorkMinutes: Record<string, number>; criticalResourceIdleMinutes: Record<string, number>; criticalResourceFirstTaskStart: Record<string, string>; criticalResourceLastTaskEnd: Record<string, string>; criticalResourceSpanImbalanceMinutes: number; criticalResourceWorkImbalanceMinutes: number; criticalResourceIdleImbalanceMinutes: number; coachLikeResourceBalanceVerdict: string; overextendedResourceIds: number[]; underusedComparableResourceIds: number[]; talentInitialWaits: Array<Record<string, unknown>>; averageArrivalToFirstTaskWaitMinutes: number; maxArrivalToFirstTaskWaitMinutes: number; talentsWithExcessiveInitialWait: number[]; callTimeAlignmentVerdict: string; talentReleaseWaits: Array<Record<string, unknown>>; mealMode: string | null; mealPlacementWindow: TimeWindow | null; actualGlobalMealBreaks: TimeWindow[]; mealPlaceholdersCount: number; tasksScheduledInsideMealWindow: number; productiveTasksAllowedInsideMealWindow: boolean; blankMealWindowMinutes: number; mealWindowTreatedAsGlobalStopSuspected: boolean; mealPolicyVerdict: string; firstArrivalTime: string | null; firstProductiveTaskTime: string | null; firstMainZoneProductiveTaskTime: string | null; preProductiveIdleByTalent: Record<string, number>; preProductiveIdleByCriticalResource: Record<string, number>; preLunchGlobalIdleWindows: TimeWindow[]; startLaterRecommendation: boolean; recommendedDayStartShiftMinutes: number; startLaterReason: string | null; mainZoneCoachSwitchPolicy: Record<string, unknown>; mainZoneCoachSequence: number[]; mainZoneCoachSwitches: number; mainZoneCoachBlocks: Record<string, number>; morningMainZoneCoachBlocks: Record<string, number>; afternoonMainZoneCoachBlocks: Record<string, number>; }

const m = (t?: string | null) => { const p = String(t ?? "").split(":").map(Number); return p.length === 2 && p.every(Number.isFinite) ? p[0] * 60 + p[1] : null; };
const hh = (x: number) => `${String(Math.floor(x / 60)).padStart(2, "0")}:${String(x % 60).padStart(2, "0")}`;
const overlap = (a: number, b: number, c: number, d: number) => a < d && c < b;
const covered = (a: number, b: number, w: TimeWindow) => { const c = m(w.start), d = m(w.end); return c != null && d != null && c <= a && d >= b; };
const pickNum = (root: any, keys: string[], fb: number) => { for (const k of keys) { const v = k.split(".").reduce((c, p) => c?.[p], root); const n = Number(v); if (Number.isFinite(n)) return n; } return fb; };
const uniq = (xs: number[]) => [...new Set(xs.filter(Number.isFinite))].sort((a,b)=>a-b);

function rc(code: RootCauseCode, severity: ProductionConceptRootCause["severity"], msg: string, extra: Partial<ProductionConceptRootCause> = {}): ProductionConceptRootCause {
  return { code, severity, affectedTaskIds: [], affectedResourceIds: [], affectedContestantIds: [], affectedSpaceIds: [], timeWindows: [], humanMessage: msg, recommendedNextCapability: "macro_production_wave_planner", readOnly: true, ...extra };
}

export function auditProductionConceptAlignment(args: { operationalState: OperationalState | null | undefined; planningSource?: string | null; selectedSimulatedStateId?: string | null; finalSelectedCandidateFamily?: string | null; previousMainZoneContinuity?: Record<string, unknown> | null }): ProductionConceptAlignmentAudit {
  const s = args.operationalState;
  const empty = (reason: string): ProductionConceptAlignmentAudit => ({ contractVersion: ORC_PRODUCTION_CONCEPT_ALIGNMENT_CONTRACT_VERSION_ID235, executed: false, readOnly: true, verdict: "insufficient_data", score: 0, warnings: [reason], rootCauses: [], macroPlannerRequired: false, planningSource: args.planningSource ?? null, selectedSimulatedStateId: args.selectedSimulatedStateId ?? null, finalSelectedCandidateFamily: args.finalSelectedCandidateFamily ?? null, mainZoneConfigured:false, mainZoneTargetKind:"unknown", mainSpaceIds:[], mainZoneIds:[], visibleMainZoneGaps:[], largestVisibleMainZoneGapMinutes:0, totalVisibleMainZoneIdleMinutes:0, gapsBeforeMealWindow:0, gapsInsideFlexibleMealWindow:0, gapsAfterMealWindow:0, gapsCoveredByActualHardBreak:0, gapsIncorrectlyIgnoredBecauseMealWindow:0, mainZoneVisibleContinuityVerdict:"insufficient_data", criticalResourceDaySpans:{}, criticalResourceWorkMinutes:{}, criticalResourceIdleMinutes:{}, criticalResourceFirstTaskStart:{}, criticalResourceLastTaskEnd:{}, criticalResourceSpanImbalanceMinutes:0, criticalResourceWorkImbalanceMinutes:0, criticalResourceIdleImbalanceMinutes:0, coachLikeResourceBalanceVerdict:"insufficient_data", overextendedResourceIds:[], underusedComparableResourceIds:[], talentInitialWaits:[], averageArrivalToFirstTaskWaitMinutes:0, maxArrivalToFirstTaskWaitMinutes:0, talentsWithExcessiveInitialWait:[], callTimeAlignmentVerdict:"insufficient_data", talentReleaseWaits:[], mealMode:null, mealPlacementWindow:null, actualGlobalMealBreaks:[], mealPlaceholdersCount:0, tasksScheduledInsideMealWindow:0, productiveTasksAllowedInsideMealWindow:false, blankMealWindowMinutes:0, mealWindowTreatedAsGlobalStopSuspected:false, mealPolicyVerdict:"insufficient_data", firstArrivalTime:null, firstProductiveTaskTime:null, firstMainZoneProductiveTaskTime:null, preProductiveIdleByTalent:{}, preProductiveIdleByCriticalResource:{}, preLunchGlobalIdleWindows:[], startLaterRecommendation:false, recommendedDayStartShiftMinutes:0, startLaterReason:null, mainZoneCoachSwitchPolicy:{configured:false}, mainZoneCoachSequence:[], mainZoneCoachSwitches:0, mainZoneCoachBlocks:{}, morningMainZoneCoachBlocks:{}, afternoonMainZoneCoachBlocks:{} });
  if (!s || !Array.isArray(s.planning)) return empty("operational_state_or_planning_missing");
  const rootCauses: ProductionConceptRootCause[] = []; const warnings: string[] = [];
  const tasks = new Map((s.tasks ?? []).map(t => [t.id, t])); const transport = resolveORCTransportContract(s as any); const meal = resolveORCMealSemantics(s);
  const target = resolveORCMainZoneTarget(s as any); const mealWindow = meal.placementWindows[0] ?? null; const mealStart = m(mealWindow?.start), mealEnd = m(mealWindow?.end);
  const entries = s.planning.map(e => ({...e, a:m(e.startPlanned)!, b:m(e.endPlanned)!, meta: resolveORCPlanningEntryOperationalRoleMetadata({ entry:e, task:tasks.get(e.taskId), mealWindow: mealWindow ?? s.availability?.meal ?? null, transportContract: transport })})).filter(e => e.a != null && e.b != null).sort((x,y)=>x.a-y.a || x.b-y.b || x.taskId-y.taskId);
  const productive = entries.filter(e => e.meta.countsAsWork);
  const mainEntries = entries.filter(e => e.meta.countsForMainFlow && ((e.spaceId != null && target.mainSpaceIds.includes(e.spaceId)) || (e.zoneId != null && target.mainZoneIds.includes(e.zoneId)))).sort((a,b)=>a.a-b.a);
  const visibleMainZoneGaps: ProductionConceptAlignmentAudit["visibleMainZoneGaps"] = [];
  let gapsCoveredByActualHardBreak = 0, gapsInsideFlexibleMealWindow = 0, gapsBeforeMealWindow = 0, gapsAfterMealWindow = 0;
  for (let i=1;i<mainEntries.length;i++) { const prev=mainEntries[i-1], next=mainEntries[i]; if (next.a <= prev.b) continue; const hardCovered = [...meal.globalHardBreaks, ...meal.actualMealBreaks].some(w => covered(prev.b,next.a,w)); if (hardCovered) { gapsCoveredByActualHardBreak++; continue; } const win={start:hh(prev.b),end:hh(next.a)}; const touchesMeal = mealStart!=null && mealEnd!=null && overlap(prev.b,next.a,mealStart,mealEnd); if (touchesMeal) gapsInsideFlexibleMealWindow++; else if (mealStart!=null && next.a <= mealStart) gapsBeforeMealWindow++; else if (mealEnd!=null && prev.b >= mealEnd) gapsAfterMealWindow++; visibleMainZoneGaps.push({...win,gapMinutes:next.a-prev.b,previousTaskId:prev.taskId,nextTaskId:next.taskId,classification: touchesMeal ? "productiveIdleAcrossFlexibleMealWindow" : "productiveIdle"}); }
  const totalVisibleMainZoneIdleMinutes = visibleMainZoneGaps.reduce((a,g)=>a+g.gapMinutes,0); const largestVisibleMainZoneGapMinutes = visibleMainZoneGaps.reduce((a,g)=>Math.max(a,g.gapMinutes),0);
  if (totalVisibleMainZoneIdleMinutes > 0) rootCauses.push(rc("main_zone_visible_idle", "warning", "Main production zone has visible idle time not covered by an actual hard break.", { affectedTaskIds: uniq(visibleMainZoneGaps.flatMap(g=>[g.previousTaskId ?? NaN,g.nextTaskId ?? NaN])), affectedSpaceIds: target.mainSpaceIds, timeWindows: visibleMainZoneGaps.map(g=>({start:g.start,end:g.end})) }));
  const prevIgnored = Number(args.previousMainZoneContinuity?.finalLargestMainZoneGapMinutes ?? args.previousMainZoneContinuity?.largestMainZoneGapMinutes ?? args.previousMainZoneContinuity?.finalLargestGapMinutes ?? 0) === 0;
  if (meal.mealMode === "flexible_meal_window" && gapsInsideFlexibleMealWindow > 0 && prevIgnored) rootCauses.push(rc("flexible_meal_window_treated_as_global_stop", "warning", "A flexible meal window appears to have hidden visible main-zone idle time.", { affectedSpaceIds: target.mainSpaceIds, timeWindows: visibleMainZoneGaps.filter(g=>mealStart!=null&&mealEnd!=null&&overlap(m(g.start)!,m(g.end)!,mealStart,mealEnd)).map(g=>({start:g.start,end:g.end})) }));
  const counts: Record<number, number> = {}, work: Record<number, number> = {}, first: Record<number, number> = {}, last: Record<number, number> = {};
  for (const e of productive) for (const r of e.assignedResourceIds ?? []) { counts[r]=(counts[r]??0)+1; work[r]=(work[r]??0)+(e.b-e.a); first[r]=Math.min(first[r]??1e9,e.a); last[r]=Math.max(last[r]??0,e.b); }
  const coachIds = s.resources.filter(r => /coach/i.test(`${r.typeCode ?? ""} ${r.typeName ?? ""} ${r.category ?? ""}`)).map(r=>r.id);
  const mainRes = uniq(mainEntries.flatMap(e=>e.assignedResourceIds ?? [])); const critical = uniq([...Object.keys(counts).map(Number).filter(id=>counts[id]>=2), ...mainRes, ...coachIds]);
  const span: Record<string,number>={}, idle:Record<string,number>={}, firstS:Record<string,string>={}, lastS:Record<string,string>={}; for (const r of critical) { span[r]=Math.max(0,(last[r]??0)-(first[r]??0)); idle[r]=Math.max(0,span[r]-(work[r]??0)); if(first[r]!=null) firstS[r]=hh(first[r]); if(last[r]!=null) lastS[r]=hh(last[r]); }
  const maxSpanImb = pickNum(s, ["constraints.optimizer.maxComparableResourceSpanImbalanceMinutes","optimizerWeights.maxComparableResourceSpanImbalanceMinutes","operationalPolicy.maxComparableResourceSpanImbalanceMinutes"], 60); const workTol = pickNum(s, ["constraints.optimizer.comparableWorkloadToleranceMinutes","optimizerWeights.comparableWorkloadToleranceMinutes","operationalPolicy.comparableWorkloadToleranceMinutes"], 30); const maxIdle = pickNum(s,["constraints.optimizer.maxCriticalResourceIdleMinutes","operationalPolicy.maxCriticalResourceIdleMinutes"],90);
  let spanImb=0, workImb=0, idleImb=0, over:number[]=[], under:number[]=[]; for (const a of critical) for (const b of critical) if (a<b && Math.abs((work[a]??0)-(work[b]??0))<=workTol) { const d=Math.abs((span[a]??0)-(span[b]??0)); if(d>spanImb){spanImb=d;workImb=Math.abs((work[a]??0)-(work[b]??0));idleImb=Math.abs((idle[a]??0)-(idle[b]??0)); over=[(span[a]??0)>(span[b]??0)?a:b]; under=[(span[a]??0)>(span[b]??0)?b:a];} }
  if (spanImb > maxSpanImb) rootCauses.push(rc("critical_resource_span_imbalance", "warning", "Comparable critical resources have similar work but very different day spans.", { affectedResourceIds: uniq([...over,...under]) }));
  const highIdle = critical.filter(r => (idle[r]??0) > maxIdle); if (highIdle.length) rootCauses.push(rc("critical_resource_idle_still_high", "info", "Critical resources still have high idle time.", { affectedResourceIds: highIdle }));
  const byTalent = (role:string) => entries.filter(e=>e.meta.role===role && tasks.get(e.taskId)?.contestantId != null); const arrivals=byTalent("transport_arrival"), deps=byTalent("transport_departure"); const maxWait=pickNum(s,["constraints.optimizer.maxArrivalToFirstTaskWaitMinutes","operationalPolicy.maxArrivalToFirstTaskWaitMinutes"],45); const relMax=pickNum(s,["constraints.optimizer.maxReleaseSlackMinutes","operationalPolicy.maxReleaseSlackMinutes"],60);
  const talentIds=uniq((s.tasks??[]).map(t=>t.contestantId ?? NaN)); const talentInitialWaits:any[]=[]; const talentReleaseWaits:any[]=[]; const preByTalent:Record<string,number>={};
  for (const tid of talentIds) { const arr=arrivals.filter(e=>tasks.get(e.taskId)?.contestantId===tid).sort((a,b)=>a.a-b.a)[0]; const prod=productive.filter(e=>tasks.get(e.taskId)?.contestantId===tid).sort((a,b)=>a.a-b.a); const firstProd=prod[0]; if(arr&&firstProd){ const wait=firstProd.a-arr.b; preByTalent[tid]=wait; const item={contestantId:tid, arrivalEndToFirstProductiveStartMinutes:wait, arrivalStartToFirstProductiveStartMinutes:firstProd.a-arr.a, firstProductiveTaskId:firstProd.taskId, arrivalTaskId:arr.taskId, excessiveInitialWait:wait>maxWait}; talentInitialWaits.push(item); } const dep=deps.filter(e=>tasks.get(e.taskId)?.contestantId===tid).sort((a,b)=>b.a-a.a)[0]; const lastProd=prod.sort((a,b)=>b.b-a.b)[0]; const mealEntry=entries.filter(e=>e.meta.role==="meal_break_placeholder"&&tasks.get(e.taskId)?.contestantId===tid).sort((a,b)=>b.b-a.b)[0]; if(dep&&lastProd){ const slack=dep.a-lastProd.b; const item={contestantId:tid,lastProductiveEndToDepartureStartMinutes:slack,mealEndToDepartureStartMinutes:mealEntry?dep.a-mealEntry.b:null,releaseSlackMinutes:slack,departureTaskId:dep.taskId,lastProductiveTaskId:lastProd.taskId,departureDelayedWithoutOperationalReason:slack>relMax}; talentReleaseWaits.push(item); } }
  const excessive=talentInitialWaits.filter(i=>i.excessiveInitialWait).map(i=>i.contestantId); if (excessive.length) rootCauses.push(rc("call_time_not_linked_to_first_productive_task", "warning", "Talent arrivals are not aligned with first productive tasks.", { affectedContestantIds: excessive }));
  const delayed=talentReleaseWaits.filter(i=>i.departureDelayedWithoutOperationalReason); if (delayed.length) rootCauses.push(rc("departure_not_linked_to_last_required_task", "warning", "Departures are delayed after the last required productive task.", { affectedContestantIds: delayed.map(i=>i.contestantId), affectedTaskIds: delayed.flatMap(i=>[i.departureTaskId,i.lastProductiveTaskId]) }));
  if (!pickNum(s,["constraints.optimizer.maxReleaseSlackMinutes","operationalPolicy.maxReleaseSlackMinutes"],NaN)) rootCauses.push(rc("release_policy_not_configured", "info", "Release/wrap policy is not configured; departure diagnostics use conservative fallback."));
  const inMeal = mealStart!=null&&mealEnd!=null ? entries.filter(e=>overlap(e.a,e.b,mealStart,mealEnd)) : []; const prodInMeal=inMeal.filter(e=>e.meta.countsAsWork).length; const mealPlaceholdersCount=entries.filter(e=>e.meta.role==="meal_break_placeholder").length; const blankMealWindowMinutes = mealStart!=null&&mealEnd!=null&&prodInMeal===0 ? mealEnd-mealStart : 0; const overBlocking = meal.mealMode==="flexible_meal_window" && blankMealWindowMinutes>0 && meal.globalHardBreaks.length===0 && productive.length>0;
  if (overBlocking) rootCauses.push(rc("meal_window_over_blocking_suspected", "warning", "Flexible meal window has no productive work scheduled and no global hard break.", { timeWindows: mealWindow ? [mealWindow] : [] }));
  const firstArrivalTime = arrivals[0]?.startPlanned ?? null, firstProductiveTaskTime = productive[0]?.startPlanned ?? null, firstMainZoneProductiveTaskTime = mainEntries[0]?.startPlanned ?? null; const avgWait = talentInitialWaits.length ? Math.round(talentInitialWaits.reduce((a,i)=>a+i.arrivalEndToFirstProductiveStartMinutes,0)/talentInitialWaits.length) : 0; const maxInitial=Math.max(0,...talentInitialWaits.map(i=>i.arrivalEndToFirstProductiveStartMinutes)); const startLaterRecommendation = excessive.length >= Math.max(1, Math.ceil(talentIds.length/2)) || maxInitial > maxWait*2; if (startLaterRecommendation) rootCauses.push(rc("macro_day_shape_missing", "critical", "Day shape is not aligned: arrivals and productive work are too far apart.", { affectedContestantIds: excessive }));
  const policy = { mainZoneMaxCoachSwitchesPerDay: pickNum(s,["constraints.optimizer.mainZoneMaxCoachSwitchesPerDay","optimizer.heuristics.mainZoneMaxCoachSwitchesPerDay","operationalPolicy.mainZoneMaxCoachSwitchesPerDay","engineConfig.mainZoneMaxCoachSwitchesPerDay"],NaN), mainZoneMaxCoachSwitchesBeforeMeal: pickNum(s,["constraints.optimizer.mainZoneMaxCoachSwitchesBeforeMeal","operationalPolicy.mainZoneMaxCoachSwitchesBeforeMeal"],NaN), mainZoneMaxCoachSwitchesAfterMeal: pickNum(s,["constraints.optimizer.mainZoneMaxCoachSwitchesAfterMeal","operationalPolicy.mainZoneMaxCoachSwitchesAfterMeal"],NaN), mainZonePreferredCoachBlocks: pickNum(s,["constraints.optimizer.mainZonePreferredCoachBlocks","operationalPolicy.mainZonePreferredCoachBlocks"],NaN), mainZoneCoachBlockBalanceWeight: pickNum(s,["constraints.optimizer.mainZoneCoachBlockBalanceWeight","operationalPolicy.mainZoneCoachBlockBalanceWeight"],NaN) };
  const policyConfigured = Object.values(policy).some(Number.isFinite); const coachSet=new Set(coachIds.length?coachIds:critical); const seq=mainEntries.map(e=>(e.assignedResourceIds??[]).find(r=>coachSet.has(r))).filter((x):x is number=>x!=null); const compactSeq=seq.filter((r,i)=>i===0||r!==seq[i-1]); const switches=Math.max(0,compactSeq.length-1); const blocks:Record<string,number>={}, morn:Record<string,number>={}, aft:Record<string,number>={}; compactSeq.forEach((r,i)=>{blocks[r]=(blocks[r]??0)+1; const st=mainEntries[i]?.a??0; ((mealStart!=null&&st>=mealStart)?aft:morn)[r]=(((mealStart!=null&&st>=mealStart)?aft:morn)[r]??0)+1;});
  if (!policyConfigured && compactSeq.length>1) rootCauses.push(rc("main_zone_coach_switch_policy_missing", "info", "Main-zone coach switch policy is not configured.", { affectedResourceIds: uniq(compactSeq) }));
  if (compactSeq.length>2 && compactSeq[0]===compactSeq[compactSeq.length-1]) rootCauses.push(rc("main_zone_single_resource_span_dominates", "warning", "One resource carries both first and last main-zone blocks.", { affectedResourceIds: [compactSeq[0]] } as any));
  if (rootCauses.some(r=>r.severity==="critical") || rootCauses.filter(r=>r.severity==="warning").length>=3) rootCauses.push(rc("local_optimization_cannot_fix_macro_shape", "critical", "Local improvements are insufficient; a macro planner is required."));
  const warningCount=rootCauses.filter(r=>r.severity!=="info").length; const score=Math.max(0, Math.round((100 - warningCount*18 - rootCauses.filter(r=>r.severity==="info").length*5)*100)/100); const verdict:Verdict = !target.configured && !productive.length ? "insufficient_data" : score>=85 ? "aligned" : score>=55 ? "partially_aligned" : "conceptually_misaligned";
  return { ...empty(""), executed:true, warnings, verdict, score, rootCauses, macroPlannerRequired: verdict==="conceptually_misaligned" || rootCauses.some(r=>r.code==="macro_day_shape_missing" || r.code==="local_optimization_cannot_fix_macro_shape"), mainZoneConfigured:target.configured, mainZoneTargetKind:target.targetKind, mainSpaceIds:target.mainSpaceIds, mainZoneIds:target.mainZoneIds, visibleMainZoneGaps, largestVisibleMainZoneGapMinutes, totalVisibleMainZoneIdleMinutes, gapsBeforeMealWindow, gapsInsideFlexibleMealWindow, gapsAfterMealWindow, gapsCoveredByActualHardBreak, gapsIncorrectlyIgnoredBecauseMealWindow:gapsInsideFlexibleMealWindow, mainZoneVisibleContinuityVerdict: totalVisibleMainZoneIdleMinutes>0?"visible_idle":"continuous_or_hard_break_covered", criticalResourceDaySpans:span, criticalResourceWorkMinutes:Object.fromEntries(critical.map(r=>[r,work[r]??0])), criticalResourceIdleMinutes:idle, criticalResourceFirstTaskStart:firstS, criticalResourceLastTaskEnd:lastS, criticalResourceSpanImbalanceMinutes:spanImb, criticalResourceWorkImbalanceMinutes:workImb, criticalResourceIdleImbalanceMinutes:idleImb, coachLikeResourceBalanceVerdict:spanImb>maxSpanImb?"imbalanced":"balanced_or_insufficient_data", overextendedResourceIds:over, underusedComparableResourceIds:under, talentInitialWaits, averageArrivalToFirstTaskWaitMinutes:avgWait, maxArrivalToFirstTaskWaitMinutes:maxInitial, talentsWithExcessiveInitialWait:excessive, callTimeAlignmentVerdict:excessive.length?"misaligned":"aligned_or_insufficient_data", talentReleaseWaits, mealMode:meal.mealMode, mealPlacementWindow:mealWindow, actualGlobalMealBreaks:[...meal.globalHardBreaks,...meal.actualMealBreaks], mealPlaceholdersCount, tasksScheduledInsideMealWindow:inMeal.length, productiveTasksAllowedInsideMealWindow:meal.mealMode==="flexible_meal_window", blankMealWindowMinutes, mealWindowTreatedAsGlobalStopSuspected:overBlocking, mealPolicyVerdict:overBlocking?"over_blocking_suspected":"ok_or_insufficient_data", firstArrivalTime, firstProductiveTaskTime, firstMainZoneProductiveTaskTime, preProductiveIdleByTalent:preByTalent, preProductiveIdleByCriticalResource:Object.fromEntries(critical.map(r=>[r, Math.max(0,(first[r]??0)-(productive[0]?.a??0))])), preLunchGlobalIdleWindows:[], startLaterRecommendation, recommendedDayStartShiftMinutes:startLaterRecommendation?Math.max(0,Math.min(maxInitial-maxWait,60)):0, startLaterReason:startLaterRecommendation?"start_later_candidate_required":null, mainZoneCoachSwitchPolicy:{...policy,configured:policyConfigured}, mainZoneCoachSequence:compactSeq, mainZoneCoachSwitches:switches, mainZoneCoachBlocks:blocks, morningMainZoneCoachBlocks:morn, afternoonMainZoneCoachBlocks:aft };
}
