import type { OperationalState, SimulatedState } from "../contracts";
import { buildMainZoneGapResourceBlockSwapCandidates } from "../see/mainZoneGapResourceBlockSwapCandidateBuilder";
import { resolveCompositeSimulationLineage, type CompositeSimulationLineage } from "./resolveCompositeSimulationLineage";
import { auditProductionConceptAlignment, type ProductionConceptAlignmentAudit } from "../analysis/productionConceptAlignmentAudit";
import { validateCompositeMaterializationChangeSources } from "./validateCompositeMaterializationChangeSources";
import { buildProductionWavePlannerBlueprint, type ProductionWavePlannerBlueprint } from "../macro/productionWavePlannerBlueprint";
import { ORC_MACRO_MAIN_ZONE_BLOCK_RELAYOUT_CONTRACT_VERSION_ID238 } from "../macro/macroMainZoneBlockRelayoutCandidateBuilder";

export const ORC_COMPOSITE_SUMMARY_CONTRACT_VERSION_ID229 = "ORC-COMPOSITE-SUMMARY-ID229" as const;
export const ORC_COMPOSITE_MATERIALIZATION_CONTRACT_VERSION_ID229 = "ORC-COMPOSITE-MATERIALIZATION-ID229" as const;
export const ORC_FINAL_MAIN_ZONE_CONTINUITY_CONTRACT_VERSION_ID229 = "ORC-FINAL-MAIN-ZONE-CONTINUITY-ID229" as const;
export const ORC_COMPOSITE_DESCENDANT_SUMMARY_CONTRACT_VERSION_ID233 = "ORC-COMPOSITE-DESCENDANT-SUMMARY-ID233" as const;
export const ORC_REJECTED_OPTIONAL_IMPROVEMENT_MATERIALIZATION_CONTRACT_VERSION_ID236 = "ORC-REJECTED-OPTIONAL-IMPROVEMENT-MATERIALIZATION-ID236" as const;

type Rec = Record<string, unknown>;
const isRec = (v: unknown): v is Rec => typeof v === "object" && v !== null && !Array.isArray(v);
const nums = (v: unknown): number[] => Array.isArray(v) ? v.map(Number).filter(Number.isFinite).sort((a,b)=>a-b) : [];
const str = (v: unknown): string | null => typeof v === "string" ? v : null;

function fp(e: any): string { return JSON.stringify({ taskId: e.taskId, startPlanned: e.startPlanned, endPlanned: e.endPlanned, spaceId: e.spaceId ?? e.assignedSpace ?? null, assignedResourceIds: [...(e.assignedResourceIds ?? e.assignedResources ?? [])].map(Number).filter(Number.isFinite).sort((a,b)=>a-b) }); }
function changedIds(from?: OperationalState | null, to?: OperationalState | null): number[] {
  const a = new Map((from?.planning ?? []).map((e: any) => [Number(e.taskId), fp(e)]));
  const b = new Map((to?.planning ?? []).map((e: any) => [Number(e.taskId), fp(e)]));
  return [...new Set([...a.keys(), ...b.keys()].filter(Number.isFinite).filter((id) => a.get(id) !== b.get(id)))].sort((x,y)=>x-y);
}

function targeted(summary: Rec): Rec {
  const before = typeof summary.targetedGapBeforeMinutes === "number" ? summary.targetedGapBeforeMinutes : (typeof summary.mainZoneGapReductionMinutes === "number" && typeof summary.mainZoneLargestGapBefore === "number" ? summary.mainZoneLargestGapBefore : summary.gapMinutesBefore ?? null);
  const after = typeof summary.targetedGapAfterMinutes === "number" ? summary.targetedGapAfterMinutes : (summary.mainZoneLargestGapAfter ?? summary.expectedGapMinutesAfter ?? null);
  const reduction = typeof summary.targetedGapReductionMinutes === "number" ? summary.targetedGapReductionMinutes : (typeof before === "number" && typeof after === "number" ? Math.max(0, before - after) : (summary.mainZoneGapReductionMinutes ?? 0));
  return { targetedGapBeforeMinutes: before, targetedGapAfterMinutes: after, targetedGapReductionMinutes: reduction, targetedGapPreviousTaskId: summary.targetedGapPreviousTaskId ?? null, targetedGapNextTaskId: summary.targetedGapNextTaskId ?? null, targetedGapWindowBefore: summary.targetedGapWindowBefore ?? null, targetedGapWindowAfter: summary.targetedGapWindowAfter ?? null, continuityMetricScope: "targeted-gap", mainZoneGapReductionMinutes: reduction };
}

export function buildFinalORCCompositeSummary(args: { originalState?: OperationalState | null; repairedState?: OperationalState | null; selectedSimulation?: SimulatedState | null; initialMainZoneContinuity?: Rec | null; mainZoneGapResourceBlockSwap?: Rec | null; postRepairMainZoneContinuityPass?: Rec | null; simulationSelection?: Rec | null; criticalResourceIdleCompression?: Rec | null; macroMainZoneBlockRelayout?: Rec | null; planningMaterialization?: Rec | null }): { mainZoneContinuity: Rec; mainZoneGapResourceBlockSwap: Rec; postRepairMainZoneContinuityPass: Rec; criticalResourceIdleCompression: Rec; planningMaterialization: Rec; summaryContractValid: boolean; summaryContractWarnings: string[]; finalSummaryBuiltFromSelectedSimulation: boolean; compositeSimulationLineage: CompositeSimulationLineage; finalSelectedCandidateFamily: string | null; finalSelectedSimulationIncludesBaselineRepair: boolean; finalSelectedSimulationIncludesPostRepairContinuity: boolean; finalSelectedSimulationIncludesCriticalResourceIdleCompression: boolean; macroMainZoneBlockRelayout: Rec; productionConceptAlignment: ProductionConceptAlignmentAudit; rejectedOptionalImprovements: Rec; rejectedMacroImprovements: Rec; explainabilityGateSource: string; readOnlyAuditDoesNotAffectGate: true; productionWavePlanner: ProductionWavePlannerBlueprint; macroPlannerBlueprintReady: boolean; recommendedNextCapabilityFromBlueprint: string | null } {
  const finalState = args.selectedSimulation?.operationalStateSnapshot ?? null;
  const selectedPost = isRec(args.postRepairMainZoneContinuityPass) && args.postRepairMainZoneContinuityPass.selectedAsCommit === true;
  const selectedSwap = isRec(args.mainZoneGapResourceBlockSwap) && args.mainZoneGapResourceBlockSwap.selectedAsCommit === true;
  const selectedIdle = isRec(args.criticalResourceIdleCompression) && args.criticalResourceIdleCompression.selectedAsCommit === true;
  const selectedMacro = isRec(args.macroMainZoneBlockRelayout) && args.macroMainZoneBlockRelayout.selectedAsCommit === true;
  const rejectedIdle = isRec(args.criticalResourceIdleCompression) && args.criticalResourceIdleCompression.executed === true && args.criticalResourceIdleCompression.selectedAsCommit === false;
  const rejectedMacro = isRec(args.macroMainZoneBlockRelayout) && args.macroMainZoneBlockRelayout.executed === true && args.macroMainZoneBlockRelayout.selectedAsCommit === false;
  const built = finalState ? buildMainZoneGapResourceBlockSwapCandidates(finalState) : null;
  const baseContinuity = built?.mainZoneContinuity ?? args.initialMainZoneContinuity ?? {};
  const finalGaps = Array.isArray((baseContinuity as any).gaps) ? [...(baseContinuity as any).gaps] : [];
  const mainZoneContinuity: Rec = {
    ...baseContinuity,
    summaryScope: "final-selected-planning",
    resolutionSource: selectedMacro || selectedIdle || selectedPost || selectedSwap ? "selected-composite-simulation" : "selected-simulation",
    selectedSimulatedStateId: args.selectedSimulation?.id ?? null,
    selectedCandidateId: str(args.postRepairMainZoneContinuityPass?.selectedCandidateId) ?? str(args.mainZoneGapResourceBlockSwap?.selectedCandidateId),
    finalPlanningSource: selectedMacro ? "macro-main-zone-block-relayout" : selectedIdle ? "critical-resource-idle-compression" : selectedPost ? "post-repair-main-zone-continuity" : "selected-orc-simulation",
    finalMainZoneGapCount: finalGaps.length,
    finalLargestMainZoneGapMinutes: finalGaps.reduce((m, g: any) => Math.max(m, Number(g.gapMinutes ?? 0)), 0),
    finalGaps,
    gapComputationScope: "final-selected-planning",
    gapExclusionPolicy: "exclude-hard-break-covered-gaps-only",
    breakCoveragePolicy: "hard-breaks-cover-gaps;flexible-meal-windows-require-placeholder",
    readOnly: true,
  };
  const warnings: string[] = [];
  if ((selectedMacro || selectedIdle || selectedPost || selectedSwap) && mainZoneContinuity.configured === false) warnings.push("main_zone_final_summary_inconsistent_with_selected_commit");

  const fromOriginal = changedIds(args.originalState, finalState);
  const fromRepaired = changedIds(args.repairedState ?? null, finalState);
  const repairIds = nums(args.mainZoneGapResourceBlockSwap?.baselineRepairChangedTaskIds).length ? nums(args.mainZoneGapResourceBlockSwap?.baselineRepairChangedTaskIds) : changedIds(args.originalState, args.repairedState ?? null);
  const postIds = [...new Set([...nums(args.postRepairMainZoneContinuityPass?.movedMainZoneTaskIds), ...nums(args.postRepairMainZoneContinuityPass?.movedBlockingTaskIds)])].sort((a,b)=>a-b);
  const idleIds = nums(args.criticalResourceIdleCompression?.movedTaskIds);
  const compositeSelected = selectedMacro || selectedIdle || selectedPost || selectedSwap;
  const effectiveChangedIds = compositeSelected ? fromOriginal : nums(args.planningMaterialization?.changedTaskIds);
  const effectiveChangedCount = compositeSelected ? fromOriginal.length : Number(args.planningMaterialization?.changedTaskCount ?? effectiveChangedIds.length);
  const existingSources = isRec(args.planningMaterialization?.changeSources) ? args.planningMaterialization.changeSources as Rec : {};
  const rejectedOptionalImprovements: Rec = { ...(rejectedIdle ? { criticalResourceIdleCompression: { rejected: true, selectedAsCommit: false, rejectionReason: args.criticalResourceIdleCompression?.rejectionReason ?? null, changedTaskIds: idleIds } } : {}), ...(rejectedMacro ? { macroMainZoneBlockRelayout: { rejected: true, selectedAsCommit: false, rejectionReason: (args.macroMainZoneBlockRelayout?.netValue as Rec | undefined)?.rejectionReason ?? args.macroMainZoneBlockRelayout?.reason ?? null, changedTaskIds: nums(args.macroMainZoneBlockRelayout?.movedTaskIds) } } : {}) };
  const macroNet = isRec(args.macroMainZoneBlockRelayout?.netValue) ? args.macroMainZoneBlockRelayout!.netValue as Rec : {};
  const rejectedMacroImprovements: Rec = rejectedMacro ? { macroMainZoneBlockRelayout: { rejected: true, candidateIds: nums(args.macroMainZoneBlockRelayout?.candidateIds).length ? nums(args.macroMainZoneBlockRelayout?.candidateIds) : (Array.isArray(args.macroMainZoneBlockRelayout?.candidateIds) ? args.macroMainZoneBlockRelayout?.candidateIds : []), simulationIds: isRec(args.macroMainZoneBlockRelayout?.lineage) && Array.isArray((args.macroMainZoneBlockRelayout!.lineage as Rec).simulatedStateIds) ? (args.macroMainZoneBlockRelayout!.lineage as Rec).simulatedStateIds : [], localValuePositive: (macroNet.acceptedByMacroValueGate === true) || Number(macroNet.localTargetGapReductionMinutes ?? macroNet.visibleMainZoneIdleReductionMinutes ?? 0) > 0, globalValuePositive: macroNet.acceptedByGlobalMacroValueGate === true, rejectionReason: macroNet.rejectionReason ?? args.macroMainZoneBlockRelayout?.reason ?? null, globalMacroRejectionReason: macroNet.globalMacroRejectionReason ?? null, declaredMovedTaskIds: nums(args.macroMainZoneBlockRelayout?.movedTaskIds), inferredChangedTaskIds: nums(macroNet.inferredChangedTaskIds), wouldHaveChangedTaskIds: nums(macroNet.changedTaskIds).length ? nums(macroNet.changedTaskIds) : nums(args.macroMainZoneBlockRelayout?.movedTaskIds), readOnly: true } } : {};
  const baselineSourceIds = repairIds.length ? repairIds : nums((existingSources.baselineOverlapRepair as Rec | undefined)?.changedTaskIds);
  const postSourceIds = postIds.length ? postIds : nums((existingSources.postRepairMainZoneContinuity as Rec | undefined)?.changedTaskIds);
  const idleSourceIds = idleIds.length ? idleIds : nums((existingSources.criticalResourceIdleCompression as Rec | undefined)?.changedTaskIds);
  const changeSources: Rec = {
    ...(baselineSourceIds.length || isRec(existingSources.baselineOverlapRepair) ? { baselineOverlapRepair: { changedTaskCount: baselineSourceIds.length || Number((existingSources.baselineOverlapRepair as Rec | undefined)?.changedTaskCount ?? 0), changedTaskIds: baselineSourceIds, readOnly: true } } : {}),
    ...(postSourceIds.length || isRec(existingSources.postRepairMainZoneContinuity) ? { postRepairMainZoneContinuity: { changedTaskCount: postSourceIds.length || Number((existingSources.postRepairMainZoneContinuity as Rec | undefined)?.changedTaskCount ?? 0), changedTaskIds: postSourceIds, readOnly: true } } : {}),
    ...(selectedIdle ? { criticalResourceIdleCompression: { changedTaskCount: idleSourceIds.length || Number((existingSources.criticalResourceIdleCompression as Rec | undefined)?.changedTaskCount ?? 0), changedTaskIds: idleSourceIds, readOnly: true } } : {}),
    ...(selectedMacro ? { macroMainZoneBlockRelayout: (() => { const existing = isRec(existingSources.macroMainZoneBlockRelayout) ? existingSources.macroMainZoneBlockRelayout as Rec : {}; const ids = nums(existing.changedTaskIds).length ? nums(existing.changedTaskIds) : (nums(macroNet.changedTaskIds).length ? nums(macroNet.changedTaskIds) : nums(args.macroMainZoneBlockRelayout?.movedTaskIds)); const declared = nums(existing.declaredMovedTaskIds).length ? nums(existing.declaredMovedTaskIds) : nums(args.macroMainZoneBlockRelayout?.movedTaskIds); const additional = ids.filter(id => !declared.includes(id)); return { changedTaskCount: ids.length, changedTaskIds: ids, declaredMovedTaskIds: declared, inferredChangedTaskIds: ids, additionalChangedTaskIdsFromSimulationDiff: additional, sourceBaseSimulationId: existing.sourceBaseSimulationId ?? args.macroMainZoneBlockRelayout?.sourceSimulationId ?? null, selectedMacroSimulationId: existing.selectedMacroSimulationId ?? args.macroMainZoneBlockRelayout?.selectedSimulatedStateId ?? null, diffScope: "post-repair-continuity-to-selected-macro-simulation", readOnly: true }; })() } : {}),
  };
  const planningMaterialization: Rec = { ...(args.planningMaterialization ?? {}), changedTaskCount: effectiveChangedCount, changedTaskIds: effectiveChangedIds, changedTaskCountFromOriginalBaseline: compositeSelected ? fromOriginal.length : effectiveChangedCount, changedTaskIdsFromOriginalBaseline: compositeSelected ? fromOriginal : effectiveChangedIds, changedTaskCountFromRepairedBaseline: compositeSelected ? fromRepaired.length : effectiveChangedCount, changedTaskIdsFromRepairedBaseline: compositeSelected ? fromRepaired : effectiveChangedIds, changedTaskIdsFromPostRepairContinuityBaseline: selectedMacro ? nums((changeSources.macroMainZoneBlockRelayout as Rec | undefined)?.changedTaskIds) : nums(args.planningMaterialization?.changedTaskIdsFromPostRepairContinuityBaseline), changeSources, compositeTransformationsApplied: [baselineSourceIds.length || isRec(existingSources.baselineOverlapRepair) ? "baseline-overlap-repair" : null, postSourceIds.length || isRec(existingSources.postRepairMainZoneContinuity) ? "post-repair-main-zone-continuity" : null, selectedIdle ? "critical-resource-idle-compression" : null, selectedMacro ? "macro-main-zone-block-relayout" : null].filter(Boolean), compositeMaterializationContractVersion: ORC_COMPOSITE_MATERIALIZATION_CONTRACT_VERSION_ID229, rejectedOptionalImprovementMaterializationContractVersion: ORC_REJECTED_OPTIONAL_IMPROVEMENT_MATERIALIZATION_CONTRACT_VERSION_ID236, summaryContractValid: warnings.length === 0, readOnly: true };
  const compositeSimulationLineage = resolveCompositeSimulationLineage({ selectedSimulation: args.selectedSimulation, simulationSelection: args.simulationSelection, baselineOverlapRepair: args.mainZoneGapResourceBlockSwap, postRepairMainZoneContinuityPass: args.postRepairMainZoneContinuityPass, mainZoneGapResourceBlockSwap: args.mainZoneGapResourceBlockSwap, criticalResourceIdleCompression: args.criticalResourceIdleCompression, changeSources: planningMaterialization.changeSources as Rec });
  warnings.push(...compositeSimulationLineage.lineageWarnings);
  const materializationDiff = compositeSelected ? validateCompositeMaterializationChangeSources({ originalState: args.originalState, selectedFinalState: finalState, changeSources: planningMaterialization.changeSources as Rec, selectedFinalCandidateFamily: compositeSimulationLineage.finalSelectedCandidateFamily, rejectedOptionalImprovements }) : { summaryContractValid: true, unexplainedChangedTaskIds: [], explainedChangedTaskIds: effectiveChangedIds, declaredButUnchangedTaskIds: [], appliedChangeSourceKeys: Object.keys(planningMaterialization.changeSources as Rec).sort(), rejectedChangeSourceKeys: Object.keys(rejectedOptionalImprovements).sort(), warnings: [], materializationDiffContractValid: true, readOnlyAuditDoesNotAffectGate: true as const };
  warnings.push(...materializationDiff.warnings);
  if (selectedIdle && args.criticalResourceIdleCompression?.mainZoneContinuityPreserved === false) warnings.push("critical_resource_idle_compression_would_worsen_main_zone_continuity");
  if (selectedIdle && args.criticalResourceIdleCompression?.selectedAsCommit !== true) warnings.push("critical_resource_idle_compression_selected_but_summary_not_committed");
  const planningSource = selectedMacro ? "macro-main-zone-block-relayout" : selectedIdle ? "critical-resource-idle-compression" : selectedPost ? "post-repair-main-zone-continuity" : "selected-orc-simulation";
  const productionConceptAlignment = auditProductionConceptAlignment({ operationalState: finalState, planningSource, selectedSimulatedStateId: args.selectedSimulation?.id ?? null, finalSelectedCandidateFamily: compositeSimulationLineage.finalSelectedCandidateFamily, previousMainZoneContinuity: mainZoneContinuity });
  const productionWavePlanner = buildProductionWavePlannerBlueprint({ operationalState: finalState, productionConceptAlignment, planningSource, selectedSimulatedStateId: args.selectedSimulation?.id ?? null });
  const macroSummary: Rec = { contractVersion: ORC_MACRO_MAIN_ZONE_BLOCK_RELAYOUT_CONTRACT_VERSION_ID238, executed:false, executionPhase:"not-executed", reason:"not_executed", sourceSimulationId:null, sourcePlanningKind:null, targetGapStart:null, targetGapEnd:null, targetGapMinutesBefore:null, generatedCandidateCount:0, candidateIds:[], prefilterAcceptedCount:0, prefilterDiscardedCount:0, candidateStateCount:0, simulatedStateCount:0, validSimulationCount:0, invalidSimulationCount:0, selectedAsCommit:false, selectedCandidateId:null, selectedSimulatedStateId:null, selectedVariantType:null, movedTaskIds:[], movedMainZoneTaskIds:[], movedSupportTaskIds:[], affectedResourceIds:[], affectedSpaceIds:[], visibleMainZoneIdleBefore:null, visibleMainZoneIdleAfter:null, visibleMainZoneIdleReductionMinutes:0, coachSwitchCountBefore:null, coachSwitchCountAfter:null, usesFlexibleMealWindowAsProductiveTime:false, mealWindowTreatedAsHardStop:false, netValue:{acceptedByMacroValueGate:false,rejectionReason:"not_executed",readOnly:true}, candidateGenerationBlockers:["not_executed"], prefilterDiscardReasons:{}, prefilterDiscardDetails:[], validationRejectReasons:[], warnings:[], dependencyAnalysisAvailable:false, dependencySafeCandidateCount:0, dependencyBlockedCandidateCount:0, dependencyBlockedReasons:[], dependencyBrokenPairsPrevented:[], selectedDependencyPreservationMode:null, selectedDependencySafeStart:null, selectedLatestPrerequisiteEnd:null, selectedMovedPrerequisiteTaskIds:[], selectedLeftInPlacePrerequisiteTaskIds:[], variantCountsByType:{}, suffixCompactionGenerated:false, suffixCompactionCandidateIds:[], suffixCompactionValidSimulationIds:[], suffixCompactionRejectedSimulationIds:[], suffixCompactionRejectReasons:[], selectedSuffixCompaction:false, selectedSuffixMovedTaskIds:[], selectedSuffixOriginalStart:null, selectedSuffixOriginalEnd:null, selectedSuffixCompactedStart:null, selectedSuffixCompactedEnd:null, selectedDependencyCursorWaitGaps:[], selectedDependencyWaitMinutes:0, macroMainZoneSuffixCompactionContractVersion:"ORC-MACRO-MAIN-ZONE-SUFFIX-COMPACTION-ID242", macroMainZoneDominanceGateContractVersion:"ORC-MACRO-MAIN-ZONE-DOMINANCE-GATE-ID243", macroMainZoneSuffixSummaryConsistencyContractVersion:"ORC-MACRO-MAIN-ZONE-SUFFIX-SUMMARY-CONSISTENCY-ID243", readOnly:true, ...(args.macroMainZoneBlockRelayout ?? {}) };
  const finalFamily = selectedMacro ? "macro-main-zone-block-relayout" : compositeSimulationLineage.finalSelectedCandidateFamily;
  return { productionWavePlanner, macroMainZoneBlockRelayout: macroSummary, macroPlannerBlueprintReady: productionWavePlanner.blueprintGenerated === true && productionWavePlanner.candidateReadiness?.safeToGenerateCandidateInNextIteration === true, recommendedNextCapabilityFromBlueprint: productionWavePlanner.recommendedNextCapability ?? null, productionConceptAlignment, mainZoneContinuity: { ...mainZoneContinuity, selectedContinuityCandidateId: str(args.postRepairMainZoneContinuityPass?.selectedCandidateId) ?? str(args.mainZoneGapResourceBlockSwap?.selectedCandidateId), selectedContinuitySimulatedStateId: str(args.postRepairMainZoneContinuityPass?.selectedSimulatedStateId), finalSelectedSimulatedStateId: compositeSimulationLineage.finalSelectedSimulatedStateId, finalSelectedCandidateFamily: finalFamily }, mainZoneGapResourceBlockSwap: { ...(args.mainZoneGapResourceBlockSwap ?? {}), ...targeted(args.mainZoneGapResourceBlockSwap ?? {}) }, postRepairMainZoneContinuityPass: { ...(args.postRepairMainZoneContinuityPass ?? {}), ...targeted(args.postRepairMainZoneContinuityPass ?? {}) }, criticalResourceIdleCompression: { ...(args.criticalResourceIdleCompression ?? {}), baseCompositeSimulationId: compositeSimulationLineage.baseCompositeSimulationId, finalSelectedSimulatedStateId: compositeSimulationLineage.finalSelectedSimulatedStateId, selectedAsFinalCommit: selectedIdle && compositeSimulationLineage.criticalResourceIdleCompressionReflectedInFinalSelection }, planningMaterialization: { ...planningMaterialization, appliedChangeSourceKeys: materializationDiff.appliedChangeSourceKeys, rejectedChangeSourceKeys: materializationDiff.rejectedChangeSourceKeys, unexplainedChangedTaskIds: materializationDiff.unexplainedChangedTaskIds, declaredButUnchangedTaskIds: materializationDiff.declaredButUnchangedTaskIds, materializationDiffContractValid: materializationDiff.materializationDiffContractValid, summaryContractValid: warnings.length === 0 }, summaryContractValid: warnings.length === 0, summaryContractWarnings: warnings, finalSummaryBuiltFromSelectedSimulation: finalState != null, compositeSimulationLineage, finalSelectedCandidateFamily: finalFamily, finalSelectedSimulationIncludesBaselineRepair: compositeSimulationLineage.includesBaselineOverlapRepair, finalSelectedSimulationIncludesPostRepairContinuity: compositeSimulationLineage.includesPostRepairMainZoneContinuity, finalSelectedSimulationIncludesCriticalResourceIdleCompression: compositeSimulationLineage.includesCriticalResourceIdleCompression, rejectedOptionalImprovements, rejectedMacroImprovements, explainabilityGateSource: "composite-materialization-change-source-validation-id236", readOnlyAuditDoesNotAffectGate: true };
}
