import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { compareInitialConstructionPartialPlanOperationalQuality, commonDecisionPathPrefixLength, createInitialConstructionSuspendedFrontier, type InitialConstructionSuspendedFrontier } from "./initialConstructionSuspendedFrontier";

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
const norm=(a:any)=>({taskId:Number(a.taskId),startPlanned:a.startPlanned??null,endPlanned:a.endPlanned??null,spaceId:a.spaceId??null,resourceIds:[...(a.resourceIds??a.assignedResourceIds??[])].map(Number).sort((x,y)=>x-y)});
const assignmentKey=(a:any)=>hash(norm(a));
const numIds=(xs:any)=>[...new Set([...(xs??[])].map(Number).filter(Number.isFinite))].sort((a,b)=>a-b);
const strIds=(xs:any)=>[...new Set([...(xs??[])].map(String).filter(Boolean))].sort();

export type InitialConstructionCausalBlockerClassification="REVERSIBLE_PROVISIONAL"|"PROTECTED_BY_LOCK_OR_STATE"|"EXTERNAL_ORIGIN"|"STRUCTURAL_UNATTRIBUTABLE";
export type InitialConstructionAlternativeCausalReason="CAUSALLY_USEFUL"|"SAME_CAUSAL_CONFLICT"|"CHANGES_ONLY_NON_BLOCKING_DECISIONS"|"NO_SHARED_CAUSAL_HISTORY"|"NO_REVERSIBLE_CAUSAL_DECISION"|"INCOMPLETE_CAUSAL_EVIDENCE"|"NOGOOD_EQUIVALENT_CONFLICT";

export function buildInitialConstructionFrontierFailureEvidence(input:any){
 const d=input?.diagnostics??input??{};
 const executionTaskId=Number(input?.executionTaskId??input?.anchorTaskId??d.executionTaskId??d.anchorTaskId??null);
 const primaryGoalTaskId=Number(input?.primaryGoalTaskId??executionTaskId);
 const rejectionReasonCodes=strIds([...(input?.rejectionReasonCodes??[]),...Object.keys(d.deadEndReasonCounts??{}),...Object.keys(d.placementReasonCounts??{}),...Object.keys(d.anchorPlacementReasonCounts??{})]);
 const attemptedIntervals=[...(input?.attemptedIntervals??d.attemptedIntervals??d.taskWindowConflictDetails??[])].map((x:any)=>({startPlanned:x?.startPlanned??x?.start??null,endPlanned:x?.endPlanned??x?.end??null})).sort((a:any,b:any)=>String(a.startPlanned).localeCompare(String(b.startPlanned))||String(a.endPlanned).localeCompare(String(b.endPlanned))).slice(0,20);
 const selectedCandidate=d.selectedFailureCandidate??input?.selectedFailureCandidate??null;
 const evidenceComplete=(selectedCandidate?.evidenceComplete??d.causalConflictEvidenceComplete)!==false && input?.evidenceComplete!==false;
 const candidateTaskIds=numIds(selectedCandidate?.repairableConflictTaskIds);
 const causalTaskIds=candidateTaskIds.length?candidateTaskIds:numIds(d.causalConflictTaskIds);
 const payload={executionTaskId:Number.isFinite(executionTaskId)?executionTaskId:null,primaryGoalTaskId:Number.isFinite(primaryGoalTaskId)?primaryGoalTaskId:null,supportedGoalTaskIds:numIds(input?.supportedGoalTaskIds??[primaryGoalTaskId]),retainedValidBranchCount:Number(input?.retainedValidBranchCount??d.retainedValidBranchCount??d.hardValidBranchCount??0),rejectionReasonCodes,selectedTemporalCandidateFingerprint:selectedCandidate?.temporalCandidateFingerprint??null,selectedFailureCandidateClassification:selectedCandidate?.classification??null,rejectedTemporalCandidateEvidence:d.rejectedTemporalCandidateEvidence??[],rejectedTemporalCandidateEvidenceCount:Number(d.rejectedTemporalCandidateEvidenceCount??0),repairableRejectedTemporalCandidateCount:Number(d.repairableRejectedTemporalCandidateCount??0),staticRejectedTemporalCandidateCount:Number(d.staticRejectedTemporalCandidateCount??0),immutableRejectedTemporalCandidateCount:Number(d.immutableRejectedTemporalCandidateCount??0),incompleteRejectedTemporalCandidateCount:Number(d.incompleteRejectedTemporalCandidateCount??0),repairableConflictTaskIds:numIds(selectedCandidate?.repairableConflictTaskIds),immutableConflictTaskIds:numIds(selectedCandidate?.immutableConflictTaskIds),staticUnrepairableReasonCodes:strIds(selectedCandidate?.staticUnrepairableReasonCodes),windowConflictCausalLinks:selectedCandidate?.windowConflictCausalLinks??[],hardBlockerDimensions:strIds(selectedCandidate?.hardBlockerDimensions),coveredHardBlockerDimensions:strIds(selectedCandidate?.coveredHardBlockerDimensions),uncoveredHardBlockerDimensions:strIds(selectedCandidate?.uncoveredHardBlockerDimensions),allHardBlockersCovered:Boolean(selectedCandidate?.allHardBlockersCovered),allHardBlockersRepairable:Boolean(selectedCandidate?.allHardBlockersRepairable),causalConflictTaskIds:causalTaskIds,contestantConflictTaskIds:numIds(selectedCandidate?.contestantConflictTaskIds??d.contestantConflictTaskIds),spaceConflictTaskIds:numIds(selectedCandidate?.spaceConflictTaskIds??d.spaceConflictTaskIds),resourceConflictTaskIds:numIds(selectedCandidate?.resourceConflictTaskIds??d.resourceConflictTaskIds),dependencyLowerBoundTaskIds:numIds(selectedCandidate?.dependencyLowerBoundTaskIds??d.dependencyLowerBoundTaskIds),dependencyUpperBoundTaskIds:numIds(selectedCandidate?.dependencyUpperBoundTaskIds??d.dependencyUpperBoundTaskIds),protectedIntervalConflictIds:strIds(selectedCandidate?.protectedIntervalConflictIds??d.protectedIntervalConflictIds),attemptedTemporalCandidateFingerprints:strIds(input?.attemptedTemporalCandidateFingerprints??d.attemptedTemporalCandidateFingerprints),attemptedIntervals,evidenceComplete,incompleteReasonCodes:evidenceComplete?[]:strIds([...(selectedCandidate?.incompleteReasonCodes??[]),...(input?.incompleteReasonCodes??[]),"INCOMPLETE_SOURCE_DIAGNOSTICS"]),sourceDiagnosticsFingerprint:selectedCandidate?.fingerprint??d.causalConflictEvidenceFingerprint??d.fingerprint??input?.sourceDiagnosticsFingerprint??null};
 return deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as any;
}

export function buildInitialConstructionDecisionAssignmentIndex(partialPlan:any){
 const rootTasks=new Set((partialPlan?.rootAssignmentTaskIds??[]).map(Number));
 const active=[...(partialPlan?.assignments??[])].map(norm).sort((a,b)=>a.taskId-b.taskId); const activeByTask=new Map(active.map(a=>[a.taskId,a]));
 const entries:any[]=[]; const byDecisionId:any={}; const byDecisionDepth:any={}; let lookupMissCount=0;
 for(const le of [...(partialPlan?.decisionLineage??[])].sort((a:any,b:any)=>Number(a.decisionDepth)-Number(b.decisionDepth)||String(a.decisionId).localeCompare(String(b.decisionId)))){
  const decision={decisionId:String(le.decisionId),decisionDepth:Number(le.decisionDepth),primaryGoalTaskId:Number(le.primaryGoalTaskId),executionTaskId:Number(le.executionTaskId),branchFingerprint:String(le.branchFingerprint??""),fingerprint:String(le.fingerprint??hash(le)),readOnly:true}; byDecisionId[decision.decisionId]=decision; byDecisionDepth[String(decision.decisionDepth)]=decision;
  for(const ia of le.introducedAssignments??[]){ const taskId=Number(ia.taskId); const a=activeByTask.get(taskId); if(!a) {lookupMissCount++; continue;} const key=assignmentKey(a); if(String(ia.assignmentFingerprint)===key) entries.push({assignment:a,assignmentKey:key,taskId,classification:rootTasks.has(taskId)?"PROTECTED_BY_LOCK_OR_STATE":"REVERSIBLE_PROVISIONAL",decision:decision.decisionId,decisionId:decision.decisionId,decisionDepth:decision.decisionDepth,decisionFingerprint:decision.fingerprint,readOnly:true}); }
 }
 const latest=new Map<number,any>(); for(const e of entries) latest.set(e.taskId,e);
 for(const a of active) if(!latest.has(a.taskId)) latest.set(a.taskId,{assignment:a,assignmentKey:assignmentKey(a),taskId:a.taskId,classification:rootTasks.has(a.taskId)?"PROTECTED_BY_LOCK_OR_STATE":"STRUCTURAL_UNATTRIBUTABLE",decision:null,decisionId:null,decisionDepth:null,readOnly:true});
 const out=[...latest.values()].sort((a,b)=>a.taskId-b.taskId); return deepFreeze({entries:out,byTaskId:Object.fromEntries(out.map(e=>[String(e.taskId),e])),byAssignmentKey:Object.fromEntries(out.map(e=>[e.assignmentKey,e])),byDecisionId,byDecisionDepth,lookupCount:out.length,lookupMissCount,fingerprint:hash(out.map(e=>({k:e.assignmentKey,t:e.taskId,c:e.classification,d:e.decisionId,depth:e.decisionDepth}))),readOnly:true}) as any;
}

export function buildInitialConstructionCausalConflict(args:{failedPartialPlan:any; expansion:any; frontierFailureEvidence?:any[]}){
 const index=buildInitialConstructionDecisionAssignmentIndex(args.failedPartialPlan);
 const source=[...(args.frontierFailureEvidence??args.expansion?.frontierFailureEvidence??[])];
 const evidences=(source.length?source:[...(args.expansion?.frontierTasksConsidered??[]).filter((x:any)=>x.causalConflictTaskIds||x.diagnostics).map((x:any)=>buildInitialConstructionFrontierFailureEvidence(x))]).map((e:any)=>e?.fingerprint?e:buildInitialConstructionFrontierFailureEvidence(e)).sort((a:any,b:any)=>Number(b.evidenceComplete)-Number(a.evidenceComplete)||Number(b.supportedGoalTaskIds?.length??0)-Number(a.supportedGoalTaskIds?.length??0)||String(a.fingerprint).localeCompare(String(b.fingerprint)));
 const selected=evidences[0]??buildInitialConstructionFrontierFailureEvidence({...(args.expansion?.frontierTasksConsidered??[])[0],diagnostics:{causalConflictEvidenceComplete:false}});
 const reasons=strIds([...(selected.rejectionReasonCodes??[]),...Object.keys(args.expansion?.frontierExhaustionReasonCounts??{})]); if(!reasons.length) reasons.push(String(args.expansion?.stopReason??"DEAD_END"));
 const evidenceTaskIds=numIds(selected.causalConflictTaskIds); const blockers:any[]=[], classified:any[]=[]; let missing=0;
 for(const taskId of evidenceTaskIds){ const e=index.byTaskId[String(taskId)]; if(!e){missing++; classified.push({taskId,classification:"EXTERNAL_ORIGIN",reason:"TASK_NOT_ASSIGNED_IN_FAILED_PARTIAL_PLAN",readOnly:true}); continue;} const c=e.classification; classified.push({taskId,classification:c,assignmentKey:e.assignmentKey,decisionId:e.decisionId,decisionDepth:e.decisionDepth,readOnly:true}); if(selected.evidenceComplete&&c==="REVERSIBLE_PROVISIONAL") blockers.push({taskId:e.taskId,assignmentKey:e.assignmentKey,classification:c,decision:e.decisionId,decisionId:e.decisionId,decisionDepth:e.decisionDepth,assignment:e.assignment,readOnly:true}); }
 const decisions:any[]=[...new Map<string,any>(blockers.filter((b:any)=>b.decisionId).map((b:any)=>[b.decisionId,{decision:b.decisionId,decisionId:b.decisionId,decisionDepth:b.decisionDepth,taskIds:blockers.filter((x:any)=>x.decisionId===b.decisionId).map((x:any)=>x.taskId).sort((a:any,b:any)=>a-b),readOnly:true}])).values()].sort((a:any,b:any)=>Number(b.decisionDepth)-Number(a.decisionDepth)||String(a.decisionId).localeCompare(String(b.decisionId)));
 const payload={frontierTaskId:selected.executionTaskId,frontierTaskIds:numIds(evidences.map((e:any)=>e.executionTaskId)),criticalGoalTaskIds:numIds(evidences.flatMap((e:any)=>[e.primaryGoalTaskId,...(e.supportedGoalTaskIds??[])])),attemptedIntervals:selected.attemptedIntervals,rejectionReasons:reasons,frontierFailureEvidence:[selected],evidenceComplete:Boolean(selected.evidenceComplete),incompleteReasonCodes:selected.incompleteReasonCodes??[],blockingAssignments:blockers,classifiedConflictTaskIds:classified,causalDecisions:decisions,mostRecentCausalDepth:decisions[0]?.decisionDepth??null,sourceEvidenceFingerprint:selected.fingerprint,causalConflictTaskIdMissingFromActiveAssignmentsCount:missing,decisionLineageLookupCount:index.lookupCount,decisionLineageLookupMissCount:index.lookupMissCount};
 return deepFreeze({...payload,fingerprint:hash({frontierTaskIds:payload.frontierTaskIds,criticalGoalTaskIds:payload.criticalGoalTaskIds,rejectionReasons:payload.rejectionReasons,attemptedIntervals:payload.attemptedIntervals,blockingAssignments:blockers.map((b:any)=>({taskId:b.taskId,assignmentKey:b.assignmentKey,decisionId:b.decisionId,decisionDepth:b.decisionDepth})),classifiedConflictTaskIds:classified,sourceEvidenceFingerprint:selected.fingerprint,evidenceComplete:payload.evidenceComplete}),readOnly:true}) as any;
}

export function evaluateInitialConstructionCausalAlternative(args:{conflict:any; failedPartialPlan:any; alternative:any; nogoodFingerprints?:ReadonlySet<string>}){
 const alt=args.alternative?.partialPlan??args.alternative; const failedPath=[...(args.failedPartialPlan?.decisionPath??[])].map(String); const altPath=[...(alt?.decisionPath??[])].map(String);
 const altByTask=new Map([...(alt?.assignments??[])].map((a:any)=>[Number(a.taskId),assignmentKey(a)])); const failedByTask=new Map([...(args.failedPartialPlan?.assignments??[])].map((a:any)=>[Number(a.taskId),assignmentKey(a)]));
 const causal=args.conflict?.blockingAssignments??[];
 const removed=causal.filter((b:any)=>!altByTask.has(Number(b.taskId))); const changed=causal.filter((b:any)=>altByTask.has(Number(b.taskId))&&altByTask.get(Number(b.taskId))!==b.assignmentKey); const conserved=causal.filter((b:any)=>altByTask.get(Number(b.taskId))===b.assignmentKey);
 const changedDecisions=[...new Set([...removed,...changed].map((b:any)=>b.decisionId??b.decision).filter(Boolean))].sort();
 const causalDepths=causal.map((b:any)=>Number(b.decisionDepth??0)).filter(Boolean); const prefix=commonDecisionPathPrefixLength(failedPath,altPath); const distance=Math.max(0,failedPath.length-prefix);
 const nonBlockingChanged=[...failedByTask].filter(([taskId,key])=>!causal.some((b:any)=>Number(b.taskId)===Number(taskId)) && altByTask.get(taskId)!==key).map(([taskId])=>taskId).sort((a:any,b:any)=>a-b);
 const same=causal.length>0&&conserved.length===causal.length; const wouldRepeat=args.nogoodFingerprints?.has(args.conflict?.fingerprint)===true&&same;
 const useful=args.conflict?.evidenceComplete!==false && !wouldRepeat && (removed.length>0||changed.length>0||causalDepths.some((d:number)=>prefix<d));
 const reason:InitialConstructionAlternativeCausalReason=args.conflict?.evidenceComplete===false?"INCOMPLETE_CAUSAL_EVIDENCE":wouldRepeat?"NOGOOD_EQUIVALENT_CONFLICT":useful?"CAUSALLY_USEFUL":nonBlockingChanged.length?"CHANGES_ONLY_NON_BLOCKING_DECISIONS":same?"SAME_CAUSAL_CONFLICT":causal.length?"NO_REVERSIBLE_CAUSAL_DECISION":"NO_SHARED_CAUSAL_HISTORY";
 const deepestChanged=Math.max(0,...[...removed,...changed].map((b:any)=>Number(b.decisionDepth??0)),...(causalDepths.filter((d:number)=>prefix<d)));
 const payload={alternativePartialPlanId:alt?.partialPlanId??null,alternativeAssignmentsFingerprint:alt?.assignmentsFingerprint??args.alternative?.assignmentsFingerprint??null,causallyUseful:useful,changedDecisions,blockersRemoved:removed.map((b:any)=>b.taskId).sort((a:any,b:any)=>a-b),blockersModified:changed.map((b:any)=>b.taskId).sort((a:any,b:any)=>a-b),blockersConserved:conserved.map((b:any)=>b.taskId).sort((a:any,b:any)=>a-b),decisionsCausalModified:changedDecisions,decisionsNonCausalModified:nonBlockingChanged,eliminatedAssignmentKeys:removed.map((b:any)=>b.assignmentKey).sort(),modifiedAssignmentKeys:changed.map((b:any)=>b.assignmentKey).sort(),conservedAssignmentKeys:conserved.map((b:any)=>b.assignmentKey).sort(),deepestChangedCausalDepth:deepestChanged||null,backjumpDistance:distance,commonDecisionPathPrefixLength:prefix,reason};
 return deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as any;
}

export function selectConflictDirectedInitialConstructionBackjump(args:{frontier:InitialConstructionSuspendedFrontier; failedPartialPlan:any; conflict:any; nogoodFingerprints?:ReadonlySet<string>}){
 const evaluations=[...args.frontier.entries].map(e=>({entry:e,evaluation:evaluateInitialConstructionCausalAlternative({conflict:args.conflict,failedPartialPlan:args.failedPartialPlan,alternative:e,nogoodFingerprints:args.nogoodFingerprints})}));
 const useful=evaluations.filter(x=>x.evaluation.causallyUseful).sort((a,b)=>Number(b.evaluation.deepestChangedCausalDepth??0)-Number(a.evaluation.deepestChangedCausalDepth??0)||Number(b.evaluation.blockersRemoved?.length??0)-Number(a.evaluation.blockersRemoved?.length??0)||compareInitialConstructionPartialPlanOperationalQuality(a.entry.partialPlan,b.entry.partialPlan)||Number(a.evaluation.backjumpDistance)-Number(b.evaluation.backjumpDistance)||a.entry.assignmentsFingerprint.localeCompare(b.entry.assignmentsFingerprint));
 const legacy=[...evaluations].sort((a,b)=>compareInitialConstructionPartialPlanOperationalQuality(a.entry.partialPlan,b.entry.partialPlan)||a.entry.assignmentsFingerprint.localeCompare(b.entry.assignmentsFingerprint))[0]??null;
 const selected=useful[0]??null; const remaining=selected?evaluations.filter(x=>x.entry.assignmentsFingerprint!==selected.entry.assignmentsFingerprint).map(x=>x.entry):args.frontier.entries;
 const skipped=evaluations.filter(x=>!x.evaluation.causallyUseful); const changed=Boolean(selected&&legacy&&selected.entry.assignmentsFingerprint!==legacy.entry.assignmentsFingerprint); const matched=Boolean(selected&&legacy&&!changed);
 const fallbackReason=selected?null:(args.conflict?.evidenceComplete===false?"INCOMPLETE_CAUSAL_EVIDENCE":((args.conflict?.causalDecisions?.length??0)>0?"NO_CAUSALLY_USEFUL_SUSPENDED_ALTERNATIVE":"NO_REVERSIBLE_CAUSAL_DECISION"));
 return deepFreeze({selectedEntry:selected?.entry??null,frontier:createInitialConstructionSuspendedFrontier(remaining),evaluations:evaluations.map(x=>x.evaluation),evidence:{conflictFingerprint:args.conflict?.fingerprint??null,selectedPartialPlanId:selected?.entry.partialPlanId??null,accepted:Boolean(selected),fallbackReason,legacySelectedPartialPlanId:legacy?.entry.partialPlanId??null,legacySelectionMatched:matched,legacySelectionChanged:changed,legacySelectionFingerprint:legacy?.entry.assignmentsFingerprint??null,conflictDirectedSelectionFingerprint:selected?.entry.assignmentsFingerprint??null,legacyOperationalQualityDelta:selected&&legacy?compareInitialConstructionPartialPlanOperationalQuality(selected.entry.partialPlan,legacy.entry.partialPlan):null,legacyDepthDelta:selected&&legacy?Number(selected.entry.depth??0)-Number(legacy.entry.depth??0):null,backtrackDistance:selected?.evaluation.backjumpDistance??0,commonDecisionPathPrefixLength:selected?.evaluation.commonDecisionPathPrefixLength??0,fromDepth:[...(args.failedPartialPlan?.decisionPath??[])].length,toDepth:selected?.entry.depth??null,changedDecisions:selected?.evaluation.changedDecisions??[],changedCausalBlockerTaskIds:selected?[...(selected.evaluation.blockersRemoved??[]),...(selected.evaluation.blockersModified??[])].sort((a:any,b:any)=>a-b):[],nonCausalAlternativeSkippedCount:skipped.filter(x=>x.evaluation.reason!=="SAME_CAUSAL_CONFLICT"&&x.evaluation.reason!=="NOGOOD_EQUIVALENT_CONFLICT").length,sameConflictAlternativeSkippedCount:skipped.filter(x=>x.evaluation.reason==="SAME_CAUSAL_CONFLICT"||x.evaluation.reason==="NOGOOD_EQUIVALENT_CONFLICT").length,changesOnlyNonBlockingDecisionsSkippedCount:skipped.filter(x=>x.evaluation.reason==="CHANGES_ONLY_NON_BLOCKING_DECISIONS").length,causalBlockerAssignmentChangedCount:selected?.evaluation.blockersModified?.length??0,causalBlockerAssignmentRemovedCount:selected?.evaluation.blockersRemoved?.length??0,readOnly:true},readOnly:true}) as any;
}
