import test from "node:test";
import assert from "node:assert/strict";
import { buildInitialConstructionCausalCheckpointCursor, advanceInitialConstructionCausalCheckpointCursor, cursorHasUninspectedCausalOption, initialConstructionCausalCheckpointCursorKey } from "./initialConstructionCausalCheckpointCursor";

test("ID 321 cursor is built deterministically and advanced immutably",()=>{const key=initialConstructionCausalCheckpointCursorKey({conflictFingerprint:"c",checkpointFingerprint:"p",causalDecisionId:"d"}); const c=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"c",checkpointFingerprint:"p",causalDecisionId:"d",buildOrdinal:1,observedDecisionBranchFingerprints:["b2","b1","b1"],observedChildAssignmentsFingerprints:["a1"]}); assert.equal(c.cursorKey,key); assert.deepEqual(c.observedDecisionBranchFingerprints,["b1","b2"]); const n=advanceInitialConstructionCausalCheckpointCursor(c,{inspectedDecisionBranchFingerprints:["b1"],activatedDecisionBranchFingerprints:["b1"],evaluatedTemporalCandidateFingerprints:["t1"],observedChildAssignmentsFingerprints:["a2"]}); assert.equal(c.advanceOrdinal,0); assert.equal(n.advanceOrdinal,1); assert.deepEqual(n.inspectedDecisionBranchFingerprints,["b1"]); assert.deepEqual(n.evaluatedTemporalCandidateFingerprints,["t1"]); assert.notEqual(n.fingerprint,c.fingerprint);});

test("ID 321 cursor records unrelated checkpoint exclusions without observing their branches",()=>{const c=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"c",checkpointFingerprint:"p",causalDecisionId:"d",buildOrdinal:1,observedDecisionBranchFingerprints:["local"],globalNodeInspectionCount:3,subtreeNodeMatchCount:1,unrelatedNodeExcludedCount:2,unrelatedNodeExcludedSamples:[{partialPlanId:"outside",readOnly:true}]}); assert.deepEqual(c.observedDecisionBranchFingerprints,["local"]); assert.equal(c.globalNodeInspectionCount,3); assert.equal(c.subtreeNodeMatchCount,1); assert.equal(c.unrelatedNodeExcludedCount,2); assert.equal(c.unrelatedNodeExcludedSamples.length,1);});

test("ID 321 cursor reuse advances the same key and can mark exhaustion explicitly",()=>{const c=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"c",checkpointFingerprint:"p",causalDecisionId:"d",buildOrdinal:1,observedDecisionBranchFingerprints:["b"]}); const n=advanceInitialConstructionCausalCheckpointCursor(c,{inspectedDecisionBranchFingerprints:["b"],exhaustedDecisionBranchFingerprints:["b"],exhausted:true,exhaustionReason:"NO_CANDIDATES"}); assert.equal(n.cursorKey,c.cursorKey); assert.equal(n.exhausted,true); assert.equal(n.exhaustionReason,"NO_CANDIDATES"); assert.equal(cursorHasUninspectedCausalOption(n),false);});

test("ID 321 cursor fingerprints ignore input order but change on real causal state",()=>{const a=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"c",checkpointFingerprint:"p",causalDecisionId:"d",buildOrdinal:1,observedDecisionBranchFingerprints:["b2","b1"]}); const b=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"c",checkpointFingerprint:"p",causalDecisionId:"d",buildOrdinal:1,observedDecisionBranchFingerprints:["b1","b2"]}); assert.equal(a.fingerprint,b.fingerprint); const advanced=advanceInitialConstructionCausalCheckpointCursor(a,{activatedDecisionBranchFingerprints:["b1"]}); assert.notEqual(advanced.fingerprint,a.fingerprint);});
