import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import type { InitialConstructionCausalBranchAttempt } from "./initialConstructionCausalBranchOutcomeLedger";

const hash=(x:unknown)=>createHash("sha256").update(stableStringify(x)).digest("hex");

export type InitialConstructionCausalAlternativeActivationSource="SUSPENDED_FRONTIER"|"GENERATED_GRAPH"|"CAUSAL_ARCHIVE"|"CHECKPOINT_REOPEN";
export type InitialConstructionCausalAlternativeActivationStatus="ACTIVATION_PREPARED"|"NO_ELIGIBLE_CANDIDATE";
export type InitialConstructionCausalAlternativeActivationSkipReason="CANDIDATE_ALREADY_ACTIVE"|"CANDIDATE_ALREADY_RESOLVED"|"CANDIDATE_EXHAUSTED_FOR_CONFLICT"|"CANDIDATE_NOT_CAUSALLY_USEFUL"|"CANDIDATE_ALREADY_EXPANDED"|"CANDIDATE_CURSOR_ALREADY_INSPECTED"|"CANDIDATE_NO_GOOD"|"CANDIDATE_HARD_INVALID"|"CANDIDATE_FUTURE_INFEASIBLE"|"CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE"|"LEDGER_CAPACITY_REACHED";

export interface InitialConstructionActivationPartialPlan { readonly partialPlanId:string; readonly assignmentsFingerprint:string; readonly status?:string|null; readonly readOnly?:true }
export interface InitialConstructionCausalBranchOpenInput { readonly conflictFingerprint:string; readonly conflictFamilyFingerprint:string; readonly frontierTaskId:number|null; readonly blockingTaskIds:readonly number[]; readonly checkpointFingerprint:string; readonly checkpointParentPartialPlanId:string; readonly checkpointParentAssignmentsFingerprint:string; readonly causalDecisionId:string; readonly causalDecisionDepth:number; readonly selectedPartialPlanId:string; readonly selectedAssignmentsFingerprint:string; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly activationOrdinal:number; readonly baselineProductiveAssignmentCount:number; readonly baselineResidualProductiveTaskCount:number; readonly baselineMaximumProductiveAssignmentCountObserved:number; readonly activatedAtExpansionWorkUnit:number }
export interface InitialConstructionCausalBranchOpenResult { readonly opened:boolean; readonly attempt:InitialConstructionCausalBranchAttempt|null; readonly reason?:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"|"LEDGER_CAPACITY_REACHED"|string }
export interface InitialConstructionCausalBranchActivationLedger { open(input:InitialConstructionCausalBranchOpenInput):InitialConstructionCausalBranchOpenResult; isBranchExhausted?(input:{conflictFingerprint:string;checkpointFingerprint:string;causalDecisionId:string;checkpointBranchFingerprint:string;checkpointBranchAssignmentsFingerprint:string}):boolean }
export interface InitialConstructionCausalAlternativeActivationCandidate { readonly source:InitialConstructionCausalAlternativeActivationSource; readonly partialPlan:InitialConstructionActivationPartialPlan; readonly sourceEntryFingerprint:string; readonly sourceOrdinal:number; readonly sourceRank:number; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly causalEvaluationFingerprint:string; readonly operationalComparatorFingerprint:string; readonly causallyUseful:boolean; readonly hardInvalid?:boolean; readonly futureInfeasible?:boolean; readonly inCheckpointSubtree:boolean; readonly readOnly:true }
export interface InitialConstructionCausalAlternativeActivationResult { readonly status:InitialConstructionCausalAlternativeActivationStatus; readonly selectedCandidate:InitialConstructionCausalAlternativeActivationCandidate|null; readonly openedAttempt:InitialConstructionCausalBranchAttempt|null; readonly openedAttemptId:string|null; readonly sourceMutation:{readonly source:InitialConstructionCausalAlternativeActivationSource;readonly selectedEntryFingerprint:string;readonly commitRequired:true}|null; readonly backtrackConsumed:false; readonly transitionConsumed:false; readonly inspectedCandidateCount:number; readonly eligibleCandidateCount:number; readonly skippedCandidateCount:number; readonly skipReasonCounts:Readonly<Record<InitialConstructionCausalAlternativeActivationSkipReason,number>>; readonly skippedCandidateSamples:readonly unknown[]; readonly fingerprint:string; readonly readOnly:true }

const inc=(m:Record<InitialConstructionCausalAlternativeActivationSkipReason,number>,k:InitialConstructionCausalAlternativeActivationSkipReason)=>{m[k]=(m[k]??0)+1;};
const freezeResult=(payload:Omit<InitialConstructionCausalAlternativeActivationResult,"fingerprint"|"readOnly">):InitialConstructionCausalAlternativeActivationResult=>deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as InitialConstructionCausalAlternativeActivationResult;

export function prepareInitialConstructionCausalAlternativeActivation(args:{readonly candidates:readonly InitialConstructionCausalAlternativeActivationCandidate[]; readonly ledger:InitialConstructionCausalBranchActivationLedger; readonly openInputForCandidate:(candidate:InitialConstructionCausalAlternativeActivationCandidate)=>InitialConstructionCausalBranchOpenInput; readonly expandedAssignmentsFingerprints?:ReadonlySet<string>; readonly cursorInspectedBranchFingerprints?:ReadonlySet<string>; readonly noGoodBranchFingerprints?:ReadonlySet<string>; readonly maxSamples?:number}):InitialConstructionCausalAlternativeActivationResult{
 const skipReasonCounts={} as Record<InitialConstructionCausalAlternativeActivationSkipReason,number>; const samples:unknown[]=[]; const maxSamples=Math.max(0,args.maxSamples??10); let inspected=0, skipped=0, eligible=0;
 const addSkip=(candidate:InitialConstructionCausalAlternativeActivationCandidate,reason:InitialConstructionCausalAlternativeActivationSkipReason)=>{skipped++; inc(skipReasonCounts,reason); if(samples.length<maxSamples)samples.push(deepFreeze({source:candidate.source,partialPlanId:candidate.partialPlan.partialPlanId,assignmentsFingerprint:candidate.partialPlan.assignmentsFingerprint,branchFingerprint:candidate.checkpointBranchFingerprint,reason,readOnly:true}));};
 const ordered=[...args.candidates].sort((a,b)=>a.sourceRank-b.sourceRank||a.sourceOrdinal-b.sourceOrdinal||a.operationalComparatorFingerprint.localeCompare(b.operationalComparatorFingerprint)||a.sourceEntryFingerprint.localeCompare(b.sourceEntryFingerprint));
 for(const candidate of ordered){inspected++;
  if(!candidate.inCheckpointSubtree){addSkip(candidate,"CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE"); continue;}
  if(candidate.hardInvalid){addSkip(candidate,"CANDIDATE_HARD_INVALID"); continue;}
  if(candidate.futureInfeasible){addSkip(candidate,"CANDIDATE_FUTURE_INFEASIBLE"); continue;}
  if(args.expandedAssignmentsFingerprints?.has(candidate.partialPlan.assignmentsFingerprint)){addSkip(candidate,"CANDIDATE_ALREADY_EXPANDED"); continue;}
  if(args.cursorInspectedBranchFingerprints?.has(candidate.checkpointBranchFingerprint)){addSkip(candidate,"CANDIDATE_CURSOR_ALREADY_INSPECTED"); continue;}
  if(args.noGoodBranchFingerprints?.has(candidate.checkpointBranchFingerprint)||args.noGoodBranchFingerprints?.has(candidate.checkpointBranchAssignmentsFingerprint)){addSkip(candidate,"CANDIDATE_NO_GOOD"); continue;}
  if(!candidate.causallyUseful){addSkip(candidate,"CANDIDATE_NOT_CAUSALLY_USEFUL"); continue;}
  if(args.ledger.isBranchExhausted?.({conflictFingerprint:args.openInputForCandidate(candidate).conflictFingerprint,checkpointFingerprint:args.openInputForCandidate(candidate).checkpointFingerprint,causalDecisionId:args.openInputForCandidate(candidate).causalDecisionId,checkpointBranchFingerprint:candidate.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:candidate.checkpointBranchAssignmentsFingerprint})){addSkip(candidate,"CANDIDATE_EXHAUSTED_FOR_CONFLICT"); continue;}
  eligible++; const opened=args.ledger.open(args.openInputForCandidate(candidate));
  if(opened.opened&&opened.attempt){return freezeResult({status:"ACTIVATION_PREPARED",selectedCandidate:candidate,openedAttempt:opened.attempt,openedAttemptId:opened.attempt.attemptId,sourceMutation:{source:candidate.source,selectedEntryFingerprint:candidate.sourceEntryFingerprint,commitRequired:true},backtrackConsumed:false,transitionConsumed:false,inspectedCandidateCount:inspected,eligibleCandidateCount:eligible,skippedCandidateCount:skipped,skipReasonCounts,skippedCandidateSamples:samples});}
  addSkip(candidate,opened.reason==="LEDGER_CAPACITY_REACHED"?"LEDGER_CAPACITY_REACHED":opened.attempt?.status&&opened.attempt.status!=="ACTIVE"?"CANDIDATE_ALREADY_RESOLVED":"CANDIDATE_ALREADY_ACTIVE");
 }
 return freezeResult({status:"NO_ELIGIBLE_CANDIDATE",selectedCandidate:null,openedAttempt:null,openedAttemptId:null,sourceMutation:null,backtrackConsumed:false,transitionConsumed:false,inspectedCandidateCount:inspected,eligibleCandidateCount:eligible,skippedCandidateCount:skipped,skipReasonCounts,skippedCandidateSamples:samples});
}

export interface InitialConstructionCausalAlternativeCandidateEnvelopeInput { readonly source:InitialConstructionCausalAlternativeActivationSource; readonly partialPlan:InitialConstructionActivationPartialPlan; readonly sourceEntryFingerprint:string; readonly sourceEntryId:string|null; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly causalEvaluationFingerprint:string; readonly causallyUseful:boolean; readonly blockersRemovedCount:number; readonly blockersModifiedCount:number; readonly backjumpDistance:number; readonly operationalRank:number; readonly deterministicSourceOrdinal:number; readonly inCheckpointSubtree:boolean; readonly alreadyExpanded:boolean; readonly hardInvalid:boolean; readonly futureInfeasible:boolean; readonly readOnly:true }
export interface InitialConstructionCausalAlternativeCandidateCollection { readonly candidates:readonly InitialConstructionCausalAlternativeActivationCandidate[]; readonly collectedBySource:Readonly<Record<InitialConstructionCausalAlternativeActivationSource,number>>; readonly deduplicationCount:number; readonly crossSourceDuplicateCount:number; readonly sourceClassificationMismatchCount:number; readonly samples:readonly unknown[]; readonly deduplicationSamples:readonly unknown[]; readonly fingerprint:string; readonly readOnly:true }
const sourcePrecedence:Record<InitialConstructionCausalAlternativeActivationSource,number>={SUSPENDED_FRONTIER:0,GENERATED_GRAPH:1,CAUSAL_ARCHIVE:2,CHECKPOINT_REOPEN:3};
export function collectInitialConstructionCausalAlternativeActivationCandidates(inputs:readonly InitialConstructionCausalAlternativeCandidateEnvelopeInput[], maxSamples=10):InitialConstructionCausalAlternativeCandidateCollection{
 const collectedBySource:Record<InitialConstructionCausalAlternativeActivationSource,number>={SUSPENDED_FRONTIER:0,GENERATED_GRAPH:0,CAUSAL_ARCHIVE:0,CHECKPOINT_REOPEN:0}; const byKey=new Map<string,InitialConstructionCausalAlternativeCandidateEnvelopeInput>(); const deduplicationSamples:unknown[]=[]; const samples:unknown[]=[]; let deduplicationCount=0,crossSourceDuplicateCount=0;
 for(const input of [...inputs].sort((a,b)=>a.source.localeCompare(b.source)||a.partialPlan.partialPlanId.localeCompare(b.partialPlan.partialPlanId)||a.partialPlan.assignmentsFingerprint.localeCompare(b.partialPlan.assignmentsFingerprint)||a.checkpointBranchFingerprint.localeCompare(b.checkpointBranchFingerprint)||a.sourceEntryFingerprint.localeCompare(b.sourceEntryFingerprint))){collectedBySource[input.source]++; const key=hash({partialPlanId:input.partialPlan.partialPlanId,assignmentsFingerprint:input.partialPlan.assignmentsFingerprint,checkpointBranchFingerprint:input.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:input.checkpointBranchAssignmentsFingerprint}); const prev=byKey.get(key); if(prev){deduplicationCount++; if(prev.source!==input.source)crossSourceDuplicateCount++; const keep=sourcePrecedence[input.source]<sourcePrecedence[prev.source]?input:prev; byKey.set(key,keep); if(deduplicationSamples.length<maxSamples)deduplicationSamples.push(deepFreeze({key,keptSource:keep.source,droppedSource:keep===input?prev.source:input.source,partialPlanId:input.partialPlan.partialPlanId,readOnly:true})); continue;} byKey.set(key,input); if(samples.length<maxSamples)samples.push(deepFreeze({source:input.source,partialPlanId:input.partialPlan.partialPlanId,assignmentsFingerprint:input.partialPlan.assignmentsFingerprint,branchFingerprint:input.checkpointBranchFingerprint,readOnly:true})); }
 const candidates=[...byKey.values()].sort((a,b)=>Number(b.causallyUseful)-Number(a.causallyUseful)||b.blockersRemovedCount-a.blockersRemovedCount||b.blockersModifiedCount-a.blockersModifiedCount||a.operationalRank-b.operationalRank||a.backjumpDistance-b.backjumpDistance||sourcePrecedence[a.source]-sourcePrecedence[b.source]||a.deterministicSourceOrdinal-b.deterministicSourceOrdinal||a.partialPlan.assignmentsFingerprint.localeCompare(b.partialPlan.assignmentsFingerprint)).map((input,idx)=>deepFreeze({source:input.source,partialPlan:input.partialPlan,sourceEntryFingerprint:input.sourceEntryFingerprint,sourceOrdinal:input.deterministicSourceOrdinal,sourceRank:idx,checkpointBranchPartialPlanId:input.checkpointBranchPartialPlanId,checkpointBranchFingerprint:input.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:input.checkpointBranchAssignmentsFingerprint,causalEvaluationFingerprint:input.causalEvaluationFingerprint,operationalComparatorFingerprint:String(input.operationalRank).padStart(8,"0")+":"+input.partialPlan.assignmentsFingerprint,causallyUseful:input.causallyUseful,hardInvalid:input.hardInvalid,futureInfeasible:input.futureInfeasible,inCheckpointSubtree:input.inCheckpointSubtree&&!input.alreadyExpanded,readOnly:true})) as InitialConstructionCausalAlternativeActivationCandidate[];
 const payload={candidates,collectedBySource,deduplicationCount,crossSourceDuplicateCount,sourceClassificationMismatchCount:0,samples,deduplicationSamples}; return deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as InitialConstructionCausalAlternativeCandidateCollection;
}
