import assert from "node:assert/strict";
import test from "node:test";
import { buildInitialConstructionPartialPlanGraphIndex, resolveInitialConstructionCheckpointBranch } from "./initialConstructionCausalDecisionCheckpoint";
import { createInitialConstructionCausalBranchOutcomeLedger, causalBranchAttemptKey } from "./initialConstructionCausalBranchOutcomeLedger";

const node=(id:string,parent:string|null,depth:number,branch:string)=>({partialPlanId:id,parentPartialPlanId:parent,depth,assignmentsFingerprint:`afp:${id}`,decisionBranchFingerprint:branch,decisionLineage:[{decisionId:`d${depth}`,decisionDepth:depth,branchFingerprint:branch}],assignments:[],readOnly:true});
const checkpoint={resolved:true,fingerprint:"chk",parentPartialPlanId:"root",parentAssignmentsFingerprint:"afp:root",causalDecisionId:"d1",causalDecisionDepth:1,readOnly:true};
function input(branch:any, conflictFingerprint="c1"){return {conflictFingerprint,conflictFamilyFingerprint:"fam",frontierTaskId:1,blockingTaskIds:[2],checkpointFingerprint:"chk",checkpointParentPartialPlanId:"root",checkpointParentAssignmentsFingerprint:"afp:root",causalDecisionId:"d1",causalDecisionDepth:1,selectedPartialPlanId:branch.partialPlanId,selectedAssignmentsFingerprint:branch.assignmentsFingerprint,checkpointBranchPartialPlanId:branch.checkpointBranchPartialPlanId??branch.partialPlanId,checkpointBranchFingerprint:branch.decisionBranchFingerprint??branch.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:branch.checkpointBranchAssignmentsFingerprint??branch.assignmentsFingerprint,activationOrdinal:1,baselineProductiveAssignmentCount:10,baselineResidualProductiveTaskCount:5,baselineMaximumProductiveAssignmentCountObserved:10,activatedAtExpansionWorkUnit:1};}

test("resolves direct checkpoint branch from deep descendant and separates siblings",()=>{const nodes=[node("root",null,0,"root"),node("a","root",1,"ba"),node("b","root",1,"bb"),node("a1","a",2,"a1"),node("a2","a1",3,"a2"),node("a3","a2",4,"a3"),node("b1","b",2,"b1")]; const index=buildInitialConstructionPartialPlanGraphIndex(nodes); const deep=resolveInitialConstructionCheckpointBranch({checkpoint,partialPlan:nodes[5],partialPlanGraphIndex:index}); const other=resolveInitialConstructionCheckpointBranch({checkpoint,partialPlan:nodes[6],partialPlanGraphIndex:index}); assert.equal(deep.checkpointBranchPartialPlanId,"a"); assert.equal(deep.relativeDepth,4); assert.notEqual(deep.fingerprint,other.fingerprint);});

test("ledger opens once, resolves repeated conflicts, and exhausts only exact conflict branch",()=>{const ledger=createInitialConstructionCausalBranchOutcomeLedger(10); const branch={partialPlanId:"a",assignmentsFingerprint:"afp:a",decisionBranchFingerprint:"ba"}; const opened=ledger.open(input(branch)); assert.equal(opened.opened,true); assert.equal(ledger.open(input(branch)).opened,false); const r=ledger.resolve(opened.attempt.attemptId,{status:"REPEATED_SAME_CONFLICT",resultingConflictFingerprint:"c1",resultingFrontierTaskId:1,maximumProductiveAssignmentCountObserved:10,minimumResidualProductiveTaskCountObserved:5,resolvedAtExpansionWorkUnit:2}); assert.equal(r.attempt.status,"REPEATED_SAME_CONFLICT"); assert.equal(ledger.isBranchExhausted(input(branch)),true); assert.equal(ledger.isBranchExhausted(input(branch,"c2")),false); const s=ledger.summary(); assert.equal(s.causalBranchAttemptOpenedCount,1); assert.equal(s.causalBranchAttemptDuplicateOpenPreventedCount,1); assert.equal(s.causalBranchNoGoodRegisteredCount,1);});

test("progress followed by same conflict is represented as progressed repeated same conflict",()=>{const ledger=createInitialConstructionCausalBranchOutcomeLedger(10); const branch={partialPlanId:"a",assignmentsFingerprint:"afp:a",decisionBranchFingerprint:"ba"}; const opened=ledger.open(input(branch)); const r=ledger.resolve(opened.attempt.attemptId,{status:"REPEATED_SAME_CONFLICT",resultingConflictFingerprint:"c1",maximumProductiveAssignmentCountObserved:12,minimumResidualProductiveTaskCountObserved:3,resolvedAtExpansionWorkUnit:2}); assert.equal(r.attempt.status,"PROGRESSED_BUT_REPEATED_SAME_CONFLICT"); assert.equal(ledger.summary().causalAttemptMaximumProductiveProgress,2);});

test("different conflict does not register branch no-good",()=>{const ledger=createInitialConstructionCausalBranchOutcomeLedger(10); const branch={partialPlanId:"a",assignmentsFingerprint:"afp:a",decisionBranchFingerprint:"ba"}; const opened=ledger.open(input(branch)); ledger.resolve(opened.attempt.attemptId,{status:"ADVANCED_TO_DIFFERENT_CONFLICT",resultingConflictFingerprint:"c2",maximumProductiveAssignmentCountObserved:10,minimumResidualProductiveTaskCountObserved:5,resolvedAtExpansionWorkUnit:2}); assert.equal(ledger.isBranchExhausted(input(branch)),false); assert.equal(ledger.summary().causalBranchAdvancedToDifferentConflictCount,1);});
