import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { compareInitialConstructionPartialPlanOperationalQuality } from "./initialConstructionSuspendedFrontier";
import { evaluateInitialConstructionCausalAlternative } from "./conflictDirectedInitialConstructionBackjump";

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
const arr=(x:any)=>[...(x??[])];
const aid=(a:any)=>hash({taskId:Number(a.taskId),startPlanned:a.startPlanned??null,endPlanned:a.endPlanned??null,spaceId:a.spaceId??null,resourceIds:[...(a.resourceIds??a.assignedResourceIds??[])].map(Number).sort((x,y)=>x-y)});
export interface InitialConstructionPartialPlanGraphIndex { readonly byId:ReadonlyMap<string,any>; readonly byAssignmentsFingerprint:ReadonlyMap<string,any>; readonly childrenByParentId:ReadonlyMap<string,readonly any[]>; readonly nodesByDepth:ReadonlyMap<number,readonly any[]>; readonly nodesByDecisionId:ReadonlyMap<string,readonly any[]>; readonly nodesByDecisionBranchFingerprint:ReadonlyMap<string,readonly any[]>; readonly nodes:readonly any[]; readonly fingerprint:string; readonly readOnly:true }
export function buildInitialConstructionPartialPlanGraphIndex(nodes:readonly any[]):InitialConstructionPartialPlanGraphIndex{
 const sorted=arr(nodes).filter(Boolean).sort((a,b)=>String(a.partialPlanId).localeCompare(String(b.partialPlanId))); const byId=new Map<string,any>(), byFp=new Map<string,any>(), byParent=new Map<string,any[]>(), byDepth=new Map<number,any[]>(), byDecision=new Map<string,any[]>(), byBranch=new Map<string,any[]>();
 for(const n of sorted){byId.set(String(n.partialPlanId),n); if(n.assignmentsFingerprint)byFp.set(String(n.assignmentsFingerprint),n); const p=n.parentPartialPlanId==null?"__root__":String(n.parentPartialPlanId); (byParent.get(p)??byParent.set(p,[]).get(p)!).push(n); const d=Number(n.depth??arr(n.decisionLineage).length); (byDepth.get(d)??byDepth.set(d,[]).get(d)!).push(n); for(const le of arr(n.decisionLineage)){ if(le?.decisionId)(byDecision.get(String(le.decisionId))??byDecision.set(String(le.decisionId),[]).get(String(le.decisionId))!).push(n); if(le?.branchFingerprint)(byBranch.get(String(le.branchFingerprint))??byBranch.set(String(le.branchFingerprint),[]).get(String(le.branchFingerprint))!).push(n); } if(n.decisionBranchFingerprint)(byBranch.get(String(n.decisionBranchFingerprint))??byBranch.set(String(n.decisionBranchFingerprint),[]).get(String(n.decisionBranchFingerprint))!).push(n); }
 for(const m of [byParent,byDepth,byDecision,byBranch] as any[]) for(const [k,v] of m) m.set(k,v.sort((a:any,b:any)=>Number(a.depth??0)-Number(b.depth??0)||String(a.assignmentsFingerprint).localeCompare(String(b.assignmentsFingerprint))));
 return deepFreeze({byId,byAssignmentsFingerprint:byFp,childrenByParentId:byParent,nodesByDepth:byDepth,nodesByDecisionId:byDecision,nodesByDecisionBranchFingerprint:byBranch,nodes:sorted,fingerprint:hash(sorted.map(n=>({id:n.partialPlanId,p:n.parentPartialPlanId,fp:n.assignmentsFingerprint,d:n.depth,b:n.decisionBranchFingerprint}))),readOnly:true}) as any;
}
function ancestors(node:any,index:InitialConstructionPartialPlanGraphIndex){const out:any[]=[]; let n=node; const seen=new Set<string>(); while(n&&!seen.has(String(n.partialPlanId))){out.push(n); seen.add(String(n.partialPlanId)); n=n.parentPartialPlanId?index.byId.get(String(n.parentPartialPlanId)):null;} return out;}
function descendants(node:any,index:InitialConstructionPartialPlanGraphIndex){const out:any[]=[]; const stack=[...arr(index.childrenByParentId.get(String(node.partialPlanId)))].sort((a,b)=>String(a.partialPlanId).localeCompare(String(b.partialPlanId))); while(stack.length){const n=stack.shift(); if(!n)continue; out.push(n); stack.push(...arr(index.childrenByParentId.get(String(n.partialPlanId))).sort((a,b)=>String(a.partialPlanId).localeCompare(String(b.partialPlanId))));} return out;}
export function resolveInitialConstructionCausalDecisionCheckpoint(args:{failedPartialPlan:any; conflict:any; partialPlanGraphIndex:InitialConstructionPartialPlanGraphIndex}){
 const conflict=args.conflict; const decision=arr(conflict?.causalDecisions).sort((a,b)=>Number(b.decisionDepth)-Number(a.decisionDepth)||String(a.decisionId).localeCompare(String(b.decisionId)))[0];
 if(!conflict?.evidenceComplete||!decision) return deepFreeze({resolved:false,reason:"INCOMPLETE_CAUSAL_EVIDENCE",readOnly:true}) as any;
 const chain=ancestors(args.failedPartialPlan,args.partialPlanGraphIndex); const child=chain.find(n=>arr(n.decisionLineage).some((le:any)=>String(le.decisionId)===String(decision.decisionId)&&Number(le.decisionDepth)===Number(decision.decisionDepth))&&Number(n.depth)===Number(decision.decisionDepth));
 const parent=child?.parentPartialPlanId?args.partialPlanGraphIndex.byId.get(String(child.parentPartialPlanId)):null; if(!child||!parent) return deepFreeze({resolved:false,reason:"CHECKPOINT_MISSING",causalDecisionId:decision.decisionId,causalDecisionDepth:decision.decisionDepth,readOnly:true}) as any;
 const siblings=arr(args.partialPlanGraphIndex.childrenByParentId.get(String(parent.partialPlanId))).filter(n=>String(n.partialPlanId)!==String(child.partialPlanId)); const descBySibling=siblings.map(s=>({siblingPartialPlanId:s.partialPlanId,descendantPartialPlanIds:descendants(s,args.partialPlanGraphIndex).map(d=>d.partialPlanId).sort(),readOnly:true}));
 const le=arr(child.decisionLineage).find((x:any)=>String(x.decisionId)===String(decision.decisionId)); const blocking=arr(conflict.blockingAssignments);
 const payload={resolved:true,causalDecisionId:String(decision.decisionId),causalDecisionDepth:Number(decision.decisionDepth),blockingTaskIds:blocking.map((b:any)=>Number(b.taskId)).sort((a,b)=>a-b),blockingAssignmentFingerprints:blocking.map((b:any)=>String(b.assignmentKey)).sort(),introducedChildPartialPlanId:child.partialPlanId,parentPartialPlanId:parent.partialPlanId,parentAssignmentsFingerprint:parent.assignmentsFingerprint,checkpointParentDepth:Number(parent.depth),decisionBranchFingerprint:String(le?.branchFingerprint??child.decisionBranchFingerprint??""),targetPrimaryGoalTaskId:Number.isFinite(Number(le?.primaryGoalTaskId))?Number(le.primaryGoalTaskId):null,targetExecutionTaskId:Number.isFinite(Number(le?.executionTaskId))?Number(le.executionTaskId):null,checkpointStatus:parent.status??null,siblingPartialPlanIds:siblings.map(s=>s.partialPlanId).sort(),descendantsBySibling:descBySibling,reopenable:true};
 return deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as any;
}
export function selectGeneratedCausalSibling(args:{checkpoint:any; conflict:any; failedPartialPlan:any; candidates:readonly any[]; expandedFingerprints?:ReadonlySet<string>; nogoodFingerprints?:ReadonlySet<string>}){
 if(!args.checkpoint?.resolved) return deepFreeze({selected:null,inspectedCount:0,rejectedCount:0,rejections:[],readOnly:true}) as any;
 const parent=String(args.checkpoint.parentPartialPlanId); const badBranch=String(args.checkpoint.decisionBranchFingerprint); const expanded=args.expandedFingerprints??new Set<string>();
 const evaluated=arr(args.candidates).filter(n=>n&&String(n.parentPartialPlanId)===parent&&String(n.decisionBranchFingerprint)!==badBranch).map(n=>({node:n,evaluation:evaluateInitialConstructionCausalAlternative({conflict:args.conflict,failedPartialPlan:args.failedPartialPlan,alternative:n,nogoodFingerprints:args.nogoodFingerprints})}));
 const valid=evaluated.filter(x=>x.evaluation.causallyUseful&&x.node.status!=="PRUNED"&&!expanded.has(String(x.node.assignmentsFingerprint))).sort((a,b)=>Number(b.evaluation.blockersRemoved.length)-Number(a.evaluation.blockersRemoved.length)||Number(b.evaluation.blockersModified.length)-Number(a.evaluation.blockersModified.length)||compareInitialConstructionPartialPlanOperationalQuality(a.node,b.node)||String(a.node.assignmentsFingerprint).localeCompare(String(b.node.assignmentsFingerprint)));
 return deepFreeze({selected:valid[0]?.node??null,inspectedCount:evaluated.length,rejectedCount:evaluated.length-valid.length,rejections:evaluated.filter(x=>!valid.includes(x)).map(x=>({partialPlanId:x.node.partialPlanId,reason:x.evaluation.reason,readOnly:true})),fingerprint:hash(evaluated.map(x=>({p:x.node.partialPlanId,e:x.evaluation.fingerprint}))),readOnly:true}) as any;
}
export function assignmentFingerprintForTask(plan:any,taskId:number){const a=arr(plan?.assignments).find((x:any)=>Number(x.taskId)===Number(taskId)); return a?aid(a):null;}
