import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { resolveInitialConstructionCheckpointBranch, type InitialConstructionPartialPlanGraphIndex } from "./initialConstructionCausalDecisionCheckpoint";
import type { InitialConstructionCausalAlternativeActivationSource } from "./initialConstructionCausalAlternativeActivation";

const hash=(x:unknown)=>createHash("sha256").update(stableStringify(x)).digest("hex");
const arr=(x:any)=>[...(x??[])];
const pp=(entry:any)=>(entry?.partialPlan&&typeof entry.partialPlan==="object"?entry.partialPlan:entry);
const sourcePrecedence:Record<InitialConstructionCausalAlternativeActivationSource,number>={CHECKPOINT_REOPEN:-1,SUSPENDED_FRONTIER:0,GENERATED_GRAPH:1,CAUSAL_ARCHIVE:2};
export interface InitialConstructionCheckpointLocalProjectedCandidate { readonly source:InitialConstructionCausalAlternativeActivationSource; readonly partialPlan:Record<string,unknown>; readonly sourceEntry:Record<string,unknown>|null; readonly sourceEntryFingerprint:string; readonly sourceEntryId:string|null; readonly viaFallback:boolean; readonly readOnly:true }
export interface InitialConstructionCheckpointLocalCandidateProjection { readonly candidates:readonly InitialConstructionCheckpointLocalProjectedCandidate[]; readonly graphCandidates:readonly Record<string,unknown>[]; readonly suspendedCandidates:readonly Record<string,unknown>[]; readonly archiveCandidates:readonly Record<string,unknown>[]; readonly reopenCandidates:readonly Record<string,unknown>[]; readonly checkpointSubtreePartialPlanIds:readonly string[]; readonly observedDecisionBranchFingerprints:readonly string[]; readonly observedChildAssignmentsFingerprints:readonly string[]; readonly globalSourceCandidateCount:number; readonly checkpointLocalCandidateCount:number; readonly unrelatedCandidateExcludedCount:number; readonly unresolvedCandidateFallbackCount:number; readonly duplicateCandidateCount:number; readonly failedPartialPlanExcludedCount:number; readonly invalidSourceCandidateExcludedCount:number; readonly accountedSourceCandidateCount:number; readonly sourceCandidateConservationResidual:number; readonly unrelatedCandidateExcludedSamples:readonly unknown[]; readonly structuralCandidateExcludedSamples:readonly unknown[]; readonly fingerprint:string; readonly readOnly:true }
function depth(n:any){return Number(n?.depth??arr(n?.decisionLineage).length??0)}
function stableCandidateSort(a:InitialConstructionCheckpointLocalProjectedCandidate,b:InitialConstructionCheckpointLocalProjectedCandidate){return depth(a.partialPlan)-depth(b.partialPlan)||String(a.partialPlan.partialPlanId).localeCompare(String(b.partialPlan.partialPlanId))||String(a.partialPlan.assignmentsFingerprint).localeCompare(String(b.partialPlan.assignmentsFingerprint))||String(a.partialPlan.decisionBranchFingerprint).localeCompare(String(b.partialPlan.decisionBranchFingerprint))||sourcePrecedence[a.source]-sourcePrecedence[b.source];}
function descendantsFrom(parentId:string,index:InitialConstructionPartialPlanGraphIndex){const out:any[]=[]; const stack=arr(index.childrenByParentId.get(parentId)).sort((a,b)=>String(a.partialPlanId).localeCompare(String(b.partialPlanId))); while(stack.length){const n=stack.shift(); if(!n)continue; out.push(n); stack.push(...arr(index.childrenByParentId.get(String(n.partialPlanId))).sort((a,b)=>String(a.partialPlanId).localeCompare(String(b.partialPlanId))));} return out.sort((a,b)=>depth(a)-depth(b)||String(a.partialPlanId).localeCompare(String(b.partialPlanId))||String(a.assignmentsFingerprint).localeCompare(String(b.assignmentsFingerprint)));}
export function buildInitialConstructionCheckpointLocalCandidateProjection(args:{checkpoint:any; partialPlanGraphIndex:InitialConstructionPartialPlanGraphIndex; suspendedFrontier:{readonly entries:readonly Record<string,unknown>[]}; causalArchive:readonly Record<string,unknown>[]; graphNodes?:readonly Record<string,unknown>[]; reopenCandidates?:readonly Record<string,unknown>[]; failedPartialPlan:Record<string,unknown>; readOnly:true}):InitialConstructionCheckpointLocalCandidateProjection{
 const subtree=descendantsFrom(String(args.checkpoint.parentPartialPlanId),args.partialPlanGraphIndex); const subtreeIds=new Set(subtree.map(n=>String(n.partialPlanId))); const subtreeFps=new Set(subtree.map(n=>String(n.assignmentsFingerprint)).filter(Boolean));
 const graphSourceNodes=args.graphNodes?arr(args.graphNodes):subtree;
 const sources:{source:InitialConstructionCausalAlternativeActivationSource;entry:any;plan:any;direct:boolean}[]=[...graphSourceNodes.map(n=>({source:"GENERATED_GRAPH" as const,entry:n,plan:n,direct:true})),...arr(args.suspendedFrontier.entries).map((e:any)=>({source:"SUSPENDED_FRONTIER" as const,entry:e,plan:pp(e),direct:false})),...arr(args.causalArchive).map((e:any)=>({source:"CAUSAL_ARCHIVE" as const,entry:e,plan:pp(e),direct:false})),...arr(args.reopenCandidates).map((e:any)=>({source:"CHECKPOINT_REOPEN" as const,entry:e,plan:pp(e),direct:true}))];
 let unrelated=0,fallback=0,dups=0,failedExcluded=0,invalidExcluded=0; const unrelatedSamples:any[]=[], structuralExcludedSamples:any[]=[]; const byKey=new Map<string,InitialConstructionCheckpointLocalProjectedCandidate>();
 for(const s of sources.sort((a,b)=>sourcePrecedence[a.source]-sourcePrecedence[b.source]||String(a.plan?.partialPlanId).localeCompare(String(b.plan?.partialPlanId))||String(a.plan?.assignmentsFingerprint).localeCompare(String(b.plan?.assignmentsFingerprint)))){const plan=s.plan; if(!plan){invalidExcluded++; if(structuralExcludedSamples.length<10)structuralExcludedSamples.push({source:s.source,partialPlanId:null,assignmentsFingerprint:null,reason:"INVALID_SOURCE_CANDIDATE",readOnly:true}); continue;} const id=String(plan.partialPlanId??""), fp=String(plan.assignmentsFingerprint??""); if(id===String(args.failedPartialPlan.partialPlanId)){failedExcluded++; if(structuralExcludedSamples.length<10)structuralExcludedSamples.push({source:s.source,partialPlanId:id||null,assignmentsFingerprint:fp||null,reason:"FAILED_PARTIAL_PLAN_EXCLUDED",readOnly:true}); continue;}
  let local=s.source==="CHECKPOINT_REOPEN"||subtreeIds.has(id)||subtreeFps.has(fp); let viaFallback=false;
  if(!local&&!s.direct&&id&&!args.partialPlanGraphIndex.byId.has(id)&&!args.partialPlanGraphIndex.byAssignmentsFingerprint.has(fp)){const branch=resolveInitialConstructionCheckpointBranch({checkpoint:args.checkpoint,partialPlan:plan,partialPlanGraphIndex:args.partialPlanGraphIndex}); fallback++; viaFallback=true; local=Boolean(branch?.resolved);} 
  if(!local){unrelated++; if(unrelatedSamples.length<10)unrelatedSamples.push({source:s.source,partialPlanId:id||null,assignmentsFingerprint:fp||null,reason:"CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE",readOnly:true}); continue;}
  const key=hash({partialPlanId:id,assignmentsFingerprint:fp}); const projected=deepFreeze({source:s.source,partialPlan:plan,sourceEntry:s.entry??null,sourceEntryFingerprint:String(s.entry?.assignmentsFingerprint??plan.assignmentsFingerprint??""),sourceEntryId:String(s.entry?.partialPlanId??plan.partialPlanId??s.entry?.assignmentsFingerprint??""),viaFallback,readOnly:true}) as InitialConstructionCheckpointLocalProjectedCandidate; const prev=byKey.get(key); if(prev){dups++; if(sourcePrecedence[projected.source]<sourcePrecedence[prev.source])byKey.set(key,projected);} else byKey.set(key,projected); }
 const candidates=[...byKey.values()].sort(stableCandidateSort); const graphCandidates=candidates.filter(c=>c.source==="GENERATED_GRAPH").map(c=>c.partialPlan); const suspendedCandidates=candidates.filter(c=>c.source==="SUSPENDED_FRONTIER").map(c=>c.sourceEntry!); const archiveCandidates=candidates.filter(c=>c.source==="CAUSAL_ARCHIVE").map(c=>c.sourceEntry??c.partialPlan); const reopenCandidates=candidates.filter(c=>c.source==="CHECKPOINT_REOPEN").map(c=>c.partialPlan);
 const observedDecisionBranchFingerprints=[...new Set([String(args.checkpoint.decisionBranchFingerprint),...candidates.map(c=>String(c.partialPlan.decisionBranchFingerprint??"")).filter(Boolean)])].sort(); const observedChildAssignmentsFingerprints=[...new Set(candidates.map(c=>String(c.partialPlan.assignmentsFingerprint??"")).filter(Boolean))].sort();
 const accountedSourceCandidateCount=candidates.length+unrelated+dups+failedExcluded+invalidExcluded; const sourceCandidateConservationResidual=sources.length-accountedSourceCandidateCount; const payload={candidates,graphCandidates,suspendedCandidates,archiveCandidates,reopenCandidates,checkpointSubtreePartialPlanIds:[...subtreeIds].sort(),observedDecisionBranchFingerprints,observedChildAssignmentsFingerprints,globalSourceCandidateCount:sources.length,checkpointLocalCandidateCount:candidates.length,unrelatedCandidateExcludedCount:unrelated,unresolvedCandidateFallbackCount:fallback,duplicateCandidateCount:dups,failedPartialPlanExcludedCount:failedExcluded,invalidSourceCandidateExcludedCount:invalidExcluded,accountedSourceCandidateCount,sourceCandidateConservationResidual,unrelatedCandidateExcludedSamples:unrelatedSamples,structuralCandidateExcludedSamples:structuralExcludedSamples}; return deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as InitialConstructionCheckpointLocalCandidateProjection;
}
