import test from "node:test";
import assert from "node:assert/strict";
import { buildInitialConstructionPartialPlanGraphIndex } from "./initialConstructionCausalDecisionCheckpoint";
import { buildInitialConstructionCausalCheckpointCursor } from "./initialConstructionCausalCheckpointCursor";
import { prepareInitialConstructionCausalActivationTransaction } from "./initialConstructionCausalActivationTransaction";

const plan=(id:string,parent:string|null,branch:string,assignments:any[])=>({partialPlanId:id,parentPartialPlanId:parent,assignmentsFingerprint:`afp:${id}`,decisionBranchFingerprint:branch,decisionPath:[id],decisionLineage:[{decisionId:"decision",decisionDepth:1,primaryGoalTaskId:1,executionTaskId:1,branchFingerprint:branch,introducedAssignments:assignments.map((a:any)=>({taskId:a.taskId,assignmentFingerprint:a.key}))}],assignments:assignments.map((a:any)=>({taskId:a.taskId,startPlanned:a.start,endPlanned:a.end,spaceId:1,resourceIds:[1]})),futureFeasibility:{status:"UNKNOWN",residualProductiveTaskCount:0},status:"ACTIVE",depth:1,readOnly:true});
const assignment=(taskId:number,start:string,end:string)=>({taskId,start,end,key:""});
const blocker={taskId:1,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:""};
blocker.key="x"; // intentionally differs from alternatives so both are causal.
const failed=plan("A","root","branch:A",[{...blocker,key:"x"}]);
const b=plan("B","root","branch:B",[{taskId:2,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:"y"}]);
const c=plan("C","root","branch:C",[{taskId:3,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:"z"}]);
const checkpoint={resolved:true,fingerprint:"checkpoint",parentPartialPlanId:"root",parentAssignmentsFingerprint:"afp:root",causalDecisionId:"decision",causalDecisionDepth:1,decisionBranchFingerprint:"branch:A",checkpointParentDepth:0,blockingTaskIds:[1],blockingAssignmentFingerprints:["x"],targetPrimaryGoalTaskId:1,targetExecutionTaskId:1,reopenable:true,readOnly:true};
const conflict={fingerprint:"conflict",frontierTaskId:1,evidenceComplete:true,blockingAssignments:[{taskId:1,assignmentKey:"x",decisionId:"decision",decisionDepth:1}],causalDecisions:[{decisionId:"decision",decisionDepth:1}],readOnly:true};

test("ID 321 transaction inspects B frontier duplicate then prepares C from generated graph",()=>{const graph=buildInitialConstructionPartialPlanGraphIndex([failed,b,c]); const cursor=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"conflict",checkpointFingerprint:"checkpoint",causalDecisionId:"decision",buildOrdinal:1,observedDecisionBranchFingerprints:["branch:A"],observedChildAssignmentsFingerprints:[]}); const ledger={open:(input:any)=>input.selectedPartialPlanId==="B"?{opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"}:{opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}},isBranchExhausted:()=>false}; const tx=prepareInitialConstructionCausalActivationTransaction({conflict,failedPartialPlan:failed,checkpoint,partialPlanGraphIndex:graph,suspendedFrontier:{entries:[{partialPlan:b,partialPlanId:"B",assignmentsFingerprint:"afp:B",depth:1}]},graphNodes:[failed,c],causalArchive:[],cursor,ledger,expandedAssignmentsFingerprints:new Set(["afp:A"]),nogoodFingerprints:new Set(),activationOrdinal:7,baselineProductiveAssignmentCount:0,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:0,expansionWorkUnitCount:9,readOnly:true}); assert.equal(tx.status,"ACTIVATION_PREPARED"); assert.equal(tx.candidateCollection.candidates.length,2); assert.equal(tx.preparedActivation?.inspectedCandidateCount,2); assert.equal(tx.preparedActivation?.skippedCandidateCount,1); assert.equal(tx.selectedCandidate?.partialPlan.partialPlanId,"C"); assert.equal(tx.selectedCandidate?.source,"GENERATED_GRAPH"); assert.equal(tx.preparedActivation?.openedAttemptId,"attempt:C"); const inspected=(tx.transactionEvidence.inspectedCandidates as any[]); assert.equal(inspected[0].status,"SKIPPED"); assert.equal(inspected[1].status,"PREPARED"); assert.ok(tx.transactionEvidence.transactionId); assert.equal(tx.updatedCursor.inspectedDecisionBranchFingerprints.includes("branch:B"),true); assert.equal(tx.updatedCursor.activatedDecisionBranchFingerprints.includes("branch:C"),false); assert.equal(tx.transactionEvidence.sourcePrevalidationFailureCount,0);});

test("ID 321 transaction preserves cursor when candidates are rejected without commit",()=>{const graph=buildInitialConstructionPartialPlanGraphIndex([failed,b]); const cursor=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"conflict",checkpointFingerprint:"checkpoint",causalDecisionId:"decision",buildOrdinal:1,observedDecisionBranchFingerprints:["branch:A"],observedChildAssignmentsFingerprints:[]}); const ledger={open:()=>({opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"}),isBranchExhausted:()=>false}; const tx=prepareInitialConstructionCausalActivationTransaction({conflict,failedPartialPlan:failed,checkpoint,partialPlanGraphIndex:graph,suspendedFrontier:{entries:[{partialPlan:b,partialPlanId:"B",assignmentsFingerprint:"afp:B",depth:1}]},graphNodes:[failed],causalArchive:[],cursor,ledger,expandedAssignmentsFingerprints:new Set(["afp:A"]),nogoodFingerprints:new Set(),activationOrdinal:8,baselineProductiveAssignmentCount:0,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:0,expansionWorkUnitCount:10,readOnly:true}); assert.equal(tx.status,"NO_EXISTING_CAUSAL_CANDIDATE"); assert.notEqual(tx.updatedCursor.fingerprint,cursor.fingerprint); assert.equal(tx.updatedCursor.inspectedDecisionBranchFingerprints.includes("branch:B"),true);});

test("ID 321 reopened child keeps CHECKPOINT_REOPEN source and sourceEntryId differs from fingerprint",()=>{const d=plan("D","root","branch:D",[{taskId:4,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:"w"}]); const graph=buildInitialConstructionPartialPlanGraphIndex([failed,d]); const cursor=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"conflict",checkpointFingerprint:"checkpoint",causalDecisionId:"decision",buildOrdinal:1,observedDecisionBranchFingerprints:["branch:A"],observedChildAssignmentsFingerprints:[]}); const ledger={open:(input:any)=>({opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}}),isBranchExhausted:()=>false}; const tx=prepareInitialConstructionCausalActivationTransaction({conflict,failedPartialPlan:failed,checkpoint,partialPlanGraphIndex:graph,suspendedFrontier:{entries:[]},graphNodes:[failed],causalArchive:[],reopenCandidates:[d],cursor,ledger,expandedAssignmentsFingerprints:new Set(["afp:A"]),nogoodFingerprints:new Set(),activationOrdinal:9,baselineProductiveAssignmentCount:0,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:0,expansionWorkUnitCount:11,readOnly:true}); assert.equal(tx.status,"ACTIVATION_PREPARED"); assert.equal(tx.selectedCandidate?.source,"CHECKPOINT_REOPEN"); assert.equal(tx.sourceCommit?.source,"CHECKPOINT_REOPEN"); assert.equal(tx.sourceCommit?.sourceEntryId,"D"); assert.equal(tx.sourceCommit?.sourceEntryFingerprint,"afp:D"); assert.equal(tx.transactionEvidence.phase,"CHECKPOINT_REOPEN");});


test("ID 321 transaction source prevalidation skips invalid frontier before ledger open",()=>{let openCallCount=0; const graph=buildInitialConstructionPartialPlanGraphIndex([failed,b,c]); const cursor=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"conflict",checkpointFingerprint:"checkpoint",causalDecisionId:"decision",buildOrdinal:1,observedDecisionBranchFingerprints:["branch:A"],observedChildAssignmentsFingerprints:[]}); const ledger={open:()=>{openCallCount++; return {opened:true,attempt:{attemptId:"unexpected",status:"ACTIVE" as const}}},isBranchExhausted:()=>false}; const tx=prepareInitialConstructionCausalActivationTransaction({conflict,failedPartialPlan:failed,checkpoint,partialPlanGraphIndex:graph,suspendedFrontier:{entries:[{partialPlan:b,partialPlanId:"B",assignmentsFingerprint:"wrong",depth:1}]},graphNodes:[],causalArchive:[],cursor,ledger,expandedAssignmentsFingerprints:new Set(["afp:A"]),nogoodFingerprints:new Set(),activationOrdinal:10,baselineProductiveAssignmentCount:0,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:0,expansionWorkUnitCount:12,readOnly:true}); assert.equal(tx.status,"NO_EXISTING_CAUSAL_CANDIDATE"); assert.equal(openCallCount,0); assert.equal(tx.preparedActivation?.skipReasonCounts.CANDIDATE_SOURCE_FINGERPRINT_MISMATCH,1); assert.equal(tx.transactionEvidence.sourcePrevalidationFailureCount,1); assert.equal(tx.updatedCursor.activatedDecisionBranchFingerprints.length,0);});

test("ID 321 transaction source prevalidation skips archive fingerprint mismatch before ledger open",()=>{let openCallCount=0; const archived={partialPlan:c,partialPlanId:"C",assignmentsFingerprint:"wrong"}; const graph=buildInitialConstructionPartialPlanGraphIndex([failed,c]); const cursor=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"conflict",checkpointFingerprint:"checkpoint",causalDecisionId:"decision",buildOrdinal:1,observedDecisionBranchFingerprints:["branch:A"],observedChildAssignmentsFingerprints:[]}); const ledger={open:()=>{openCallCount++; return {opened:true,attempt:{attemptId:"unexpected",status:"ACTIVE" as const}}},isBranchExhausted:()=>false}; const tx=prepareInitialConstructionCausalActivationTransaction({conflict,failedPartialPlan:failed,checkpoint,partialPlanGraphIndex:graph,suspendedFrontier:{entries:[]},graphNodes:[],causalArchive:[archived],cursor,ledger,expandedAssignmentsFingerprints:new Set(["afp:A"]),nogoodFingerprints:new Set(),activationOrdinal:11,baselineProductiveAssignmentCount:0,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:0,expansionWorkUnitCount:13,readOnly:true}); assert.equal(tx.status,"NO_EXISTING_CAUSAL_CANDIDATE"); assert.equal(openCallCount,0); assert.equal(tx.preparedActivation?.skipReasonCounts.CANDIDATE_SOURCE_FINGERPRINT_MISMATCH,1);});
