import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { CandidateAssignment, OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { resolveInitialConstructionCanonicalContext, type InitialConstructionCanonicalContext } from "../understanding/initialConstructionCanonicalContext";

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
export const normalizeOptionalTaskIds = (xs: readonly unknown[] | null | undefined): number[] => [...new Set((xs ?? []).map((x:any)=> (typeof x === "string" && x.trim() === "") ? NaN : Number(x)).filter((n)=>Number.isInteger(n)&&n>0))].sort((a,b)=>a-b);
const uniq = normalizeOptionalTaskIds;
export interface InitialConstructionRepairWindowConflictClassification { readonly kind: string; readonly expected: unknown; readonly actual: unknown; readonly violatedBoundary: string | null; readonly causalSourceTaskIds: readonly number[]; readonly reversibleSourceTaskIds: readonly number[]; readonly immutableSourceTaskIds: readonly number[]; readonly static: boolean; readonly dependencyBoundShiftable: boolean; readonly covered: boolean; readonly uncoveredReasonCode: string | null; readonly fingerprint: string; readonly readOnly: true }
export interface InitialConstructionEffectiveRepairRoot { readonly blockedAnchorTaskId: number; readonly blockedAnchorRank: number | null; readonly ejectedTaskIds: readonly number[]; readonly repairDependencyClosureTaskIds: readonly number[]; readonly repairNeighborhoodTaskIds: readonly number[]; readonly repairNeighborhoodTopologicalTaskIds: readonly number[]; readonly supportingCandidateProfileFingerprints: readonly string[]; readonly supportingTemporalCandidateFingerprints: readonly string[]; readonly representativeCandidateProfileFingerprint: string; readonly representativeCandidateRank: number; readonly productiveClosureTaskIds: readonly number[]; readonly productiveClosureTaskCount: number; readonly effectiveStateFingerprint: string; readonly readOnly: true }
export interface InitialConstructionRepairCandidateProfile { readonly blockedAnchorTaskId: number; readonly temporalCandidateFingerprint: string; readonly windowIndex: number; readonly candidateRank: number; readonly startPlanned: string; readonly endPlanned: string; readonly sourceKinds: readonly string[]; readonly frontierSourceTaskIds: readonly number[]; readonly dependencyBoundSourceTaskIds: readonly number[]; readonly reasonCodes: readonly string[]; readonly taskWindowConflictDetails: readonly any[]; readonly contestantConflictTaskIds: readonly number[]; readonly spaceConflictTaskIds: readonly number[]; readonly resourceConflictTaskIds: readonly number[]; readonly dependencyLowerBoundTaskIds: readonly number[]; readonly dependencyUpperBoundTaskIds: readonly number[]; readonly protectedIntervalConflictIds: readonly string[]; readonly directCausalTaskIds: readonly number[]; readonly repairableConflictTaskIds: readonly number[]; readonly immutableConflictTaskIds: readonly number[]; readonly staticUnrepairableReasonCodes: readonly string[]; readonly repairableReasonCodes: readonly string[]; readonly hardBlockerDimensions: readonly string[]; readonly coveredHardBlockerDimensions: readonly string[]; readonly uncoveredHardBlockerDimensions: readonly string[]; readonly windowConflictClassifications: readonly InitialConstructionRepairWindowConflictClassification[]; readonly staticWindowConflictCount: number; readonly shiftableWindowConflictCount: number; readonly allHardBlockersCovered: boolean; readonly allHardBlockersRepairable: boolean; readonly uncoveredBlockerReasonCodes: readonly string[]; readonly uncoveredBlockerTaskIds: readonly number[]; readonly repairable: boolean; readonly evidenceComplete: boolean; readonly fingerprint: string; readonly readOnly: true }

export interface InitialConstructionRepairEjectionSet { readonly ejectedTaskIds: readonly number[]; readonly repairDependencyClosureTaskIds: readonly number[]; readonly repairNeighborhoodTaskIds: readonly number[]; readonly repairNeighborhoodTopologicalTaskIds: readonly number[]; readonly repairNeighborhoodDependencyFingerprint: string; readonly candidateProfileFingerprint?: string | null; readonly causalTemporalCandidateFingerprint?: string | null; readonly effectiveStateFingerprint?: string | null; readonly supportingCandidateProfileFingerprints?: readonly string[]; readonly supportingTemporalCandidateFingerprints?: readonly string[]; readonly representativeCandidateRank?: number; readonly frontierSourceTaskIds?: readonly number[]; ejectionReasonByTaskId?: Readonly<Record<string,string[]>>; readonly coveredBlockerTaskIds?: readonly number[]; readonly uncoveredBlockerTaskIds?: readonly number[]; readonly coveredReasonCodes?: readonly string[]; readonly uncoveredReasonCodes?: readonly string[]; readonly allKnownCandidateBlockersCovered?: boolean; readonly executable?: boolean; readonly rejectionReason?: string | null; readonly combinatorialExpansionUsed?: false; readonly fingerprint: string; readonly readOnly: true }
export interface InitialConstructionRepairProblem {
  readonly residualFingerprint: string; readonly blockedAnchorTaskId: number; readonly blockedAnchorRank: number | null; readonly blockedAnchorClosureTaskIds: readonly number[];
  readonly directConflictTaskIds: readonly number[]; readonly dependencyConflictTaskIds: readonly number[]; readonly effectiveRepairRoots: readonly InitialConstructionEffectiveRepairRoot[]; readonly effectiveRepairRootCount: number; readonly equivalentRepairRootDedupCount: number; readonly staticHardBlockerProfileCount: number; readonly shiftableDependencyBoundProfileCount: number; readonly uncoveredHardBlockerProfileCount: number; readonly rootRejectedReasonCounts: Readonly<Record<string,number>>; readonly rootStaticWindowConflictCountsByAnchor: Readonly<Record<string,number>>; readonly rootShiftableWindowConflictCountsByAnchor: Readonly<Record<string,number>>; readonly repairCandidateProfiles: readonly InitialConstructionRepairCandidateProfile[]; readonly repairCandidateProfileCount: number; readonly repairableCandidateProfileCount: number; readonly unrepairableCandidateProfileCount: number; readonly candidateProfilesWithDependencyBoundBlockers: number; readonly repairCandidateProfilesFingerprint: string; readonly combinatorialExpansionUsed: false; readonly candidateEjectionSets: readonly InitialConstructionRepairEjectionSet[];
  readonly protectedTaskIds: readonly number[]; readonly immutableTaskIds: readonly number[]; readonly repairableConflictTaskIds: readonly number[]; readonly immutableConflictTaskIds: readonly number[]; readonly maximumEjectionDepth: number; readonly fingerprint: string; readonly readOnly: true;
}

export function resolveInitialConstructionImmutableTaskIds(args: { input: EngineInput; originOperationalState: OperationalState; protectedTaskIds?: readonly number[] }): number[] {
  const out = new Set<number>(args.protectedTaskIds ?? []);
  for (const t of args.input.tasks ?? []) if (["done", "in_progress"].includes(String((t as any).status))) out.add(Number((t as any).id));
  for (const l of (args.input as any).locks ?? []) out.add(Number(l.taskId ?? l.task_id ?? l.id));
  for (const p of args.originOperationalState.planning ?? []) out.add(Number((p as any).taskId));
  return uniq([...out]);
}

export function repairDependencyClosure(args: { input: EngineInput; seedTaskIds: readonly number[]; provisionalAssignmentTaskIds: readonly number[]; canonicalContext?: InitialConstructionCanonicalContext | null }): number[] {
  const graph = resolveInitialConstructionCanonicalContext({ input: args.input, canonicalContext: args.canonicalContext });
  const provisional = new Set(args.provisionalAssignmentTaskIds.map(Number));
  const closure = new Set(args.seedTaskIds.map(Number).filter((id)=>provisional.has(id)));
  let changed = true;
  while (changed) {
    changed = false;
    for (const taskId of [...closure]) {
      for (const dependent of graph.dependentsByTaskId.get(taskId) ?? []) {
        if (provisional.has(dependent) && !closure.has(dependent)) { closure.add(dependent); changed = true; }
      }
    }
  }
  return graph.topologicalTaskIds.filter((id) => closure.has(id));
}

const dim=(xs:number[], name:string)=>xs.length?[name]:[];
const classifyWindowConflict=(d:any, depSourceIds:number[], provisional:Set<number>, immutable:Set<number>): InitialConstructionRepairWindowConflictClassification=>{
  const kind=String(d?.kind??d?.reasonCode??d?.code??d?.type??"WINDOW_CONFLICT").toUpperCase();
  const violatedBoundary=String(d?.violatedBoundary??d?.boundaryKind??d?.sourceKind??d?.frontierKind??"")||null;
  const boundarySources=normalizeOptionalTaskIds([...(d?.causalSourceTaskIds??[]),...(d?.sourceTaskIds??[]),...(d?.dependencyBoundSourceTaskIds??[]),d?.dependencyBoundSourceTaskId,d?.taskId,...(d?.conflictTaskIds??[])]).filter(id=>provisional.has(id));
  const mobileKinds=new Set(["assigned-prerequisite-end","assigned-dependent-start","dependency-lower-bound","dependency-upper-bound","DEPENDENCY_LOWER_BOUND","DEPENDENCY_UPPER_BOUND"]);
  const boundaryKindMobile=violatedBoundary ? mobileKinds.has(violatedBoundary) : false;
  const causal=normalizeOptionalTaskIds([...boundarySources,...(boundaryKindMobile?depSourceIds:[])]).filter(id=>provisional.has(id));
  const reversible=causal.filter(id=>!immutable.has(id)); const imm=causal.filter(id=>immutable.has(id));
  const dependencyBoundShiftable=causal.length>0 && imm.length===0 && (boundaryKindMobile || normalizeOptionalTaskIds(d?.dependencyBoundSourceTaskIds).some(id=>depSourceIds.includes(id)));
  const temporalStatic=/OUTSIDE_AVAILABILITY|AVAILABILITY|OUTSIDE_WORKDAY|WORKDAY|OUTSIDE_FIXED_WINDOW|FIXED_WINDOW|DURATION|EMPTY_WINDOW|PROTECTED/.test(kind);
  const staticConflict=temporalStatic && !dependencyBoundShiftable;
  const covered=dependencyBoundShiftable && reversible.length===causal.length;
  const uncoveredReasonCode=covered?null:(staticConflict?`${kind}_STATIC`:(imm.length?`${kind}_IMMUTABLE`:null));
  const base:any={kind,expected:d?.expected??d?.expectedWindow??null,actual:d?.actual??d?.actualWindow??null,violatedBoundary,causalSourceTaskIds:causal,reversibleSourceTaskIds:reversible,immutableSourceTaskIds:imm,static:staticConflict,dependencyBoundShiftable,covered,uncoveredReasonCode,fingerprint:"",readOnly:true};
  base.fingerprint=hash({...base,fingerprint:undefined}); return deepFreeze(base) as any;
};

export function profileFromAnchorPlacementEvidence(args:{ blockedAnchorTaskId:number; evidence:any; provisionalTaskIds: readonly number[]; immutableTaskIds: readonly number[] }): InitialConstructionRepairCandidateProfile {
  const ev=args.evidence??{}; const causal={...ev,...(ev.causalConflictEvidence??{})}; const provisional=new Set(normalizeOptionalTaskIds(args.provisionalTaskIds as any)); const immutable=new Set(normalizeOptionalTaskIds(args.immutableTaskIds as any));
  const frontierSources=Array.isArray(ev.frontierSources)?ev.frontierSources:[];
  const depSourceIds=normalizeOptionalTaskIds([...(ev.dependencyBoundSourceTaskIds??[]),...(causal.dependencyBoundSourceTaskIds??[]),...frontierSources.filter((s:any)=>["assigned-prerequisite-end","assigned-dependent-start","dependency-lower-bound","dependency-upper-bound"].includes(String(s?.kind))).flatMap((s:any)=>[s.taskId,...(s.taskIds??[]),...(s.sourceTaskIds??[])])]).filter(id=>provisional.has(id));
  const contestant=normalizeOptionalTaskIds(causal.contestantConflictTaskIds).filter(id=>provisional.has(id));
  const space=normalizeOptionalTaskIds(causal.spaceConflictTaskIds).filter(id=>provisional.has(id));
  const resource=normalizeOptionalTaskIds(causal.resourceConflictTaskIds).filter(id=>provisional.has(id));
  const lower=normalizeOptionalTaskIds(causal.dependencyLowerBoundTaskIds).filter(id=>provisional.has(id));
  const upper=normalizeOptionalTaskIds(causal.dependencyUpperBoundTaskIds).filter(id=>provisional.has(id));
  const details=Array.isArray(causal.taskWindowConflictDetails)?causal.taskWindowConflictDetails:[];
  const windowConflictClassifications=details.map((d:any)=>classifyWindowConflict(d,depSourceIds,provisional,immutable)).sort((a:any,b:any)=>a.fingerprint.localeCompare(b.fingerprint));
  const shiftableIds=normalizeOptionalTaskIds(windowConflictClassifications.flatMap((c:any)=>c.reversibleSourceTaskIds as number[]));
  const detailIds=normalizeOptionalTaskIds(windowConflictClassifications.flatMap((c:any)=>c.causalSourceTaskIds as number[]));
  const direct=normalizeOptionalTaskIds([...(causal.causalConflictTaskIds??[]),...contestant,...space,...resource,...lower,...upper,...detailIds,...shiftableIds]).filter(id=>id!==Number(args.blockedAnchorTaskId));
  const repairableIds=direct.filter(id=>!immutable.has(id)); const immutableIds=direct.filter(id=>immutable.has(id));
  const reasons=[...(ev.reasonCodes??[]),...(causal.reasonCodes??[])].map(String).sort();
  const repairableReasonCodes=[...dim(contestant,"CONTESTANT_OVERLAP"),...dim(space,"SPACE_OVERLAP"),...dim(resource,"RESOURCE_OVERLAP"),...dim(lower,"DEPENDENCY_LOWER_BOUND"),...dim(upper,"DEPENDENCY_UPPER_BOUND"),...dim(shiftableIds,"DEPENDENCY_BOUND_FRONTIER")].sort();
  const hardBlockerDimensions=[...dim(contestant,"contestant"),...dim(space,"space"),...dim(resource,"resource"),...dim(lower,"dependency lower bound"),...dim(upper,"dependency upper bound"),...(causal.protectedIntervalConflictIds?.length?["protected interval"]:[])];
  for(const c of windowConflictClassifications){ const k=c.kind; if(k.includes("AVAILABILITY")) hardBlockerDimensions.push("availability"); else if(k.includes("WORKDAY")) hardBlockerDimensions.push("workday"); else if(k.includes("FIXED_WINDOW")) hardBlockerDimensions.push("fixed window"); else if(k.includes("PROTECTED")) hardBlockerDimensions.push("protected interval"); }
  const coveredHardBlockerDimensions=[...dim(contestant.filter(id=>!immutable.has(id)),"contestant"),...dim(space.filter(id=>!immutable.has(id)),"space"),...dim(resource.filter(id=>!immutable.has(id)),"resource"),...dim(lower.filter(id=>!immutable.has(id)),"dependency lower bound"),...dim(upper.filter(id=>!immutable.has(id)),"dependency upper bound")];
  for(const c of windowConflictClassifications.filter((c:any)=>c.covered)){ if(c.kind.includes("AVAILABILITY")) coveredHardBlockerDimensions.push("availability"); else if(c.kind.includes("WORKDAY")) coveredHardBlockerDimensions.push("workday"); else if(c.kind.includes("FIXED_WINDOW")) coveredHardBlockerDimensions.push("fixed window"); }
  const hard=Array.from(new Set(hardBlockerDimensions)).sort(); const coveredDims=Array.from(new Set(coveredHardBlockerDimensions)).filter(d=>hard.includes(d)).sort(); const uncoveredDims=hard.filter(d=>!coveredDims.includes(d));
  const staticUnrepairableReasonCodes=[...windowConflictClassifications.filter((c:any)=>c.static).map((c:any)=>c.uncoveredReasonCode??c.kind),...(direct.length===0?reasons.filter(r=>/WORKDAY|AVAILABILITY|FIXED_WINDOW|DURATION|PROTECTED/.test(r.toUpperCase())):[])].sort();
  const uncoveredBlockerTaskIds=immutableIds; const uncoveredBlockerReasonCodes=[...staticUnrepairableReasonCodes,...(immutableIds.length?["IMMUTABLE_BLOCKER"]:[]),...uncoveredDims.map(d=>`UNCOVERED_${d.toUpperCase().replaceAll(" ","_")}`)].sort();
  const allHardBlockersCovered=(hard.length>0 ? uncoveredDims.length===0 : direct.length>0) && immutableIds.length===0 && staticUnrepairableReasonCodes.length===0;
  const allHardBlockersRepairable=direct.length>0 && repairableIds.length===direct.length && allHardBlockersCovered;
  const base:any={blockedAnchorTaskId:Number(args.blockedAnchorTaskId),temporalCandidateFingerprint:String(ev.temporalCandidateFingerprint??ev.fingerprint??hash({s:ev.startPlanned,e:ev.endPlanned,w:ev.windowIndex,r:ev.candidateRankWithinWindow})),windowIndex:Number(ev.windowIndex??0),candidateRank:Number(ev.candidateRankWithinWindow??ev.candidateRank??0),startPlanned:String(ev.startPlanned??""),endPlanned:String(ev.endPlanned??""),sourceKinds:[...(ev.sourceKinds??[]),...frontierSources.map((s:any)=>String(s.kind??""))].filter(Boolean).sort(),frontierSourceTaskIds:normalizeOptionalTaskIds([...(ev.frontierSourceTaskIds??[]),...frontierSources.flatMap((s:any)=>[s.taskId,...(s.taskIds??[]),...(s.sourceTaskIds??[])])]),dependencyBoundSourceTaskIds:depSourceIds,reasonCodes:reasons,taskWindowConflictDetails:details,contestantConflictTaskIds:contestant,spaceConflictTaskIds:space,resourceConflictTaskIds:resource,dependencyLowerBoundTaskIds:lower,dependencyUpperBoundTaskIds:upper,protectedIntervalConflictIds:[...(causal.protectedIntervalConflictIds??[])].map(String).sort(),directCausalTaskIds:direct,repairableConflictTaskIds:repairableIds,immutableConflictTaskIds:immutableIds,staticUnrepairableReasonCodes,repairableReasonCodes,hardBlockerDimensions:hard,coveredHardBlockerDimensions:coveredDims,uncoveredHardBlockerDimensions:uncoveredDims,windowConflictClassifications,staticWindowConflictCount:windowConflictClassifications.filter((c:any)=>c.static).length,shiftableWindowConflictCount:windowConflictClassifications.filter((c:any)=>c.dependencyBoundShiftable).length,allHardBlockersCovered,allHardBlockersRepairable,uncoveredBlockerReasonCodes,uncoveredBlockerTaskIds,repairable:allHardBlockersRepairable,evidenceComplete:causal.evidenceComplete!==false,fingerprint:"",readOnly:true};
  base.fingerprint=hash({...base,fingerprint:undefined}); return deepFreeze(base) as any;
}

export function buildInitialConstructionRepairProblem(args: { input: EngineInput; originOperationalState: OperationalState; residualFingerprint: string; blockedAnchorTaskId: number; blockedAnchorRank?: number | null; blockedAnchorClosureTaskIds?: readonly number[]; terminalEvidence?: any; repairCandidateProfiles?: readonly InitialConstructionRepairCandidateProfile[]; provisionalAssignments: readonly CandidateAssignment[]; protectedTaskIds?: readonly number[]; maxEjectedAssignments?: number; maxRepairNeighborhoodTasks?: number; canonicalContext?: InitialConstructionCanonicalContext | null }): InitialConstructionRepairProblem {
  const canonicalContext = resolveInitialConstructionCanonicalContext({ input: args.input, canonicalContext: args.canonicalContext });
  const maxDepth = args.maxEjectedAssignments ?? 4; const maxNeighborhood = args.maxRepairNeighborhoodTasks ?? 12;
  const provisionalIds = uniq(args.provisionalAssignments.map(a=>Number(a.taskId))); const immutable = resolveInitialConstructionImmutableTaskIds(args); const immutableSet = new Set(immutable);
  const ev = args.terminalEvidence ?? {}; const details = Array.isArray(ev.taskWindowConflictDetails) ? ev.taskWindowConflictDetails : [];
  const direct = uniq([...(ev.causalConflictTaskIds ?? []), ...(ev.contestantConflictTaskIds ?? []), ...(ev.spaceConflictTaskIds ?? []), ...(ev.resourceConflictTaskIds ?? []), ...(ev.dependencyBoundSourceTaskIds ?? []), ...details.flatMap((d:any)=>[...(d.conflictTaskIds ?? []), ...(d.dependencyBoundSourceTaskIds ?? []), d.taskId].filter((id:any)=>Number(id)!==Number(args.blockedAnchorTaskId)))]).filter((id)=>provisionalIds.includes(Number(id)) && !immutableSet.has(Number(id)));
  const dep = uniq([...(ev.dependencyLowerBoundTaskIds ?? []), ...(ev.dependencyUpperBoundTaskIds ?? []), ...(ev.dependencyBoundSourceTaskIds ?? [])]).filter((id)=>provisionalIds.includes(id) && !immutableSet.has(id));
  const immutableConflicts = uniq([...(ev.causalConflictTaskIds ?? []), ...(ev.contestantConflictTaskIds ?? []), ...(ev.spaceConflictTaskIds ?? []), ...(ev.resourceConflictTaskIds ?? []), ...(ev.dependencyLowerBoundTaskIds ?? []), ...(ev.dependencyUpperBoundTaskIds ?? [])].map(Number).filter((id)=>provisionalIds.includes(id) && immutableSet.has(id)));
  const fallbackProfile = profileFromAnchorPlacementEvidence({blockedAnchorTaskId:Number(args.blockedAnchorTaskId), evidence:{...ev,temporalCandidateFingerprint:hash({anchor:args.blockedAnchorTaskId,ev}),causalConflictEvidence:{...ev,causalConflictTaskIds:[...direct,...dep,...immutableConflicts],evidenceComplete:ev.causalConflictEvidenceComplete!==false}}, provisionalTaskIds:provisionalIds, immutableTaskIds:immutable});
  const sessionRequiresProfiles = ev.requireCandidateScopedProfiles===true;
  const profiles = [...(args.repairCandidateProfiles?.length ? args.repairCandidateProfiles : (sessionRequiresProfiles ? [] : [fallbackProfile]))].sort((a,b)=>a.candidateRank-b.candidateRank||a.fingerprint.localeCompare(b.fingerprint));
  const candidateEjectionSets: InitialConstructionRepairEjectionSet[] = []; const effectiveRepairRoots: any[] = []; const effectiveByKey=new Map<string, any>();
  for (const profile of profiles) {
    if (!profile.repairable || !profile.allHardBlockersRepairable) continue;
    const seed=uniq(profile.repairableConflictTaskIds.map(Number).filter((id)=>provisionalIds.includes(id)&&!immutableSet.has(id)));
    if (!seed.length) continue;
    if (seed.length>maxDepth) continue;
    const closure = repairDependencyClosure({ input: args.input, seedTaskIds: seed, provisionalAssignmentTaskIds: provisionalIds, canonicalContext });
    const neighborhood = uniq([Number(args.blockedAnchorTaskId), ...(args.blockedAnchorClosureTaskIds ?? []), ...closure]);
    if (closure.length === 0 || neighborhood.length > maxNeighborhood || closure.some((id)=>immutableSet.has(id))) continue;
    const neighborhoodTopo = canonicalContext.topologicalTaskIds.filter((id) => neighborhood.includes(id));
    const depFp = hash({ edges: (canonicalContext.dependencyGraph.edges ?? []).filter((e:any) => neighborhood.includes(e.fromTaskId) && neighborhood.includes(e.toTaskId)) });
    const effectiveStateFingerprint=hash({base:args.residualFingerprint,anchor:args.blockedAnchorTaskId,seed,closure,neighborhood});
    const key=stableStringify({anchor:args.blockedAnchorTaskId,seed,closure,neighborhood});
    const existing=effectiveByKey.get(key);
    if(existing){ existing.supportingCandidateProfileFingerprints=[...new Set([...existing.supportingCandidateProfileFingerprints, profile.fingerprint])].sort(); existing.supportingTemporalCandidateFingerprints=[...new Set([...existing.supportingTemporalCandidateFingerprints, profile.temporalCandidateFingerprint])].sort(); if(profile.candidateRank<existing.representativeCandidateRank){ existing.representativeCandidateProfileFingerprint=profile.fingerprint; existing.representativeCandidateRank=profile.candidateRank; } continue; }
    const root:any={blockedAnchorTaskId:Number(args.blockedAnchorTaskId),blockedAnchorRank:args.blockedAnchorRank??null,ejectedTaskIds:seed,repairDependencyClosureTaskIds:closure,repairNeighborhoodTaskIds:neighborhood,repairNeighborhoodTopologicalTaskIds:neighborhoodTopo,supportingCandidateProfileFingerprints:[profile.fingerprint],supportingTemporalCandidateFingerprints:[profile.temporalCandidateFingerprint],representativeCandidateProfileFingerprint:profile.fingerprint,representativeCandidateRank:profile.candidateRank,productiveClosureTaskIds:closure,productiveClosureTaskCount:closure.length,effectiveStateFingerprint,readOnly:true}; effectiveByKey.set(key,root); effectiveRepairRoots.push(root);
    const ejectionReasonByTaskId: Readonly<Record<string,string[]>> = Object.fromEntries(seed.map((id) => [String(id), profile.reasonCodes.length ? [...profile.reasonCodes] : ["CAUSAL_CANDIDATE_BLOCKER"]]));
    const fingerprint = effectiveStateFingerprint;
    candidateEjectionSets.push({ ejectedTaskIds: seed, repairDependencyClosureTaskIds: closure, repairNeighborhoodTaskIds: neighborhood, repairNeighborhoodTopologicalTaskIds: neighborhoodTopo, repairNeighborhoodDependencyFingerprint: depFp, candidateProfileFingerprint: profile.fingerprint, causalTemporalCandidateFingerprint: profile.temporalCandidateFingerprint, effectiveStateFingerprint, supportingCandidateProfileFingerprints:[profile.fingerprint], supportingTemporalCandidateFingerprints:[profile.temporalCandidateFingerprint], representativeCandidateRank:profile.candidateRank, frontierSourceTaskIds: profile.frontierSourceTaskIds, ejectionReasonByTaskId, coveredBlockerTaskIds: seed, uncoveredBlockerTaskIds: profile.uncoveredBlockerTaskIds, coveredReasonCodes: profile.repairableReasonCodes, uncoveredReasonCodes: profile.uncoveredBlockerReasonCodes, allKnownCandidateBlockersCovered: profile.uncoveredBlockerTaskIds.length===0 && profile.uncoveredBlockerReasonCodes.length===0, executable: profile.uncoveredBlockerTaskIds.length===0 && profile.uncoveredBlockerReasonCodes.length===0, rejectionReason: null, combinatorialExpansionUsed:false, fingerprint, readOnly: true });
  }
  for(const root of effectiveRepairRoots) Object.freeze(root);
  candidateEjectionSets.sort((a:any,b:any)=>Number(a.representativeCandidateRank??999999)-Number(b.representativeCandidateRank??999999)||b.repairDependencyClosureTaskIds.length-a.repairDependencyClosureTaskIds.length||a.ejectedTaskIds.length-b.ejectedTaskIds.length||a.repairDependencyClosureTaskIds.length-b.repairDependencyClosureTaskIds.length||a.fingerprint.localeCompare(b.fingerprint));
  effectiveRepairRoots.sort((a:any,b:any)=>a.representativeCandidateRank-b.representativeCandidateRank||b.productiveClosureTaskCount-a.productiveClosureTaskCount||a.ejectedTaskIds.length-b.ejectedTaskIds.length||a.repairDependencyClosureTaskIds.length-b.repairDependencyClosureTaskIds.length||a.effectiveStateFingerprint.localeCompare(b.effectiveStateFingerprint));
  const related=uniq([...direct,...dep,...profiles.flatMap(p=>p.repairableConflictTaskIds as number[])]);
  const profilesFp=hash(profiles.map(p=>p.fingerprint)); const payload = { residualFingerprint: args.residualFingerprint, blockedAnchorTaskId: Number(args.blockedAnchorTaskId), profiles: profiles.map(p=>p.fingerprint), sets: candidateEjectionSets.map(s=>({e:s.ejectedTaskIds,c:s.repairDependencyClosureTaskIds,p:s.candidateProfileFingerprint})) };
  const rootRejectedReasonCounts:Record<string,number>={}; for(const p of profiles.filter(p=>!p.repairable)) for(const r of p.uncoveredBlockerReasonCodes.length?p.uncoveredBlockerReasonCodes:["UNREPAIRABLE_PROFILE"]) rootRejectedReasonCounts[r]=(rootRejectedReasonCounts[r]??0)+1;
  return deepFreeze({ residualFingerprint: args.residualFingerprint, blockedAnchorTaskId: Number(args.blockedAnchorTaskId), blockedAnchorRank: args.blockedAnchorRank ?? null, blockedAnchorClosureTaskIds: uniq(args.blockedAnchorClosureTaskIds ?? [Number(args.blockedAnchorTaskId)]), directConflictTaskIds: direct, dependencyConflictTaskIds: dep, effectiveRepairRoots, effectiveRepairRootCount: effectiveRepairRoots.length, equivalentRepairRootDedupCount: Math.max(0,candidateEjectionSets.length-effectiveRepairRoots.length), staticHardBlockerProfileCount: profiles.filter(p=>p.staticWindowConflictCount>0).length, shiftableDependencyBoundProfileCount: profiles.filter(p=>p.shiftableWindowConflictCount>0).length, uncoveredHardBlockerProfileCount: profiles.filter(p=>p.uncoveredHardBlockerDimensions.length>0 || p.uncoveredBlockerReasonCodes.length>0).length, rootRejectedReasonCounts, rootStaticWindowConflictCountsByAnchor: {[String(args.blockedAnchorTaskId)]: profiles.reduce((n,p)=>n+p.staticWindowConflictCount,0)}, rootShiftableWindowConflictCountsByAnchor: {[String(args.blockedAnchorTaskId)]: profiles.reduce((n,p)=>n+p.shiftableWindowConflictCount,0)}, repairCandidateProfiles: profiles, repairCandidateProfileCount: profiles.length, repairableCandidateProfileCount: profiles.filter(p=>p.repairable).length, unrepairableCandidateProfileCount: profiles.filter(p=>!p.repairable).length, candidateProfilesWithDependencyBoundBlockers: profiles.filter(p=>p.dependencyBoundSourceTaskIds.length>0).length, repairCandidateProfilesFingerprint: profilesFp, combinatorialExpansionUsed:false, candidateEjectionSets, protectedTaskIds: uniq(args.protectedTaskIds ?? []), immutableTaskIds: immutable, repairableConflictTaskIds: related, immutableConflictTaskIds: immutableConflicts, maximumEjectionDepth: maxDepth, fingerprint: hash(payload), readOnly: true });
}
