import test from "node:test";
import assert from "node:assert/strict";
import { buildInitialConstructionPartialPlanGraphIndex } from "./initialConstructionCausalDecisionCheckpoint";
import { buildInitialConstructionCausalCheckpointCursor } from "./initialConstructionCausalCheckpointCursor";
import { prepareInitialConstructionCausalActivationTransaction } from "./initialConstructionCausalActivationTransaction";

const plan=(id:string,parent:string|null,branch:string,assignments:any[])=>({partialPlanId:id,parentPartialPlanId:parent,assignmentsFingerprint:`afp:${id}`,decisionBranchFingerprint:branch,decisionPath:[id],decisionLineage:[{decisionId:"decision",decisionDepth:1,primaryGoalTaskId:1,executionTaskId:1,branchFingerprint:branch,introducedAssignments:assignments.map((a:any)=>({taskId:a.taskId,assignmentFingerprint:a.key}))}],assignments:assignments.map((a:any)=>({taskId:a.taskId,startPlanned:a.start,endPlanned:a.end,spaceId:1,resourceIds:[1]})),futureFeasibility:{status:"UNKNOWN",residualProductiveTaskCount:0},status:"ACTIVE",depth:1,readOnly:true});
const assignment=(taskId:number,start:string,end:string)=>({taskId,start,end,key:""});
const blocker={taskId:1,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:""};
blocker.key="x"; // intentionally differs from alternatives so both are causal.
const failed=plan("A","root","branch:A",[{...blocker,key:"x"}]);
const b=plan("B","root","branch:B",[{taskId:2,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:"y"}]);
const c=plan("C","root","branch:C",[{taskId:3,start:"2026-01-01T08:00:00.000Z",end:"2026-01-01T09:00:00.000Z",key:"z"}]);
const checkpoint={resolved:true,fingerprint:"checkpoint",parentPartialPlanId:"root",parentAssignmentsFingerprint:"afp:root",causalDecisionId:"decision",causalDecisionDepth:1,decisionBranchFingerprint:"branch:A",checkpointParentDepth:0,blockingTaskIds:[1],blockingAssignmentFingerprints:["x"],targetPrimaryGoalTaskId:1,targetExecutionTaskId:1,reopenable:true,readOnly:true};
const conflict={fingerprint:"conflict",frontierTaskId:1,evidenceComplete:true,blockingAssignments:[{taskId:1,assignmentKey:"x",decisionId:"decision",decisionDepth:1}],causalDecisions:[{decisionId:"decision",decisionDepth:1}],readOnly:true};

test("ID 321 transaction inspects B frontier duplicate then prepares C from generated graph",()=>{const graph=buildInitialConstructionPartialPlanGraphIndex([failed,b,c]); const cursor=buildInitialConstructionCausalCheckpointCursor({conflictFingerprint:"conflict",checkpointFingerprint:"checkpoint",causalDecisionId:"decision",buildOrdinal:1,observedDecisionBranchFingerprints:["branch:A"],observedChildAssignmentsFingerprints:[]}); const ledger={open:(input:any)=>input.selectedPartialPlanId==="B"?{opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"}:{opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}},isBranchExhausted:()=>false}; const tx=prepareInitialConstructionCausalActivationTransaction({conflict,failedPartialPlan:failed,checkpoint,partialPlanGraphIndex:graph,suspendedFrontier:{entries:[{partialPlan:b,partialPlanId:"B",assignmentsFingerprint:"afp:B",depth:1}]},graphNodes:[failed,c],causalArchive:[],cursor,ledger,expandedAssignmentsFingerprints:new Set(["afp:A"]),nogoodFingerprints:new Set(),activationOrdinal:7,baselineProductiveAssignmentCount:0,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:0,expansionWorkUnitCount:9,readOnly:true}); assert.equal(tx.status,"ACTIVATION_PREPARED"); assert.equal(tx.candidateCollection.candidates.length,2); assert.equal(tx.preparedActivation?.inspectedCandidateCount,2); assert.equal(tx.preparedActivation?.skippedCandidateCount,1); assert.equal(tx.selectedCandidate?.partialPlan.partialPlanId,"C"); assert.equal(tx.selectedCandidate?.source,"GENERATED_GRAPH"); assert.equal(tx.preparedActivation?.openedAttemptId,"attempt:C"); const inspected=(tx.transactionEvidence.inspectedCandidates as any[]); assert.equal(inspected[0].status,"SKIPPED"); assert.equal(inspected[1].status,"PREPARED"); assert.ok(tx.transactionEvidence.transactionId); assert.equal(tx.updatedCursor.inspectedDecisionBranchFingerprints.includes("branch:B"),true); assert.equal(tx.updatedCursor.activatedDecisionBranchFingerprints.includes("branch:C"),true);});
