import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { CandidateAssignment, OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { resolveInitialConstructionCanonicalContext, type InitialConstructionCanonicalContext } from "../understanding/initialConstructionCanonicalContext";
import { evaluateInitialConstructionPlacementFeasibility } from "../see/initialConstructionPlacementFeasibility";

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
export const normalizeOptionalTaskIds = (xs: readonly unknown[] | null | undefined): number[] => [...new Set((xs ?? []).map((x:any)=> (typeof x === "string" && x.trim() === "") ? NaN : Number(x)).filter((n)=>Number.isInteger(n)&&n>0))].sort((a,b)=>a-b);
const uniq = normalizeOptionalTaskIds;
const uniqStrings=(xs:readonly string[])=>[...new Set(xs)].sort();
export interface InitialConstructionRepairFrontierSource { readonly kind:string; readonly taskId:number|null; readonly boundary:string|null; readonly time:string|null; readonly readOnly:boolean }
export interface InitialConstructionRepairWindowConflictClassification { readonly kind: string; readonly expected: unknown; readonly actual: unknown; readonly violatedBoundary: string | null; readonly candidateStart:string; readonly candidateEnd:string; readonly expectedStart:string|null; readonly expectedEnd:string|null; readonly violatedStart:boolean; readonly violatedEnd:boolean; readonly matchingMobileFrontierSources:readonly InitialConstructionRepairFrontierSource[]; readonly nonMatchingMobileFrontierSources:readonly InitialConstructionRepairFrontierSource[]; readonly requiredShiftDirection:"earlier"|"later"|"both"|null; readonly causalSourceTaskIds: readonly number[]; readonly reversibleSourceTaskIds: readonly number[]; readonly immutableSourceTaskIds: readonly number[]; readonly static: boolean; readonly dependencyBoundShiftable: boolean; readonly covered: boolean; readonly uncoveredReasonCode: string | null; readonly causalLinkFingerprint:string; readonly fingerprint: string; readonly readOnly: true }
export interface InitialConstructionRepairTargetProjection { readonly blockedAnchorTaskId:number; readonly candidateProfileFingerprint:string; readonly originalStart:string; readonly originalEnd:string; readonly projectedStart:string; readonly projectedEnd:string; readonly requiredShiftDirection:"earlier"|"later"; readonly requiredShiftMinutes:number; readonly violatedBoundary:string; readonly mobileSourceTaskIds:readonly number[]; readonly mobileSourceBoundaryRequirements:readonly unknown[]; readonly originalCandidateConflictTaskIds:readonly number[]; readonly projectedTargetBlockerTaskIds:readonly number[]; readonly projectedTargetImmutableBlockerTaskIds:readonly number[]; readonly obsoleteOriginalCandidateBlockerTaskIds:readonly number[]; readonly projectedPlacementReasonCodes:readonly string[]; readonly projectedWindowConflictDetails:readonly unknown[]; readonly projectedTargetValidAfterEjection:boolean; readonly dependencySourcePendingReconstruction:boolean; readonly executable:boolean; readonly rejectionReason:string|null; readonly fingerprint:string; readonly readOnly:true }
export interface InitialConstructionEffectiveRepairRoot { readonly blockedAnchorTaskId: number; readonly blockedAnchorRank: number | null; readonly ejectedTaskIds: readonly number[]; readonly repairDependencyClosureTaskIds: readonly number[]; readonly repairNeighborhoodTaskIds: readonly number[]; readonly repairNeighborhoodTopologicalTaskIds: readonly number[]; readonly supportingCandidateProfileFingerprints: readonly string[]; readonly supportingTemporalCandidateFingerprints: readonly string[]; readonly representativeCandidateProfileFingerprint: string; readonly representativeCandidateRank: number; readonly productiveClosureTaskIds: readonly number[]; readonly productiveClosureTaskCount: number; readonly residualProductiveClosureTaskIds:readonly number[]; readonly residualProductiveClosureTaskCount:number; readonly allHardBlockersCovered:boolean; readonly targetProjection:InitialConstructionRepairTargetProjection|null; readonly projectedTargetStart:string|null; readonly projectedTargetEnd:string|null; readonly requiredShiftDirection:"earlier"|"later"|null; readonly requiredShiftMinutes:number; readonly mobileSourceTaskIds:readonly number[]; readonly projectedTargetBlockerTaskIds:readonly number[]; readonly obsoleteOriginalCandidateBlockerTaskIds:readonly number[]; readonly projectedTargetValidAfterEjection:boolean; readonly repairObjectiveFingerprint:string|null; readonly effectiveStateFingerprint: string; readonly readOnly: true }
export interface InitialConstructionRepairCandidateProfile { readonly blockedAnchorTaskId: number; readonly temporalCandidateFingerprint: string; readonly windowIndex: number; readonly candidateRank: number; readonly startPlanned: string; readonly endPlanned: string; readonly frontierSources:readonly InitialConstructionRepairFrontierSource[]; readonly mobileFrontierSources:readonly InitialConstructionRepairFrontierSource[]; readonly staticFrontierSources:readonly InitialConstructionRepairFrontierSource[]; readonly effectiveMobileFrontierSourceTaskIds:readonly number[]; readonly windowConflictCausalLinks:readonly InitialConstructionRepairWindowConflictClassification[]; readonly sourceKinds: readonly string[]; readonly frontierSourceTaskIds: readonly number[]; readonly dependencyBoundSourceTaskIds: readonly number[]; readonly reasonCodes: readonly string[]; readonly taskWindowConflictDetails: readonly any[]; readonly contestantConflictTaskIds: readonly number[]; readonly spaceConflictTaskIds: readonly number[]; readonly resourceConflictTaskIds: readonly number[]; readonly dependencyLowerBoundTaskIds: readonly number[]; readonly dependencyUpperBoundTaskIds: readonly number[]; readonly protectedIntervalConflictIds: readonly string[]; readonly directCausalTaskIds: readonly number[]; readonly repairableConflictTaskIds: readonly number[]; readonly immutableConflictTaskIds: readonly number[]; readonly staticUnrepairableReasonCodes: readonly string[]; readonly repairableReasonCodes: readonly string[]; readonly hardBlockerDimensions: readonly string[]; readonly coveredHardBlockerDimensions: readonly string[]; readonly uncoveredHardBlockerDimensions: readonly string[]; readonly windowConflictClassifications: readonly InitialConstructionRepairWindowConflictClassification[]; readonly staticWindowConflictCount: number; readonly shiftableWindowConflictCount: number; readonly allHardBlockersCovered: boolean; readonly allHardBlockersRepairable: boolean; readonly uncoveredBlockerReasonCodes: readonly string[]; readonly uncoveredBlockerTaskIds: readonly number[]; readonly repairable: boolean; readonly evidenceComplete: boolean; readonly incompleteReasonCodes: readonly string[]; readonly fingerprint: string; readonly readOnly: true }

export interface InitialConstructionRepairEjectionSet { readonly ejectedTaskIds: readonly number[]; readonly repairDependencyClosureTaskIds: readonly number[]; readonly repairNeighborhoodTaskIds: readonly number[]; readonly repairNeighborhoodTopologicalTaskIds: readonly number[]; readonly repairNeighborhoodDependencyFingerprint: string; readonly candidateProfileFingerprint?: string | null; readonly causalTemporalCandidateFingerprint?: string | null; readonly effectiveStateFingerprint?: string | null; readonly targetProjection?: InitialConstructionRepairTargetProjection | null; readonly repairObjectiveFingerprint?: string | null; readonly supportingCandidateProfileFingerprints?: readonly string[]; readonly supportingTemporalCandidateFingerprints?: readonly string[]; readonly representativeCandidateRank?: number; readonly frontierSourceTaskIds?: readonly number[]; ejectionReasonByTaskId?: Readonly<Record<string,string[]>>; readonly coveredBlockerTaskIds?: readonly number[]; readonly uncoveredBlockerTaskIds?: readonly number[]; readonly coveredReasonCodes?: readonly string[]; readonly uncoveredReasonCodes?: readonly string[]; readonly allKnownCandidateBlockersCovered?: boolean; readonly executable?: boolean; readonly rejectionReason?: string | null; readonly combinatorialExpansionUsed?: false; readonly fingerprint: string; readonly readOnly: true }
export interface InitialConstructionRepairProblem {
  readonly residualFingerprint: string; readonly blockedAnchorTaskId: number; readonly blockedAnchorRank: number | null; readonly blockedAnchorClosureTaskIds: readonly number[];
  readonly directConflictTaskIds: readonly number[]; readonly dependencyConflictTaskIds: readonly number[]; readonly effectiveRepairRoots: readonly InitialConstructionEffectiveRepairRoot[]; readonly effectiveRepairRootCount: number; readonly equivalentRepairRootDedupCount: number; readonly staticHardBlockerProfileCount: number; readonly shiftableDependencyBoundProfileCount: number; readonly uncoveredHardBlockerProfileCount: number; readonly rootRejectedReasonCounts: Readonly<Record<string,number>>; readonly rootStaticWindowConflictCountsByAnchor: Readonly<Record<string,number>>; readonly rootShiftableWindowConflictCountsByAnchor: Readonly<Record<string,number>>; readonly repairCandidateProfiles: readonly InitialConstructionRepairCandidateProfile[]; readonly repairCandidateProfileCount: number; readonly repairableCandidateProfileCount: number; readonly unrepairableCandidateProfileCount: number; readonly candidateProfilesWithDependencyBoundBlockers: number; readonly repairCandidateProfilesFingerprint: string; readonly combinatorialExpansionUsed: false; readonly candidateEjectionSets: readonly InitialConstructionRepairEjectionSet[];
  readonly shiftableTargetProjectionCount:number; readonly executableTargetProjectionCount:number; readonly rejectedTargetProjectionCount:number; readonly projectedRepairRootCount:number; readonly projectionRejectedReasonCounts:Readonly<Record<string,number>>; readonly projectedRepairRootPortfolioFingerprint:string;
  readonly protectedTaskIds: readonly number[]; readonly immutableTaskIds: readonly number[]; readonly repairableConflictTaskIds: readonly number[]; readonly immutableConflictTaskIds: readonly number[]; readonly maximumEjectionDepth: number; readonly fingerprint: string; readonly readOnly: true;
}

export function resolveInitialConstructionImmutableTaskIds(args: { input: EngineInput; originOperationalState: OperationalState; protectedTaskIds?: readonly number[] }): number[] {
  const out = new Set<number>(args.protectedTaskIds ?? []);
  for (const t of args.input.tasks ?? []) if (["done", "in_progress"].includes(String((t as any).status))) out.add(Number((t as any).id));
  for (const l of (args.input as any).locks ?? []) out.add(Number(l.taskId ?? l.task_id ?? l.id));
  for (const p of args.originOperationalState.planning ?? []) out.add(Number((p as any).taskId));
  return uniq([...out]);
}

export function repairDependencyClosure(args: { input: EngineInput; seedTaskIds: readonly number[]; provisionalAssignmentTaskIds: readonly number[]; canonicalContext?: InitialConstructionCanonicalContext | null }): number[] {
  const graph = resolveInitialConstructionCanonicalContext({ input: args.input, canonicalContext: args.canonicalContext });
  const provisional = new Set(args.provisionalAssignmentTaskIds.map(Number));
  const closure = new Set(args.seedTaskIds.map(Number).filter((id)=>provisional.has(id)));
  let changed = true;
  while (changed) {
    changed = false;
    for (const taskId of [...closure]) {
      for (const dependent of graph.dependentsByTaskId.get(taskId) ?? []) {
        if (provisional.has(dependent) && !closure.has(dependent)) { closure.add(dependent); changed = true; }
      }
    }
  }
  return graph.topologicalTaskIds.filter((id) => closure.has(id));
}

const dim=(xs:number[], name:string)=>xs.length?[name]:[];
const mobileKinds=new Set(["assigned-prerequisite-end","assigned-dependent-start"]);
const clock=(value:unknown):number|null=>{ const m=String(value??"").match(/(?:T|^)(\d{1,2}):(\d{2})/); return m?Number(m[1])*60+Number(m[2]):null; };
const interval=(value:any):[string|null,string|null]=>{
  if(value && typeof value==="object") return [value.start??value.startPlanned??value.from??null,value.end??value.endPlanned??value.to??null].map(x=>x==null?null:String(x)) as any;
  const parts=String(value??"").split(/\s*(?:-|–|—|\.\.)\s*/); return parts.length>=2?[parts[0],parts[1]]:[null,null];
};
const normalizeFrontier=(source:any):InitialConstructionRepairFrontierSource=>deepFreeze({kind:String(source?.kind??""),taskId:normalizeOptionalTaskIds([source?.taskId])[0]??null,boundary:source?.boundary==null?null:String(source.boundary),time:source?.time==null?null:String(source.time),readOnly:source?.readOnly===true}) as any;

export function classifyInitialConstructionRepairWindowConflict(args:{detail:any; candidate:{startPlanned?:unknown;endPlanned?:unknown}; frontierSources:readonly InitialConstructionRepairFrontierSource[]; provisionalTaskIds:readonly number[]; immutableTaskIds:readonly number[]}):InitialConstructionRepairWindowConflictClassification {
  const d=args.detail??{}; const candidateStart=String(args.candidate.startPlanned??""); const candidateEnd=String(args.candidate.endPlanned??"");
  const [expectedStart,expectedEnd]=interval(d.expected??d.expectedWindow); const [actualStart,actualEnd]=interval(d.actual??d.actualWindow);
  const start=clock(actualStart)??clock(candidateStart); const end=clock(actualEnd)??clock(candidateEnd); const expectedStartClock=clock(expectedStart); const expectedEndClock=clock(expectedEnd);
  const violatedStart=expectedStartClock!=null && start!=null && start<expectedStartClock; const violatedEnd=expectedEndClock!=null && end!=null && end>expectedEndClock;
  const explicitBoundary=String(d.violatedBoundary??d.boundaryKind??"");
  const requiredShiftDirection=violatedStart&&violatedEnd?"both":violatedStart?"later":violatedEnd?"earlier":mobileKinds.has(explicitBoundary)?"earlier":null;
  const provisional=new Set(normalizeOptionalTaskIds(args.provisionalTaskIds)); const immutable=new Set(normalizeOptionalTaskIds(args.immutableTaskIds));
  const mobile=args.frontierSources.filter(s=>mobileKinds.has(s.kind) && s.taskId!=null && provisional.has(s.taskId));
  const matches=(source:InitialConstructionRepairFrontierSource)=>{
    const sourceClock=clock(source.time); if(sourceClock==null) return false;
    const boundary=String(source.boundary??"").toLowerCase(); const matchesEnd=boundary.includes("end") && sourceClock===clock(candidateEnd);
    const matchesStart=sourceClock===clock(candidateStart);
    if(requiredShiftDirection==="earlier") return matchesStart || matchesEnd;
    if(requiredShiftDirection==="later") return matchesStart || matchesEnd;
    return false;
  };
  let matchingMobileFrontierSources=mobile.filter(matches); let nonMatchingMobileFrontierSources=mobile.filter(s=>!matches(s));
  const explicitIds=normalizeOptionalTaskIds(d.dependencyBoundSourceTaskIds??[]);
  if(!matchingMobileFrontierSources.length&&mobileKinds.has(explicitBoundary)) { matchingMobileFrontierSources=mobile.filter(s=>s.taskId!=null&&explicitIds.includes(s.taskId)); nonMatchingMobileFrontierSources=mobile.filter(s=>!matchingMobileFrontierSources.includes(s)); }
  const causal=normalizeOptionalTaskIds(matchingMobileFrontierSources.map(s=>s.taskId)); const immutableIds=causal.filter(id=>immutable.has(id)); const reversible=causal.filter(id=>!immutable.has(id));
  const dependencyBoundShiftable=requiredShiftDirection!==null && requiredShiftDirection!=="both" && causal.length>0 && immutableIds.length===0;
  const kind=String(d.kind??d.reasonCode??d.code??d.type??"WINDOW_CONFLICT").toUpperCase(); const temporal=/AVAILABILITY|WORKDAY|FIXED_WINDOW|DURATION|EMPTY_WINDOW|PROTECTED/.test(kind);
  const violatedBoundary=violatedStart&&violatedEnd?"both":violatedStart?"start":violatedEnd?"end":String(d.violatedBoundary??"")||null;
  const covered=dependencyBoundShiftable; const staticConflict=temporal&&!covered; const uncoveredReasonCode=covered?null:(immutableIds.length?`${kind}_IMMUTABLE`:`${kind}_STATIC`);
  const causalLinkFingerprint=hash({kind,candidateStart,candidateEnd,expectedStart,expectedEnd,violatedStart,violatedEnd,requiredShiftDirection,matchingMobileFrontierSources});
  const base:any={kind,expected:d.expected??d.expectedWindow??null,actual:d.actual??d.actualWindow??null,violatedBoundary,candidateStart,candidateEnd,expectedStart,expectedEnd,violatedStart,violatedEnd,matchingMobileFrontierSources,nonMatchingMobileFrontierSources,requiredShiftDirection,causalSourceTaskIds:causal,reversibleSourceTaskIds:reversible,immutableSourceTaskIds:immutableIds,static:staticConflict,dependencyBoundShiftable,covered,uncoveredReasonCode,causalLinkFingerprint,fingerprint:"",readOnly:true};
  base.fingerprint=hash({...base,fingerprint:undefined}); return deepFreeze(base) as unknown as InitialConstructionRepairWindowConflictClassification;
}

export function profileFromAnchorPlacementEvidence(args:{ blockedAnchorTaskId:number; evidence:any; provisionalTaskIds: readonly number[]; immutableTaskIds: readonly number[] }): InitialConstructionRepairCandidateProfile {
  const ev=args.evidence??{}; const causal={...ev,...(ev.causalConflictEvidence??{})}; const provisional=new Set(normalizeOptionalTaskIds(args.provisionalTaskIds as any)); const immutable=new Set(normalizeOptionalTaskIds(args.immutableTaskIds as any));
  const frontierSources:InitialConstructionRepairFrontierSource[]=(Array.isArray(ev.frontierSources)?ev.frontierSources:[]).map(normalizeFrontier);
  const depSourceIds=normalizeOptionalTaskIds([...(ev.dependencyBoundSourceTaskIds??[]),...(causal.dependencyBoundSourceTaskIds??[]),...frontierSources.filter(s=>mobileKinds.has(s.kind)).map(s=>s.taskId)]).filter(id=>provisional.has(id));
  const contestant=normalizeOptionalTaskIds(causal.contestantConflictTaskIds).filter(id=>provisional.has(id));
  const space=normalizeOptionalTaskIds(causal.spaceConflictTaskIds).filter(id=>provisional.has(id));
  const resource=normalizeOptionalTaskIds(causal.resourceConflictTaskIds).filter(id=>provisional.has(id));
  const lower=normalizeOptionalTaskIds(causal.dependencyLowerBoundTaskIds).filter(id=>provisional.has(id));
  const upper=normalizeOptionalTaskIds(causal.dependencyUpperBoundTaskIds).filter(id=>provisional.has(id));
  const details=Array.isArray(causal.taskWindowConflictDetails)?causal.taskWindowConflictDetails:[];
  const windowConflictClassifications:InitialConstructionRepairWindowConflictClassification[]=details.map((detail:any)=>classifyInitialConstructionRepairWindowConflict({detail,candidate:ev,frontierSources,provisionalTaskIds:[...provisional],immutableTaskIds:[...immutable]})).sort((a:any,b:any)=>a.fingerprint.localeCompare(b.fingerprint));
  const shiftableIds=normalizeOptionalTaskIds(windowConflictClassifications.flatMap((c:any)=>c.reversibleSourceTaskIds as number[]));
  const detailIds=normalizeOptionalTaskIds(windowConflictClassifications.flatMap((c:any)=>c.causalSourceTaskIds as number[]));
  const direct=normalizeOptionalTaskIds([...(causal.causalConflictTaskIds??[]),...contestant,...space,...resource,...lower,...upper,...detailIds,...shiftableIds]).filter(id=>id!==Number(args.blockedAnchorTaskId));
  const repairableIds=direct.filter(id=>!immutable.has(id)); const immutableIds=direct.filter(id=>immutable.has(id));
  const reasons=[...(ev.reasonCodes??[]),...(causal.reasonCodes??[])].map(String).sort();
  const repairableReasonCodes=[...dim(contestant,"CONTESTANT_OVERLAP"),...dim(space,"SPACE_OVERLAP"),...dim(resource,"RESOURCE_OVERLAP"),...dim(lower,"DEPENDENCY_LOWER_BOUND"),...dim(upper,"DEPENDENCY_UPPER_BOUND"),...dim(shiftableIds,"DEPENDENCY_BOUND_FRONTIER")].sort();
  const hardBlockerDimensions=[...dim(contestant,"contestant"),...dim(space,"space"),...dim(resource,"resource"),...dim(lower,"dependency lower bound"),...dim(upper,"dependency upper bound"),...(causal.protectedIntervalConflictIds?.length?["protected interval"]:[])];
  for(const c of windowConflictClassifications){ const k=c.kind; if(k.includes("AVAILABILITY")) hardBlockerDimensions.push("availability"); else if(k.includes("WORKDAY")) hardBlockerDimensions.push("workday"); else if(k.includes("FIXED_WINDOW")) hardBlockerDimensions.push("fixed window"); else if(k.includes("PROTECTED")) hardBlockerDimensions.push("protected interval"); }
  const coveredHardBlockerDimensions=[...dim(contestant.filter(id=>!immutable.has(id)),"contestant"),...dim(space.filter(id=>!immutable.has(id)),"space"),...dim(resource.filter(id=>!immutable.has(id)),"resource"),...dim(lower.filter(id=>!immutable.has(id)),"dependency lower bound"),...dim(upper.filter(id=>!immutable.has(id)),"dependency upper bound")];
  for(const c of windowConflictClassifications.filter((c:any)=>c.covered)){ if(c.kind.includes("AVAILABILITY")) coveredHardBlockerDimensions.push("availability"); else if(c.kind.includes("WORKDAY")) coveredHardBlockerDimensions.push("workday"); else if(c.kind.includes("FIXED_WINDOW")) coveredHardBlockerDimensions.push("fixed window"); }
  const hard=Array.from(new Set(hardBlockerDimensions)).sort(); const coveredDims=Array.from(new Set(coveredHardBlockerDimensions)).filter(d=>hard.includes(d)).sort(); const uncoveredDims=hard.filter(d=>!coveredDims.includes(d));
  const staticUnrepairableReasonCodes=[...windowConflictClassifications.filter((c:any)=>c.static).map((c:any)=>c.uncoveredReasonCode??c.kind),...(direct.length===0?reasons.filter(r=>/WORKDAY|AVAILABILITY|FIXED_WINDOW|DURATION|PROTECTED/.test(r.toUpperCase())):[])].sort();
  const uncoveredBlockerTaskIds=immutableIds; const uncoveredBlockerReasonCodes=[...staticUnrepairableReasonCodes,...(immutableIds.length?["IMMUTABLE_BLOCKER"]:[]),...uncoveredDims.map(d=>`UNCOVERED_${d.toUpperCase().replaceAll(" ","_")}`)].sort();
  const hasTaskWindowConflict=reasons.some(r=>String(r).toUpperCase()==="TASK_WINDOW_CONFLICT")||details.length>0;
  const hasWindowExplanation=details.length===0||windowConflictClassifications.some((c:any)=>c.dependencyBoundShiftable||c.static||c.immutableSourceTaskIds.length>0)||immutableIds.length>0||staticUnrepairableReasonCodes.length>0||lower.length>0||upper.length>0;
  const unexplainedTaskWindowConflict=hasTaskWindowConflict&&!hasWindowExplanation&&direct.length===0;
  const incompleteReasonCodes=[...(causal.evidenceComplete===false?["SOURCE_EVIDENCE_INCOMPLETE"]:[]),...(unexplainedTaskWindowConflict?["TASK_WINDOW_CONFLICT_WITHOUT_EXPLANATION"]:[])].sort();
  const allHardBlockersCovered=(hard.length>0 ? uncoveredDims.length===0 : direct.length>0) && immutableIds.length===0 && staticUnrepairableReasonCodes.length===0 && !unexplainedTaskWindowConflict;
  const allHardBlockersRepairable=direct.length>0 && repairableIds.length===direct.length && allHardBlockersCovered;
  const mobileFrontierSources=frontierSources.filter(s=>mobileKinds.has(s.kind)); const staticFrontierSources=frontierSources.filter(s=>!mobileKinds.has(s.kind));
  const base:any={blockedAnchorTaskId:Number(args.blockedAnchorTaskId),temporalCandidateFingerprint:String(ev.temporalCandidateFingerprint??ev.fingerprint??hash({s:ev.startPlanned,e:ev.endPlanned,w:ev.windowIndex,r:ev.candidateRankWithinWindow})),windowIndex:Number(ev.windowIndex??0),candidateRank:Number(ev.candidateRankWithinWindow??ev.candidateRank??0),startPlanned:String(ev.startPlanned??""),endPlanned:String(ev.endPlanned??""),frontierSources,mobileFrontierSources,staticFrontierSources,effectiveMobileFrontierSourceTaskIds:normalizeOptionalTaskIds(windowConflictClassifications.flatMap(c=>c.causalSourceTaskIds as number[])),windowConflictCausalLinks:windowConflictClassifications,sourceKinds:[...(ev.sourceKinds??[]),...frontierSources.map((s:any)=>String(s.kind??""))].filter(Boolean).sort(),frontierSourceTaskIds:normalizeOptionalTaskIds([...(ev.frontierSourceTaskIds??[]),...frontierSources.map(s=>s.taskId)]),dependencyBoundSourceTaskIds:depSourceIds,reasonCodes:reasons,taskWindowConflictDetails:details,contestantConflictTaskIds:contestant,spaceConflictTaskIds:space,resourceConflictTaskIds:resource,dependencyLowerBoundTaskIds:lower,dependencyUpperBoundTaskIds:upper,protectedIntervalConflictIds:[...(causal.protectedIntervalConflictIds??[])].map(String).sort(),directCausalTaskIds:direct,repairableConflictTaskIds:repairableIds,immutableConflictTaskIds:immutableIds,staticUnrepairableReasonCodes,repairableReasonCodes,hardBlockerDimensions:hard,coveredHardBlockerDimensions:coveredDims,uncoveredHardBlockerDimensions:uncoveredDims,windowConflictClassifications,staticWindowConflictCount:windowConflictClassifications.filter((c:any)=>c.static).length,shiftableWindowConflictCount:windowConflictClassifications.filter((c:any)=>c.dependencyBoundShiftable).length,allHardBlockersCovered,allHardBlockersRepairable,uncoveredBlockerReasonCodes,uncoveredBlockerTaskIds,repairable:allHardBlockersRepairable,evidenceComplete:causal.evidenceComplete!==false&&incompleteReasonCodes.length===0,incompleteReasonCodes,fingerprint:"",readOnly:true};
  base.fingerprint=hash({...base,fingerprint:undefined}); return deepFreeze(base) as any;
}

const minuteText=(minutes:number):string=>`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;
const taskDuration=(task:any):number=>Number(task?.durationOverrideMin??task?.durationMin??task?.durationMinutes??task?.duration??0);
const feasibilityBlockers=(f:any):number[]=>uniq([...(f.contestantConflictTaskIds??[]),...(f.spaceConflictTaskIds??[]),...(f.resourceConflictTaskIds??[]),...(f.dependencyLowerBoundTaskIds??[]),...(f.dependencyUpperBoundTaskIds??[])]);

/** Projects a dependency-bound invalid candidate to its nearest valid temporal boundary.
 * Constraint truth remains owned by the normal placement-feasibility evaluator. */
export function projectInitialConstructionRepairTarget(args:{input:EngineInput; originOperationalState:OperationalState; canonicalContext?:InitialConstructionCanonicalContext|null; candidateProfile:InitialConstructionRepairCandidateProfile; blockedTask:any; provisionalAssignments:readonly CandidateAssignment[]; immutableTaskIds:readonly number[]}):InitialConstructionRepairTargetProjection|null {
  const profile=args.candidateProfile;
  const links=profile.windowConflictClassifications.filter(c=>c.dependencyBoundShiftable);
  if(!links.length || links.some(c=>c.requiredShiftDirection==="both"||c.requiredShiftDirection==null)) return null;
  const directions=uniqStrings(links.map(c=>String(c.requiredShiftDirection))); if(directions.length!==1) return null;
  const direction=directions[0] as "earlier"|"later";
  if(links.some(c=>c.kind.includes("FIXED_"))) return null;
  const duration=taskDuration(args.blockedTask); const originalStart=clock(profile.startPlanned), originalEnd=clock(profile.endPlanned);
  const boundaries=links.map(c=>clock(direction==="earlier"?c.expectedEnd:c.expectedStart)).filter((n):n is number=>n!=null);
  if(duration<=0||originalStart==null||originalEnd==null||!boundaries.length) return null;
  const boundary=direction==="earlier"?Math.min(...boundaries):Math.max(...boundaries);
  const projectedStart=direction==="earlier"?boundary-duration:boundary; const projectedEnd=projectedStart+duration;
  if(projectedStart<0||projectedEnd>24*60) return null;
  const mobileSourceTaskIds=uniq(links.flatMap(c=>c.reversibleSourceTaskIds as number[]));
  const originalCandidateConflictTaskIds=uniq([...profile.contestantConflictTaskIds,...profile.spaceConflictTaskIds,...profile.resourceConflictTaskIds,...profile.dependencyLowerBoundTaskIds,...profile.dependencyUpperBoundTaskIds]);
  const removed=new Set([Number(args.blockedTask.id),...mobileSourceTaskIds]);
  const occupied=args.provisionalAssignments.filter(a=>!removed.has(Number(a.taskId))) as CandidateAssignment[];
  const tasks=new Map((args.input.tasks??[]).map((t:any)=>[Number(t.id),t])) as any;
  const assignment:any={taskId:Number(args.blockedTask.id),startPlanned:minuteText(projectedStart),endPlanned:minuteText(projectedEnd),spaceId:args.blockedTask.spaceId??null,resourceIds:[...(args.blockedTask.resourceIds??args.blockedTask.requiredResourceIds??[])]};
  const first=evaluateInitialConstructionPlacementFeasibility({input:args.input,originOperationalState:args.originOperationalState,task:args.blockedTask,assignment,occupiedAssignments:occupied,tasks,canonicalContext:args.canonicalContext});
  const projectedBlockers=feasibilityBlockers(first); const immutable=new Set(args.immutableTaskIds.map(Number));
  const immutableBlockers=projectedBlockers.filter(id=>immutable.has(id));
  const reversibleBlockers=projectedBlockers.filter(id=>!immutable.has(id)&&args.provisionalAssignments.some(a=>Number(a.taskId)===id));
  const staticWindow=first.taskWindowConflictDetails.filter(d=>!["DEPENDENCY_LOWER_BOUND","DEPENDENCY_UPPER_BOUND"].includes(d.kind));
  const seed=new Set([...mobileSourceTaskIds,...reversibleBlockers]);
  const secondOccupied=args.provisionalAssignments.filter(a=>!seed.has(Number(a.taskId))&&Number(a.taskId)!==Number(args.blockedTask.id)) as CandidateAssignment[];
  const second=evaluateInitialConstructionPlacementFeasibility({input:args.input,originOperationalState:args.originOperationalState,task:args.blockedTask,assignment,occupiedAssignments:secondOccupied,tasks,canonicalContext:args.canonicalContext});
  const remaining=feasibilityBlockers(second).filter(id=>!mobileSourceTaskIds.includes(id));
  const projectedTargetValidAfterEjection=remaining.length===0&&second.protectedIntervalConflictIds.length===0&&second.taskWindowConflictDetails.every(d=>["DEPENDENCY_LOWER_BOUND","DEPENDENCY_UPPER_BOUND"].includes(d.kind)&&mobileSourceTaskIds.some(id=>d.conflictTaskIds.includes(id)));
  const executable=immutableBlockers.length===0&&first.protectedIntervalConflictIds.length===0&&staticWindow.length===0&&projectedBlockers.length===reversibleBlockers.length&&projectedTargetValidAfterEjection;
  const rejectionReason=executable?null:immutableBlockers.length?"IMMUTABLE_PROJECTED_BLOCKER":first.protectedIntervalConflictIds.length?"PROTECTED_PROJECTED_INTERVAL":staticWindow.length?"PROJECTED_TARGET_OUTSIDE_WINDOW":"PROJECTED_TARGET_NOT_CLEAR_AFTER_EJECTION";
  const base:any={blockedAnchorTaskId:Number(args.blockedTask.id),candidateProfileFingerprint:profile.fingerprint,originalStart:profile.startPlanned,originalEnd:profile.endPlanned,projectedStart:assignment.startPlanned,projectedEnd:assignment.endPlanned,requiredShiftDirection:direction,requiredShiftMinutes:Math.abs(projectedStart-originalStart),violatedBoundary:direction==="earlier"?"end":"start",mobileSourceTaskIds,mobileSourceBoundaryRequirements:links.map(c=>({kind:c.kind,boundary:c.violatedBoundary,expectedStart:c.expectedStart,expectedEnd:c.expectedEnd,sourceTaskIds:c.causalSourceTaskIds})),originalCandidateConflictTaskIds,projectedTargetBlockerTaskIds:reversibleBlockers,projectedTargetImmutableBlockerTaskIds:immutableBlockers,obsoleteOriginalCandidateBlockerTaskIds:originalCandidateConflictTaskIds.filter(id=>!projectedBlockers.includes(id)),projectedPlacementReasonCodes:first.reasonCodes,projectedWindowConflictDetails:first.taskWindowConflictDetails,projectedTargetValidAfterEjection,dependencySourcePendingReconstruction:mobileSourceTaskIds.length>0,executable,rejectionReason,fingerprint:"",readOnly:true};
  base.fingerprint=hash({...base,fingerprint:undefined}); return deepFreeze(base) as InitialConstructionRepairTargetProjection;
}

export function buildInitialConstructionRepairProblem(args: { input: EngineInput; originOperationalState: OperationalState; residualFingerprint: string; blockedAnchorTaskId: number; blockedAnchorRank?: number | null; blockedAnchorClosureTaskIds?: readonly number[]; productiveTaskIds?:readonly number[]; residualProductiveTaskIds?:readonly number[]; terminalEvidence?: any; repairCandidateProfiles?: readonly InitialConstructionRepairCandidateProfile[]; provisionalAssignments: readonly CandidateAssignment[]; protectedTaskIds?: readonly number[]; maxEjectedAssignments?: number; maxRepairNeighborhoodTasks?: number; canonicalContext?: InitialConstructionCanonicalContext | null }): InitialConstructionRepairProblem {
  const canonicalContext = resolveInitialConstructionCanonicalContext({ input: args.input, canonicalContext: args.canonicalContext });
  const maxDepth = args.maxEjectedAssignments ?? 4; const maxNeighborhood = args.maxRepairNeighborhoodTasks ?? 12;
  const provisionalIds = uniq(args.provisionalAssignments.map(a=>Number(a.taskId))); const immutable = resolveInitialConstructionImmutableTaskIds(args); const immutableSet = new Set(immutable);
  const ev = args.terminalEvidence ?? {}; const details = Array.isArray(ev.taskWindowConflictDetails) ? ev.taskWindowConflictDetails : [];
  const direct = uniq([...(ev.causalConflictTaskIds ?? []), ...(ev.contestantConflictTaskIds ?? []), ...(ev.spaceConflictTaskIds ?? []), ...(ev.resourceConflictTaskIds ?? []), ...(ev.dependencyBoundSourceTaskIds ?? []), ...details.flatMap((d:any)=>[...(d.conflictTaskIds ?? []), ...(d.dependencyBoundSourceTaskIds ?? []), d.taskId].filter((id:any)=>Number(id)!==Number(args.blockedAnchorTaskId)))]).filter((id)=>provisionalIds.includes(Number(id)) && !immutableSet.has(Number(id)));
  const dep = uniq([...(ev.dependencyLowerBoundTaskIds ?? []), ...(ev.dependencyUpperBoundTaskIds ?? []), ...(ev.dependencyBoundSourceTaskIds ?? [])]).filter((id)=>provisionalIds.includes(id) && !immutableSet.has(id));
  const immutableConflicts = uniq([...(ev.causalConflictTaskIds ?? []), ...(ev.contestantConflictTaskIds ?? []), ...(ev.spaceConflictTaskIds ?? []), ...(ev.resourceConflictTaskIds ?? []), ...(ev.dependencyLowerBoundTaskIds ?? []), ...(ev.dependencyUpperBoundTaskIds ?? [])].map(Number).filter((id)=>provisionalIds.includes(id) && immutableSet.has(id)));
  const fallbackProfile = profileFromAnchorPlacementEvidence({blockedAnchorTaskId:Number(args.blockedAnchorTaskId), evidence:{...ev,temporalCandidateFingerprint:hash({anchor:args.blockedAnchorTaskId,ev}),causalConflictEvidence:{...ev,causalConflictTaskIds:[...direct,...dep,...immutableConflicts],evidenceComplete:ev.causalConflictEvidenceComplete!==false}}, provisionalTaskIds:provisionalIds, immutableTaskIds:immutable});
  const sessionRequiresProfiles = ev.requireCandidateScopedProfiles===true;
  const profiles = [...(args.repairCandidateProfiles?.length ? args.repairCandidateProfiles : (sessionRequiresProfiles ? [] : [fallbackProfile]))].sort((a,b)=>a.candidateRank-b.candidateRank||a.fingerprint.localeCompare(b.fingerprint));
  const effectiveByKey=new Map<string, any>(); const targetProjections:InitialConstructionRepairTargetProjection[]=[]; let executableCandidateProfileCount=0;
  for (const profile of profiles) {
    const blockedTask=(args.input.tasks??[]).find((t:any)=>Number(t.id)===Number(args.blockedAnchorTaskId));
    const targetProjection=profile.shiftableWindowConflictCount>0&&blockedTask?projectInitialConstructionRepairTarget({input:args.input,originOperationalState:args.originOperationalState,canonicalContext,candidateProfile:profile,blockedTask,provisionalAssignments:args.provisionalAssignments,immutableTaskIds:immutable}):null;
    if(targetProjection) targetProjections.push(targetProjection);
    if(targetProjection&&!targetProjection.executable) continue;
    if (!targetProjection&&(!profile.repairable || !profile.allHardBlockersRepairable)) continue;
    const seed=targetProjection?uniq([...targetProjection.mobileSourceTaskIds,...targetProjection.projectedTargetBlockerTaskIds]):uniq(profile.repairableConflictTaskIds.map(Number).filter((id)=>provisionalIds.includes(id)&&!immutableSet.has(id)));
    if (!seed.length || seed.length>maxDepth) continue;
    const closure=repairDependencyClosure({input:args.input,seedTaskIds:seed,provisionalAssignmentTaskIds:provisionalIds,canonicalContext});
    const neighborhood=uniq([Number(args.blockedAnchorTaskId),...(args.blockedAnchorClosureTaskIds??[]),...closure]);
    if(!closure.length||neighborhood.length>maxNeighborhood||closure.some(id=>immutableSet.has(id))) continue;
    executableCandidateProfileCount++;
    const neighborhoodTopo=canonicalContext.topologicalTaskIds.filter(id=>neighborhood.includes(id));
    const depFp=hash({edges:(canonicalContext.dependencyGraph.edges??[]).filter((e:any)=>neighborhood.includes(e.fromTaskId)&&neighborhood.includes(e.toTaskId))});
    const repairObjectiveFingerprint=targetProjection?hash({projection:targetProjection.fingerprint,direction:targetProjection.requiredShiftDirection,target:[targetProjection.projectedStart,targetProjection.projectedEnd]}):null;
    const effectiveStateFingerprint=hash({base:args.residualFingerprint,anchor:args.blockedAnchorTaskId,ejectedTaskIds:seed,closure,neighborhood,repairObjectiveFingerprint});
    const key=stableStringify({base:args.residualFingerprint,anchor:args.blockedAnchorTaskId,ejectedTaskIds:seed,closure,neighborhood}); const existing=effectiveByKey.get(key);
    if(existing){ existing.supportingCandidateProfileFingerprints=uniqStrings([...existing.supportingCandidateProfileFingerprints,profile.fingerprint]); existing.supportingTemporalCandidateFingerprints=uniqStrings([...existing.supportingTemporalCandidateFingerprints,profile.temporalCandidateFingerprint]); if(profile.candidateRank<existing.representativeCandidateRank){existing.representativeCandidateProfileFingerprint=profile.fingerprint;existing.representativeCandidateRank=profile.candidateRank;} continue; }
    const productive=new Set(normalizeOptionalTaskIds(args.productiveTaskIds??args.residualProductiveTaskIds??[])); const residualProductive=new Set(normalizeOptionalTaskIds(args.residualProductiveTaskIds??[]));
    const productiveClosureTaskIds=closure.filter(id=>productive.has(id)); const residualProductiveClosureTaskIds=uniq([Number(args.blockedAnchorTaskId),...(args.blockedAnchorClosureTaskIds??[])]).filter(id=>residualProductive.has(id));
    effectiveByKey.set(key,{blockedAnchorTaskId:Number(args.blockedAnchorTaskId),blockedAnchorRank:args.blockedAnchorRank??null,ejectedTaskIds:seed,repairDependencyClosureTaskIds:closure,repairNeighborhoodTaskIds:neighborhood,repairNeighborhoodTopologicalTaskIds:neighborhoodTopo,repairNeighborhoodDependencyFingerprint:depFp,supportingCandidateProfileFingerprints:[profile.fingerprint],supportingTemporalCandidateFingerprints:[profile.temporalCandidateFingerprint],representativeCandidateProfileFingerprint:profile.fingerprint,representativeCandidateRank:profile.candidateRank,productiveClosureTaskIds,productiveClosureTaskCount:productiveClosureTaskIds.length,residualProductiveClosureTaskIds,residualProductiveClosureTaskCount:residualProductiveClosureTaskIds.length,allHardBlockersCovered:targetProjection?.executable??profile.allHardBlockersCovered,targetProjection,projectedTargetStart:targetProjection?.projectedStart??null,projectedTargetEnd:targetProjection?.projectedEnd??null,requiredShiftDirection:targetProjection?.requiredShiftDirection??null,requiredShiftMinutes:targetProjection?.requiredShiftMinutes??0,mobileSourceTaskIds:targetProjection?.mobileSourceTaskIds??[],projectedTargetBlockerTaskIds:targetProjection?.projectedTargetBlockerTaskIds??[],obsoleteOriginalCandidateBlockerTaskIds:targetProjection?.obsoleteOriginalCandidateBlockerTaskIds??[],projectedTargetValidAfterEjection:targetProjection?.projectedTargetValidAfterEjection??false,repairObjectiveFingerprint,effectiveStateFingerprint,readOnly:true});
  }
  const effectiveRepairRoots=[...effectiveByKey.values()];
  effectiveRepairRoots.sort((a,b)=>Number(b.allHardBlockersCovered)-Number(a.allHardBlockersCovered)||b.residualProductiveClosureTaskCount-a.residualProductiveClosureTaskCount||a.representativeCandidateRank-b.representativeCandidateRank||a.ejectedTaskIds.length-b.ejectedTaskIds.length||a.repairNeighborhoodTaskIds.length-b.repairNeighborhoodTaskIds.length||a.effectiveStateFingerprint.localeCompare(b.effectiveStateFingerprint));
  const candidateEjectionSets:InitialConstructionRepairEjectionSet[]=effectiveRepairRoots.map(root=>({ejectedTaskIds:root.ejectedTaskIds,repairDependencyClosureTaskIds:root.repairDependencyClosureTaskIds,repairNeighborhoodTaskIds:root.repairNeighborhoodTaskIds,repairNeighborhoodTopologicalTaskIds:root.repairNeighborhoodTopologicalTaskIds,repairNeighborhoodDependencyFingerprint:root.repairNeighborhoodDependencyFingerprint,candidateProfileFingerprint:root.representativeCandidateProfileFingerprint,causalTemporalCandidateFingerprint:root.supportingTemporalCandidateFingerprints[0]??null,effectiveStateFingerprint:root.effectiveStateFingerprint,targetProjection:root.targetProjection,repairObjectiveFingerprint:root.repairObjectiveFingerprint,supportingCandidateProfileFingerprints:root.supportingCandidateProfileFingerprints,supportingTemporalCandidateFingerprints:root.supportingTemporalCandidateFingerprints,representativeCandidateRank:root.representativeCandidateRank,frontierSourceTaskIds:root.mobileSourceTaskIds,ejectionReasonByTaskId:Object.fromEntries(root.ejectedTaskIds.map((id:number)=>[String(id),root.mobileSourceTaskIds.includes(id)?["MOBILE_DEPENDENCY_FRONTIER"]:["PROJECTED_TARGET_BLOCKER"]])),coveredBlockerTaskIds:root.ejectedTaskIds,uncoveredBlockerTaskIds:[],coveredReasonCodes:root.targetProjection?["VALID_BOUNDARY_PROJECTION"]:["CAUSAL_CONFLICT"],uncoveredReasonCodes:[],allKnownCandidateBlockersCovered:true,executable:true,rejectionReason:null,combinatorialExpansionUsed:false,fingerprint:root.effectiveStateFingerprint,readOnly:true}));
  const related=uniq([...direct,...dep,...profiles.flatMap(p=>p.repairableConflictTaskIds as number[])]);
  const profilesFp=hash(profiles.map(p=>p.fingerprint)); const payload = { residualFingerprint: args.residualFingerprint, blockedAnchorTaskId: Number(args.blockedAnchorTaskId), profiles: profiles.map(p=>p.fingerprint), sets: candidateEjectionSets.map(s=>({e:s.ejectedTaskIds,c:s.repairDependencyClosureTaskIds,p:s.candidateProfileFingerprint})) };
  const rootRejectedReasonCounts:Record<string,number>={}; for(const p of profiles.filter(p=>!p.repairable)) for(const r of p.uncoveredBlockerReasonCodes.length?p.uncoveredBlockerReasonCodes:["UNREPAIRABLE_PROFILE"]) rootRejectedReasonCounts[r]=(rootRejectedReasonCounts[r]??0)+1;
  const projectionRejectedReasonCounts:Record<string,number>={}; for(const p of targetProjections.filter(p=>!p.executable)) projectionRejectedReasonCounts[p.rejectionReason??"UNKNOWN"]=(projectionRejectedReasonCounts[p.rejectionReason??"UNKNOWN"]??0)+1;
  return deepFreeze({ shiftableTargetProjectionCount:targetProjections.length, executableTargetProjectionCount:targetProjections.filter(p=>p.executable).length, rejectedTargetProjectionCount:targetProjections.filter(p=>!p.executable).length, projectedRepairRootCount:effectiveRepairRoots.filter(r=>r.targetProjection).length, projectionRejectedReasonCounts, projectedRepairRootPortfolioFingerprint:hash(effectiveRepairRoots.filter(r=>r.targetProjection).map(r=>r.repairObjectiveFingerprint)), residualFingerprint: args.residualFingerprint, blockedAnchorTaskId: Number(args.blockedAnchorTaskId), blockedAnchorRank: args.blockedAnchorRank ?? null, blockedAnchorClosureTaskIds: uniq(args.blockedAnchorClosureTaskIds ?? [Number(args.blockedAnchorTaskId)]), directConflictTaskIds: direct, dependencyConflictTaskIds: dep, effectiveRepairRoots, effectiveRepairRootCount: effectiveRepairRoots.length, executableCandidateProfileCount, equivalentRepairRootDedupCount: Math.max(0,executableCandidateProfileCount-effectiveRepairRoots.length), staticHardBlockerProfileCount: profiles.filter(p=>p.staticWindowConflictCount>0).length, shiftableDependencyBoundProfileCount: profiles.filter(p=>p.shiftableWindowConflictCount>0).length, uncoveredHardBlockerProfileCount: profiles.filter(p=>p.uncoveredHardBlockerDimensions.length>0 || p.uncoveredBlockerReasonCodes.length>0).length, rootRejectedReasonCounts, rootStaticWindowConflictCountsByAnchor: {[String(args.blockedAnchorTaskId)]: profiles.reduce((n,p)=>n+p.staticWindowConflictCount,0)}, rootShiftableWindowConflictCountsByAnchor: {[String(args.blockedAnchorTaskId)]: profiles.reduce((n,p)=>n+p.shiftableWindowConflictCount,0)}, repairCandidateProfiles: profiles, repairCandidateProfileCount: profiles.length, repairableCandidateProfileCount: profiles.filter(p=>p.repairable).length, unrepairableCandidateProfileCount: profiles.filter(p=>!p.repairable).length, candidateProfilesWithDependencyBoundBlockers: profiles.filter(p=>p.dependencyBoundSourceTaskIds.length>0).length, repairCandidateProfilesFingerprint: profilesFp, combinatorialExpansionUsed:false, candidateEjectionSets, protectedTaskIds: uniq(args.protectedTaskIds ?? []), immutableTaskIds: immutable, repairableConflictTaskIds: related, immutableConflictTaskIds: immutableConflicts, maximumEjectionDepth: maxDepth, fingerprint: hash(payload), readOnly: true });
}
