import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import type { InitialConstructionCausalBranchAttempt } from "./initialConstructionCausalBranchOutcomeLedger";

const hash=(x:unknown)=>createHash("sha256").update(stableStringify(x)).digest("hex");

export type InitialConstructionCausalAlternativeActivationSource="SUSPENDED_FRONTIER"|"GENERATED_GRAPH"|"CAUSAL_ARCHIVE"|"CHECKPOINT_REOPEN";
export type InitialConstructionCausalAlternativeActivationStatus="ACTIVATION_PREPARED"|"NO_ELIGIBLE_CANDIDATE";
export type InitialConstructionCausalAlternativeActivationSkipReason="CANDIDATE_ALREADY_ACTIVE"|"CANDIDATE_ALREADY_RESOLVED"|"CANDIDATE_EXHAUSTED_FOR_CONFLICT"|"CANDIDATE_NOT_CAUSALLY_USEFUL"|"CANDIDATE_ALREADY_EXPANDED"|"CANDIDATE_CURSOR_ALREADY_INSPECTED"|"CANDIDATE_NO_GOOD"|"CANDIDATE_HARD_INVALID"|"CANDIDATE_FUTURE_INFEASIBLE"|"CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE"|"LEDGER_CAPACITY_REACHED";

export interface InitialConstructionActivationPartialPlan { readonly partialPlanId:string; readonly assignmentsFingerprint:string; readonly status?:string|null; readonly readOnly?:true }
export interface InitialConstructionCausalBranchOpenInput { readonly conflictFingerprint:string; readonly conflictFamilyFingerprint:string; readonly frontierTaskId:number|null; readonly blockingTaskIds:readonly number[]; readonly checkpointFingerprint:string; readonly checkpointParentPartialPlanId:string; readonly checkpointParentAssignmentsFingerprint:string; readonly causalDecisionId:string; readonly causalDecisionDepth:number; readonly selectedPartialPlanId:string; readonly selectedAssignmentsFingerprint:string; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly activationOrdinal:number; readonly baselineProductiveAssignmentCount:number; readonly baselineResidualProductiveTaskCount:number; readonly baselineMaximumProductiveAssignmentCountObserved:number; readonly activatedAtExpansionWorkUnit:number }
export interface InitialConstructionCausalBranchOpenResult { readonly opened:boolean; readonly attempt:InitialConstructionCausalBranchAttempt|null; readonly reason?:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"|"LEDGER_CAPACITY_REACHED"|string }
export interface InitialConstructionCausalBranchActivationLedger { open(input:InitialConstructionCausalBranchOpenInput):InitialConstructionCausalBranchOpenResult; isBranchExhausted?(input:{conflictFingerprint:string;checkpointFingerprint:string;causalDecisionId:string;checkpointBranchFingerprint:string;checkpointBranchAssignmentsFingerprint:string}):boolean }
export interface InitialConstructionCausalAlternativeActivationCandidate { readonly source:InitialConstructionCausalAlternativeActivationSource; readonly partialPlan:InitialConstructionActivationPartialPlan; readonly sourceEntryFingerprint:string; readonly sourceOrdinal:number; readonly sourceRank:number; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly causalEvaluationFingerprint:string; readonly operationalComparatorFingerprint:string; readonly causallyUseful:boolean; readonly hardInvalid?:boolean; readonly futureInfeasible?:boolean; readonly inCheckpointSubtree:boolean; readonly readOnly:true }
export interface InitialConstructionCausalAlternativeActivationResult { readonly status:InitialConstructionCausalAlternativeActivationStatus; readonly selectedCandidate:InitialConstructionCausalAlternativeActivationCandidate|null; readonly openedAttempt:InitialConstructionCausalBranchAttempt|null; readonly openedAttemptId:string|null; readonly sourceMutation:{readonly source:InitialConstructionCausalAlternativeActivationSource;readonly selectedEntryFingerprint:string;readonly commitRequired:true}|null; readonly backtrackConsumed:false; readonly transitionConsumed:false; readonly inspectedCandidateCount:number; readonly eligibleCandidateCount:number; readonly skippedCandidateCount:number; readonly skipReasonCounts:Readonly<Record<InitialConstructionCausalAlternativeActivationSkipReason,number>>; readonly skippedCandidateSamples:readonly unknown[]; readonly fingerprint:string; readonly readOnly:true }

const inc=(m:Record<InitialConstructionCausalAlternativeActivationSkipReason,number>,k:InitialConstructionCausalAlternativeActivationSkipReason)=>{m[k]=(m[k]??0)+1;};
const freezeResult=(payload:Omit<InitialConstructionCausalAlternativeActivationResult,"fingerprint"|"readOnly">):InitialConstructionCausalAlternativeActivationResult=>deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as InitialConstructionCausalAlternativeActivationResult;

export function prepareInitialConstructionCausalAlternativeActivation(args:{readonly candidates:readonly InitialConstructionCausalAlternativeActivationCandidate[]; readonly ledger:InitialConstructionCausalBranchActivationLedger; readonly openInputForCandidate:(candidate:InitialConstructionCausalAlternativeActivationCandidate)=>InitialConstructionCausalBranchOpenInput; readonly expandedAssignmentsFingerprints?:ReadonlySet<string>; readonly cursorInspectedBranchFingerprints?:ReadonlySet<string>; readonly noGoodBranchFingerprints?:ReadonlySet<string>; readonly maxSamples?:number}):InitialConstructionCausalAlternativeActivationResult{
 const skipReasonCounts={} as Record<InitialConstructionCausalAlternativeActivationSkipReason,number>; const samples:unknown[]=[]; const maxSamples=Math.max(0,args.maxSamples??10); let inspected=0, skipped=0, eligible=0;
 const addSkip=(candidate:InitialConstructionCausalAlternativeActivationCandidate,reason:InitialConstructionCausalAlternativeActivationSkipReason)=>{skipped++; inc(skipReasonCounts,reason); if(samples.length<maxSamples)samples.push(deepFreeze({source:candidate.source,partialPlanId:candidate.partialPlan.partialPlanId,assignmentsFingerprint:candidate.partialPlan.assignmentsFingerprint,branchFingerprint:candidate.checkpointBranchFingerprint,reason,readOnly:true}));};
 const ordered=[...args.candidates].sort((a,b)=>a.sourceRank-b.sourceRank||a.sourceOrdinal-b.sourceOrdinal||a.operationalComparatorFingerprint.localeCompare(b.operationalComparatorFingerprint)||a.sourceEntryFingerprint.localeCompare(b.sourceEntryFingerprint));
 for(const candidate of ordered){inspected++;
  if(!candidate.inCheckpointSubtree){addSkip(candidate,"CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE"); continue;}
  if(candidate.hardInvalid){addSkip(candidate,"CANDIDATE_HARD_INVALID"); continue;}
  if(candidate.futureInfeasible){addSkip(candidate,"CANDIDATE_FUTURE_INFEASIBLE"); continue;}
  if(args.expandedAssignmentsFingerprints?.has(candidate.partialPlan.assignmentsFingerprint)){addSkip(candidate,"CANDIDATE_ALREADY_EXPANDED"); continue;}
  if(args.cursorInspectedBranchFingerprints?.has(candidate.checkpointBranchFingerprint)){addSkip(candidate,"CANDIDATE_CURSOR_ALREADY_INSPECTED"); continue;}
  if(args.noGoodBranchFingerprints?.has(candidate.checkpointBranchFingerprint)||args.noGoodBranchFingerprints?.has(candidate.checkpointBranchAssignmentsFingerprint)){addSkip(candidate,"CANDIDATE_NO_GOOD"); continue;}
  if(!candidate.causallyUseful){addSkip(candidate,"CANDIDATE_NOT_CAUSALLY_USEFUL"); continue;}
  if(args.ledger.isBranchExhausted?.({conflictFingerprint:args.openInputForCandidate(candidate).conflictFingerprint,checkpointFingerprint:args.openInputForCandidate(candidate).checkpointFingerprint,causalDecisionId:args.openInputForCandidate(candidate).causalDecisionId,checkpointBranchFingerprint:candidate.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:candidate.checkpointBranchAssignmentsFingerprint})){addSkip(candidate,"CANDIDATE_EXHAUSTED_FOR_CONFLICT"); continue;}
  eligible++; const opened=args.ledger.open(args.openInputForCandidate(candidate));
  if(opened.opened&&opened.attempt){return freezeResult({status:"ACTIVATION_PREPARED",selectedCandidate:candidate,openedAttempt:opened.attempt,openedAttemptId:opened.attempt.attemptId,sourceMutation:{source:candidate.source,selectedEntryFingerprint:candidate.sourceEntryFingerprint,commitRequired:true},backtrackConsumed:false,transitionConsumed:false,inspectedCandidateCount:inspected,eligibleCandidateCount:eligible,skippedCandidateCount:skipped,skipReasonCounts,skippedCandidateSamples:samples});}
  addSkip(candidate,opened.reason==="LEDGER_CAPACITY_REACHED"?"LEDGER_CAPACITY_REACHED":opened.attempt?.status&&opened.attempt.status!=="ACTIVE"?"CANDIDATE_ALREADY_RESOLVED":"CANDIDATE_ALREADY_ACTIVE");
 }
 return freezeResult({status:"NO_ELIGIBLE_CANDIDATE",selectedCandidate:null,openedAttempt:null,openedAttemptId:null,sourceMutation:null,backtrackConsumed:false,transitionConsumed:false,inspectedCandidateCount:inspected,eligibleCandidateCount:eligible,skippedCandidateCount:skipped,skipReasonCounts,skippedCandidateSamples:samples});
}
