import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
const arr=(x:any)=>[...(x??[])];
export type InitialConstructionCausalBranchAttemptStatus="ACTIVE"|"RESOLVED_BLOCKED_FRONTIER"|"ADVANCED_TO_DIFFERENT_CONFLICT"|"REPEATED_SAME_CONFLICT"|"PROGRESSED_BUT_REPEATED_SAME_CONFLICT"|"HARD_INVALID"|"FUTURE_INFEASIBLE"|"COMPLETE"|"BUDGET_INTERRUPTED";
export interface InitialConstructionCausalBranchAttempt { readonly attemptId:string; readonly conflictFingerprint:string; readonly conflictFamilyFingerprint:string; readonly frontierTaskId:number|null; readonly blockingTaskIds:readonly number[]; readonly checkpointFingerprint:string; readonly checkpointParentPartialPlanId:string; readonly checkpointParentAssignmentsFingerprint:string; readonly causalDecisionId:string; readonly causalDecisionDepth:number; readonly selectedPartialPlanId:string; readonly selectedAssignmentsFingerprint:string; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly activationOrdinal:number; readonly baselineProductiveAssignmentCount:number; readonly baselineResidualProductiveTaskCount:number; readonly baselineMaximumProductiveAssignmentCountObserved:number; readonly status:InitialConstructionCausalBranchAttemptStatus; readonly resultingConflictFingerprint:string|null; readonly resultingFrontierTaskId:number|null; readonly maximumProductiveAssignmentCountObserved:number; readonly minimumResidualProductiveTaskCountObserved:number; readonly blockedFrontierTaskBecameAssigned:boolean; readonly durableProductiveProgressObserved:boolean; readonly activatedAtExpansionWorkUnit:number; readonly resolvedAtExpansionWorkUnit:number|null; readonly outcomeFingerprint:string|null; readonly fingerprint:string; readonly readOnly:true }
export const causalBranchAttemptKey=(x:{conflictFingerprint:string;checkpointFingerprint:string;causalDecisionId:string;checkpointBranchFingerprint:string;checkpointBranchAssignmentsFingerprint:string})=>hash({conflictFingerprint:x.conflictFingerprint,checkpointFingerprint:x.checkpointFingerprint,causalDecisionId:x.causalDecisionId,checkpointBranchFingerprint:x.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:x.checkpointBranchAssignmentsFingerprint});
function freezeAttempt(a:any):InitialConstructionCausalBranchAttempt{const outcome=a.status==="ACTIVE"?null:hash({attemptId:a.attemptId,status:a.status,resultingConflictFingerprint:a.resultingConflictFingerprint,resultingFrontierTaskId:a.resultingFrontierTaskId,maximumProductiveAssignmentCountObserved:a.maximumProductiveAssignmentCountObserved,minimumResidualProductiveTaskCountObserved:a.minimumResidualProductiveTaskCountObserved,blockedFrontierTaskBecameAssigned:a.blockedFrontierTaskBecameAssigned,durableProductiveProgressObserved:a.durableProductiveProgressObserved}); return deepFreeze({...a,outcomeFingerprint:outcome,fingerprint:hash({...a,outcomeFingerprint:outcome,readOnly:true}),readOnly:true}) as any;}
export function createInitialConstructionCausalBranchOutcomeLedger(maxEntries:number){const attempts=new Map<string,InitialConstructionCausalBranchAttempt>(); const active=new Map<string,string>(); const exhausted=new Set<string>(); const noGoods=new Map<string,any>(); let duplicateOpen=0; const samples:any[]=[];
 const open=(input:any)=>{const attemptId=causalBranchAttemptKey(input); if(attempts.has(attemptId)||active.has(attemptId)){duplicateOpen++; return {opened:false,attempt:attempts.get(attemptId)??null,reason:"DUPLICATE_CAUSAL_BRANCH_ATTEMPT"};} if(attempts.size>=maxEntries) return {opened:false,attempt:null,reason:"LEDGER_CAPACITY_REACHED"}; const attempt=freezeAttempt({...input,attemptId,status:"ACTIVE",resultingConflictFingerprint:null,resultingFrontierTaskId:null,maximumProductiveAssignmentCountObserved:input.baselineProductiveAssignmentCount,minimumResidualProductiveTaskCountObserved:input.baselineResidualProductiveTaskCount,blockedFrontierTaskBecameAssigned:false,durableProductiveProgressObserved:false,resolvedAtExpansionWorkUnit:null}); attempts.set(attemptId,attempt); active.set(attemptId,attemptId); if(samples.length<10)samples.push(attempt); return {opened:true,attempt}; };
 const isExhausting=(s:string)=>s==="REPEATED_SAME_CONFLICT"||s==="PROGRESSED_BUT_REPEATED_SAME_CONFLICT";
 const resolve=(attemptId:string,input:any)=>{const prev=attempts.get(attemptId); if(!prev||prev.status!=="ACTIVE") return {resolved:false,attempt:prev??null}; const max=Math.max(prev.maximumProductiveAssignmentCountObserved,Number(input.maximumProductiveAssignmentCountObserved??prev.maximumProductiveAssignmentCountObserved)); const min=Math.min(prev.minimumResidualProductiveTaskCountObserved,Number(input.minimumResidualProductiveTaskCountObserved??prev.minimumResidualProductiveTaskCountObserved)); const progressed=max>prev.baselineMaximumProductiveAssignmentCountObserved||max>prev.baselineProductiveAssignmentCount; const status=input.status==="REPEATED_SAME_CONFLICT"&&progressed?"PROGRESSED_BUT_REPEATED_SAME_CONFLICT":input.status; const next=freezeAttempt({...prev,status,resultingConflictFingerprint:input.resultingConflictFingerprint??null,resultingFrontierTaskId:input.resultingFrontierTaskId??null,maximumProductiveAssignmentCountObserved:max,minimumResidualProductiveTaskCountObserved:min,blockedFrontierTaskBecameAssigned:Boolean(input.blockedFrontierTaskBecameAssigned),durableProductiveProgressObserved:progressed,resolvedAtExpansionWorkUnit:Number(input.resolvedAtExpansionWorkUnit??prev.activatedAtExpansionWorkUnit)}); attempts.set(attemptId,next); active.delete(attemptId); if(isExhausting(status)){exhausted.add(attemptId); noGoods.set(attemptId,deepFreeze({conflictFingerprint:next.conflictFingerprint,checkpointFingerprint:next.checkpointFingerprint,causalDecisionId:next.causalDecisionId,checkpointBranchFingerprint:next.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:next.checkpointBranchAssignmentsFingerprint,status,productiveProgress:max-prev.baselineProductiveAssignmentCount,fingerprint:hash({attemptId,status}),readOnly:true}));} return {resolved:true,attempt:next}; };
 const isBranchExhausted=(input:any)=>exhausted.has(causalBranchAttemptKey(input));
 const summary=()=>{const values=[...attempts.values()].sort((a,b)=>a.attemptId.localeCompare(b.attemptId)); const count=(s:string)=>values.filter(a=>a.status===s).length; const progress=values.map(a=>Math.max(0,a.maximumProductiveAssignmentCountObserved-a.baselineProductiveAssignmentCount)); return deepFreeze({causalBranchAttemptOpenedCount:values.length,causalBranchAttemptResolvedCount:values.filter(a=>a.status!=="ACTIVE").length,causalBranchAttemptActiveAtEndCount:values.filter(a=>a.status==="ACTIVE").length,causalBranchAttemptDuplicateOpenPreventedCount:duplicateOpen,causalBranchOutcomeLedgerEntryCount:values.length,causalBranchResolvedBlockedFrontierCount:count("RESOLVED_BLOCKED_FRONTIER"),causalBranchAdvancedToDifferentConflictCount:count("ADVANCED_TO_DIFFERENT_CONFLICT"),causalBranchRepeatedSameConflictCount:count("REPEATED_SAME_CONFLICT"),causalBranchProgressedButRepeatedSameConflictCount:count("PROGRESSED_BUT_REPEATED_SAME_CONFLICT"),causalBranchHardInvalidOutcomeCount:count("HARD_INVALID"),causalBranchFutureInfeasibleOutcomeCount:count("FUTURE_INFEASIBLE"),causalBranchCompleteOutcomeCount:count("COMPLETE"),causalBranchBudgetInterruptedOutcomeCount:count("BUDGET_INTERRUPTED"),causalBranchNoGoodRegisteredCount:noGoods.size,causalAttemptMaximumProductiveProgress:progress.length?Math.max(...progress):0,causalAttemptAverageProductiveProgress:progress.length?Number((progress.reduce((a,b)=>a+b,0)/progress.length).toFixed(6)):0,causalBranchAttemptSamples:samples,causalBranchOutcomeSamples:values.slice(0,10),causalBranchNoGoodSamples:[...noGoods.values()].slice(0,10),causalBranchLedgerFingerprint:hash(values.map(a=>a.fingerprint)),readOnly:true}) as any;};
 const closeActiveAsBudgetInterrupted=(work:number)=>{for(const id of [...active.keys()])resolve(id,{status:"BUDGET_INTERRUPTED",resolvedAtExpansionWorkUnit:work});};
 return {open,resolve,isBranchExhausted,closeActiveAsBudgetInterrupted,summary,get attempts(){return attempts;},get noGoods(){return noGoods;}};
}
