import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
export type InitialConstructionCausalAlternativeActivationSource="SUSPENDED_FRONTIER"|"GENERATED_GRAPH"|"CAUSAL_ARCHIVE"|"CHECKPOINT_REOPEN";
export interface InitialConstructionCausalAlternativeActivationCandidate { readonly source:InitialConstructionCausalAlternativeActivationSource; readonly partialPlan:any; readonly sourceEntryFingerprint:string; readonly sourceOrdinal:number; readonly checkpointBranchPartialPlanId:string; readonly checkpointBranchFingerprint:string; readonly checkpointBranchAssignmentsFingerprint:string; readonly causalEvaluationFingerprint:string; readonly operationalComparatorFingerprint:string; readonly readOnly:true }
export interface InitialConstructionCausalAlternativeActivationResult { readonly status:string; readonly selectedCandidate:InitialConstructionCausalAlternativeActivationCandidate|null; readonly openedAttemptId:string|null; readonly sourceMutation:{source:string;selectedEntryFingerprint:string;commitRequired:true}|null; readonly backtrackConsumed:boolean; readonly transitionConsumed:boolean; readonly inspectedCandidateCount:number; readonly skippedCandidateCount:number; readonly skipReasonCounts:Readonly<Record<string,number>>; readonly skippedCandidateSamples:readonly unknown[]; readonly fingerprint:string; readonly readOnly:true }
export function prepareInitialConstructionCausalAlternativeActivation(args:{candidates:readonly InitialConstructionCausalAlternativeActivationCandidate[]; ledger:any; openInputForCandidate:(candidate:InitialConstructionCausalAlternativeActivationCandidate)=>any; expandedAssignmentsFingerprints?:ReadonlySet<string>; cursorInspectedBranchFingerprints?:ReadonlySet<string>}):InitialConstructionCausalAlternativeActivationResult{const skip:Record<string,number>={}; const samples:any[]=[]; let inspected=0; const add=(c:any,r:string)=>{skip[r]=(skip[r]??0)+1; if(samples.length<10)samples.push({source:c.source,partialPlanId:c.partialPlan?.partialPlanId??null,branchFingerprint:c.checkpointBranchFingerprint,reason:r,readOnly:true});}; for(const c of [...args.candidates].sort((a,b)=>a.sourceOrdinal-b.sourceOrdinal||a.source.localeCompare(b.source)||a.sourceEntryFingerprint.localeCompare(b.sourceEntryFingerprint))){inspected++; if(args.expandedAssignmentsFingerprints?.has(String(c.partialPlan?.assignmentsFingerprint))){add(c,"CANDIDATE_ALREADY_EXPANDED"); continue;} if(args.cursorInspectedBranchFingerprints?.has(String(c.checkpointBranchFingerprint))){add(c,"CANDIDATE_CURSOR_ALREADY_INSPECTED"); continue;} const opened=args.ledger.open(args.openInputForCandidate(c)); if(opened?.opened&&opened.attempt){const payload={status:"ACTIVATION_COMMITTED",selectedCandidate:c,openedAttemptId:opened.attempt.attemptId,sourceMutation:{source:c.source,selectedEntryFingerprint:c.sourceEntryFingerprint,commitRequired:true},backtrackConsumed:true,transitionConsumed:true,inspectedCandidateCount:inspected,skippedCandidateCount:samples.length,skipReasonCounts:skip,skippedCandidateSamples:samples,readOnly:true}; return deepFreeze({...payload,fingerprint:hash(payload)}) as any;} add(c,opened?.reason==="LEDGER_CAPACITY_REACHED"?"LEDGER_CAPACITY_REACHED":"CANDIDATE_ALREADY_ACTIVE");}
 const payload={status:"NO_ELIGIBLE_CANDIDATE",selectedCandidate:null,openedAttemptId:null,sourceMutation:null,backtrackConsumed:false,transitionConsumed:false,inspectedCandidateCount:inspected,skippedCandidateCount:samples.length,skipReasonCounts:skip,skippedCandidateSamples:samples,readOnly:true}; return deepFreeze({...payload,fingerprint:hash(payload)}) as any;}
