import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
const uniq=(xs:readonly string[])=>[...new Set(xs.filter(Boolean).map(String))].sort();

export interface InitialConstructionCausalCheckpointCursor { readonly cursorKey:string; readonly conflictFingerprint:string; readonly checkpointFingerprint:string; readonly causalDecisionId:string; readonly observedDecisionBranchFingerprints:readonly string[]; readonly inspectedDecisionBranchFingerprints:readonly string[]; readonly activatedDecisionBranchFingerprints:readonly string[]; readonly exhaustedDecisionBranchFingerprints:readonly string[]; readonly observedChildAssignmentsFingerprints:readonly string[]; readonly inspectedChildAssignmentsFingerprints:readonly string[]; readonly evaluatedTemporalCandidateFingerprints:readonly string[]; readonly hardInvalidCandidateFingerprints:readonly string[]; readonly futureInfeasibleCandidateFingerprints:readonly string[]; readonly buildOrdinal:number; readonly advanceOrdinal:number; readonly exhausted:boolean; readonly exhaustionReason:string|null; readonly fingerprint:string; readonly readOnly:true }
export const initialConstructionCausalCheckpointCursorKey=(input:{conflictFingerprint:string;checkpointFingerprint:string;causalDecisionId:string})=>hash({conflictFingerprint:input.conflictFingerprint,checkpointFingerprint:input.checkpointFingerprint,causalDecisionId:input.causalDecisionId});
function make(p:any):InitialConstructionCausalCheckpointCursor{const payload={...p,observedDecisionBranchFingerprints:uniq(p.observedDecisionBranchFingerprints??[]),inspectedDecisionBranchFingerprints:uniq(p.inspectedDecisionBranchFingerprints??[]),activatedDecisionBranchFingerprints:uniq(p.activatedDecisionBranchFingerprints??[]),exhaustedDecisionBranchFingerprints:uniq(p.exhaustedDecisionBranchFingerprints??[]),observedChildAssignmentsFingerprints:uniq(p.observedChildAssignmentsFingerprints??[]),inspectedChildAssignmentsFingerprints:uniq(p.inspectedChildAssignmentsFingerprints??[]),evaluatedTemporalCandidateFingerprints:uniq(p.evaluatedTemporalCandidateFingerprints??[]),hardInvalidCandidateFingerprints:uniq(p.hardInvalidCandidateFingerprints??[]),futureInfeasibleCandidateFingerprints:uniq(p.futureInfeasibleCandidateFingerprints??[]),exhausted:Boolean(p.exhausted),exhaustionReason:p.exhaustionReason??null,readOnly:true}; return deepFreeze({...payload,fingerprint:hash({...payload,readOnly:undefined})}) as any;}
export function buildInitialConstructionCausalCheckpointCursor(input:{conflictFingerprint:string;checkpointFingerprint:string;causalDecisionId:string; buildOrdinal:number; observedDecisionBranchFingerprints?:readonly string[]; observedChildAssignmentsFingerprints?:readonly string[]}):InitialConstructionCausalCheckpointCursor{return make({cursorKey:initialConstructionCausalCheckpointCursorKey(input),conflictFingerprint:input.conflictFingerprint,checkpointFingerprint:input.checkpointFingerprint,causalDecisionId:String(input.causalDecisionId),observedDecisionBranchFingerprints:input.observedDecisionBranchFingerprints??[],observedChildAssignmentsFingerprints:input.observedChildAssignmentsFingerprints??[],inspectedDecisionBranchFingerprints:[],activatedDecisionBranchFingerprints:[],exhaustedDecisionBranchFingerprints:[],inspectedChildAssignmentsFingerprints:[],evaluatedTemporalCandidateFingerprints:[],hardInvalidCandidateFingerprints:[],futureInfeasibleCandidateFingerprints:[],buildOrdinal:input.buildOrdinal,advanceOrdinal:0});}
export function advanceInitialConstructionCausalCheckpointCursor(cursor:InitialConstructionCausalCheckpointCursor,input:{observedDecisionBranchFingerprints?:readonly string[]; inspectedDecisionBranchFingerprints?:readonly string[]; activatedDecisionBranchFingerprints?:readonly string[]; exhaustedDecisionBranchFingerprints?:readonly string[]; observedChildAssignmentsFingerprints?:readonly string[]; inspectedChildAssignmentsFingerprints?:readonly string[]; evaluatedTemporalCandidateFingerprints?:readonly string[]; hardInvalidCandidateFingerprints?:readonly string[]; futureInfeasibleCandidateFingerprints?:readonly string[]; exhausted?:boolean; exhaustionReason?:string|null;}):InitialConstructionCausalCheckpointCursor{return make({...cursor,observedDecisionBranchFingerprints:[...cursor.observedDecisionBranchFingerprints,...(input.observedDecisionBranchFingerprints??[])],inspectedDecisionBranchFingerprints:[...cursor.inspectedDecisionBranchFingerprints,...(input.inspectedDecisionBranchFingerprints??[])],activatedDecisionBranchFingerprints:[...cursor.activatedDecisionBranchFingerprints,...(input.activatedDecisionBranchFingerprints??[])],exhaustedDecisionBranchFingerprints:[...cursor.exhaustedDecisionBranchFingerprints,...(input.exhaustedDecisionBranchFingerprints??[])],observedChildAssignmentsFingerprints:[...cursor.observedChildAssignmentsFingerprints,...(input.observedChildAssignmentsFingerprints??[])],inspectedChildAssignmentsFingerprints:[...cursor.inspectedChildAssignmentsFingerprints,...(input.inspectedChildAssignmentsFingerprints??[])],evaluatedTemporalCandidateFingerprints:[...cursor.evaluatedTemporalCandidateFingerprints,...(input.evaluatedTemporalCandidateFingerprints??[])],hardInvalidCandidateFingerprints:[...cursor.hardInvalidCandidateFingerprints,...(input.hardInvalidCandidateFingerprints??[])],futureInfeasibleCandidateFingerprints:[...cursor.futureInfeasibleCandidateFingerprints,...(input.futureInfeasibleCandidateFingerprints??[])],advanceOrdinal:cursor.advanceOrdinal+1,exhausted:input.exhausted??cursor.exhausted,exhaustionReason:input.exhaustionReason??cursor.exhaustionReason});}
