import test from "node:test";
import assert from "node:assert/strict";
import { prepareInitialConstructionCausalAlternativeActivation, collectInitialConstructionCausalAlternativeActivationCandidates, type InitialConstructionCausalAlternativeActivationCandidate, type InitialConstructionCausalBranchOpenInput } from "./initialConstructionCausalAlternativeActivation";
const cand=(id:string,ord:number,extra:Partial<InitialConstructionCausalAlternativeActivationCandidate>={}):InitialConstructionCausalAlternativeActivationCandidate=>({source:"SUSPENDED_FRONTIER",partialPlan:{partialPlanId:id,assignmentsFingerprint:`afp:${id}`,readOnly:true},sourceEntryFingerprint:`entry:${id}`,sourceOrdinal:ord,sourceRank:0,checkpointBranchPartialPlanId:`bp:${id}`,checkpointBranchFingerprint:`bf:${id}`,checkpointBranchAssignmentsFingerprint:`bafp:${id}`,causalEvaluationFingerprint:`cef:${id}`,operationalComparatorFingerprint:`of:${id}`,causallyUseful:true,inCheckpointSubtree:true,readOnly:true,...extra});
const openInput=(c:InitialConstructionCausalAlternativeActivationCandidate):InitialConstructionCausalBranchOpenInput=>({conflictFingerprint:"conflict",conflictFamilyFingerprint:"family",frontierTaskId:1,blockingTaskIds:[2],checkpointFingerprint:"checkpoint",checkpointParentPartialPlanId:"parent",checkpointParentAssignmentsFingerprint:"parent-afp",causalDecisionId:"decision",causalDecisionDepth:1,selectedPartialPlanId:c.partialPlan.partialPlanId,selectedAssignmentsFingerprint:c.partialPlan.assignmentsFingerprint,checkpointBranchPartialPlanId:c.checkpointBranchPartialPlanId,checkpointBranchFingerprint:c.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:c.checkpointBranchAssignmentsFingerprint,activationOrdinal:1,baselineProductiveAssignmentCount:1,baselineResidualProductiveTaskCount:1,baselineMaximumProductiveAssignmentCountObserved:1,activatedAtExpansionWorkUnit:1});
const sum=(r:Readonly<Record<string,number>>)=>Object.values(r).reduce((a,b)=>a+Number(b),0);

test("ID 321 duplicate activation candidate is skipped without consuming transition and next candidate prepares",()=>{const ledger={open:(input:InitialConstructionCausalBranchOpenInput)=>input.selectedPartialPlanId==="B"?{opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"}:{opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}}}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("B",0),cand("C",1)],ledger,openInputForCandidate:openInput}); assert.equal(r.status,"ACTIVATION_PREPARED"); assert.equal(r.selectedCandidate?.partialPlan.partialPlanId,"C"); assert.equal(r.openedAttemptId,"attempt:C"); assert.equal(r.backtrackConsumed,false); assert.equal(r.transitionConsumed,false); assert.equal(r.skippedCandidateCount,1); assert.equal(r.skipReasonCounts.CANDIDATE_ALREADY_ACTIVE,1);});

test("ID 321 all candidates rejected leaves no source mutation backtrack or transition",()=>{const ledger={open:()=>({opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"})}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("B",0)],ledger,openInputForCandidate:openInput}); assert.equal(r.status,"NO_ELIGIBLE_CANDIDATE"); assert.equal(r.sourceMutation,null); assert.equal(r.backtrackConsumed,false); assert.equal(r.transitionConsumed,false);});

test("ID 321 skip counters are independent from bounded samples",()=>{const ledger={open:()=>({opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"})}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:Array.from({length:25},(_,i)=>cand(`B${i}`,i)),ledger,openInputForCandidate:openInput,maxSamples:10}); assert.equal(r.skippedCandidateCount,25); assert.equal(r.skippedCandidateSamples.length,10); assert.equal(sum(r.skipReasonCounts),25);});

test("ID 321 filters expanded cursor and no-good candidates before ledger",()=>{let opens=0; const ledger={open:()=>{opens++; return {opened:true,attempt:{attemptId:"x",status:"ACTIVE" as const}};}}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("expanded",0),cand("cursor",1),cand("nogood",2)],ledger,openInputForCandidate:openInput,expandedAssignmentsFingerprints:new Set(["afp:expanded"]),cursorInspectedBranchFingerprints:new Set(["bf:cursor"]),noGoodBranchFingerprints:new Set(["bf:nogood"])}); assert.equal(r.status,"NO_ELIGIBLE_CANDIDATE"); assert.equal(opens,0); assert.equal(r.skipReasonCounts.CANDIDATE_ALREADY_EXPANDED,1); assert.equal(r.skipReasonCounts.CANDIDATE_CURSOR_ALREADY_INSPECTED,1); assert.equal(r.skipReasonCounts.CANDIDATE_NO_GOOD,1); assert.equal(sum(r.skipReasonCounts),r.skippedCandidateCount);});

test("ID 321 rejects non-causal and non-checkpoint candidates without opening ledger",()=>{let opens=0; const ledger={open:()=>{opens++; return {opened:true,attempt:{attemptId:"x",status:"ACTIVE" as const}};}}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("outside",0,{inCheckpointSubtree:false}),cand("noncausal",1,{causallyUseful:false})],ledger,openInputForCandidate:openInput}); assert.equal(r.status,"NO_ELIGIBLE_CANDIDATE"); assert.equal(opens,0); assert.equal(r.skipReasonCounts.CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE,1); assert.equal(r.skipReasonCounts.CANDIDATE_NOT_CAUSALLY_USEFUL,1);});

test("ID 321 ordering is deterministic with ordinal as final tie breaker",()=>{const prepared:string[]=[]; const ledger={open:(input:InitialConstructionCausalBranchOpenInput)=>{prepared.push(input.selectedPartialPlanId); return {opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}};}}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("later",2,{operationalComparatorFingerprint:"same"}),cand("first",1,{operationalComparatorFingerprint:"same"})],ledger,openInputForCandidate:openInput}); assert.equal(r.selectedCandidate?.partialPlan.partialPlanId,"first"); assert.deepEqual(prepared,["first"]);});

test("ID 321 preparation does not declare commit",()=>{const ledger={open:(input:InitialConstructionCausalBranchOpenInput)=>({opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}})}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("C",0)],ledger,openInputForCandidate:openInput}); assert.equal(r.status,"ACTIVATION_PREPARED"); assert.equal(r.backtrackConsumed,false); assert.equal(r.transitionConsumed,false); assert.equal(r.sourceMutation?.commitRequired,true);});

const env=(id:string,source:any,rank:number,extra:any={})=>({source,partialPlan:{partialPlanId:id,assignmentsFingerprint:`afp:${id}`,readOnly:true},sourceEntryFingerprint:`entry:${source}:${id}`,sourceEntryId:`${source}:${id}`,checkpointBranchPartialPlanId:`bp:${id}`,checkpointBranchFingerprint:`bf:${id}`,checkpointBranchAssignmentsFingerprint:`bafp:${id}`,causalEvaluationFingerprint:`cef:${id}`,causallyUseful:true,blockersRemovedCount:0,blockersModifiedCount:0,backjumpDistance:0,operationalRank:rank,deterministicSourceOrdinal:rank,inCheckpointSubtree:true,alreadyExpanded:false,hardInvalid:false,futureInfeasible:false,readOnly:true,...extra});

test("ID 321 collection chooses better generated graph candidate over physical frontier order",()=>{const collection=collectInitialConstructionCausalAlternativeActivationCandidates([env("frontier","SUSPENDED_FRONTIER",10),env("graph","GENERATED_GRAPH",1,{blockersRemovedCount:1})]); assert.equal(collection.candidates[0].partialPlan.partialPlanId,"graph"); assert.equal(collection.collectedBySource.SUSPENDED_FRONTIER,1); assert.equal(collection.collectedBySource.GENERATED_GRAPH,1);});

test("ID 321 collection deduplicates cross-source candidates with source precedence",()=>{const collection=collectInitialConstructionCausalAlternativeActivationCandidates([env("same","CAUSAL_ARCHIVE",3),env("same","GENERATED_GRAPH",2),env("same","SUSPENDED_FRONTIER",1)]); assert.equal(collection.candidates.length,1); assert.equal(collection.candidates[0].source,"SUSPENDED_FRONTIER"); assert.equal(collection.deduplicationCount,2); assert.equal(collection.crossSourceDuplicateCount,2);});

test("ID 321 helper prepares C from graph after B duplicate in frontier",()=>{const collection=collectInitialConstructionCausalAlternativeActivationCandidates([env("B","SUSPENDED_FRONTIER",0,{blockersRemovedCount:2}),env("C","GENERATED_GRAPH",1,{blockersRemovedCount:1})]); const ledger={open:(input:InitialConstructionCausalBranchOpenInput)=>input.selectedPartialPlanId==="B"?{opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"}:{opened:true,attempt:{attemptId:`attempt:${input.selectedPartialPlanId}`,status:"ACTIVE" as const}}}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:collection.candidates,ledger,openInputForCandidate:openInput}); assert.equal(r.status,"ACTIVATION_PREPARED"); assert.equal(r.selectedCandidate?.partialPlan.partialPlanId,"C"); assert.equal(r.selectedCandidate?.source,"GENERATED_GRAPH"); assert.equal(r.inspectedCandidateCount,2); assert.equal(r.skippedCandidateCount,1);});

test("ID 321 collection preserves explicit checkpoint reopen source",()=>{const collection=collectInitialConstructionCausalAlternativeActivationCandidates([env("D","CHECKPOINT_REOPEN",0)]); assert.equal(collection.candidates[0].source,"CHECKPOINT_REOPEN");});

test("ID 321 collection is deterministic under physical source order changes",()=>{const a=collectInitialConstructionCausalAlternativeActivationCandidates([env("A","CAUSAL_ARCHIVE",3),env("B","SUSPENDED_FRONTIER",2),env("C","GENERATED_GRAPH",1)]); const b=collectInitialConstructionCausalAlternativeActivationCandidates([env("C","GENERATED_GRAPH",1),env("A","CAUSAL_ARCHIVE",3),env("B","SUSPENDED_FRONTIER",2)]); assert.equal(a.fingerprint,b.fingerprint); assert.deepEqual(a.candidates.map(c=>c.partialPlan.partialPlanId),b.candidates.map(c=>c.partialPlan.partialPlanId));});

test("ID 321 already expanded candidate remains in subtree but skips as already expanded",()=>{let opens=0; const ledger={open:()=>{opens++; return {opened:true,attempt:{attemptId:"x",status:"ACTIVE" as const}};}}; const collection=collectInitialConstructionCausalAlternativeActivationCandidates([env("expanded","GENERATED_GRAPH",0,{alreadyExpanded:true,inCheckpointSubtree:true})]); const r=prepareInitialConstructionCausalAlternativeActivation({candidates:collection.candidates,ledger,openInputForCandidate:openInput}); assert.equal(r.status,"NO_ELIGIBLE_CANDIDATE"); assert.equal(r.skipReasonCounts.CANDIDATE_ALREADY_EXPANDED,1); assert.equal(r.skipReasonCounts.CANDIDATE_NOT_IN_CHECKPOINT_SUBTREE??0,0); assert.equal(opens,0);});

test("ID 321 open input is built once for each inspected candidate",()=>{let inputCalls=0; const ledger={isBranchExhausted:()=>false,open:()=>({opened:false,attempt:null,reason:"CAUSAL_BRANCH_ATTEMPT_ALREADY_RESOLVED_OR_ACTIVE"})}; const r=prepareInitialConstructionCausalAlternativeActivation({candidates:[cand("B",0),cand("C",1)],ledger,openInputForCandidate:(candidate)=>{inputCalls++; return openInput(candidate);}}); assert.equal(r.inspectedCandidateCount,2); assert.equal(inputCalls,2);});
