import { createHash } from "node:crypto";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { evaluateInitialConstructionCausalAlternative } from "./conflictDirectedInitialConstructionBackjump";
import { resolveInitialConstructionCheckpointBranch } from "./initialConstructionCausalDecisionCheckpoint";
import { advanceInitialConstructionCausalCheckpointCursor, type InitialConstructionCausalCheckpointCursor } from "./initialConstructionCausalCheckpointCursor";
import { collectInitialConstructionCausalAlternativeActivationCandidates, prepareInitialConstructionCausalAlternativeActivation, type InitialConstructionCausalAlternativeActivationCandidate, type InitialConstructionCausalAlternativeActivationSource, type InitialConstructionCausalAlternativeActivationResult, type InitialConstructionCausalBranchActivationLedger, type InitialConstructionCausalBranchOpenInput, type InitialConstructionCausalAlternativeCandidateCollection, type InitialConstructionCausalAlternativeCandidateEnvelopeInput } from "./initialConstructionCausalAlternativeActivation";
import { compareInitialConstructionPartialPlanResults } from "./initialConstructionSuspendedFrontier";

const hash=(x:unknown)=>createHash("sha256").update(stableStringify(x)).digest("hex");
const sourceOrder:InitialConstructionCausalAlternativeActivationSource[]=["SUSPENDED_FRONTIER","GENERATED_GRAPH","CAUSAL_ARCHIVE","CHECKPOINT_REOPEN"];

type SourceInput={readonly source:InitialConstructionCausalAlternativeActivationSource; readonly partialPlan:Record<string,unknown>; readonly sourceEntryFingerprint:string; readonly sourceEntryId:string|null};
export interface InitialConstructionCausalActivationTransactionInput { readonly conflict:Record<string,unknown>; readonly failedPartialPlan:Record<string,unknown>; readonly checkpoint:Record<string,unknown>; readonly partialPlanGraphIndex:unknown; readonly suspendedFrontier:{readonly entries:readonly Record<string,unknown>[]}; readonly graphNodes:readonly Record<string,unknown>[]; readonly causalArchive:readonly Record<string,unknown>[]; readonly reopenCandidates?:readonly Record<string,unknown>[]; readonly cursor:InitialConstructionCausalCheckpointCursor; readonly ledger:InitialConstructionCausalBranchActivationLedger; readonly expandedAssignmentsFingerprints:ReadonlySet<string>; readonly nogoodFingerprints:ReadonlySet<string>; readonly activationOrdinal:number; readonly baselineProductiveAssignmentCount:number; readonly baselineResidualProductiveTaskCount:number; readonly baselineMaximumProductiveAssignmentCountObserved:number; readonly expansionWorkUnitCount:number; readonly readOnly:true }
export interface InitialConstructionCausalActivationTransactionResult { readonly status:"ACTIVATION_PREPARED"|"NO_EXISTING_CAUSAL_CANDIDATE"|"CHECKPOINT_NOT_RESOLVED"|"INCOMPLETE_CAUSAL_EVIDENCE"; readonly preparedActivation:InitialConstructionCausalAlternativeActivationResult|null; readonly selectedCandidate:InitialConstructionCausalAlternativeActivationCandidate|null; readonly candidateCollection:InitialConstructionCausalAlternativeCandidateCollection; readonly updatedCursor:InitialConstructionCausalCheckpointCursor; readonly sourceCommit:{readonly source:InitialConstructionCausalAlternativeActivationSource; readonly sourceEntryFingerprint:string; readonly sourceEntryId:string|null}|null; readonly transactionEvidence:Record<string,unknown>; readonly fingerprint:string; readonly readOnly:true }

const pp=(entry:Record<string,unknown>)=>(entry.partialPlan&&typeof entry.partialPlan==="object"?entry.partialPlan:entry) as Record<string,unknown>;
const sourceInputs=(args:InitialConstructionCausalActivationTransactionInput):SourceInput[]=>[
 ...[...(args.suspendedFrontier.entries??[])].map((entry)=>({source:"SUSPENDED_FRONTIER" as const,partialPlan:pp(entry),sourceEntryFingerprint:String(entry.assignmentsFingerprint??pp(entry).assignmentsFingerprint??""),sourceEntryId:String(entry.partialPlanId??pp(entry).partialPlanId??entry.assignmentsFingerprint??"")})),
 ...[...(args.graphNodes??[])].map((node)=>({source:"GENERATED_GRAPH" as const,partialPlan:node,sourceEntryFingerprint:String(node.assignmentsFingerprint??""),sourceEntryId:String(node.partialPlanId??node.assignmentsFingerprint??"")})),
 ...[...(args.causalArchive??[])].map((node)=>({source:"CAUSAL_ARCHIVE" as const,partialPlan:node,sourceEntryFingerprint:String(node.assignmentsFingerprint??""),sourceEntryId:String(node.partialPlanId??node.assignmentsFingerprint??"")})),
 ...[...(args.reopenCandidates??[])].map((node)=>({source:"CHECKPOINT_REOPEN" as const,partialPlan:node,sourceEntryFingerprint:String(node.assignmentsFingerprint??""),sourceEntryId:String(node.partialPlanId??node.assignmentsFingerprint??"")})),
];

export function prepareInitialConstructionCausalActivationTransaction(args:InitialConstructionCausalActivationTransactionInput):InitialConstructionCausalActivationTransactionResult{
 const transactionId=hash({conflictFingerprint:args.conflict.fingerprint,checkpointFingerprint:args.checkpoint.fingerprint,causalDecisionId:args.checkpoint.causalDecisionId,activationOrdinal:args.activationOrdinal});
 const ranked=new Map<string,number>(); [...sourceInputs(args)].map(x=>x.partialPlan).sort(compareInitialConstructionPartialPlanResults).forEach((plan,index)=>ranked.set(String(plan.assignmentsFingerprint),index));
 const envelopes:InitialConstructionCausalAlternativeCandidateEnvelopeInput[]=[];
 for(const input of sourceInputs(args).sort((a,b)=>sourceOrder.indexOf(a.source)-sourceOrder.indexOf(b.source)||String(a.partialPlan.partialPlanId).localeCompare(String(b.partialPlan.partialPlanId))||String(a.partialPlan.assignmentsFingerprint).localeCompare(String(b.partialPlan.assignmentsFingerprint)))){
  if(String(input.partialPlan.partialPlanId)===String(args.failedPartialPlan.partialPlanId)) continue;
  const branch=resolveInitialConstructionCheckpointBranch({checkpoint:args.checkpoint,partialPlan:input.partialPlan,partialPlanGraphIndex:args.partialPlanGraphIndex as any});
  const evaluation=evaluateInitialConstructionCausalAlternative({conflict:args.conflict,failedPartialPlan:args.failedPartialPlan,alternative:input.partialPlan,nogoodFingerprints:args.nogoodFingerprints});
  envelopes.push({source:input.source,partialPlan:{...input.partialPlan,partialPlanId:String(input.partialPlan.partialPlanId),assignmentsFingerprint:String(input.partialPlan.assignmentsFingerprint),status:String(input.partialPlan.status??""),readOnly:true},sourceEntryFingerprint:input.sourceEntryFingerprint,sourceEntryId:input.sourceEntryId,checkpointBranchPartialPlanId:String(branch?.checkpointBranchPartialPlanId??input.partialPlan.partialPlanId??""),checkpointBranchFingerprint:String(branch?.decisionBranchFingerprint??input.partialPlan.decisionBranchFingerprint??""),checkpointBranchAssignmentsFingerprint:String(branch?.checkpointBranchAssignmentsFingerprint??input.partialPlan.assignmentsFingerprint??""),causalEvaluationFingerprint:String(evaluation.fingerprint),causallyUseful:Boolean(evaluation.causallyUseful),blockersRemovedCount:Number(evaluation.blockersRemoved?.length??0),blockersModifiedCount:Number(evaluation.blockersModified?.length??0),backjumpDistance:Number(evaluation.backjumpDistance??0),operationalRank:ranked.get(String(input.partialPlan.assignmentsFingerprint))??999999,deterministicSourceOrdinal:envelopes.length,inCheckpointSubtree:Boolean(branch?.resolved),alreadyExpanded:args.expandedAssignmentsFingerprints.has(String(input.partialPlan.assignmentsFingerprint)),hardInvalid:String(input.partialPlan.status)==="HARD_INVALID",futureInfeasible:String((input.partialPlan.futureFeasibility as Record<string,unknown>|undefined)?.status??"")==="INFEASIBLE",readOnly:true});
 }
 const collection=collectInitialConstructionCausalAlternativeActivationCandidates(envelopes);
 const openInputForCandidate=(candidate:InitialConstructionCausalAlternativeActivationCandidate):InitialConstructionCausalBranchOpenInput=>({conflictFingerprint:String(args.conflict.fingerprint??""),conflictFamilyFingerprint:hash({frontierTaskId:args.conflict.frontierTaskId,blockingTaskIds:[...((args.conflict.blockingAssignments as readonly Record<string,unknown>[]|undefined)??[])].map(b=>b.taskId).sort()}),frontierTaskId:Number.isFinite(Number(args.conflict.frontierTaskId))?Number(args.conflict.frontierTaskId):null,blockingTaskIds:[...((args.conflict.blockingAssignments as readonly Record<string,unknown>[]|undefined)??[])].map(b=>Number(b.taskId)).filter(Number.isFinite).sort((a,b)=>a-b),checkpointFingerprint:String(args.checkpoint.fingerprint??""),checkpointParentPartialPlanId:String(args.checkpoint.parentPartialPlanId??""),checkpointParentAssignmentsFingerprint:String(args.checkpoint.parentAssignmentsFingerprint??""),causalDecisionId:String(args.checkpoint.causalDecisionId??""),causalDecisionDepth:Number(args.checkpoint.causalDecisionDepth??0),selectedPartialPlanId:String(candidate.partialPlan.partialPlanId),selectedAssignmentsFingerprint:String(candidate.partialPlan.assignmentsFingerprint),checkpointBranchPartialPlanId:candidate.checkpointBranchPartialPlanId,checkpointBranchFingerprint:candidate.checkpointBranchFingerprint,checkpointBranchAssignmentsFingerprint:candidate.checkpointBranchAssignmentsFingerprint,activationOrdinal:args.activationOrdinal,baselineProductiveAssignmentCount:args.baselineProductiveAssignmentCount,baselineResidualProductiveTaskCount:args.baselineResidualProductiveTaskCount,baselineMaximumProductiveAssignmentCountObserved:args.baselineMaximumProductiveAssignmentCountObserved,activatedAtExpansionWorkUnit:args.expansionWorkUnitCount});
 const prepared=prepareInitialConstructionCausalAlternativeActivation({candidates:collection.candidates,ledger:args.ledger,openInputForCandidate,expandedAssignmentsFingerprints:args.expandedAssignmentsFingerprints,cursorInspectedBranchFingerprints:new Set(args.cursor.inspectedDecisionBranchFingerprints),noGoodBranchFingerprints:new Set()});
 const inspected=collection.candidates.slice(0,prepared.inspectedCandidateCount); const selected=prepared.selectedCandidate;
 const updatedCursor=advanceInitialConstructionCausalCheckpointCursor(args.cursor,{inspectedDecisionBranchFingerprints:inspected.map(c=>c.checkpointBranchFingerprint),activatedDecisionBranchFingerprints:selected?[selected.checkpointBranchFingerprint]:[],inspectedChildAssignmentsFingerprints:inspected.map(c=>c.checkpointBranchAssignmentsFingerprint)});
 const inspectedCandidates=inspected.map(c=>{const skipKey=hash({partialPlanId:c.partialPlan.partialPlanId,assignmentsFingerprint:c.partialPlan.assignmentsFingerprint,branchFingerprint:c.checkpointBranchFingerprint,source:c.source}); const skipped=(prepared.skippedCandidateSamples as readonly Record<string,unknown>[]).find(s=>s.skipKey===skipKey); return {partialPlanId:c.partialPlan.partialPlanId,assignmentsFingerprint:c.partialPlan.assignmentsFingerprint,source:c.source,branchFingerprint:c.checkpointBranchFingerprint,status:selected?.checkpointBranchFingerprint===c.checkpointBranchFingerprint&&selected?.partialPlan.assignmentsFingerprint===c.partialPlan.assignmentsFingerprint?"PREPARED":"SKIPPED",reason:skipped?.reason??null,readOnly:true};});
 const evidence={transactionId,phase:args.reopenCandidates?.length?"CHECKPOINT_REOPEN":"EXISTING_SOURCES",conflictFingerprint:args.conflict.fingerprint??null,checkpointFingerprint:args.checkpoint.fingerprint??null,causalDecisionId:args.checkpoint.causalDecisionId??null,inspectedCandidates,selectedPartialPlanId:selected?.partialPlan.partialPlanId??null,selectedSource:selected?.source??null,openedAttemptId:prepared.openedAttemptId,committed:false,backtrackConsumed:false,transitionConsumed:false,collectionFingerprint:collection.fingerprint,readOnly:true};
 const payload={status:prepared.status==="ACTIVATION_PREPARED"?"ACTIVATION_PREPARED":collection.candidates.length?"NO_EXISTING_CAUSAL_CANDIDATE":"NO_EXISTING_CAUSAL_CANDIDATE",preparedActivation:prepared,selectedCandidate:selected,candidateCollection:collection,updatedCursor,sourceCommit:selected?{source:selected.source,sourceEntryFingerprint:selected.sourceEntryFingerprint,sourceEntryId:selected.sourceEntryId??null}:null,transactionEvidence:evidence};
 return deepFreeze({...payload,fingerprint:hash(payload),readOnly:true}) as InitialConstructionCausalActivationTransactionResult;
}
