import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { CandidateAssignment, OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { initialConstructionAssignmentFingerprint, materializeInitialConstructionAnchorAttempt } from "./materializeInitialConstructionAnchorAttempt";
import { buildInitialConstructionRepairProblem, repairDependencyClosure } from "./initialConstructionRepairProblem";
import { buildInitialConstructionMap } from "../understanding/initialConstructionMap";
import { buildInitialConstructionResidualContext } from "../understanding/initialConstructionResidualContext";
import { selectInitialConstructionAnchors } from "../see/initialConstructionAnchorSelector";
import { buildInitialConstructionSearchSpaces } from "../see/initialConstructionSearchSpace";
import { buildCandidateStates } from "../transformation/transformationEngine";
import { simulateCandidateStates } from "../simulation/simulationEngine";
import { validateSimulatedStates } from "../validation/validationEngine";

const norm=(a:any):CandidateAssignment=>({taskId:Number(a.taskId),startPlanned:a.startPlanned??null,endPlanned:a.endPlanned??null,spaceId:a.spaceId??null,resourceIds:[...(a.resourceIds??a.assignedResourceIds??[])].map(Number).sort((x,y)=>x-y)});

export interface InitialConstructionRepairSearchNode { readonly rootCandidateProfileFingerprint: string | null; readonly triggeringFailedTaskId: number | null; readonly triggeringCandidateProfileFingerprint: string | null; readonly cumulativeEjectedTaskIds: readonly number[]; readonly newlyEjectedTaskIds: readonly number[]; readonly cumulativeRepairDependencyClosureTaskIds: readonly number[]; readonly repairNeighborhoodTaskIds: readonly number[]; readonly repairNeighborhoodTopologicalTaskIds: readonly number[]; readonly expansionDepth: number; readonly parentNodeFingerprint: string | null; readonly baseAssignmentsFingerprint: string; readonly candidateRank: number; readonly fingerprint: string; readonly readOnly: true }
export interface InitialConstructionRepairSearchFailure { readonly phase?: string | null; readonly stopReason?: string | null; readonly failedTaskId?: number | null; readonly failedRepairCandidateProfiles?: readonly any[]; readonly failedRepairCandidateProfilesFingerprint?: string | null; readonly failedRepairableCandidateProfileCount?: number; readonly failedTaskAttemptFingerprint?: string | null; readonly failedTaskSearchSpaceCount?: number; readonly failedTaskTemporalCandidateCount?: number; readonly failedTaskBranchCount?: number; readonly failedTaskCandidateBranchCount?: number; readonly failedTaskBlockerReasonCounts?: Readonly<Record<string,number>>; readonly materialized?: any }
export interface InitialConstructionRepairNodeEvaluation { readonly solved: CandidateAssignment[] | null; readonly failure: InitialConstructionRepairSearchFailure | null; readonly anchorAttemptCount: number; readonly validationCount: number; readonly partialPlansVisited: number; readonly branchOptionsVisited: number; readonly anchorBranchOptionCount: number; readonly anchorBranchOptionsVisited: number; readonly anchorBranchBacktrackCount: number; readonly cumulativeClosureRemovalComplete: boolean; readonly cumulativeClosureTaskIdsStillAssigned: readonly number[]; readonly basePreservationAudit: unknown }
export interface InitialConstructionRepairNodeExpansion { readonly children: readonly InitialConstructionRepairSearchNode[]; readonly pruned: readonly { readonly stopReason: string; readonly fingerprint: string; readonly transitionAudit?: unknown; readonly readOnly: true }[]; readonly stopReasonCounts: Readonly<Record<string,number>>; readonly readOnly: true }
interface InitialConstructionRepairSearchNodeFields extends Omit<InitialConstructionRepairSearchNode, "fingerprint" | "readOnly" | "baseAssignmentsFingerprint" | "rootCandidateProfileFingerprint"> {}

const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");

export function auditInitialConstructionRepairNeighborhoodPreservation(args:{ before: readonly CandidateAssignment[]; after: readonly CandidateAssignment[]; repairNeighborhoodTaskIds: readonly number[]; protectedTaskIds?: readonly number[]; productiveTaskIds?: readonly number[] }){
  const neighborhood=new Set(args.repairNeighborhoodTaskIds.map(Number)); const protectedSet=new Set((args.protectedTaskIds??[]).map(Number)); const productive=new Set((args.productiveTaskIds??[]).map(Number));
  const before=new Map(args.before.map(a=>[a.taskId,norm(a)])); const after=new Map(args.after.map(a=>[a.taskId,norm(a)]));
  const changed=(ids:number[])=>ids.filter(id=>stableStringify(before.get(id)??null)!==stableStringify(after.get(id)??null)).sort((a,b)=>a-b);
  const outside=[...new Set([...before.keys(),...after.keys()])].filter(id=>!neighborhood.has(id));
  const protectedChanged=changed([...protectedSet]); const outsideChanged=changed(outside);
  const lost=[...before.keys()].filter(id=>productive.has(id)&&!after.has(id)).sort((a,b)=>a-b); const newly=[...after.keys()].filter(id=>productive.has(id)&&!before.has(id)).sort((a,b)=>a-b);
  const afterIds=args.after.map(a=>a.taskId); const duplicateTaskIds=[...new Set(afterIds.filter((id,i)=>afterIds.indexOf(id)!==i))].sort((a,b)=>a-b);
  const removedAssignmentIds=[...before.keys()].filter(id=>!after.has(id)).sort((a,b)=>a-b); const reinsertedAssignmentIds=[...after.keys()].filter(id=>!before.has(id)).sort((a,b)=>a-b);
  const modifiedNeighborhoodAssignmentIds=changed([...neighborhood]);
  return deepFreeze({protectedAssignmentsModified:protectedChanged.length>0,protectedAssignmentIdsModified:protectedChanged,outsideNeighborhoodAssignmentsModified:outsideChanged.length,outsideNeighborhoodAssignmentIdsModified:outsideChanged,lostProductiveTaskIds:lost,newlyAssignedProductiveTaskIds:newly,removedAssignmentIds,reinsertedAssignmentIds,modifiedNeighborhoodAssignmentIds,duplicateTaskIds,fingerprint:hash({protectedChanged,outsideChanged,lost,newly,removedAssignmentIds,reinsertedAssignmentIds,modifiedNeighborhoodAssignmentIds,duplicateTaskIds}),readOnly:true}) as any;
}

function candidate(id:string, assignments:CandidateAssignment[]):any{ return {id,assignments,state:{status:"draft",evidenceIds:[],metadata:{readOnly:true}},metadata:{strategy:"SCHEDULE_PENDING_TASKS",planningInfluence:"candidate-assignments",initialConstructionStage:"repair-neighborhood",executesTransformations:assignments.length>0,commitsPlanning:false,readOnly:true},evidenceIds:[],operationalValues:[]}; }
function prereqClosure(anchorId:number, base:CandidateAssignment[], context:any): number[] { const assigned=new Set(base.map(a=>a.taskId)); const out=new Set<number>([anchorId]); const visit=(id:number)=>{ for(const p of context.prerequisitesByTaskId?.get(id)??[]) if(!assigned.has(p)&&!out.has(p)){ out.add(p); visit(p); } }; visit(anchorId); return (context.topologicalTaskIds??[...out]).filter((id:number)=>out.has(id)); }
function validateCombined(args:any, assignments:CandidateAssignment[], id:string){ const tr=buildCandidateStates(args.originOperationalState,[candidate(id,assignments)],{createdAt:null,maxTransformations:1}); const sim=simulateCandidateStates(args.originOperationalState,tr.candidateStates,{createdAt:null,maxSimulations:1}); const val=validateSimulatedStates(sim.simulatedStates,{createdAt:null}); return val.validationResults[0]?.result??"INVALID"; }

export function materializeRepairTaskOptions(args:any, current:CandidateAssignment[], taskId:number, maxBranches:number){
  const map:any=buildInitialConstructionMap({input:args.originInput,state:args.originOperationalState,planningMode:"INITIAL_CONSTRUCTION",provisionalAssignments:current,provisionallyAssignedTaskIds:current.map(a=>a.taskId)});
  const anchors:any[]=selectInitialConstructionAnchors({input:args.originInput,initialConstructionMap:map,maxAnchors:Number.MAX_SAFE_INTEGER});
  const anchor=anchors.find(a=>Number(a.anchorTaskId)===Number(taskId))??{anchorTaskId:taskId};
  const searchSpaces:any[]=buildInitialConstructionSearchSpaces({input:args.originInput,anchors:[anchor],initialConstructionMap:map,maxSearchSpaces:1,maxWindowsPerAnchor:20});
  const closure=prereqClosure(taskId,current,args.canonicalContext);
  const stage={...(args.stage1??{}),selectedAnchor:anchor,selectedAnchorTaskId:taskId,initialConstructionMap:map,searchSpaces};
  const attempt=materializeInitialConstructionAnchorAttempt({originInput:args.originInput,originOperationalState:args.originOperationalState,stage,anchor,baseProvisionalAssignments:current,provisionallySatisfiedTaskIds:current.map((a:any)=>a.taskId),closureTaskIds:closure,maxBranches,reasoningBudget:args.localBudget,createdAt:null,canonicalContext:args.canonicalContext});
  const options:any[]=[];
  for(const opt of attempt.selectable??[]){ const byId=new Map(current.map(a=>[a.taskId,a])); for(const a of opt.branch.assignments.map(norm)) byId.set(a.taskId,a); const combined=[...byId.values()].sort((a,b)=>a.taskId-b.taskId); if(new Set(combined.map(a=>a.taskId)).size!==combined.length) continue; if(validateCombined(args,combined,`repair-neighborhood:${taskId}`)==="VALID") options.push({combined,attempt,closure,branchFingerprint:hash(opt.branch),branch:opt.branch}); }
  const objective=args.ejectionSet?.targetProjection??null;
  const tm=(v:any)=>/^\d\d:\d\d$/.test(String(v??""))?Number(String(v).slice(0,2))*60+Number(String(v).slice(3)):null;
  for(const option of options){ const placed=option.combined.find((a:any)=>Number(a.taskId)===Number(objective?.blockedAnchorTaskId)); const start=tm(placed?.startPlanned),end=tm(placed?.endPlanned),targetStart=tm(objective?.projectedStart),targetEnd=tm(objective?.projectedEnd); const boundaryOk=!objective||(objective.requiredShiftDirection==="earlier"?(end!=null&&targetEnd!=null&&end<=targetEnd):(start!=null&&targetStart!=null&&start>=targetStart)); option.repairObjectiveUnmetConditionCount=boundaryOk?0:1; option.repairObjectiveSatisfied=Boolean(objective&&boundaryOk); option.repairObjectiveDistanceMinutes=objective&&start!=null&&targetStart!=null?Math.abs(start-targetStart):Number.MAX_SAFE_INTEGER; }
  if(objective) options.sort((a,b)=>Number(b.repairObjectiveSatisfied)-Number(a.repairObjectiveSatisfied)||a.repairObjectiveUnmetConditionCount-b.repairObjectiveUnmetConditionCount||a.repairObjectiveDistanceMinutes-b.repairObjectiveDistanceMinutes||a.branchFingerprint.localeCompare(b.branchFingerprint));
  const out:any={taskId,closureTaskIds:closure,attempt,options,repairObjectiveOptionCount:objective?options.length:0,repairObjectiveSatisfiedOptionCount:objective?options.filter(o=>o.repairObjectiveSatisfied).length:0,repairCandidateProfiles:attempt.repairCandidateProfiles??[],repairCandidateProfilesFingerprint:attempt.repairCandidateProfilesFingerprint??hash([]),repairableCandidateProfileCount:attempt.repairableCandidateProfileCount??0,searchSpaceCount:searchSpaces.length,temporalCandidateCount:attempt.diagnostics?.anchorTemporalCandidateCount??attempt.diagnostics?.temporalCandidateCountAvailable??0,branchCount:attempt.branchCount??attempt.branches?.length??0,candidateBranchCount:attempt.candidateBranchCount??0,validationCount:attempt.validationsExecuted??0,stopReason:options.length?"OPTIONS_AVAILABLE":(attempt.diagnostics?.anchorExplorationStopReason??"NO_OPTIONS"),fingerprint:"",readOnly:true};
  out.fingerprint=hash({taskId,closure,options:options.map(o=>o.branchFingerprint),profiles:out.repairCandidateProfilesFingerprint,stopReason:out.stopReason}); return deepFreeze(out) as any;
}
function makeNode(args:{ rootCandidateProfileFingerprint?: string | null; baseAssignmentsFingerprint: string }, fields:InitialConstructionRepairSearchNodeFields): InitialConstructionRepairSearchNode { const n:any={rootCandidateProfileFingerprint:args.rootCandidateProfileFingerprint??null,triggeringFailedTaskId:fields.triggeringFailedTaskId??null,triggeringCandidateProfileFingerprint:fields.triggeringCandidateProfileFingerprint??null,cumulativeEjectedTaskIds:[...fields.cumulativeEjectedTaskIds].map(Number).sort((a,b)=>a-b),newlyEjectedTaskIds:[...fields.newlyEjectedTaskIds].map(Number).sort((a,b)=>a-b),cumulativeRepairDependencyClosureTaskIds:[...fields.cumulativeRepairDependencyClosureTaskIds].map(Number).sort((a,b)=>a-b),repairNeighborhoodTaskIds:[...fields.repairNeighborhoodTaskIds].map(Number).sort((a,b)=>a-b),repairNeighborhoodTopologicalTaskIds:[...fields.repairNeighborhoodTopologicalTaskIds].map(Number),expansionDepth:Number(fields.expansionDepth),parentNodeFingerprint:fields.parentNodeFingerprint??null,baseAssignmentsFingerprint:args.baseAssignmentsFingerprint,candidateRank:Number(fields.candidateRank),fingerprint:"",readOnly:true}; n.fingerprint=hash({rootCandidateProfileFingerprint:n.rootCandidateProfileFingerprint,triggeringFailedTaskId:n.triggeringFailedTaskId,triggeringCandidateProfileFingerprint:n.triggeringCandidateProfileFingerprint,cumulativeEjectedTaskIds:n.cumulativeEjectedTaskIds,cumulativeRepairDependencyClosureTaskIds:n.cumulativeRepairDependencyClosureTaskIds,repairNeighborhoodTaskIds:n.repairNeighborhoodTaskIds,expansionDepth:n.expansionDepth,parentNodeFingerprint:n.parentNodeFingerprint,baseAssignmentsFingerprint:n.baseAssignmentsFingerprint,candidateRank:n.candidateRank}); return deepFreeze(n) as InitialConstructionRepairSearchNode; }
function nodeSort(a:InitialConstructionRepairSearchNode,b:InitialConstructionRepairSearchNode){ return a.cumulativeEjectedTaskIds.length-b.cumulativeEjectedTaskIds.length||a.cumulativeRepairDependencyClosureTaskIds.length-b.cumulativeRepairDependencyClosureTaskIds.length||a.expansionDepth-b.expansionDepth||a.candidateRank-b.candidateRank||a.fingerprint.localeCompare(b.fingerprint); }
export function auditInitialConstructionRepairSearchNodeTransition(parent: InitialConstructionRepairSearchNode, child: InitialConstructionRepairSearchNode){
  const parentEjected=new Set(parent.cumulativeEjectedTaskIds.map(Number)); const childEjected=new Set(child.cumulativeEjectedTaskIds.map(Number));
  const parentClosure=new Set(parent.cumulativeRepairDependencyClosureTaskIds.map(Number)); const childClosure=new Set(child.cumulativeRepairDependencyClosureTaskIds.map(Number));
  const parentNeighborhood=new Set(parent.repairNeighborhoodTaskIds.map(Number)); const childNeighborhood=new Set(child.repairNeighborhoodTaskIds.map(Number));
  const missingEjected=[...parentEjected].filter(id=>!childEjected.has(id)).sort((a,b)=>a-b);
  const parentClosureTaskIdsMissingFromChild=[...parentClosure].filter(id=>!childClosure.has(id)).sort((a,b)=>a-b);
  const parentNeighborhoodTaskIdsMissingFromChild=[...parentNeighborhood].filter(id=>!childNeighborhood.has(id)).sort((a,b)=>a-b);
  const expectedNewly=[...childEjected].filter(id=>!parentEjected.has(id)).sort((a,b)=>a-b);
  const actualNewly=[...child.newlyEjectedTaskIds].map(Number).sort((a,b)=>a-b);
  const cumulativeEjectedMonotonic=missingEjected.length===0; const dependencyClosureMonotonic=parentClosureTaskIdsMissingFromChild.length===0; const neighborhoodMonotonic=parentNeighborhoodTaskIdsMissingFromChild.length===0;
  const newlyEjectedMatchesDifference=stableStringify(expectedNewly)===stableStringify(actualNewly); const valid=cumulativeEjectedMonotonic&&dependencyClosureMonotonic&&neighborhoodMonotonic&&newlyEjectedMatchesDifference;
  return deepFreeze({cumulativeEjectedMonotonic,dependencyClosureMonotonic,neighborhoodMonotonic,newlyEjectedMatchesDifference,parentClosureTaskIdsMissingFromChild,parentNeighborhoodTaskIdsMissingFromChild,valid,fingerprint:hash({parent:parent.fingerprint,child:child.fingerprint,expectedNewly,actualNewly,parentClosureTaskIdsMissingFromChild,parentNeighborhoodTaskIdsMissingFromChild,valid}),readOnly:true}) as any;
}
function failedFromMaterialized(m:any, phase:string){ return {phase,failedTaskId:m.taskId,failedRepairCandidateProfiles:m.repairCandidateProfiles,failedRepairCandidateProfilesFingerprint:m.repairCandidateProfilesFingerprint,failedRepairableCandidateProfileCount:m.repairableCandidateProfileCount,failedTaskAttemptFingerprint:m.attempt?.diagnostics?.fingerprint??m.fingerprint,failedTaskSearchSpaceCount:m.searchSpaceCount,failedTaskTemporalCandidateCount:m.temporalCandidateCount,failedTaskBranchCount:m.branchCount,failedTaskCandidateBranchCount:m.candidateBranchCount,failedTaskBlockerReasonCounts:m.attempt?.diagnostics?.deadEndReasonCounts??{},materialized:m}; }
function nextNeighborhoodTask(args:any, plan:CandidateAssignment[], node:any, anchorPlaced:boolean){
  const assigned=new Set(plan.map(a=>a.taskId)); if(!anchorPlaced && !assigned.has(Number(args.blockedAnchorTaskId))) return Number(args.blockedAnchorTaskId);
  const todo=node.repairNeighborhoodTopologicalTaskIds.filter((id:number)=>!assigned.has(id));
  const ready=todo.filter((id:number)=>[...(args.canonicalContext?.prerequisitesByTaskId?.get(id)??[])].every((p:number)=>assigned.has(p)||!node.repairNeighborhoodTaskIds.includes(p)));
  if(!ready.length) return todo[0]??null;
  const map:any=buildInitialConstructionMap({input:args.originInput,state:args.originOperationalState,planningMode:"INITIAL_CONSTRUCTION",provisionalAssignments:plan,provisionallyAssignedTaskIds:plan.map(a=>a.taskId)});
  const anchors:any[]=selectInitialConstructionAnchors({input:args.originInput,initialConstructionMap:map,maxAnchors:Number.MAX_SAFE_INTEGER});
  const ranked=anchors.map(a=>Number(a.anchorTaskId)).filter(id=>ready.includes(id)); return (ranked[0]??ready[0])??null;
}
export function evaluateInitialConstructionRepairSearchNode(args:any, node:InitialConstructionRepairSearchNode, deadlineMs:number): InitialConstructionRepairNodeEvaluation {
  const before=[...(args.combinedPartialPlan?.assignments??[])].map(norm).sort((a,b)=>a.taskId-b.taskId); const removed=new Set(node.cumulativeRepairDependencyClosureTaskIds.map(Number)); const base=before.filter(a=>!removed.has(a.taskId)); const cumulativeClosureTaskIdsStillAssigned=base.filter(a=>removed.has(a.taskId)).map(a=>a.taskId).sort((a,b)=>a-b); const cumulativeClosureRemovalComplete=cumulativeClosureTaskIdsStillAssigned.length===0; const basePreservationAudit=auditInitialConstructionRepairNeighborhoodPreservation({before,after:base,repairNeighborhoodTaskIds:node.repairNeighborhoodTaskIds,protectedTaskIds:args.repairProblem?.protectedTaskIds??[],productiveTaskIds:(args.originInput.tasks??[]).map((t:any)=>Number(t.id))}); if(!cumulativeClosureRemovalComplete) return {solved:null,failure:{phase:"PRESERVATION_AUDIT",stopReason:"CUMULATIVE_CLOSURE_REMOVAL_INCOMPLETE",failedTaskId:null},anchorAttemptCount:0,validationCount:0,partialPlansVisited:0,branchOptionsVisited:0,anchorBranchOptionCount:0,anchorBranchOptionsVisited:0,anchorBranchBacktrackCount:0,cumulativeClosureRemovalComplete,cumulativeClosureTaskIdsStillAssigned,basePreservationAudit};
  let anchorAttemptCount=0, validationCount=0, partialPlansVisited=0, branchOptionsVisited=0, anchorBranchOptionCount=0, anchorBranchOptionsVisited=0, anchorBranchBacktrackCount=0; let failure:any=null; const maxBranches=Number(args.localBudget?.maxNeighborhoodBranchEvaluations??128); const maxPlans=Number(args.localBudget?.maxNeighborhoodPartialPlansVisited??128); const maxAnchorAttempts=Number(args.localBudget?.maxNeighborhoodAnchorAttempts??64); const maxValidations=Number(args.localBudget?.maxNeighborhoodValidations??64);
  const dfs=(plan:CandidateAssignment[], anchorPlaced:boolean):CandidateAssignment[]|null=>{ if(performance.now()>deadlineMs){ failure={phase:"DEADLINE",stopReason:"REPAIR_DEADLINE_EXHAUSTED"}; return null; } if(partialPlansVisited>=maxPlans){ failure={phase:"BUDGET",stopReason:"MAX_NEIGHBORHOOD_PARTIAL_PLANS"}; return null; } partialPlansVisited++;
    const next=nextNeighborhoodTask(args,plan,node,anchorPlaced); if(next==null) return plan; if(anchorAttemptCount>=maxAnchorAttempts){ failure={phase:"BUDGET",stopReason:"MAX_NEIGHBORHOOD_ANCHOR_ATTEMPTS"}; return null; }
    const mat=materializeRepairTaskOptions(args,plan,Number(next),maxBranches); anchorAttemptCount++; validationCount+=Math.max(1,mat.validationCount); if(validationCount>maxValidations){ failure={phase:"BUDGET",stopReason:"MAX_NEIGHBORHOOD_VALIDATIONS"}; return null; }
    if(Number(next)===Number(args.blockedAnchorTaskId)) anchorBranchOptionCount+=mat.options.length;
    if(!mat.options.length){ failure=failedFromMaterialized(mat, Number(next)===Number(args.blockedAnchorTaskId)?"BLOCKED_ANCHOR_RECONSTRUCTION":"NEIGHBORHOOD_TASK_REINSERTION"); return null; }
    for(const opt of mat.options){ branchOptionsVisited++; if(Number(next)===Number(args.blockedAnchorTaskId)) anchorBranchOptionsVisited++; const r=dfs(opt.combined, anchorPlaced||Number(next)===Number(args.blockedAnchorTaskId)); if(r) return r; if(Number(next)===Number(args.blockedAnchorTaskId)) anchorBranchBacktrackCount++; }
    return null; };
  const solved=dfs(base,false); return {solved, failure, anchorAttemptCount, validationCount, partialPlansVisited, branchOptionsVisited, anchorBranchOptionCount, anchorBranchOptionsVisited, anchorBranchBacktrackCount,cumulativeClosureRemovalComplete,cumulativeClosureTaskIdsStillAssigned,basePreservationAudit};
}
export function expandInitialConstructionRepairSearchNode(args:any, parent:InitialConstructionRepairSearchNode, failure:InitialConstructionRepairSearchFailure): InitialConstructionRepairNodeExpansion {
  const profiles=[...(failure?.failedRepairCandidateProfiles??[])].filter((p:any)=>p?.repairable); const before=[...(args.combinedPartialPlan?.assignments??[])].map(norm); const assigned=new Set(before.map(a=>a.taskId)); const immutable=new Set((args.repairProblem?.immutableTaskIds??[]).map(Number)); const children:InitialConstructionRepairSearchNode[]=[]; const pruned:any[]=[]; const stopReasonCounts:Record<string,number>={}; const inc=(k:string)=>{stopReasonCounts[k]=(stopReasonCounts[k]??0)+1}; const seen=new Set<string>();
  for(const profile of profiles){ if(children.length>=Number(args.localBudget?.maxRepairChildNodesPerFailure??8)) break; if(parent.expansionDepth>=Number(args.localBudget?.maxRepairExpansionDepth??3)) break; const problem=buildInitialConstructionRepairProblem({input:args.originInput,originOperationalState:args.originOperationalState,residualFingerprint:args.repairProblem?.residualFingerprint??"repair",blockedAnchorTaskId:Number(failure.failedTaskId??0),blockedAnchorRank:args.repairProblem?.blockedAnchorRank??null,blockedAnchorClosureTaskIds:prereqClosure(Number(failure.failedTaskId??0),before,args.canonicalContext),repairCandidateProfiles:[profile],terminalEvidence:{requireCandidateScopedProfiles:true},provisionalAssignments:before,protectedTaskIds:args.repairProblem?.protectedTaskIds??[],maxEjectedAssignments:args.localBudget?.maxEjectedAssignments,maxRepairNeighborhoodTasks:args.localBudget?.maxRepairNeighborhoodTasks,canonicalContext:args.canonicalContext});
    for(const set of problem.candidateEjectionSets??[]){ const blockers=[...set.ejectedTaskIds].map(Number).filter(id=>assigned.has(id)&&!immutable.has(id)&&!parent.cumulativeRepairDependencyClosureTaskIds.includes(id)); if(!blockers.length) continue; const cumulativeEjectedTaskIds=[...new Set([...parent.cumulativeEjectedTaskIds,...blockers])].sort((a,b)=>a-b); if(cumulativeEjectedTaskIds.length>Number(args.localBudget?.maxEjectedAssignments??4)){ inc("CUMULATIVE_EJECTION_LIMIT"); pruned.push({stopReason:"CUMULATIVE_EJECTION_LIMIT",fingerprint:hash({parent:parent.fingerprint,blockers,cumulativeEjectedTaskIds}),readOnly:true}); continue; } const closure=repairDependencyClosure({input:args.originInput,seedTaskIds:cumulativeEjectedTaskIds,provisionalAssignmentTaskIds:[...assigned],canonicalContext:args.canonicalContext}); const neighborhood=[...new Set([Number(args.blockedAnchorTaskId),...(args.repairProblem?.blockedAnchorClosureTaskIds??[]),...closure])].sort((a,b)=>a-b); if(neighborhood.length>Number(args.localBudget?.maxRepairNeighborhoodTasks??12)){ inc("CUMULATIVE_NEIGHBORHOOD_LIMIT"); pruned.push({stopReason:"CUMULATIVE_NEIGHBORHOOD_LIMIT",fingerprint:hash({parent:parent.fingerprint,neighborhood}),readOnly:true}); continue; } const topo=(args.canonicalContext?.topologicalTaskIds??neighborhood).filter((id:number)=>neighborhood.includes(id)); const key=hash({base:parent.baseAssignmentsFingerprint,anchor:args.blockedAnchorTaskId,closure}); if(seen.has(key)){ inc("DUPLICATE_CUMULATIVE_CLOSURE"); pruned.push({stopReason:"DUPLICATE_CUMULATIVE_CLOSURE",fingerprint:key,readOnly:true}); continue; } seen.add(key); const child=makeNode({rootCandidateProfileFingerprint:parent.rootCandidateProfileFingerprint,baseAssignmentsFingerprint:parent.baseAssignmentsFingerprint},{triggeringFailedTaskId:failure.failedTaskId??null,triggeringCandidateProfileFingerprint:profile.fingerprint,cumulativeEjectedTaskIds,newlyEjectedTaskIds:cumulativeEjectedTaskIds.filter(id=>!parent.cumulativeEjectedTaskIds.includes(id)),cumulativeRepairDependencyClosureTaskIds:closure,repairNeighborhoodTaskIds:neighborhood,repairNeighborhoodTopologicalTaskIds:topo,expansionDepth:parent.expansionDepth+1,parentNodeFingerprint:parent.fingerprint,candidateRank:profile.candidateRank}); const transitionAudit=auditInitialConstructionRepairSearchNodeTransition(parent,child); if(!transitionAudit.valid){ inc("INVALID_NODE_TRANSITION"); pruned.push({stopReason:"INVALID_NODE_TRANSITION",fingerprint:child.fingerprint,transitionAudit,readOnly:true}); continue; } children.push(child); }
  }
  return deepFreeze({children:children.sort(nodeSort),pruned,stopReasonCounts,readOnly:true}) as InitialConstructionRepairNodeExpansion;
}

function compactSearchNodeSample(node: InitialConstructionRepairSearchNode, transitionValid: boolean | null = null, stopReason: string | null = null){ return {fingerprint:node.fingerprint,parentNodeFingerprint:node.parentNodeFingerprint,depth:node.expansionDepth,cumulativeEjectedTaskIds:node.cumulativeEjectedTaskIds,cumulativeRepairDependencyClosureTaskIds:node.cumulativeRepairDependencyClosureTaskIds,failedTaskId:node.triggeringFailedTaskId,triggeringCandidateProfileFingerprint:node.triggeringCandidateProfileFingerprint,transitionValid,stopReason}; }
function compactSearchEvidence(nodes: readonly InitialConstructionRepairSearchNode[], stopReasonCounts: Record<string,number>, acceptedNodeFingerprint: string | null, stopReason: string, finalAssignmentsFingerprint?: string | null){ const samples=nodes.map(n=>compactSearchNodeSample(n,n.parentNodeFingerprint?true:null,null)); return {searchNodeSequenceFingerprint:hash(nodes.map(n=>n.fingerprint)),searchNodeTransitionFingerprint:hash(nodes.map(n=>({fingerprint:n.fingerprint,parent:n.parentNodeFingerprint,depth:n.expansionDepth,cumulativeEjectedTaskIds:n.cumulativeEjectedTaskIds,cumulativeRepairDependencyClosureTaskIds:n.cumulativeRepairDependencyClosureTaskIds}))),searchNodeSampleFirst:samples.slice(0,5),searchNodeSampleLast:samples.slice(Math.max(0,samples.length-5)),acceptedPathNodeFingerprints:acceptedNodeFingerprint?[acceptedNodeFingerprint]:[],prunedNodeReasonCounts:{},stopReasonCounts,acceptedNodeFingerprint,finalAssignmentsFingerprint:finalAssignmentsFingerprint??null,stopReason}; }
export function runInitialConstructionRepairNeighborhoodSession(args:{ originInput:EngineInput; originOperationalState:OperationalState; canonicalContext:any; combinedPartialPlan:any; repairProblem:any; ejectionSet:any; blockedAnchorTaskId:number; localBudget?:any; stage1?:any; deadlineMs?:number }){
  const before=[...(args.combinedPartialPlan?.assignments??[])].map(norm).sort((a,b)=>a.taskId-b.taskId);
  const baseFp=initialConstructionAssignmentFingerprint(before); const rootRemoved=[...(args.ejectionSet?.repairDependencyClosureTaskIds??[])].map(Number).sort((a,b)=>a-b);
  const rootNeighborhood=[...(args.ejectionSet?.repairNeighborhoodTaskIds??[...rootRemoved,Number(args.blockedAnchorTaskId)])].map(Number).sort((a,b)=>a-b);
  const productiveTaskIds=buildInitialConstructionResidualContext({originInput:args.originInput,originOperationalState:args.originOperationalState,stage2:{selectedAssignments:[],selectedPartialPlanId:"repair-audit-empty"}}).residualProductiveTaskIds??(args.originInput.tasks??[]).map((t:any)=>Number(t.id));
  const auditBefore=(after:CandidateAssignment[])=>auditInitialConstructionRepairNeighborhoodPreservation({before,after,repairNeighborhoodTaskIds:rootNeighborhood,protectedTaskIds:args.repairProblem?.protectedTaskIds??[],productiveTaskIds});
  if (rootRemoved.some(id=>(args.repairProblem?.immutableTaskIds??[]).map(Number).includes(id))) { const audit=auditBefore(before); return deepFreeze({version:"INITIAL-CONSTRUCTION-REPAIR-NEIGHBORHOOD-SESSION-V1",executed:true,accepted:false,combinedPartialPlan:args.combinedPartialPlan,anchorAssigned:before.some(a=>a.taskId===Number(args.blockedAnchorTaskId)),allNeighborhoodReinserted:false,acceptedCycleCount:0,anchorAttemptCount:0,validationCount:0,partialPlansVisited:0,branchOptionsVisited:0,anchorBranchOptionCount:0,anchorBranchOptionsVisited:0,anchorBranchBacktrackCount:0,audit,failurePhase:"PRESERVATION_AUDIT",failedTaskId:null,searchNodes:[],searchNodeCount:0,searchNodePrunedCount:0,expansionAttemptCount:0,expansionChildNodeCount:0,expansionAcceptedCount:0,maxExpansionDepthObserved:0,failedTaskIds:[],failurePhaseCounts:{PRESERVATION_AUDIT:1},stopReasonCounts:{IMMUTABLE_EJECTION_REJECTED:1},stopReason:"IMMUTABLE_EJECTION_REJECTED",sessionFingerprint:hash({audit:audit.fingerprint}),readOnly:true}) as any; }
  const root=makeNode({rootCandidateProfileFingerprint:args.ejectionSet?.candidateProfileFingerprint??null,baseAssignmentsFingerprint:baseFp},{triggeringFailedTaskId:null,triggeringCandidateProfileFingerprint:args.ejectionSet?.candidateProfileFingerprint??null,cumulativeEjectedTaskIds:args.ejectionSet?.ejectedTaskIds??[],newlyEjectedTaskIds:args.ejectionSet?.ejectedTaskIds??[],cumulativeRepairDependencyClosureTaskIds:rootRemoved,repairNeighborhoodTaskIds:rootNeighborhood,repairNeighborhoodTopologicalTaskIds:args.ejectionSet?.repairNeighborhoodTopologicalTaskIds??rootNeighborhood,expansionDepth:0,parentNodeFingerprint:null,candidateRank:0});
  const deadline=args.deadlineMs??(performance.now()+Number(args.localBudget?.maxRepairElapsedMs??30000)); const queue:any[]=[root], nodes:any[]=[]; const seen=new Set<string>([hash({base:baseFp,anchor:args.blockedAnchorTaskId,closure:root.cumulativeRepairDependencyClosureTaskIds})]);
  let searchNodePrunedCount=0, expansionAttemptCount=0, expansionChildNodeCount=0, expansionAcceptedCount=0, maxExpansionDepthObserved=0, anchorAttemptCount=0, validationCount=0, partialPlansVisited=0, branchOptionsVisited=0, anchorBranchOptionCount=0, anchorBranchOptionsVisited=0, anchorBranchBacktrackCount=0; const failedTaskIds:number[]=[]; const failurePhaseCounts:Record<string,number>={}; const stopReasonCounts:Record<string,number>={}; let lastFailure:any=null; let stopReason="NO_VALID_REPAIR";
  const inc=(m:Record<string,number>,k:any)=>{ if(k)m[String(k)]=(m[String(k)]??0)+1; };
  while(queue.length){ if(performance.now()>deadline){ stopReason="REPAIR_DEADLINE_EXHAUSTED"; break; } if(nodes.length>=Number(args.localBudget?.maxRepairSearchNodesPerAttempt??64)){ stopReason="MAX_REPAIR_SEARCH_NODES"; break; } queue.sort(nodeSort); const node=queue.shift(); nodes.push(node); maxExpansionDepthObserved=Math.max(maxExpansionDepthObserved,node.expansionDepth);
    const ev=evaluateInitialConstructionRepairSearchNode(args,node,deadline); anchorAttemptCount+=ev.anchorAttemptCount; validationCount+=ev.validationCount; partialPlansVisited+=ev.partialPlansVisited; branchOptionsVisited+=ev.branchOptionsVisited; anchorBranchOptionCount+=ev.anchorBranchOptionCount; anchorBranchOptionsVisited+=ev.anchorBranchOptionsVisited; anchorBranchBacktrackCount+=ev.anchorBranchBacktrackCount;
    if(ev.solved){ const current=ev.solved.map(norm).sort((a,b)=>a.taskId-b.taskId); const audit=auditInitialConstructionRepairNeighborhoodPreservation({before,after:current,repairNeighborhoodTaskIds:node.repairNeighborhoodTaskIds,protectedTaskIds:args.repairProblem?.protectedTaskIds??[],productiveTaskIds}); const beforeResidual=buildInitialConstructionResidualContext({originInput:args.originInput, originOperationalState:args.originOperationalState, stage2:{selectedAssignments:before, selectedPartialPlanId:`before:${baseFp}`}}); const afterResidual=buildInitialConstructionResidualContext({originInput:args.originInput, originOperationalState:args.originOperationalState, stage2:{selectedAssignments:current, selectedPartialPlanId:`after:${initialConstructionAssignmentFingerprint(current)}`}}); const accepted=current.some(a=>a.taskId===Number(args.blockedAnchorTaskId)) && node.cumulativeRepairDependencyClosureTaskIds.every((id:number)=>current.some(a=>a.taskId===id)) && afterResidual.residualProductiveTaskIds.length<beforeResidual.residualProductiveTaskIds.length && audit.duplicateTaskIds.length===0 && !audit.protectedAssignmentsModified && audit.outsideNeighborhoodAssignmentsModified===0 && validateCombined(args,current,"repair-neighborhood:final")==="VALID"; validationCount++;
      if(accepted){ expansionAcceptedCount+=node.expansionDepth>0?1:0; inc(stopReasonCounts,"REPAIR_ACCEPTED"); const finalPlan={...args.combinedPartialPlan,assignments:current,combinedAssignmentsFingerprint:initialConstructionAssignmentFingerprint(current),readOnly:true}; return deepFreeze({version:"INITIAL-CONSTRUCTION-REPAIR-NEIGHBORHOOD-SESSION-V1",executed:true,accepted:true,combinedPartialPlan:finalPlan,anchorAssigned:true,allNeighborhoodReinserted:true,acceptedCycleCount:node.repairNeighborhoodTopologicalTaskIds.length,anchorAttemptCount,validationCount,partialPlansVisited,branchOptionsVisited,anchorBranchOptionCount,anchorBranchOptionsVisited,anchorBranchBacktrackCount,audit,failurePhase:null,failedTaskId:null,searchNodes:nodes,searchNodeCount:nodes.length,searchNodePrunedCount,expansionAttemptCount,expansionChildNodeCount,expansionAcceptedCount,maxExpansionDepthObserved,failedTaskIds:[...new Set(failedTaskIds)].sort((a,b)=>a-b),failurePhaseCounts,...compactSearchEvidence(nodes,stopReasonCounts,node.fingerprint,"REPAIR_ACCEPTED",finalPlan.combinedAssignmentsFingerprint),sessionFingerprint:hash({accepted:node.fingerprint,after:finalPlan.combinedAssignmentsFingerprint,nodes:nodes.map(n=>n.fingerprint),transitions:nodes.map(n=>[n.parentNodeFingerprint,n.fingerprint])}),readOnly:true}) as any; }
    }
    const failure=ev.failure; lastFailure=failure; if(failure?.failedTaskId) failedTaskIds.push(Number(failure.failedTaskId)); inc(failurePhaseCounts,failure?.phase); if(failure?.stopReason){ stopReason=failure.stopReason; inc(stopReasonCounts,stopReason); continue; }
    if(!failure?.failedRepairCandidateProfiles?.some((p:any)=>p.repairable)){ stopReason="NO_REPAIRABLE_FAILURE_PROFILE"; inc(stopReasonCounts,stopReason); continue; }
    if(node.expansionDepth>=Number(args.localBudget?.maxRepairExpansionDepth??3)){ stopReason="MAX_REPAIR_EXPANSION_DEPTH"; inc(stopReasonCounts,stopReason); continue; }
    expansionAttemptCount++; const expansion=expandInitialConstructionRepairSearchNode(args,node,failure); for(const [reason,count] of Object.entries(expansion.stopReasonCounts)) for(let i=0;i<Number(count);i++) inc(stopReasonCounts,reason); searchNodePrunedCount+=expansion.pruned.length; let added=0; for(const child of expansion.children){ const key=hash({base:baseFp,anchor:args.blockedAnchorTaskId,closure:child.cumulativeRepairDependencyClosureTaskIds}); if(seen.has(key)){ searchNodePrunedCount++; continue; } if(added>=Number(args.localBudget?.maxRepairChildNodesPerFailure??8)){ stopReason="MAX_REPAIR_CHILD_NODES"; break; } seen.add(key); queue.push(child); added++; } expansionChildNodeCount+=added;
  }
  const audit=auditBefore(before); inc(stopReasonCounts,stopReason); return deepFreeze({version:"INITIAL-CONSTRUCTION-REPAIR-NEIGHBORHOOD-SESSION-V1",executed:true,accepted:false,combinedPartialPlan:args.combinedPartialPlan,anchorAssigned:before.some(a=>a.taskId===Number(args.blockedAnchorTaskId)),allNeighborhoodReinserted:false,acceptedCycleCount:0,anchorAttemptCount,validationCount,partialPlansVisited,branchOptionsVisited,anchorBranchOptionCount,anchorBranchOptionsVisited,anchorBranchBacktrackCount,audit,failurePhase:lastFailure?.phase??null,failedTaskId:lastFailure?.failedTaskId??null,failedRepairCandidateProfiles:lastFailure?.failedRepairCandidateProfiles??[],failedRepairCandidateProfilesFingerprint:lastFailure?.failedRepairCandidateProfilesFingerprint??null,failedRepairableCandidateProfileCount:lastFailure?.failedRepairableCandidateProfileCount??0,failedTaskAttemptFingerprint:lastFailure?.failedTaskAttemptFingerprint??null,failedTaskSearchSpaceCount:lastFailure?.failedTaskSearchSpaceCount??0,failedTaskTemporalCandidateCount:lastFailure?.failedTaskTemporalCandidateCount??0,failedTaskBranchCount:lastFailure?.failedTaskBranchCount??0,failedTaskCandidateBranchCount:lastFailure?.failedTaskCandidateBranchCount??0,failedTaskBlockerReasonCounts:lastFailure?.failedTaskBlockerReasonCounts??{},searchNodes:nodes,searchNodeCount:nodes.length,searchNodePrunedCount,expansionAttemptCount,expansionChildNodeCount,expansionAcceptedCount,maxExpansionDepthObserved,failedTaskIds:[...new Set(failedTaskIds)].sort((a,b)=>a-b),failurePhaseCounts,...compactSearchEvidence(nodes,stopReasonCounts,null,stopReason,initialConstructionAssignmentFingerprint(before)),sessionFingerprint:hash({baseFp,nodes:nodes.map(n=>n.fingerprint),transitions:nodes.map(n=>[n.parentNodeFingerprint,n.fingerprint]),failedTaskIds,stopReason,stopReasonCounts}),readOnly:true}) as any;
}
