import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { OperationalState, ReasoningBudgetProfile } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { initialConstructionSemanticIntegrityAudit } from "./runInitialConstructionStage1";
import { materializeInitialConstructionAnchorAttempt } from "./materializeInitialConstructionAnchorAttempt";

const SAMPLE_LIMIT = 10;
const CHECKED_FUTURE_DIMENSIONS = ["contestant_remaining_load", "fixed_resource_inventory"] as const;
const UNCOVERED_FUTURE_DIMENSIONS = ["future_space_capacity", "future_itinerant_team_capacity", "future_camera_capacity", "future_zone_changes", "future_setups", "pending_dependency_chains"] as const;
type FutureFeasibilityStatus = "FEASIBLE" | "INFEASIBLE" | "UNKNOWN";
const minutes = (value?: string | null): number | null => /^\d{2}:\d{2}$/.test(String(value ?? "")) ? Number(String(value).slice(0, 2)) * 60 + Number(String(value).slice(3)) : null;
const durationOf = (task: any): number => Number(task?.durationOverrideMin ?? task?.durationMin ?? task?.durationMinutes ?? task?.duration ?? 0) || 0;

function preliminaryFutureFeasibility(input: EngineInput, branch: any) {
  const assigned = new Set(branch.assignments.map((assignment: any) => assignment.taskId));
  const pending = (input.tasks ?? []).filter((task: any) => (task.status === "pending" || task.status === "interrupted") && !assigned.has(task.id));
  const reasons: string[] = [];
  for (const task of pending as any[]) for (const resourceItemId of Object.keys(task.resourceRequirements?.byItem ?? {})) if (!(input.planResourceItems ?? []).some((item: any) => item.isAvailable !== false && item.resourceItemId === Number(resourceItemId))) reasons.push("RESOURCE_WITHOUT_INVENTORY");
  const loadByContestant = new Map<number, number>();
  for (const task of pending as any[]) if (task.contestantId != null) loadByContestant.set(Number(task.contestantId), (loadByContestant.get(Number(task.contestantId)) ?? 0) + durationOf(task));
  for (const [contestantId, load] of loadByContestant) {
    const availability = (input.contestantAvailabilityById ?? {})[contestantId];
    const latestAssignedEnd = Math.max(...branch.assignments.filter((assignment: any) => (input.tasks ?? []).find((task: any) => task.id === assignment.taskId)?.contestantId === contestantId).map((assignment: any) => minutes(assignment.endPlanned) ?? minutes(input.workDay.start) ?? 0), minutes(input.workDay.start) ?? 0);
    const capacity = (minutes(availability?.end ?? input.workDay.end) ?? minutes(input.workDay.end) ?? 0) - latestAssignedEnd;
    if (load > capacity) reasons.push("CONTESTANT_REMAINING_LOAD_EXCEEDS_AVAILABILITY");
  }
  const status: FutureFeasibilityStatus = reasons.length > 0 ? "INFEASIBLE" : UNCOVERED_FUTURE_DIMENSIONS.length > 0 ? "UNKNOWN" : "FEASIBLE";
  return { status, checkedDimensions: [...CHECKED_FUTURE_DIMENSIONS], uncoveredDimensions: [...UNCOVERED_FUTURE_DIMENSIONS], reasons: [...new Set(reasons)].sort().slice(0, SAMPLE_LIMIT), confidence: status === "INFEASIBLE" ? "medium" : "low", preliminary: true, readOnly: true };
}
function futureRank(status: FutureFeasibilityStatus): number { return status === "FEASIBLE" ? 0 : status === "UNKNOWN" ? 1 : 2; }
function cap(flags: any) { return { originalInputOnly: true, v4PlanningRead: false, canonicalDependencyClosureUsed: true, concreteAssignmentsGenerated: flags.assignments, partialPlansComposed: flags.partialPlans, transformationsExecuted: flags.transformations, simulationsExecuted: flags.simulations, validationsExecuted: flags.validations, contestantOverlapChecked: true, spaceOverlapChecked: true, resourceOverlapChecked: true, spaceCapacityConstructiveCheckSupported: true, nonBlockingSpaceOccupancySupported: true, contestantAvailabilityChecked: true, taskWindowChecked: true, taskScopedProtectedIntervalsChecked: true, byItemQuantityOneSupported: true, anyOfQuantityOneSupported: true, byTypeSupported: false, multiQuantitySupported: false, itinerantTeamConstructiveCheckSupported: false, cameraCapacityConstructiveCheckSupported: false, zoneChangeConstructiveCheckSupported: false, setupConstructiveCheckSupported: false, branchRetryImplemented: flags.branchRetryObserved, recursiveAssignmentBacktrackingImplemented: true, recursiveAssignmentBacktrackingSupported: true, recursiveAssignmentBacktrackingObserved: flags.recursiveAssignmentBacktrackingObserved, temporalAssignmentBacktrackingSupported: true, resourceAssignmentBacktrackingSupported: true, temporalAssignmentBacktrackingObserved: flags.temporalAssignmentBacktrackingObserved, resourceAssignmentBacktrackingObserved: flags.resourceAssignmentBacktrackingObserved, branchAlternativeEvaluationSupported: flags.branchAlternativeEvaluationSupported, branchRetryObserved: flags.branchRetryObserved, anchorBacktrackingImplemented: false, anchorRetrySupported: false, fullFutureFeasibilityImplemented: false, completeInitialPlanningImplemented: false, publicPlanningUsesStage2: false, coherent: flags.coherent, capabilityName: "bounded_recursive_assignment_backtracking", warnings: ["Stage 2 is an experimental read-only first PartialPlan gate.", "Future Feasibility is preliminary and normally UNKNOWN when uncovered dimensions remain."] }; }
export function runInitialConstructionStage2FirstPartialPlan(args: { originInput: EngineInput; originOperationalState: OperationalState; stage1: any; reasoningBudget?: ReasoningBudgetProfile | null; createdAt?: string | null }) {
  const audit = initialConstructionSemanticIntegrityAudit(args.stage1); const anchor = args.stage1.selectedAnchor; const hasSpace = (args.stage1.searchSpaces ?? []).some((space: any) => space.anchorTaskId === anchor?.anchorTaskId);
  if (args.stage1.planningMode !== "INITIAL_CONSTRUCTION" || !audit.coherent || !anchor || !hasSpace) return deepFreeze({ version: "INITIAL-CONSTRUCTION-STAGE2-FIRST-PARTIAL-PLAN-V3", executed: false, reason: "stage2_preconditions_not_met", selectedAnchorTaskId: anchor?.anchorTaskId ?? null, readOnly: true }) as any;
  const maxBranches = Math.max(2, Math.min(2, args.reasoningBudget?.maxCandidates ?? 2));
  const attempt = materializeInitialConstructionAnchorAttempt({ originInput: args.originInput, originOperationalState: args.originOperationalState, stage: args.stage1, anchor, maxBranches, reasoningBudget: args.reasoningBudget, createdAt: args.createdAt ?? null, requireFutureFeasibility: (branch) => preliminaryFutureFeasibility(args.originInput, branch) });
  const attempts = [...attempt.attempts].sort((a: any, b: any) => { const af = a.futureFeasibility?.status ?? "UNKNOWN", bf = b.futureFeasibility?.status ?? "UNKNOWN"; return futureRank(af) - futureRank(bf); });
  const selected = [...(attempt.selectable ?? [])].sort((a: any, b: any) => futureRank(a.futureFeasibility?.status ?? "UNKNOWN") - futureRank(b.futureFeasibility?.status ?? "UNKNOWN") || a.branch.branchId.localeCompare(b.branch.branchId))[0] ?? null;
  const selectedIndex = attempt.attempts.findIndex((a: any) => a.branchId === selected?.branch.branchId);
  const branchesRejectedBeforeSelection = selectedIndex >= 0 ? attempt.attempts.slice(0, selectedIndex).filter((a: any) => a.rejectionReason != null || a.status !== "candidate").length : attempt.attempts.filter((a: any) => a.rejectionReason != null || a.status !== "candidate").length;
  const built = attempt.built; const recursive = built.branches.reduce((s: number, b: any) => s + (b.searchEvidence?.recursiveBacktrackCount ?? 0), 0); const temporal = built.branches.reduce((s: number, b: any) => s + (b.searchEvidence?.temporalDecisionBacktrackCount ?? 0), 0); const resource = built.branches.reduce((s: number, b: any) => s + (b.searchEvidence?.resourceDecisionBacktrackCount ?? 0), 0); const placement = built.branches.reduce((s: number, b: any) => s + (b.searchEvidence?.placementAttemptCount ?? 0), 0); const prune = built.branches.reduce((s: number, b: any) => s + (b.searchEvidence?.repeatedStatePruneCount ?? 0), 0);
  const capabilityAudit = cap({ assignments: built.branches.some((b: any) => b.assignments.length > 0), partialPlans: attempt.attempts.some((a: any) => a.partialPlanId != null), transformations: attempt.transformationsExecuted > 0, simulations: attempt.simulationsExecuted > 0, validations: attempt.validationsExecuted > 0, branchAlternativeEvaluationSupported: maxBranches > 1, branchRetryObserved: branchesRejectedBeforeSelection > 0, recursiveAssignmentBacktrackingObserved: recursive > 0, temporalAssignmentBacktrackingObserved: temporal > 0, resourceAssignmentBacktrackingObserved: resource > 0, coherent: attempt.attempts.every((a: any) => a.lineageCoherent !== false) });
  const fp = createHash("sha256").update(stableStringify({ version: "INITIAL-CONSTRUCTION-STAGE2-FIRST-PARTIAL-PLAN-FINGERPRINT-V2", anchor: built.selectedAnchorTaskId, closure: built.closureTaskIds, attempts: attempt.attempts.map((a: any) => ({ branchId: a.branchId, status: a.status, rejectionReason: a.rejectionReason, assignmentCount: a.assignmentCount, validation: a.validation?.result, future: a.futureFeasibility?.status, lineage: a.lineageCoherent })) })).digest("hex");
  return deepFreeze({ version: "INITIAL-CONSTRUCTION-STAGE2-FIRST-PARTIAL-PLAN-V3", executed: true, executedBeforeV4: true, inputSource: "original-engine-input-and-origin-operational-state", v4SeedUsed: false, selectedAnchorTaskId: built.selectedAnchorTaskId, stage1SelectedAnchorTaskId: anchor.anchorTaskId ?? null, anchorMatchesStage1: built.selectedAnchorTaskId === anchor.anchorTaskId, closureTaskIds: built.closureTaskIds, closureTaskCount: built.closureTaskIds.length, topologicalTaskOrder: built.topologicalTaskOrder, branchCandidateCount: built.branches.length, attemptedBranchCount: attempt.attempts.length, closureIncompleteBranchCount: built.branches.filter((b: any) => b.status === "closure-incomplete").length, completeClosureBranchCount: built.branches.filter((b: any) => b.searchEvidence?.closureComplete === true).length, recursiveAssignmentBacktrackCount: recursive, recursiveBacktrackCount: recursive, totalTemporalDecisionBacktrackCount: temporal, totalResourceDecisionBacktrackCount: resource, totalPlacementAttemptCount: placement, totalRepeatedStatePruneCount: prune, unsupportedBranchCount: built.branches.filter((b: any) => b.status === "unsupported").length, hardInvalidBranchCount: attempt.attempts.filter((a: any) => a.rejectionReason === "hard-invalid").length, futureInfeasibleBranchCount: attempt.attempts.filter((a: any) => a.rejectionReason === "future-infeasible").length, futureUnknownBranchCount: attempt.attempts.filter((a: any) => a.futureFeasibility?.status === "UNKNOWN").length, hardValidBranchCount: attempt.hardValidBranchCount, selectedBranchId: selected?.branch.branchId ?? null, selectedPartialPlanId: selected?.partialPlanId ?? null, selectedAssignmentCount: selected?.branch.assignments.length ?? 0, selectedAssignments: selected?.branch.assignments ?? [], selectedAssignmentsSample: (selected?.branch.assignments ?? []).slice(0, SAMPLE_LIMIT), selectedValidation: selected?.validation ?? null, selectedValidationResult: selected?.validation.result ?? null, selectedFutureFeasibility: selected?.futureFeasibility ?? null, selectedFutureFeasibilityStatus: selected?.futureFeasibility?.status ?? null, checkedFutureFeasibilityDimensions: selected?.futureFeasibility?.checkedDimensions ?? [...CHECKED_FUTURE_DIMENSIONS], uncoveredFutureFeasibilityDimensions: selected?.futureFeasibility?.uncoveredDimensions ?? [...UNCOVERED_FUTURE_DIMENSIONS], branchRetryCount: branchesRejectedBeforeSelection, branchesRejectedBeforeSelection, backtrackCount: branchesRejectedBeforeSelection, transformationsExecuted: attempt.transformationsExecuted, simulationsExecuted: attempt.simulationsExecuted, validationsExecuted: attempt.validationsExecuted, commitsExecuted: 0, branchAttempts: attempt.attempts.slice(0, SAMPLE_LIMIT), structuralFingerprint: fp, branchBuilderFingerprint: built.structuralFingerprint, capabilityAudit, warnings: capabilityAudit.warnings, readOnly: true }) as any;
}
