import test from "node:test"; import assert from "node:assert/strict"; import type { EngineInput } from "../../types"; import { buildOperationalStateFromEngineInput } from "../adapters/fromEngineInput"; import { stableStringify } from "../structuralEquality"; import { buildInitialConstructionStage1StructuralFingerprint, initialConstructionSemanticIntegrityAudit, runInitialConstructionStage1 } from "./runInitialConstructionStage1";
const scenario=(end="10:00"):EngineInput=>({planId:1,workDay:{start:"08:00",end:"18:00"},meal:{start:"13:00",end:"14:00"},camerasAvailable:1,optimizerMainZoneId:5,optimizerMainZonePriorityLevel:3,contestantAvailabilityById:{1:{start:"08:00",end},2:{start:"08:00",end:"18:00"}},tasks:[{id:2,planId:1,templateId:20,status:"pending",durationOverrideMin:30,contestantId:1,spaceId:4,resourceRequirements:{byItem:{7:1}}},{id:1,planId:1,templateId:10,status:"pending",durationOverrideMin:60,contestantId:1,spaceId:5,dependsOnTaskIds:[2],resourceRequirements:{anyOf:[{quantity:1,resourceItemIds:[7,8]}]}},{id:3,planId:1,templateId:10,status:"pending",durationOverrideMin:60,contestantId:2,spaceId:5}],locks:[],zoneResourceAssignments:{},spaceResourceAssignments:{},zoneResourceTypeRequirements:{},spaceResourceTypeRequirements:{},planResourceItems:[{id:7,resourceItemId:7,typeId:1,name:"R7",isAvailable:true},{id:8,resourceItemId:8,typeId:1,name:"R8",isAvailable:true}],resourceItemComponents:{},groupingZoneIds:[],maxTemplateChangesByZoneId:{5:0}});
const run=(i:EngineInput)=>runInitialConstructionStage1({originInput:i,originOperationalState:buildOperationalStateFromEngineInput(i),createdAt:null});
test("stage 1 builds map, dependencies, anchors and read-only search spaces without planning",()=>{ const r:any=run(scenario()); assert.equal(r.planningMode,"INITIAL_CONSTRUCTION"); assert.equal(r.initialConstructionMap.originPlanningCount,0); assert.ok(r.initialConstructionMap.dependencyGraph.directDependencyEdgeCount>=1); assert.ok(r.initialConstructionMap.contestantPressure.length>0); assert.ok(r.initialConstructionMap.resourcePressure.length>0); assert.ok(r.initialConstructionMap.spacePressure.length>0); assert.ok(r.anchors.length>0); assert.ok(r.searchSpaces.length>0); assert.equal(r.evidence[0].transformationsExecuted,0); assert.equal(r.evidence[0].commitsExecuted,0); });
test("direct dependency direction makes prerequisite closure for dependent anchor",()=>{ const r:any=run(scenario()); const a=r.anchors.find((x:any)=>x.anchorTaskId===1); assert.ok(a.transitivePrerequisiteTaskIds.includes(2)); });
test("stage 1 is independent of artificial V4 outputs",()=>{ const a:any=run(scenario()); const b:any=run(scenario()); assert.equal(stableStringify({map:a.initialConstructionMap,anchors:a.anchors,spaces:a.searchSpaces,evidence:a.evidence}), stableStringify({map:b.initialConstructionMap,anchors:b.anchors,spaces:b.searchSpaces,evidence:b.evidence})); });
test("dynamic criticality changes with real availability",()=>{ const tight:any=run(scenario("09:40")); const loose:any=run(scenario("18:00")); assert.notEqual(tight.initialConstructionMap.contestantPressure[0].slackMinutes, loose.initialConstructionMap.contestantPressure.find((c:any)=>c.contestantId===1).slackMinutes); });

test("semantic audit rejects incoherent main-flow and inventory evidence",()=>{ const r:any=JSON.parse(JSON.stringify(run(scenario()))); r.initialConstructionMap.mainFlowPressure.mainFlowSpaceIds=[]; r.initialConstructionMap.mainFlowPressure.mainFlowProductiveTaskIds=[]; r.initialConstructionMap.mainFlowPressure.mainFlowAnchorEligibleTaskIds=[]; r.initialConstructionMap.inputCatalog.resourceInventory=[]; const audit:any=initialConstructionSemanticIntegrityAudit(r); assert.equal(audit.coherent,false); assert.ok(audit.failureCodes.includes("main_flow_classification_invalid") || audit.failureCodes.includes("resource_inventory_invalid")); });
test("stage 1 structural fingerprint is stable across repeated equivalent runs",()=>{ const a:any=run(scenario()); const b:any=run(scenario()); assert.equal(buildInitialConstructionStage1StructuralFingerprint(a), buildInitialConstructionStage1StructuralFingerprint(b)); assert.equal(a.evidence[0].stage1StructuralFingerprint,b.evidence[0].stage1StructuralFingerprint); });
