import test from "node:test"; import assert from "node:assert/strict"; import type { EngineInput } from "../../types"; import { buildOperationalStateFromEngineInput } from "../adapters/fromEngineInput"; import { stableStringify } from "../structuralEquality"; import { buildInitialConstructionStage1StructuralFingerprint, initialConstructionSemanticIntegrityAudit, runInitialConstructionStage1 } from "./runInitialConstructionStage1";
const scenario=(end="10:00"):EngineInput=>({planId:1,workDay:{start:"08:00",end:"18:00"},meal:{start:"13:00",end:"14:00"},camerasAvailable:1,optimizerMainZoneId:5,optimizerMainZonePriorityLevel:3,contestantAvailabilityById:{1:{start:"08:00",end},2:{start:"08:00",end:"18:00"}},tasks:[{id:2,planId:1,templateId:20,status:"pending",durationOverrideMin:30,contestantId:1,spaceId:4,resourceRequirements:{byItem:{7:1}}},{id:1,planId:1,templateId:10,status:"pending",durationOverrideMin:60,contestantId:1,spaceId:5,dependsOnTaskIds:[2],resourceRequirements:{anyOf:[{quantity:1,resourceItemIds:[7,8]}]}},{id:3,planId:1,templateId:10,status:"pending",durationOverrideMin:60,contestantId:2,spaceId:5}],locks:[],zoneResourceAssignments:{},spaceResourceAssignments:{},zoneResourceTypeRequirements:{},spaceResourceTypeRequirements:{},planResourceItems:[{id:7,resourceItemId:7,typeId:1,name:"R7",isAvailable:true},{id:8,resourceItemId:8,typeId:1,name:"R8",isAvailable:true}],resourceItemComponents:{},groupingZoneIds:[],maxTemplateChangesByZoneId:{5:0}});
const run=(i:EngineInput)=>runInitialConstructionStage1({originInput:i,originOperationalState:buildOperationalStateFromEngineInput(i),createdAt:null});
test("stage 1 builds map, dependencies, anchors and read-only search spaces without planning",()=>{ const r:any=run(scenario()); assert.equal(r.planningMode,"INITIAL_CONSTRUCTION"); assert.equal(r.initialConstructionMap.originPlanningCount,0); assert.ok(r.initialConstructionMap.dependencyGraph.directDependencyEdgeCount>=1); assert.ok(r.initialConstructionMap.contestantPressure.length>0); assert.ok(r.initialConstructionMap.resourcePressure.length>0); assert.ok(r.initialConstructionMap.spacePressure.length>0); assert.ok(r.anchors.length>0); assert.ok(r.searchSpaces.length>0); assert.equal(r.evidence[0].transformationsExecuted,0); assert.equal(r.evidence[0].commitsExecuted,0); });
test("direct dependency direction makes prerequisite closure for dependent anchor",()=>{ const r:any=run(scenario()); const a=r.anchors.find((x:any)=>x.anchorTaskId===1); assert.ok(a.transitivePrerequisiteTaskIds.includes(2)); });
test("stage 1 is independent of artificial V4 outputs",()=>{ const a:any=run(scenario()); const b:any=run(scenario()); assert.equal(stableStringify({map:a.initialConstructionMap,anchors:a.anchors,spaces:a.searchSpaces,evidence:a.evidence}), stableStringify({map:b.initialConstructionMap,anchors:b.anchors,spaces:b.searchSpaces,evidence:b.evidence})); });
test("dynamic criticality changes with real availability",()=>{ const tight:any=run(scenario("09:40")); const loose:any=run(scenario("18:00")); assert.notEqual(tight.initialConstructionMap.contestantPressure[0].slackMinutes, loose.initialConstructionMap.contestantPressure.find((c:any)=>c.contestantId===1).slackMinutes); });

test("semantic audit rejects incoherent main-flow and inventory evidence",()=>{ const r:any=JSON.parse(JSON.stringify(run(scenario()))); r.initialConstructionMap.mainFlowPressure.mainFlowSpaceIds=[]; r.initialConstructionMap.mainFlowPressure.mainFlowProductiveTaskIds=[]; r.initialConstructionMap.mainFlowPressure.mainFlowAnchorEligibleTaskIds=[]; r.initialConstructionMap.inputCatalog.resourceInventory=[]; const audit:any=initialConstructionSemanticIntegrityAudit(r); assert.equal(audit.coherent,false); assert.ok(audit.failureCodes.includes("main_flow_classification_invalid") || audit.failureCodes.includes("resource_inventory_invalid")); });
test("stage 1 structural fingerprint is stable across repeated equivalent runs",()=>{ const a:any=run(scenario()); const b:any=run(scenario()); assert.equal(buildInitialConstructionStage1StructuralFingerprint(a), buildInitialConstructionStage1StructuralFingerprint(b)); assert.equal(a.evidence[0].stage1StructuralFingerprint,b.evidence[0].stage1StructuralFingerprint); });

test("semantic audit accepts valid inventory and rejects manipulated resource mapping",()=>{ const r:any=run(scenario()); let audit:any=initialConstructionSemanticIntegrityAudit(r); assert.equal(audit.resourceInventoryValid,true); assert.equal(audit.coherent,true); const broken:any=JSON.parse(JSON.stringify(r)); broken.initialConstructionMap.inputCatalog.planResourceItemById[7].resourceItemId=999; audit=initialConstructionSemanticIntegrityAudit(broken); assert.equal(audit.resourceInventoryValid,false); assert.ok(audit.failureCodes.includes("resource_inventory_invalid")); });

test("semantic audit rejects swapped anchor order and protected window crossings",()=>{ const r:any=JSON.parse(JSON.stringify(run(scenario()))); assert.equal(initialConstructionSemanticIntegrityAudit(r).anchorComparatorDirectionValid,true); if(r.anchors.length>1){ [r.anchors[0],r.anchors[1]]=[r.anchors[1],r.anchors[0]]; const audit:any=initialConstructionSemanticIntegrityAudit(r); assert.equal(audit.anchorComparatorDirectionValid,false); assert.ok(audit.failureCodes.includes("anchor_comparator_invalid")); } const crossed:any=JSON.parse(JSON.stringify(run(scenario()))); crossed.searchSpaces[0].protectedIntervalsApplied=[{start:"08:30",end:"09:00",scope:"global",contestantId:null,spaceId:null,source:"test",readOnly:true}]; crossed.searchSpaces[0].provisionalWindows=[{start:"08:00",end:"09:30",source:"test"}]; const audit:any=initialConstructionSemanticIntegrityAudit(crossed); assert.equal(audit.protectedIntervalsExcluded,false); assert.ok(audit.failureCodes.includes("protected_interval_crossed")); });

test("semantic audit rejects manipulated critical path and omitted main-flow task",()=>{ const r:any=JSON.parse(JSON.stringify(run(scenario()))); r.initialConstructionMap.dependencyGraph.nodes.find((n:any)=>n.taskId===1).totalCriticalPathMinutes=1; let audit:any=initialConstructionSemanticIntegrityAudit(r); assert.equal(audit.criticalPathSemanticsValid,false); const omitted:any=JSON.parse(JSON.stringify(run(scenario()))); omitted.initialConstructionMap.mainFlowPressure.mainFlowProductiveTaskIds=omitted.initialConstructionMap.mainFlowPressure.mainFlowProductiveTaskIds.slice(1); audit=initialConstructionSemanticIntegrityAudit(omitted); assert.equal(audit.mainFlowProductiveClassificationValid,false); });

test("stage 1 fingerprint is compact hex and changes when payload changes",()=>{ const r:any=run(scenario()); const fp=buildInitialConstructionStage1StructuralFingerprint(r); assert.match(fp,/^[a-f0-9]{64}$/); const changed:any=JSON.parse(JSON.stringify(r)); changed.searchSpaces[0].excludedProtectedIntervalCount=(changed.searchSpaces[0].excludedProtectedIntervalCount??0)+1; assert.notEqual(buildInitialConstructionStage1StructuralFingerprint(changed),fp); assert.ok(Object.keys(r.evidence[0].dependencyCounters).length>0); assert.ok(r.evidence[0].stage1FingerprintPayloadByteLength>64); });

test("stage 1 files do not contain unconditional true disjunctions",async()=>{ const fs=await import("node:fs"); for(const file of ["engine/orc/active/runInitialConstructionStage1.ts","engine/orc/see/initialConstructionAnchorSelector.ts","engine/orc/see/initialConstructionSearchSpace.ts"]){ assert.equal(fs.readFileSync(file,"utf8").includes("|| true"),false,file); } });

test("canonical main-flow audit classifies synthetic meal without legacy fields and dependency counters publish non-applicable refs",()=>{ const input:any=scenario(); input.mealMode="flexible_meal_window"; input.mealWindow={start:"13:00",end:"16:30"}; input.tasks.push({id:-10,planId:1,templateId:999,status:"pending",durationOverrideMin:75,spaceId:5,start:"13:00",end:"14:15"}); input.tasks.push({id:4,planId:1,templateId:40,status:"pending",durationOverrideMin:10,contestantId:2,spaceId:4,dependsOnTemplateIds:[123456]}); const r:any=run(input); assert.equal(r.initialConstructionMap.mainFlowPressure.mainFlowProtectedDowntimeTaskIds.includes(-10),true); assert.equal(r.initialConstructionMap.mainFlowPressure.mainFlowProductiveTaskIds.includes(-10),false); assert.equal(initialConstructionSemanticIntegrityAudit(r).coherent,true); assert.equal(r.evidence[0].dependencyCounters.nonApplicableTemplateReferences,1); assert.equal(r.evidence[0].nonApplicableTemplateDependencyReferences,1); });
