import type { EngineInput } from "../../types";
import type { OperationalState, ReasoningBudgetProfile } from "../contracts";
import { composePartialPlans } from "../see/partialPlanComposer";
import { buildCandidateStates } from "../transformation/transformationEngine";
import { simulateCandidateStates } from "../simulation/simulationEngine";
import { validateSimulatedStates } from "../validation/validationEngine";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { createHash } from "node:crypto";
import { branchToCandidate, buildInitialConstructionBranches } from "../see/initialConstructionBranchBuilder";
import { initialConstructionSemanticIntegrityAudit } from "./runInitialConstructionStage1";

const min=(s?:string|null)=>/^\d{2}:\d{2}$/.test(String(s??""))?Number(String(s).slice(0,2))*60+Number(String(s).slice(3)):null;
const dur=(t:any)=>Number(t?.durationOverrideMin??t?.durationMin??t?.durationMinutes??t?.duration??0)||0;
function preliminaryFutureFeasibility(input:EngineInput, branch:any){ const assigned=new Set(branch.assignments.map((a:any)=>a.taskId)); const pending=(input.tasks??[]).filter((t:any)=>(t.status==="pending"||t.status==="interrupted")&&!assigned.has(t.id)); const reasons:string[]=[]; for(const t of pending){ const req=t.resourceRequirements??{}; for(const rid of Object.keys(req.byItem??{})){ if(!(input.planResourceItems??[]).some(x=>x.isAvailable!==false&&x.resourceItemId===Number(rid))) reasons.push("RESOURCE_WITHOUT_INVENTORY"); } }
 const byContestant=new Map<number,number>(); for(const t of pending){ if(t.contestantId!=null) byContestant.set(Number(t.contestantId),(byContestant.get(Number(t.contestantId))??0)+dur(t)); }
 for(const [cid,load] of byContestant){ const av=(input.contestantAvailabilityById??{})[cid]; const end=Math.max(...branch.assignments.filter((a:any)=>(input.tasks??[]).find(t=>t.id===a.taskId)?.contestantId===cid).map((a:any)=>min(a.endPlanned)??min(input.workDay.start)!), min(input.workDay.start)!); const cap=(min(av?.end??input.workDay.end)??min(input.workDay.end)!)-end; if(load>cap) reasons.push("CONTESTANT_REMAINING_LOAD_EXCEEDS_AVAILABILITY"); }
 return {status:reasons.length?"INFEASIBLE":"FEASIBLE",preliminary:true,reasons:[...new Set(reasons)].sort().slice(0,10),readOnly:true}; }
export function runInitialConstructionStage2FirstPartialPlan(args:{originInput:EngineInput; originOperationalState:OperationalState; stage1:any; reasoningBudget?:ReasoningBudgetProfile|null; createdAt?:string|null}){ const audit=initialConstructionSemanticIntegrityAudit(args.stage1); const anchor=args.stage1.selectedAnchor; const hasSpace=(args.stage1.searchSpaces??[]).some((s:any)=>s.anchorTaskId===anchor?.anchorTaskId); if(args.stage1.planningMode!=="INITIAL_CONSTRUCTION"||!audit.coherent||!anchor||!hasSpace){ return deepFreeze({executed:false,reason:"stage2_preconditions_not_met",selectedAnchorTaskId:anchor?.anchorTaskId??null,readOnly:true}) as any; }
 const max=Math.max(2, Math.min(8, args.reasoningBudget?.maxCandidates??6)); const built=buildInitialConstructionBranches({input:args.originInput,originOperationalState:args.originOperationalState,stage1:args.stage1,maxBranches:max}); const attempts:any[]=[]; let selected:any=null; let hardValid=0, futureFeasible=0, rejected=0; const valid:any[]=[];
 for(const branch of built.branches){ const attempt:any={branchId:branch.branchId,status:branch.status,assignmentCount:branch.assignments.length,rejectionReason:branch.rejectionReason??null,validation:null,futureFeasibility:null,partialPlanId:null}; if(branch.status!=="candidate"){ rejected++; attempts.push(attempt); continue; } const candidate=branchToCandidate(branch); const pp=composePartialPlans([candidate],{createdAt:args.createdAt??null,maxPartialPlans:1}); const states=buildCandidateStates(args.originOperationalState,[candidate],{createdAt:args.createdAt??null,maxTransformations:1}); const sims=simulateCandidateStates(args.originOperationalState,states.candidateStates,{createdAt:args.createdAt??null,maxSimulations:1}); const vals=validateSimulatedStates(sims.simulatedStates,{createdAt:args.createdAt??null}); const val=vals.validationResults[0]??null; attempt.partialPlanId=pp.partialPlans[0]?.partialPlanId??null; attempt.validation={result:val?.result??"INVALID",violatedConstraints:(val?.violatedConstraints??[]).slice(0,10)}; if(val?.result==="VALID"){ hardValid++; const ff=preliminaryFutureFeasibility(args.originInput,branch); attempt.futureFeasibility=ff; if(ff.status==="FEASIBLE") futureFeasible++; valid.push({branch,candidate,partialPlan:pp.partialPlans[0],validation:val,futureFeasibility:ff}); } else { rejected++; attempt.rejectionReason="hard-invalid"; }
 attempts.push(attempt); }
 valid.sort((a,b)=>(a.futureFeasibility.status==="FEASIBLE"?0:1)-(b.futureFeasibility.status==="FEASIBLE"?0:1)|| (min(a.branch.assignments.find((x:any)=>x.taskId===built.selectedAnchorTaskId)?.endPlanned)??9999)-(min(b.branch.assignments.find((x:any)=>x.taskId===built.selectedAnchorTaskId)?.endPlanned)??9999)||a.branch.branchId.localeCompare(b.branch.branchId)); selected=valid[0]??null; const unsupported=[...new Set(built.branches.flatMap(b=>b.unsupportedRequirementCodes))].sort(); const payload={version:"INITIAL-CONSTRUCTION-STAGE2-FIRST-PARTIAL-PLAN-FINGERPRINT-V1",anchor:built.selectedAnchorTaskId,closure:built.closureTaskIds,attempts:attempts.map(a=>({branchId:a.branchId,status:a.status,rejectionReason:a.rejectionReason,assignmentCount:a.assignmentCount,validation:a.validation?.result,future:a.futureFeasibility?.status}))}; const fingerprint=createHash("sha256").update(stableStringify(payload)).digest("hex"); return deepFreeze({executed:true,selectedAnchorTaskId:built.selectedAnchorTaskId,closureTaskIds:built.closureTaskIds,topologicalTaskOrder:built.topologicalTaskOrder,branchCandidateCount:built.branches.length,attemptedBranchCount:attempts.length,rejectedBranchCount:rejected,hardValidBranchCount:hardValid,futureFeasibleBranchCount:futureFeasible,backtrackCount:Math.max(0,attempts.findIndex(a=>a.branchId===selected?.branch.branchId)),branchAttempts:attempts,selectedBranchId:selected?.branch.branchId??null,selectedPartialPlanId:selected?.partialPlan?.partialPlanId??null,selectedAssignments:selected?.branch.assignments??[],selectedValidation:selected?.validation??null,selectedFutureFeasibility:selected?.futureFeasibility??null,unsupportedRequirementCodes:unsupported,structuralFingerprint:fingerprint,branchBuilderFingerprint:built.structuralFingerprint,readOnly:true}) as any; }
