import test from "node:test"; import assert from "node:assert/strict";
import { buildOperationalStateFromEngineInput } from "../adapters/fromEngineInput";
import { runInitialConstructionStage2FirstPartialPlan } from "./runInitialConstructionStage2FirstPartialPlan";
import { runInitialConstructionIterativeSession } from "./runInitialConstructionIterativeSession";
import { runInitialConstructionStage1 } from "./runInitialConstructionStage1";
const input:any={planId:1,workDay:{start:"09:00",end:"14:00"},meal:{start:"13:00",end:"14:00"},contestantAvailabilityById:{1:{start:"09:00",end:"14:00"},2:{start:"09:00",end:"14:00"}},planResourceItems:[],tasks:[{id:1,planId:1,templateId:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:20,dependsOnTaskIds:[2]},{id:2,planId:1,templateId:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:20},{id:3,planId:1,templateId:3,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:20},{id:4,planId:1,templateId:4,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:20,dependsOnTaskIds:[3]}]};
const state:any=buildOperationalStateFromEngineInput(input); const stage1:any=runInitialConstructionStage1({originInput:input,originOperationalState:state,createdAt:"fixed"});
test("iterative session recomputes residuals, accepts combined plans, and is deterministic/read-only",()=>{ const before=JSON.stringify({input,state}); const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const a=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:2,maxCandidates:4},createdAt:"fixed"}); const b=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:2,maxCandidates:4},createdAt:"fixed"}); assert.equal(a.executed,true); assert.ok(a.evidence.acceptedCycleCount>=1); assert.ok(a.evidence.finalCombinedAssignmentCount>stage2.selectedAssignmentCount); assert.equal(a.evidence.commitsExecuted,0); assert.equal(a.evidence.publicPlanningUsesIterativeSession,false); assert.equal(a.evidence.sessionFingerprint,b.evidence.sessionFingerprint); assert.notEqual(a.evidence.cycles[0]?.residualFingerprint,null); assert.equal(JSON.stringify({input,state}),before); });
test("iterative session explains budget exhaustion",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:0,maxCandidates:1},createdAt:"fixed"}); assert.equal(r.evidence.stopReason,"BUDGET_EXHAUSTED"); assert.equal(r.evidence.budgetLimitReached,"MAX_ACCEPTED_CYCLES"); assert.equal(r.combinedPartialPlan.assignments.length, stage2.selectedAssignmentCount); });


test("iterative session respects maxAcceptedCycles = 1",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:1,maxCandidates:4} as any,createdAt:"fixed"}); assert.ok(r.evidence.acceptedCycleCount<=1); assert.equal(r.evidence.budgetLimitReached,"MAX_ACCEPTED_CYCLES"); });

test("iterative session preserves valid partial plan on elapsed budget exhaustion",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:24,maxElapsedMs:0,maxCandidates:4} as any,createdAt:"fixed"}); assert.equal(r.evidence.stopReason,"BUDGET_EXHAUSTED"); assert.equal(r.evidence.budgetLimitReached,"MAX_ELAPSED_MS"); assert.equal(r.evidence.finalCombinedValidationResult,"VALID"); assert.ok(r.combinedPartialPlan.assignments.length>=stage2.selectedAssignmentCount); });

test("larger constructive budget does not reduce valid assignments for the same input",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const small=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:1,maxCandidates:4} as any,createdAt:"fixed"}); const large=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:4,maxCandidates:4} as any,createdAt:"fixed"}); assert.ok(large.evidence.finalCombinedAssignmentCount>=small.evidence.finalCombinedAssignmentCount); });
