import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { selectInitialConstructionAnchors } from "../see/initialConstructionAnchorSelector";
import { buildInitialConstructionMap } from "../understanding/initialConstructionMap";
import { buildInitialConstructionResidualContext } from "../understanding/initialConstructionResidualContext";
import { buildInitialConstructionSearchSpaces } from "../see/initialConstructionSearchSpace";
const sample=(a:any[])=>[...(a??[])].slice(0,10);
function hash(x:any){return createHash("sha256").update(stableStringify(x)).digest("hex");}
export function runInitialConstructionStage3ResidualAnchorSelection(args:{originInput:EngineInput; originOperationalState:OperationalState; stage1:any; stage2:any}){
 if(args.stage2?.executed!==true||args.stage2?.selectedValidationResult!=="VALID"||!args.stage2?.selectedPartialPlanId) return deepFreeze({version:"INITIAL-CONSTRUCTION-STAGE3-RESIDUAL-ANCHOR-SELECTION-V1",executed:false,reason:"stage2_hard_valid_partial_plan_required",readOnly:true}) as any;
 const residualContext=buildInitialConstructionResidualContext({originInput:args.originInput,originOperationalState:args.originOperationalState,stage2:args.stage2});
 const residualMap:any=buildInitialConstructionMap({input:args.originInput,state:args.originOperationalState,planningMode:"INITIAL_CONSTRUCTION",provisionalAssignments:residualContext.provisionalAssignments,provisionallyAssignedTaskIds:residualContext.provisionallyAssignedTaskIds});
 const residualAnchors:any[]=selectInitialConstructionAnchors({input:args.originInput,initialConstructionMap:residualMap,maxAnchors:20});
 const residualSearchSpaces:any[]=buildInitialConstructionSearchSpaces({input:args.originInput,anchors:residualAnchors,initialConstructionMap:residualMap,maxSearchSpaces:20,maxWindowsPerAnchor:20});
 const firstClosure=new Set(residualContext.firstClosureTaskIds);
 const selected=residualAnchors.find(a=>!firstClosure.has(a.anchorTaskId))??null;
 const original=(args.stage1?.anchors??[]).find((a:any)=>!firstClosure.has(a.anchorTaskId))?.anchorTaskId??null;
 const node=(residualMap.dependencyGraph?.nodes??[]).find((n:any)=>n.taskId===selected?.anchorTaskId);
 const allPre=node?.transitivePrerequisiteTaskIds??[]; const sat=allPre.filter((id:number)=>residualContext.provisionallyAssignedTaskIds.includes(id)); const rem=allPre.filter((id:number)=>!sat.includes(id));
 const residualMapFingerprint=hash({version:"RESIDUAL-MAP-FP-V1",pending:residualMap.pendingTaskCount,productive:residualMap.mainFlowPressure?.mainFlowProductiveTaskIds,contestant:residualMap.contestantPressure,resource:residualMap.resourcePressure,space:residualMap.spacePressure,regions:residualMap.bottleneckRegions?.map((r:any)=>({id:r.id,kind:r.kind,relatedTaskIds:r.relatedTaskIds}))});
 const reason=selected?selected.selectionReason:"NO_RESIDUAL_ANCHOR";
 return deepFreeze({version:"INITIAL-CONSTRUCTION-STAGE3-RESIDUAL-ANCHOR-SELECTION-V1",executed:true,executedBeforeV4:true,inputSource:"original-engine-input-and-stage2-partial-plan",v4SeedUsed:false,residualContext,residualMap,residualAnchors,residualSearchSpaces,selectedAnchor:selected?{...selected,allPrerequisiteTaskIds:allPre,satisfiedByFirstPartialPlanTaskIds:sat,remainingPrerequisiteTaskIds:rem,directDependents:node?.directDependentTaskIds??[],mainFlow:selected.mainFlow,selectionReason:reason,decisiveDimension:selected.decisiveDimension}:null,evidence:{version:"INITIAL-CONSTRUCTION-STAGE3-EVIDENCE-V1",executed:true,executedBeforeV4:true,inputSource:"original_engine_input_stage2_partial_plan",v4SeedUsed:false,basePartialPlanId:residualContext.basePartialPlanId,firstAnchorTaskId:residualContext.firstAnchorTaskId,firstClosureTaskIds:sample(residualContext.firstClosureTaskIds as any),provisionalAssignmentCount:residualContext.provisionalAssignments.length,residualPendingTaskCount:residualContext.residualPendingTaskIds.length,residualProductiveTaskCount:residualMap.pendingTaskCount,residualMainFlowTaskCount:residualContext.residualMainFlowTaskIds.length,provisionallySatisfiedDependencyCount:sat.length,residualBottleneckRegionCount:residualMap.bottleneckRegions?.length??0,residualBottleneckRegionKinds:sample([...(new Set((residualMap.bottleneckRegions??[]).map((r:any)=>r.kind))) as any]),originalStage1NextEligibleAnchorTaskId:original,residualSelectedAnchorTaskId:selected?.anchorTaskId??null,secondAnchorMainFlow:selected?.mainFlow??null,secondAnchorContestantId:selected?.contestantId??null,secondAnchorSelectionReason:reason,secondAnchorDecisiveDimension:selected?.decisiveDimension??null,secondAnchorAllPrerequisiteTaskIds:sample(allPre),secondAnchorSatisfiedPrerequisiteTaskIds:sample(sat),secondAnchorRemainingPrerequisiteTaskIds:sample(rem),selectionChangedAfterResidualRecalculation:(selected?.anchorTaskId??null)!==original,residualSelectionSource:"recomputed_residual_operational_map",residualMapFingerprint,transformationsExecuted:0,simulationsExecuted:0,validationsExecuted:0,commitsExecuted:0,warnings:[],readOnly:true},readOnly:true}) as any;
}
