import test from "node:test"; import assert from "node:assert/strict";
import { buildOperationalStateFromEngineInput } from "../adapters/fromEngineInput";
import { runInitialConstructionStage2FirstPartialPlan } from "./runInitialConstructionStage2FirstPartialPlan";
import { runInitialConstructionIterativeSession } from "./runInitialConstructionIterativeSession";
import { runInitialConstructionStage1 } from "./runInitialConstructionStage1";
const input:any={planId:1,workDay:{start:"09:00",end:"14:00"},meal:{start:"13:00",end:"14:00"},contestantAvailabilityById:{1:{start:"09:00",end:"14:00"},2:{start:"09:00",end:"14:00"}},planResourceItems:[],tasks:[{id:1,planId:1,templateId:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:20,dependsOnTaskIds:[2]},{id:2,planId:1,templateId:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:20},{id:3,planId:1,templateId:3,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:20},{id:4,planId:1,templateId:4,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:20,dependsOnTaskIds:[3]}]};
const state:any=buildOperationalStateFromEngineInput(input); const stage1:any=runInitialConstructionStage1({originInput:input,originOperationalState:state,createdAt:"fixed"});
test("iterative session recomputes residuals, accepts combined plans, and is deterministic/read-only",()=>{ const before=JSON.stringify({input,state}); const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const a=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:2,maxCandidates:4},createdAt:"fixed"}); const b=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:2,maxCandidates:4},createdAt:"fixed"}); assert.equal(a.executed,true); assert.ok(a.evidence.acceptedCycleCount>=1); assert.ok(a.evidence.finalCombinedAssignmentCount>stage2.selectedAssignmentCount); assert.equal(a.evidence.commitsExecuted,0); assert.equal(a.evidence.publicPlanningUsesIterativeSession,false); assert.equal(a.evidence.sessionFingerprint,b.evidence.sessionFingerprint); assert.notEqual(a.evidence.cycles[0]?.residualFingerprint,null); assert.equal(JSON.stringify({input,state}),before); });
test("iterative session explains budget exhaustion",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:0,maxCandidates:1},createdAt:"fixed"}); assert.equal(r.evidence.stopReason,"BUDGET_EXHAUSTED"); assert.equal(r.evidence.budgetLimitReached,"MAX_ACCEPTED_CYCLES"); assert.equal(r.combinedPartialPlan.assignments.length, stage2.selectedAssignmentCount); });


test("iterative session respects maxAcceptedCycles = 1",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:1,maxCandidates:4} as any,createdAt:"fixed"}); assert.ok(r.evidence.acceptedCycleCount<=1); assert.equal(r.evidence.budgetLimitReached,"MAX_ACCEPTED_CYCLES"); });

test("iterative session preserves valid partial plan on elapsed budget exhaustion",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:24,maxElapsedMs:0,maxCandidates:4} as any,createdAt:"fixed"}); assert.equal(r.evidence.stopReason,"BUDGET_EXHAUSTED"); assert.equal(r.evidence.budgetLimitReached,"MAX_ELAPSED_MS"); assert.equal(r.evidence.finalCombinedValidationResult,"VALID"); assert.ok(r.combinedPartialPlan.assignments.length>=stage2.selectedAssignmentCount); });

test("larger constructive budget does not reduce valid assignments for the same input",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const small=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:1,maxCandidates:4} as any,createdAt:"fixed"}); const large=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:4,maxCandidates:4} as any,createdAt:"fixed"}); assert.ok(large.evidence.finalCombinedAssignmentCount>=small.evidence.finalCombinedAssignmentCount); });

test("iterative session exposes progressive widening evidence and preserves final valid validation",()=>{ const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxAcceptedCycles:2,anchorBatchSize:1,maxAnchorRanksScannedPerCycle:4} as any,createdAt:"fixed"}); const c=r.evidence.cycles[0]; assert.ok(c.anchorBatchSize===1); assert.ok(c.wideningBatches.length>=1); assert.ok(c.anchorRanksScanned<=4); assert.equal(r.evidence.finalCombinedValidationResult,"VALID"); assert.equal(r.evidence.terminalCycleAccepted, (r.evidence.cycles.at(-1)?.acceptedAnchorTaskId??null)!=null); });

test("scan limit is not reported as no viable anchor when eligible ranks remain",()=>{ const many:any={...input,tasks:Array.from({length:8},(_,i)=>({id:i+1,planId:1,templateId:i+1,status:"pending",contestantId:(i%2)+1,spaceId:(i%2)+1,durationOverrideMin:20}))}; const st:any=buildOperationalStateFromEngineInput(many); const s1:any=runInitialConstructionStage1({originInput:many,originOperationalState:st,createdAt:"fixed"}); const s2=runInitialConstructionStage2FirstPartialPlan({originInput:many,originOperationalState:st,stage1:s1,createdAt:"fixed"}); const r=runInitialConstructionIterativeSession({originInput:many,originOperationalState:st,stage1:s1,stage2:s2,reasoningBudget:{maxAcceptedCycles:1,anchorBatchSize:1,maxAnchorRanksScannedPerCycle:1,maxTotalAnchorAttempts:1} as any,createdAt:"fixed"}); assert.notEqual(r.evidence.stopReason,"NO_VIABLE_ANCHOR"); assert.ok(["MAX_ANCHOR_ATTEMPTS","MAX_ACCEPTED_CYCLES","MAX_ANCHOR_RANKS_SCANNED"].includes(r.evidence.budgetLimitReached)); });

test("retained-alternatives budget gives explicit top-level values precedence",()=>{
 const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"});
 const requested={maxElapsedMs:1234,maxSuspendedPartialPlans:7,maxTotalConstructivePartialPlans:11,maxCriticalChainsPerDecision:1,maxExecutableFrontierTasksPerChain:1,maxRetainedChainBranches:2,maxChildrenPerDecision:3,maxCrossCycleBacktracks:4};
 const r:any=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{...requested,criticalChainRetainedAlternatives:{maxElapsedMs:9999,maxChildrenPerDecision:99}} as any,createdAt:"fixed",constructionSearchStrategy:"critical_chain_retained_alternatives"});
 const expected={...requested,maxExpandedPartialPlans:256,maxGeneratedPartialPlans:11};
 assert.deepEqual(r.evidence.resolvedRetainedAlternativesBudget,expected);
 assert.deepEqual(r.budget,expected);
});

test("retained alternatives session exports Best-K frontier and backtrack evidence",()=>{
 const stage2=runInitialConstructionStage2FirstPartialPlan({originInput:input,originOperationalState:state,stage1,createdAt:"fixed"});
 const r:any=runInitialConstructionIterativeSession({originInput:input,originOperationalState:state,stage1,stage2,reasoningBudget:{maxSuspendedPartialPlans:2,maxExpandedPartialPlans:4,maxGeneratedPartialPlans:12,maxChildrenPerDecision:3,maxCrossCycleBacktracks:4} as any,createdAt:"fixed",constructionSearchStrategy:"critical_chain_retained_alternatives"});
 assert.equal(r.evidence.blindSuspendedFrontierRejectionCount,0);
 assert.equal(r.evidence.bestRankedSuspendedAlternativeEvictedCount,0);
 assert.equal(r.evidence.frontierAdmissionOrderInvariant,true);
 assert.ok("suspendedFrontierOfferCount" in r.evidence);
 assert.ok("backtrackSelectionFingerprint" in r.evidence);
 assert.ok("rootChainFrontierOccurrenceCount" in r.evidence);
 assert.equal(r.evidence.backtrackSelectionCount,r.evidence.crossCycleBacktrackCount);
});
