import { createHash } from "node:crypto";
import type { EngineInput } from "../../types";
import type { Candidate, CandidateAssignment, OperationalState, ReasoningBudgetProfile } from "../contracts";
import { initialConstructionIterationBudgetFromReasoningBudget, type InitialConstructionBudgetLimit } from "./initialConstructionIterationBudget";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { buildInitialConstructionMap } from "../understanding/initialConstructionMap";
import { buildInitialConstructionResidualContext } from "../understanding/initialConstructionResidualContext";
import { selectInitialConstructionAnchors } from "../see/initialConstructionAnchorSelector";
import { buildInitialConstructionSearchSpaces } from "../see/initialConstructionSearchSpace";
import { buildCandidateStates } from "../transformation/transformationEngine";
import { simulateCandidateStates } from "../simulation/simulationEngine";
import { validateSimulatedStates } from "../validation/validationEngine";
import { initialConstructionAssignmentFingerprint, materializeInitialConstructionAnchorAttempt } from "./materializeInitialConstructionAnchorAttempt";

export type InitialConstructionIterativeStopReason = "COMPLETE"|"NO_RESIDUAL_WORK"|"NO_VIABLE_ANCHOR"|"NO_PROGRESS"|"BUDGET_EXHAUSTED"|"UNSUPPORTED_REQUIREMENT"|"INTERNAL_INTEGRITY_FAILURE";
const sample=(a:any[])=>[...(a??[])].slice(0,10); const now=()=>Math.round(performance.now()); const hash=(x:any)=>createHash("sha256").update(stableStringify(x)).digest("hex");
function candidate(id:string, assignments:CandidateAssignment[]):Candidate{ return {id,assignments,state:{status:"draft",evidenceIds:[],metadata:{readOnly:true}},metadata:{strategy:"SCHEDULE_PENDING_TASKS",planningInfluence:"candidate-assignments",initialConstructionStage:"iterative-session",executesTransformations:assignments.length>0,commitsPlanning:false,readOnly:true},evidenceIds:[],operationalValues:[]}; }
function norm(a:any):CandidateAssignment{return {taskId:Number(a.taskId),startPlanned:a.startPlanned??null,endPlanned:a.endPlanned??null,spaceId:a.spaceId??null,resourceIds:[...(a.resourceIds??a.assignedResourceIds??[])].map(Number).sort((x,y)=>x-y)};}
export function runInitialConstructionIterativeSession(args:{originInput:EngineInput; originOperationalState:OperationalState; stage1:any; stage2:any; reasoningBudget?:ReasoningBudgetProfile|null; createdAt?:string|null}){
 if(args.stage2?.executed!==true||args.stage2?.selectedValidationResult!=="VALID") return deepFreeze({version:"INITIAL-CONSTRUCTION-ITERATIVE-SESSION-V1",executed:false,reason:"stage2_hard_valid_partial_plan_required",readOnly:true}) as any;
 const startedAt=now(); const budget=initialConstructionIterationBudgetFromReasoningBudget(args.reasoningBudget as any); let budgetLimitReached:InitialConstructionBudgetLimit|null=null; let current=[...(args.stage2.selectedAssignments??[])].map(norm).sort((a,b)=>a.taskId-b.taskId); const initialCount=current.length; const cycles:any[]=[]; const exhaustedByFp=new Map<string,Set<number>>(); let transformations=0,simulations=0,validations=0,residualStates=0,attempted=0,exhausted=0,anchorRetryCount=0,combinedValidationCount=0,branchesMaterialized=0,logicalSteps=0; let stopReason:InitialConstructionIterativeStopReason="NO_PROGRESS"; let finalResidual:any=null; const acceptedPlans:any[]=[]; const residualCache=new Map<string,any>(); const mapCache=new Map<string,any>(); const validatedCombinedFingerprints=new Set<string>(); const anchorAttemptsPerAcceptedCycle:number[]=[]; const acceptedAssignmentsPerCycle:number[]=[]; const limit=():InitialConstructionBudgetLimit|null=>{ const elapsed=now()-startedAt; if(budget.maxElapsedMs===0||elapsed>=budget.maxElapsedMs) return "MAX_ELAPSED_MS"; if(cycles.filter(c=>c.acceptedAnchorTaskId!=null).length>=budget.maxAcceptedCycles) return "MAX_ACCEPTED_CYCLES"; if(attempted>=budget.maxTotalAnchorAttempts) return "MAX_ANCHOR_ATTEMPTS"; if(branchesMaterialized>=budget.maxTotalBranches) return "MAX_BRANCHES"; if(transformations>=budget.maxTransformations) return "MAX_TRANSFORMATIONS"; if(simulations>=budget.maxSimulations) return "MAX_SIMULATIONS"; if(validations>=budget.maxValidations) return "MAX_VALIDATIONS"; if(residualStates>=budget.maxResidualStates) return "MAX_RESIDUAL_STATES"; if(logicalSteps>=budget.maxLogicalSteps) return "MAX_LOGICAL_STEPS"; return null; }; const markBudget=(l:InitialConstructionBudgetLimit|null)=>{ if(l){ budgetLimitReached=l; stopReason="BUDGET_EXHAUSTED"; return true;} return false; };
 if(budget.maxAcceptedCycles===0){ budgetLimitReached="MAX_ACCEPTED_CYCLES"; const current=[...(args.stage2.selectedAssignments??[])].map(norm).sort((a,b)=>a.taskId-b.taskId); const finalFp=initialConstructionAssignmentFingerprint(current); const evidence={version:"INITIAL-CONSTRUCTION-ITERATIVE-SESSION-EVIDENCE-V1",executed:true,executedBeforeV4:true,inputSource:"original-engine-input-origin-operational-state-stage1-stage2",v4SeedUsed:false,initialAssignmentCount:current.length,acceptedCycleCount:0,attemptedAnchorCount:0,exhaustedAnchorCount:0,anchorRetryCount:0,combinedValidationCount:0,finalCombinedAssignmentCount:current.length,finalCombinedValidationResult:"VALID",finalResidualPendingTaskCount:null,finalResidualProductiveTaskCount:null,finalResidualMainFlowTaskCount:null,sessionRuntimeMs:now()-startedAt,budget,budgetLimitReached,acceptedAssignmentsPerCycle:[],anchorAttemptsPerAcceptedCycle:[],transformationsExecuted:0,simulationsExecuted:0,validationsExecuted:0,residualStatesBuilt:0,logicalStepsConsumed:0,assignmentsPerSecond:0,productiveTasksRemaining:null,progressRatio:0,lastAcceptedCycleIndex:null,lastAcceptedAnchorTaskId:null,stopReason:"BUDGET_EXHAUSTED",budgetExhausted:true,cycles:[],finalCombinedPartialPlanId:args.stage2.selectedPartialPlanId??null,finalCombinedAssignmentsFingerprint:finalFp,sessionFingerprint:hash({finalFp,stopReason:"BUDGET_EXHAUSTED"}),commitsExecuted:0,publicPlanningUsesIterativeSession:false,warnings:[],readOnly:true}; return deepFreeze({version:"INITIAL-CONSTRUCTION-ITERATIVE-SESSION-V1",executed:true,budget,combinedPartialPlan:{combinedPartialPlanId:args.stage2.selectedPartialPlanId??null,assignments:current,combinedAssignmentsFingerprint:finalFp,readOnly:true},acceptedPlans:[],cycles:[],evidence,transformationsExecuted:0,simulationsExecuted:0,validationsExecuted:0,commitsExecuted:0,publicPlanningUsesIterativeSession:false,readOnly:true}) as any; }
 for(let cycleIndex=0;cycleIndex<budget.maxAcceptedCycles;cycleIndex++){ if(markBudget(limit())) break;
   const pseudo={...args.stage2,selectedAssignments:current,selectedPartialPlanId:`iterative:${initialConstructionAssignmentFingerprint(current)}`,selectedBranchId:`iterative:${cycleIndex}`};
   const currentFp=initialConstructionAssignmentFingerprint(current); let residualContext=residualCache.get(currentFp); if(!residualContext){ residualContext=buildInitialConstructionResidualContext({originInput:args.originInput,originOperationalState:args.originOperationalState,stage2:pseudo}); residualCache.set(currentFp,residualContext); residualStates++; logicalSteps++; } finalResidual=residualContext;
   if(residualContext.residualPendingTaskIds.length===0){stopReason="NO_RESIDUAL_WORK";break;} if(markBudget(limit())) break;
   const mapKey=residualContext.fingerprint; let residualMap:any=mapCache.get(mapKey); if(!residualMap){ residualMap=buildInitialConstructionMap({input:args.originInput,state:args.originOperationalState,planningMode:"INITIAL_CONSTRUCTION",provisionalAssignments:current,provisionallyAssignedTaskIds:current.map(a=>a.taskId)}); mapCache.set(mapKey,residualMap); logicalSteps++; }
   const anchors:any[]=selectInitialConstructionAnchors({input:args.originInput,initialConstructionMap:residualMap,maxAnchors:budget.maxAnchorsPerCycle});
   const searchSpaces:any[]=buildInitialConstructionSearchSpaces({input:args.originInput,anchors,initialConstructionMap:residualMap,maxSearchSpaces:budget.maxAnchorsPerCycle,maxWindowsPerAnchor:20});
   const exhaustedSet=exhaustedByFp.get(residualContext.fingerprint)??new Set<number>(); exhaustedByFp.set(residualContext.fingerprint,exhaustedSet);
   const cycle:any={cycleIndex,residualFingerprint:residualContext.fingerprint,rankedAnchorSample:sample(anchors.map(a=>a.anchorTaskId)),attemptedAnchorIds:[],rejectedAnchorReasons:{},acceptedAnchorTaskId:null,deltaAssignmentCount:0,combinedAssignmentCount:current.length,combinedValidationResult:null}; let accepted=false;
   for(const anchor of anchors){ if(markBudget(limit())) break; if(exhaustedSet.has(anchor.anchorTaskId)) continue; if(cycle.attemptedAnchorIds.length>=budget.maxAnchorsPerCycle) break; attempted++; cycle.attemptedAnchorIds.push(anchor.anchorTaskId);
     const assignedIds=new Set(current.map(a=>a.taskId)); const node=(residualMap.dependencyGraph?.nodes??[]).find((n:any)=>n.taskId===anchor.anchorTaskId)??{}; const allPre=[...(node.transitivePrerequisiteTaskIds??[])].map(Number); const sat=allPre.filter(id=>assignedIds.has(id)); const rem=allPre.filter(id=>!assignedIds.has(id)); const closure=[...rem,Number(anchor.anchorTaskId)].filter((id,i,arr)=>Number.isFinite(id)&&!assignedIds.has(id)&&arr.indexOf(id)===i);
     const stage={...args.stage1,selectedAnchor:anchor,selectedAnchorTaskId:anchor.anchorTaskId,initialConstructionMap:residualMap,searchSpaces}; const attempt=materializeInitialConstructionAnchorAttempt({originInput:args.originInput,originOperationalState:args.originOperationalState,stage,anchor:{...anchor,allPrerequisiteTaskIds:allPre},baseProvisionalAssignments:current,provisionallySatisfiedTaskIds:sat,closureTaskIds:closure,maxBranches:Math.max(1,Math.min(8, budget.maxTotalBranches-branchesMaterialized)),reasoningBudget:args.reasoningBudget,createdAt:args.createdAt??null}); transformations+=attempt.transformationsExecuted; simulations+=attempt.simulationsExecuted; validations+=attempt.validationsExecuted; branchesMaterialized+=attempt.attemptedBranchCount??attempt.branchCandidateCount??0; logicalSteps++;
     let reason="no_hard_valid_branch";
     for(const opt of attempt.selectable??[]){ if(markBudget(limit())) break; const byId=new Map(current.map(a=>[a.taskId,a])); for(const a of opt.branch.assignments.map(norm)) if(!byId.has(a.taskId)) byId.set(a.taskId,a); const combined=[...byId.values()].sort((a,b)=>a.taskId-b.taskId); const combinedFp=initialConstructionAssignmentFingerprint(combined); if(validatedCombinedFingerprints.has(combinedFp)){ reason="duplicate_combined_partial_plan"; continue; } validatedCombinedFingerprints.add(combinedFp); const tr=buildCandidateStates(args.originOperationalState,[candidate(`candidate:iterative:${cycleIndex}:${opt.branch.branchId}`,combined)],{createdAt:args.createdAt??null,maxTransformations:1}); const sim=simulateCandidateStates(args.originOperationalState,tr.candidateStates,{createdAt:args.createdAt??null,maxSimulations:1}); const val=validateSimulatedStates(sim.simulatedStates,{createdAt:args.createdAt??null}); transformations+=tr.summary.transformedCount; simulations+=sim.summary.simulatedCount; validations+=val.validationResults.length; combinedValidationCount++; const validation=val.validationResults[0]??null; if(validation?.result==="VALID"&&combined.length>current.length){ const delta=combined.length-current.length; current=combined; accepted=true; cycle.acceptedAnchorTaskId=anchor.anchorTaskId; cycle.deltaAssignmentCount=delta; cycle.combinedAssignmentCount=current.length; cycle.combinedValidationResult="VALID"; acceptedPlans.push({cycleIndex,anchorTaskId:anchor.anchorTaskId,assignments:current,partialPlanId:`combined-initial-construction:${hash(current).slice(0,16)}`}); break; } reason=`combined_${validation?.result??"INVALID"}`; }
     if(accepted) break; if(markBudget(limit())) break; exhaustedSet.add(anchor.anchorTaskId); exhausted++; cycle.rejectedAnchorReasons[anchor.anchorTaskId]=reason; anchorRetryCount++;
   }
   cycles.push(cycle); if(accepted){ acceptedAssignmentsPerCycle.push(cycle.deltaAssignmentCount); anchorAttemptsPerAcceptedCycle.push(cycle.attemptedAnchorIds.length); } if(budgetLimitReached) break; if(!accepted){stopReason=cycle.attemptedAnchorIds.length?"NO_VIABLE_ANCHOR":"NO_RESIDUAL_WORK";break;} if(current.length===initialCount){stopReason="NO_PROGRESS";break;} if(markBudget(limit())) break; stopReason="BUDGET_EXHAUSTED";
 }
 if(!budgetLimitReached && stopReason==="BUDGET_EXHAUSTED") budgetLimitReached="MAX_ACCEPTED_CYCLES"; const sessionRuntimeMs=now()-startedAt; const finalCombinedPartialPlanId=acceptedPlans.at(-1)?.partialPlanId??args.stage2.selectedPartialPlanId??null; const finalFp=initialConstructionAssignmentFingerprint(current); const evidence={version:"INITIAL-CONSTRUCTION-ITERATIVE-SESSION-EVIDENCE-V1",executed:true,executedBeforeV4:true,inputSource:"original-engine-input-origin-operational-state-stage1-stage2",v4SeedUsed:false,initialAssignmentCount:initialCount,acceptedCycleCount:cycles.filter(c=>c.acceptedAnchorTaskId!=null).length,attemptedAnchorCount:attempted,exhaustedAnchorCount:exhausted,anchorRetryCount,combinedValidationCount,finalCombinedAssignmentCount:current.length,finalCombinedValidationResult:cycles.length?cycles.at(-1).combinedValidationResult:"VALID",finalResidualPendingTaskCount:finalResidual?.residualPendingTaskIds.length??0,finalResidualProductiveTaskCount:finalResidual?.residualProductiveTaskIds.length??0,finalResidualMainFlowTaskCount:finalResidual?.residualMainFlowTaskIds.length??0,sessionRuntimeMs,budget,budgetLimitReached,acceptedAssignmentsPerCycle,anchorAttemptsPerAcceptedCycle,transformationsExecuted:transformations,simulationsExecuted:simulations,validationsExecuted:validations,residualStatesBuilt:residualStates,logicalStepsConsumed:logicalSteps,assignmentsPerSecond:sessionRuntimeMs>0?Number(((current.length-initialCount)/(sessionRuntimeMs/1000)).toFixed(3)):0,productiveTasksRemaining:finalResidual?.residualProductiveTaskIds.length??0,progressRatio:((current.length-initialCount)+((finalResidual?.residualProductiveTaskIds.length??0))>0)?Number(((current.length-initialCount)/((current.length-initialCount)+(finalResidual?.residualProductiveTaskIds.length??0))).toFixed(6)):1,lastAcceptedCycleIndex:acceptedPlans.at(-1)?.cycleIndex??null,lastAcceptedAnchorTaskId:acceptedPlans.at(-1)?.anchorTaskId??null,stopReason,budgetExhausted:stopReason==="BUDGET_EXHAUSTED",cycles:sample(cycles),finalCombinedPartialPlanId,finalCombinedAssignmentsFingerprint:finalFp,sessionFingerprint:hash({cycles:cycles.map(c=>({i:c.cycleIndex,fp:c.residualFingerprint,a:c.acceptedAnchorTaskId,r:c.rejectedAnchorReasons,n:c.combinedAssignmentCount})),finalFp,stopReason}),commitsExecuted:0,publicPlanningUsesIterativeSession:false,warnings:[],readOnly:true};
 return deepFreeze({version:"INITIAL-CONSTRUCTION-ITERATIVE-SESSION-V1",executed:true,budget,combinedPartialPlan:{combinedPartialPlanId:finalCombinedPartialPlanId,assignments:current,combinedAssignmentsFingerprint:finalFp,readOnly:true},acceptedPlans,cycles,evidence,transformationsExecuted:transformations,simulationsExecuted:simulations,validationsExecuted:validations,commitsExecuted:0,publicPlanningUsesIterativeSession:false,readOnly:true}) as any;
}
