import test from "node:test";
import assert from "node:assert/strict";
import { runMacroMainZoneBlockRelayoutPass } from "./runMacroMainZoneBlockRelayoutPass";

const op = (extra:any={}) => ({ id:"s", planId:1, source:"EngineInput", schemaVersion:"ORC-SPEC-01", workDay:{start:"09:00",end:"18:00"}, tasks:[1,2,3].map(id=>({id,status:"pending"})), resources:[{id:10,typeName:"Coach"}], spaces:{exclusiveById:{1:true},capacityById:{1:1}}, locks:[], dependencies:[], constraints:{mealMode:"flexible_meal_window",optimizer:{mainFlowSpaceId:1,mainZoneMaxCoachSwitchesPerDay:4}}, availability:{workDay:{start:"09:00",end:"18:00"},mealWindow:{start:"13:00",end:"16:30"},globalHardBreaks:[],protectedBreaks:[]}, planning:[{taskId:1,startPlanned:"11:30",endPlanned:"12:05",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:2,startPlanned:"14:20",endPlanned:"14:50",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"},{taskId:3,startPlanned:"14:50",endPlanned:"15:20",assignedResourceIds:[10],spaceId:1,operationalRole:"productive_task"}], cognitive:{opportunities:[],searchSpaces:[],candidates:[],candidateStates:[],simulatedStates:[],validationResults:[],operationalValues:[],commitDecisions:[],evidence:[],metadata:{}}, ...extra } as any);
const sim = (state:any=op()) => ({ id:"sim:base", candidateStateId:"cs:base", baseStateId:"s", operationalStateSnapshot:state, appliedTransformations:[], simulationMode:"READ_ONLY_BASELINE", readOnly:true, createdAt:null, planningMaterialization:{source:"candidate_transformations", plannedTaskCount:state.planning.length, changedTaskCount:0, warnings:[], preservedAssignedSpaceCount:state.planning.length, missingAssignedSpaceFieldCount:0, nullAssignedSpaceCount:0, assignedSpaceContractValid:true, materializationContractVersion:"ORC-PLANNING-MATERIALIZATION-ID225", readOnly:true} } as any);
const val = (result="VALID", violated:string[]=[]) => ({ simulatedStateId:"sim:base", result, violatedConstraints:violated, hardViolationCount:violated.length, readOnly:true } as any);
const blueprint:any = { candidateReadiness:{recommendedCandidateFamily:"macro_main_zone_block_relayout"}, mealBlueprint:{productiveWorkAllowedInsideMealWindow:true} };

test("Does not execute on hard-infeasible base",()=>{ const r=runMacroMainZoneBlockRelayoutPass({originalState:op(),baseSimulation:sim(),baseValidation:val("INVALID",["SPACE_OVERLAP"]),productionWavePlanner:blueprint}); assert.equal(r.summary.executed,false); assert.equal(r.summary.reason,"base_plan_hard_infeasible"); });
test("Executes after productionWavePlanner blueprint",()=>{ const r=runMacroMainZoneBlockRelayoutPass({originalState:op(),baseSimulation:sim(),baseValidation:val(),productionWavePlanner:blueprint}); assert.equal(r.summary.executed,true); assert.equal(r.summary.executionPhase,"post-blueprint-pass"); });
test("Accepts valid macro relayout with visible main-zone idle reduction",()=>{ const r=runMacroMainZoneBlockRelayoutPass({originalState:op(),baseSimulation:sim(),baseValidation:val(),productionWavePlanner:blueprint}); assert.ok(r.summary.generatedCandidateCount>0); assert.equal(r.summary.selectedAsCommit,true); assert.ok(r.summary.visibleMainZoneIdleReductionMinutes>0); });
test("Rejects candidate that worsens makespan",()=>{ const st=op({planning:[...op().planning,{taskId:9,startPlanned:"17:50",endPlanned:"18:00",assignedResourceIds:[99],spaceId:9,operationalRole:"productive_task"}],tasks:[...op().tasks,{id:9,status:"pending"}]}); const r=runMacroMainZoneBlockRelayoutPass({originalState:st,baseSimulation:sim(st),baseValidation:val(),productionWavePlanner:blueprint}); assert.equal(r.summary.netValue.acceptedByMacroValueGate,true); });
test("Rejects candidate with hard violation",()=>{ const st=op({availability:{workDay:{start:"09:00",end:"18:00"},mealWindow:{start:"13:00",end:"16:30"},globalHardBreaks:[{start:"12:10",end:"12:40"}],protectedBreaks:[{start:"12:10",end:"12:40",kind:"global",code:"BREAK"}]}}); const r=runMacroMainZoneBlockRelayoutPass({originalState:st,baseSimulation:sim(st),baseValidation:val(),productionWavePlanner:blueprint}); assert.equal(r.summary.selectedAsCommit,false); });
test("Preserves ID225 assignedSpace contract",()=>{ const r=runMacroMainZoneBlockRelayoutPass({originalState:op(),baseSimulation:sim(),baseValidation:val(),productionWavePlanner:blueprint}); assert.equal((r.selectedSimulation?.planningMaterialization as any).assignedSpaceContractValid,true); });
test("Preserves ID236 rejected optional improvement handling",()=>{ const r=runMacroMainZoneBlockRelayoutPass({originalState:op(),baseSimulation:sim(),baseValidation:val(),basePlanningMaterialization:{changeSources:{},rejectedChangeSourceKeys:["criticalResourceIdleCompression"]},productionWavePlanner:blueprint}); assert.deepEqual((r.selectedSimulation?.planningMaterialization as any).rejectedChangeSourceKeys,["criticalResourceIdleCompression"]); });
test("Keeps previous plan if no macro candidate validates",()=>{ const st=op({tasks:[{id:1},{id:2,status:"done"},{id:3,status:"done"}]}); const r=runMacroMainZoneBlockRelayoutPass({originalState:st,baseSimulation:sim(st),baseValidation:val(),productionWavePlanner:blueprint}); assert.equal(r.summary.selectedAsCommit,false); assert.equal(r.selectedSimulation,null); });
