import test from "node:test";import assert from "node:assert/strict";import { compareZoneTaskChangeAudits, enrichPlanningEntriesForTaskChangeLimit, evaluateSpaceTaskChangeLimit } from "./spaceTaskChangeLimit";
test("meal break is ignored between same task group",()=>{const r=evaluateSpaceTaskChangeLimit({planning:[{taskId:1,taskGroupId:"Jose",startPlanned:"10:00",endPlanned:"11:00",spaceId:7,operationalRole:"productive_task"},{taskId:-1,startPlanned:"13:00",endPlanned:"14:15",spaceId:7,operationalRole:"meal_break_placeholder",isMealBreakBlock:true},{taskId:2,taskGroupId:"Jose",startPlanned:"14:15",endPlanned:"15:00",spaceId:7,operationalRole:"productive_task"}],maxChangesBySpaceId:{7:0}}); assert.equal(r.changeCountBySpaceId[7],0); assert.equal(r.exceeded,false);});
test("real task group change is counted across meal break",()=>{const r=evaluateSpaceTaskChangeLimit({planning:[{taskId:1,taskGroupId:"Jose",startPlanned:"10:00",endPlanned:"11:00",spaceId:7,operationalRole:"productive_task"},{taskId:-1,startPlanned:"13:00",endPlanned:"14:15",spaceId:7,operationalRole:"meal_break_placeholder",isMealBreakBlock:true},{taskId:2,taskGroupId:"Lucia",startPlanned:"14:15",endPlanned:"15:00",spaceId:7,operationalRole:"productive_task"}],maxChangesBySpaceId:{7:4}}); assert.equal(r.changeCountBySpaceId[7],1);});
test("exceeding configured limit creates rejection evidence",()=>{const planning=Array.from({length:6},(_,i)=>({taskId:i+1,taskGroupId:String(i),startPlanned:`1${i}:00`,endPlanned:`1${i}:30`,spaceId:7,operationalRole:"productive_task"})); const r=evaluateSpaceTaskChangeLimit({planning,maxChangesBySpaceId:{7:4}}); assert.equal(r.exceeded,true); assert.equal(r.violations[0].reason,"space_task_change_limit_exceeded");});
test("enriches template metadata before falling back to task id",()=>{const planning=enrichPlanningEntriesForTaskChangeLimit({planning:[{taskId:1,startPlanned:"10:00",endPlanned:"10:10",spaceId:7,zoneId:7},{taskId:2,startPlanned:"10:10",endPlanned:"10:20",spaceId:7,zoneId:7}],tasks:[{id:1,templateId:99,templateName:"Ensayo"},{id:2,templateId:99,templateName:"Ensayo"}]}); const r=evaluateSpaceTaskChangeLimit({planning,maxChangesBySpaceId:{7:0}}); assert.deepEqual(r.groupingKeySourceByZoneId["7"],["templateId"]); assert.equal(r.warnings.includes("zone_task_change_grouping_used_task_id_fallback"),false);});
test("baseline-relative task-change comparison allows inherited violation",()=>{const r=compareZoneTaskChangeAudits({baseline:{changeCountByZoneId:{7:14},limitByZoneId:{7:4}},candidate:{changeCountByZoneId:{7:14},limitByZoneId:{7:4}}}); assert.equal(r.baselineExceeded,true); assert.equal(r.candidateExceeded,true); assert.equal(r.passedNonRegression,true); assert.deepEqual(r.unchangedViolatingZoneIds,["7"]);});
test("baseline-relative task-change comparison treats inherited improvement as pass",()=>{const r=compareZoneTaskChangeAudits({baseline:{changeCountByZoneId:{7:14},limitByZoneId:{7:4}},candidate:{changeCountByZoneId:{7:12},limitByZoneId:{7:4}}}); assert.equal(r.passedNonRegression,true); assert.deepEqual(r.improvedZoneIds,["7"]);});
test("baseline-relative task-change comparison rejects worsening",()=>{const r=compareZoneTaskChangeAudits({baseline:{changeCountByZoneId:{7:14},limitByZoneId:{7:4}},candidate:{changeCountByZoneId:{7:15},limitByZoneId:{7:4}}}); assert.equal(r.passedNonRegression,false); assert.deepEqual(r.worsenedZoneIds,["7"]);});
test("baseline-relative task-change comparison rejects new violation",()=>{const r=compareZoneTaskChangeAudits({baseline:{changeCountByZoneId:{7:4},limitByZoneId:{7:4}},candidate:{changeCountByZoneId:{7:5},limitByZoneId:{7:4}}}); assert.equal(r.passedNonRegression,false); assert.deepEqual(r.newViolatingZoneIds,["7"]);});
