import assert from "node:assert/strict";import test from "node:test";
import { projectCombinedFocalA2ItinerantProblem, projectNeutralStandaloneFocalA2RealityProblem } from "./benchmarks/focal-a2/focalA2RealityReference";
import { anchoredAccompanimentPreflight, materializeAnchoredOperation } from "./anchoredAccompaniment";import { planMainFlowAndFeeders } from "./planMainFlowAndFeeders";

test("main anchored accompaniment is materialized atomically and preserves task identity",()=>{const p=projectCombinedFocalA2ItinerantProblem(),before=JSON.stringify(p),r=planMainFlowAndFeeders(p);assert.deepEqual(anchoredAccompanimentPreflight(p),[]);assert.equal(r.complete,true);assert.equal(r.metrics.hardValid,true);assert.equal(r.scheduledTasks.length,53);assert.equal(r.metrics.anchoredAccompanimentPlannedCount,3);assert.equal(r.metrics.anchoredAccompanimentScheduledSegmentCount,6);for(const c of p.anchoredAccompaniments!){const ids=[...c.beforeTaskIds,c.anchorTaskId,...c.afterTaskIds],actual=ids.map(id=>r.scheduledTasks.find(t=>t.id===id)!);assert.ok(actual.every(Boolean));assert.ok(actual.slice(1).every((t,i)=>actual[i]!.end===t.start));for(const task of actual){const original=p.tasks.find(t=>t.id===task.id)!;const {start:_s,end:_e,...scheduledIdentity}=task;assert.deepEqual(scheduledIdentity,original)}}assert.equal(JSON.stringify(p),before)});

test("materializer permits an empty side and never publishes partial state",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!,anchor=p.tasks.find(t=>t.id===c.anchorTaskId)!;c.beforeTaskIds=[];const operation=materializeAnchoredOperation(p,anchor,720,[]);assert.ok(operation);assert.deepEqual(operation.tasks.map(t=>t.id),[c.anchorTaskId,...c.afterTaskIds]);p.tasks.find(t=>t.id===c.afterTaskIds[0])!.availability=[{start:0,end:1}];assert.equal(materializeAnchoredOperation(p,anchor,720,[]),null)});

test("invalid and non-main contracts retain deterministic explicit reasons",()=>{const p=projectCombinedFocalA2ItinerantProblem();p.anchoredAccompaniments![0]!.anchorTaskId=p.tasks.find(t=>t.kind==="vocal")!.id;const reasons=anchoredAccompanimentPreflight(p);assert.ok(reasons.some(x=>x.includes("UNSUPPORTED_ANCHOR_KIND")));assert.deepEqual(reasons,[...reasons].sort())});

test("anchored planning is deterministic, order invariant, and absence preserves history",()=>{const p=projectCombinedFocalA2ItinerantProblem(),a=planMainFlowAndFeeders(p),b=planMainFlowAndFeeders(projectCombinedFocalA2ItinerantProblem()),reversed=projectCombinedFocalA2ItinerantProblem();reversed.tasks.reverse();reversed.anchoredAccompaniments!.reverse();const c=planMainFlowAndFeeders(reversed);assert.equal(a.metrics.planFingerprint,b.metrics.planFingerprint);assert.equal(a.metrics.planFingerprint,c.metrics.planFingerprint);const standalone=planMainFlowAndFeeders(projectNeutralStandaloneFocalA2RealityProblem());assert.equal(standalone.complete,true);assert.equal(standalone.scheduledTasks.length,47)});
