import assert from "node:assert/strict";import test from "node:test";
import { projectCombinedFocalA2ItinerantProblem, projectNeutralStandaloneFocalA2RealityProblem } from "./benchmarks/focal-a2/focalA2RealityReference";
import { anchoredAccompanimentPreflight, materializeAnchoredOperation } from "./anchoredAccompaniment";import { planMainFlowAndFeeders } from "./planMainFlowAndFeeders";

test("main anchored accompaniment is materialized atomically and preserves task identity",()=>{const p=projectCombinedFocalA2ItinerantProblem(),before=JSON.stringify(p),r=planMainFlowAndFeeders(p);assert.deepEqual(anchoredAccompanimentPreflight(p),[]);assert.equal(r.complete,true);assert.equal(r.metrics.hardValid,true);assert.equal(r.scheduledTasks.length,53);assert.equal(r.metrics.anchoredAccompanimentPlannedCount,3);assert.equal(r.metrics.anchoredAccompanimentScheduledSegmentCount,6);for(const c of p.anchoredAccompaniments!){const ids=[...c.beforeTaskIds,c.anchorTaskId,...c.afterTaskIds],actual=ids.map(id=>r.scheduledTasks.find(t=>t.id===id)!);assert.ok(actual.every(Boolean));assert.ok(actual.slice(1).every((t,i)=>actual[i]!.end===t.start));for(const task of actual){const original=p.tasks.find(t=>t.id===task.id)!;const {start:_s,end:_e,...scheduledIdentity}=task;assert.deepEqual(scheduledIdentity,original)}}assert.equal(JSON.stringify(p),before)});

test("materializer permits an empty side and never publishes partial state",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!,anchor=p.tasks.find(t=>t.id===c.anchorTaskId)!;c.beforeTaskIds=[];const operation=materializeAnchoredOperation(p,anchor,720,[]);assert.equal(operation.success,true);if(!operation.success)throw Error("expected success");assert.deepEqual(operation.operation.tasks.map(t=>t.id),[c.anchorTaskId,...c.afterTaskIds]);p.tasks.find(t=>t.id===c.afterTaskIds[0])!.availability=[{start:0,end:1}];assert.equal(materializeAnchoredOperation(p,anchor,720,[]).success,false)});

test("invalid and non-main contracts retain deterministic explicit reasons",()=>{const p=projectCombinedFocalA2ItinerantProblem();p.anchoredAccompaniments![0]!.anchorTaskId=p.tasks.find(t=>t.kind==="vocal")!.id;const reasons=anchoredAccompanimentPreflight(p);assert.ok(reasons.some(x=>x.includes("UNSUPPORTED_ANCHOR_KIND")));assert.deepEqual(reasons,[...reasons].sort())});

test("anchored planning is deterministic, order invariant, and absence preserves history",()=>{const p=projectCombinedFocalA2ItinerantProblem(),a=planMainFlowAndFeeders(p),b=planMainFlowAndFeeders(projectCombinedFocalA2ItinerantProblem()),reversed=projectCombinedFocalA2ItinerantProblem();reversed.tasks.reverse();reversed.anchoredAccompaniments!.reverse();const c=planMainFlowAndFeeders(reversed);assert.equal(a.metrics.planFingerprint,b.metrics.planFingerprint);assert.equal(a.metrics.planFingerprint,c.metrics.planFingerprint);const standalone=planMainFlowAndFeeders(projectNeutralStandaloneFocalA2RealityProblem());assert.equal(standalone.complete,true);assert.equal(standalone.scheduledTasks.length,47)});

test("a contract may omit its after side",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!;c.afterTaskIds=[];assert.deepEqual(anchoredAccompanimentPreflight(p),[])});
test("a contract rejects both empty sides",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!;c.beforeTaskIds=[];c.afterTaskIds=[];assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("INVALID_CONTRACT")))});
test("a segment must remain auxiliary",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!,t=p.tasks.find(t=>t.id===c.beforeTaskIds[0])!;Object.assign(t,{kind:"main",coachId:p.coaches[0]!.id,blockKey:"x",spaceId:p.mainFlow.spaceId});assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("INVALID_SEGMENT_KIND")))});
test("all phases require the same participant",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!,t=p.tasks.find(t=>t.id===c.afterTaskIds[0])!;t.participantId=p.participants.find(x=>x.id!==t.participantId)!.id;assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("PARTICIPANT_MISMATCH")))});
test("contract ids are unique",()=>{const p=projectCombinedFocalA2ItinerantProblem();p.anchoredAccompaniments![1]!.id=p.anchoredAccompaniments![0]!.id;assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("INVALID_CONTRACT")))});
test("tasks cannot be reused between contracts",()=>{const p=projectCombinedFocalA2ItinerantProblem();p.anchoredAccompaniments![1]!.beforeTaskIds=[p.anchoredAccompaniments![0]!.beforeTaskIds[0]!];assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("TASK_REUSED")))});
test("cross-contract nesting is rejected",()=>{const p=projectCombinedFocalA2ItinerantProblem();p.anchoredAccompaniments![1]!.beforeTaskIds=[p.anchoredAccompaniments![0]!.anchorTaskId];assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("NESTING_NOT_SUPPORTED")))});
test("resource continuity is derived from the phase intersection",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!,ids=[...c.beforeTaskIds,c.anchorTaskId,...c.afterTaskIds];for(const id of ids)p.tasks.find(t=>t.id===id)!.requiredResourceIds=["reality-camera-3"];assert.deepEqual(anchoredAccompanimentPreflight(p),[])});
test("absence of a continuous resource is rejected",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!;p.tasks.find(t=>t.id===c.beforeTaskIds[0])!.requiredResourceIds=[];assert.ok(anchoredAccompanimentPreflight(p).some(r=>r.includes("NO_CONTINUOUS_RESOURCE")))});
test("materialization reports deterministic task-window reasons",()=>{const p=projectCombinedFocalA2ItinerantProblem(),c=p.anchoredAccompaniments![0]!,anchor=p.tasks.find(t=>t.id===c.anchorTaskId)!;p.tasks.find(t=>t.id===c.beforeTaskIds[0])!.availability=[{start:0,end:1}];const result=materializeAnchoredOperation(p,anchor,720,[]);assert.equal(result.success,false);if(result.success)throw Error("expected failure");assert.ok(result.reasonCodes.includes("TASK_WINDOW"));assert.deepEqual(result.reasonCodes,[...result.reasonCodes].sort())});
test("rejection metrics are derived from observed candidates",()=>{const r=planMainFlowAndFeeders(projectCombinedFocalA2ItinerantProblem()),m=r.metrics,total=Object.values(m.anchoredAccompanimentRejectedReasonCountByCode).reduce((a,b)=>a+b,0);assert.ok(m.anchoredAccompanimentRejectedPositionCount>0);assert.ok(total>=m.anchoredAccompanimentRejectedPositionCount)});
