import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { buildTimeline, candidateCuts, candidateTimelineDomain, candidateTimelines, mainFlowMealAligned } from "./mainFlowMeal";
import { constructExactMainAndFeederCore } from "./exactMainAndFeederCore";
import { mainFlowMealScenario } from "./scenarios/mainFlowMealScenario";
import { planMainFlowAndFeeders } from "./planMainFlowAndFeeders";
describe("NEXT-017 main flow meal",()=>{it("orders block boundaries before internal boundaries without eliminating either",()=>{const p=mainFlowMealScenario(),pattern=["a","a","b","b"];assert.deepEqual(candidateCuts(pattern),[2,1,3]);assert.deepEqual(buildTimeline(p,pattern,15,2).slots,[810,825,900,915]);assert.equal(mainFlowMealAligned(p),true)});it("selects a feasible boundary atomically",()=>{const r=planMainFlowAndFeeders(mainFlowMealScenario());assert.equal(r.complete,true);assert.ok((r.metrics.mainFlowSelectedSplitIndex??0)>0);assert.deepEqual(({start:r.scheduledSpaceMeals.find(x=>x.spaceId==="main-stage")?.start,end:r.scheduledSpaceMeals.find(x=>x.spaceId==="main-stage")?.end}),{start:840,end:900})})});

it("generates several in-window meal starts for one pattern and ranks natural block changes first",()=>{const p=mainFlowMealScenario();p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:780,end:990},duration:75};const timelines=candidateTimelines(p,["a","a","b","b"],15);assert.ok(new Set(timelines.filter(x=>x.splitIndex===2).map(x=>x.meal.start)).size>1);assert.ok(timelines.every(x=>x.meal.start>=780&&x.meal.end<=990));assert.equal(timelines[0]!.splitIndex,2);assert.ok(timelines.some(x=>x.splitIndex===1&&x.strategyRank===1));assert.ok(timelines.every(x=>x.morningTaskCount+x.afternoonTaskCount===4));});

it("calculates exact feasible meal ranges and cardinalities without materializing starts",()=>{const p=mainFlowMealScenario();p.day={start:0,end:100};p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:0,end:100},duration:20};const domain=candidateTimelineDomain(p,["a","a","b","b"],15);assert.deepEqual(domain.ranges.map(({cut,startMin,startMax,feasibleCount,rawCount,analyticallyEliminated})=>({cut,startMin,startMax,feasibleCount,rawCount,analyticallyEliminated})),[
  {cut:2,startMin:30,startMax:50,feasibleCount:5,rawCount:17,analyticallyEliminated:12},
  {cut:1,startMin:15,startMax:35,feasibleCount:5,rawCount:17,analyticallyEliminated:12},
  {cut:3,startMin:45,startMax:65,feasibleCount:5,rawCount:17,analyticallyEliminated:12},
]);assert.equal(domain.domainCount,51);assert.equal(domain.feasibleCount,15);assert.equal(domain.analyticallyEliminated,36);assert.equal("timelines" in domain,false);});

it("eliminates wholly impossible intervals without constructing timelines",()=>{const p=mainFlowMealScenario();p.day={start:0,end:40};p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:0,end:100},duration:20};const domain=candidateTimelineDomain(p,["a","a","b","b"],15);assert.equal(domain.feasibleCount,0);assert.equal(domain.analyticallyEliminated,domain.domainCount);assert.deepEqual(candidateTimelines(p,["a","a","b","b"],15),[]);});

it("reconciles lazy meal evidence, preserves preferred-first ordering, and is deterministic",()=>{const make=()=>{const p=mainFlowMealScenario();p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:780,end:990},duration:75};return p};const domain=candidateTimelineDomain(make(),["a","a","b","b"],15);assert.equal(domain.domainCount,domain.feasibleCount+domain.analyticallyEliminated);assert.deepEqual(domain.ranges.map(({cut,strategyRank})=>[cut,strategyRank]),[[2,0],[1,1],[3,1]]);const first=constructExactMainAndFeederCore(make()),again=constructExactMainAndFeederCore(make());assert.deepEqual(first.evidence,again.evidence);assert.equal(first.evidence.mealTimelinesPreferred+first.evidence.mealTimelinesNonPreferred,first.evidence.mealTimelinesExplored);assert.equal(first.evidence.mealTimelineDomainCount,first.evidence.mealTimelinesEliminatedAnalytically+first.evidence.mealTimelinesExplored+first.evidence.mealTimelinesPendingAtExhaustion);assert.ok(first.evidence.mealTimelinesPreferred>0);});

it("materializes exactly one meal timeline when only one timeline branch remains",()=>{const p=mainFlowMealScenario();p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:780,end:990},duration:75};p.budget.maxBranchExpansions=2;const result=constructExactMainAndFeederCore(p);assert.equal(result.status,"BRANCH_BUDGET_EXHAUSTED");assert.equal(result.evidence.mealTimelinesExplored,1);assert.equal(result.evidence.mealTimelinesPreferred,1);assert.ok(result.evidence.mealTimelinesPendingAtExhaustion>0);assert.equal(result.evidence.mealTimelineDomainCount,result.evidence.mealTimelinesEliminatedAnalytically+result.evidence.mealTimelinesExplored+result.evidence.mealTimelinesPendingAtExhaustion);});
