import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { buildTimeline, candidateCuts, candidateTimelineDomain, candidateTimelines, mainFlowMealAligned } from "./mainFlowMeal";
import { constructExactMainAndFeederCore } from "./exactMainAndFeederCore";
import { mainFlowMealScenario } from "./scenarios/mainFlowMealScenario";
import { planMainFlowAndFeeders } from "./planMainFlowAndFeeders";
describe("NEXT-017 main flow meal",()=>{it("orders block boundaries before internal boundaries without eliminating either",()=>{const p=mainFlowMealScenario(),pattern=["a","a","b","b"];assert.deepEqual(candidateCuts(pattern),[2,1,3]);assert.deepEqual(buildTimeline(p,pattern,15,2).slots,[810,825,900,915]);assert.equal(mainFlowMealAligned(p),true)});it("selects a feasible boundary atomically",()=>{const r=planMainFlowAndFeeders(mainFlowMealScenario());assert.equal(r.complete,true);assert.ok((r.metrics.mainFlowSelectedSplitIndex??0)>0);assert.deepEqual(({start:r.scheduledSpaceMeals.find(x=>x.spaceId==="main-stage")?.start,end:r.scheduledSpaceMeals.find(x=>x.spaceId==="main-stage")?.end}),{start:840,end:900})})});

it("generates several in-window meal starts for one pattern and ranks natural block changes first",()=>{const p=mainFlowMealScenario();p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:780,end:990},duration:75};const timelines=candidateTimelines(p,["a","a","b","b"],15);assert.ok(new Set(timelines.filter(x=>x.splitIndex===2).map(x=>x.meal.start)).size>1);assert.ok(timelines.every(x=>x.meal.start>=780&&x.meal.end<=990));assert.equal(timelines[0]!.splitIndex,2);assert.ok(timelines.some(x=>x.splitIndex===1&&x.strategyRank===1));assert.ok(timelines.every(x=>x.morningTaskCount+x.afternoonTaskCount===4));});

it("reconciles the analytical meal domain with individually branched timelines deterministically",()=>{const make=()=>{const p=mainFlowMealScenario();p.protectedMeal=undefined;p.spaces.find(({id})=>id==="main-stage")!.mealPolicy={window:{start:780,end:990},duration:75};return p};const domain=candidateTimelineDomain(make(),["a","a","b","b"],15);assert.equal(domain.domainCount,domain.timelines.length+domain.analyticallyEliminated);const first=constructExactMainAndFeederCore(make()),again=constructExactMainAndFeederCore(make());assert.deepEqual(first.evidence,again.evidence);assert.equal(first.evidence.mealTimelinesPreferred+first.evidence.mealTimelinesNonPreferred,first.evidence.mealTimelinesExplored);assert.ok(first.evidence.branchesExplored>=first.evidence.mealTimelinesExplored);assert.ok(first.evidence.mealTimelineDomainCount>=first.evidence.mealTimelinesExplored+first.evidence.mealTimelinesEliminatedAnalytically);});
