import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, readdirSync } from "node:fs";
import { planMainFlowAndFeeders } from "./planMainFlowAndFeeders";
import { mainFlowVocalScenario } from "./scenarios/mainFlowVocalScenario";
import { hm } from "./time";

test("NEXT-001 completes all tasks with a continuous, hard-valid main flow",()=>{const p=mainFlowVocalScenario(),before=JSON.stringify(p),r=planMainFlowAndFeeders(p);assert.equal(r.complete,true);assert.equal(r.metrics.plannedTaskCount,16);assert.equal(r.metrics.unplannedTaskCount,0);assert.equal(r.metrics.hardValid,true);assert.equal(r.metrics.mainFlowGapMinutes,0);assert.equal(r.metrics.mainFlowEnd,hm("15:00"));assert.equal(r.metrics.dependencyViolationCount+r.metrics.overlapViolationCount+r.metrics.transitionViolationCount+r.metrics.availabilityViolationCount+r.metrics.blockViolationCount,0);assert.ok(r.metrics.maxParticipantPresenceMinutes<=90);assert.equal(JSON.stringify(p),before);const mains=r.scheduledTasks.filter(t=>t.kind==="main");assert.notEqual(mains[0].participantId,"participant-a");assert.ok(mains.findIndex(t=>t.participantId==="participant-z")<3);assert.ok(mains.find(t=>t.participantId==="participant-a")!.start>=hm("14:00"));});
test("fingerprint is repeatable and independent of array order",()=>{const p=mainFlowVocalScenario(),a=planMainFlowAndFeeders(p);const reversed={...p,participants:[...p.participants].reverse(),coaches:[...p.coaches].reverse(),spaces:[...p.spaces].reverse(),tasks:[...p.tasks].reverse()};const b=planMainFlowAndFeeders(p),c=planMainFlowAndFeeders(reversed);assert.equal(a.metrics.planFingerprint,b.metrics.planFingerprint);assert.equal(a.metrics.planFingerprint,c.metrics.planFingerprint);assert.deepEqual(a.scheduledTasks,c.scheduledTasks);});
test("impossible input fails completely with a stable operational reason",()=>{const p=mainFlowVocalScenario();p.participants=p.participants.map(x=>x.id==="participant-z"?{...x,availability:[{start:hm("09:00"),end:hm("10:00")}]}:x);const a=planMainFlowAndFeeders(p),b=planMainFlowAndFeeders(p);assert.equal(a.complete,false);assert.deepEqual(a.scheduledTasks,[]);assert.deepEqual(a.metrics.reasonCodes,["NO_COMPLETE_HARD_VALID_PLAN"]);assert.deepEqual(a.metrics.reasonCodes,b.metrics.reasonCodes);});
const sourceFiles=(dir:string):string[]=>readdirSync(dir,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?sourceFiles(`${dir}/${entry.name}`):/\.tsx?$/.test(entry.name)?[`${dir}/${entry.name}`]:[]);
test("planner-next remains isolated from legacy and production",()=>{for(const file of sourceFiles("engine/planner-next").filter(f=>!f.endsWith(".spec.ts"))){const text=readFileSync(file,"utf8");assert.doesNotMatch(text,/engine\/(v3|v4|orc)|generatePlanV[34]|orcActivePlanner/);}for(const root of ["server","client","shared"])for(const file of sourceFiles(root))assert.doesNotMatch(readFileSync(file,"utf8"),/planner-next/);for(const file of ["engine/solve.ts","engine/buildInput.ts","engine/types.ts"])assert.doesNotMatch(readFileSync(file,"utf8"),/planner-next/);});
