import assert from "node:assert/strict";
import test from "node:test";
import type { PlannerNextProblem } from "./contracts";
import { placeAuxiliaryTasks } from "./placeAuxiliaryTasks";
import { constructSaturatedResourceWindowBlockCandidates, deriveSaturatedResourceWindowBlocks, saturatedResourceWindowBlockKey } from "./saturatedResourceWindowBlock";

function scenario(): PlannerNextProblem {
  return { day:{start:600,end:660},protectedMeal:{start:900,end:930},spaces:["a","b","main"].map(id=>({id,availability:[{start:600,end:660}]})),resources:[{id:"camera",availability:[{start:600,end:660}],presencePreference:"OFF"}],participants:["p1","p2"].map(id=>({id,availability:[{start:600,end:660}]})),coaches:[],tasks:[{id:"a",kind:"auxiliary",participantId:"p1",duration:20,spaceId:"a",dependencies:[],requiredResourceIds:["camera"],availability:[{start:600,end:660}]},{id:"b",kind:"auxiliary",participantId:"p2",duration:40,spaceId:"b",dependencies:[],requiredResourceIds:["camera"],availability:[{start:600,end:660}]}],mainFlow:{spaceId:"main",preferredEnd:660,continuity:"REQUIRED",maxBlocksByKey:1,minTasksPerBlock:1},participantTransitionMinutes:0,resourceTransitionMinutes:0,budget:{bestK:8,maxBacktracks:20,maxPatterns:20,maxBranchExpansions:100},auxiliaryPolicy:{participantPresencePreference:"OFF"} };
}

test("derives a canonical exact-fit shared-resource cohort without mutating input",()=>{const p=scenario(),before=JSON.stringify(p),blocks=deriveSaturatedResourceWindowBlocks(p,[...p.tasks].reverse(),[]);assert.equal(blocks.length,1);assert.equal(blocks[0]!.key,saturatedResourceWindowBlockKey(["camera"],{start:600,end:660},["b","a"]));assert.deepEqual(blocks[0]!.taskIds,["a","b"]);assert.equal(JSON.stringify(p),before)});
test("constructs complete deterministic candidates and auxiliary places the cohort atomically",()=>{const p=scenario(),block=deriveSaturatedResourceWindowBlocks(p,p.tasks,[])[0]!,a=constructSaturatedResourceWindowBlockCandidates(p,block,[],100),b=constructSaturatedResourceWindowBlockCandidates(p,block,[],100);assert.deepEqual(a,b);assert.equal(a.candidates.length,2);assert.ok(a.candidates.every(candidate=>candidate.tasks[0]!.start===600&&candidate.tasks.at(-1)!.end===660));const placed=placeAuxiliaryTasks(p,[],100);assert.ok(placed.tasks);assert.equal(placed.saturatedBlockCount,1);assert.equal(placed.saturatedBlockPlannedCount,1);assert.deepEqual(placed.tasks!.map(t=>t.spaceId).sort(),["a","b"])});
test("rejects non-saturated and incompatible cohorts",()=>{const less=scenario();less.tasks[0]!.duration=15;assert.deepEqual(deriveSaturatedResourceWindowBlocks(less,less.tasks,[]),[]);const resources=scenario();resources.tasks[0]!.requiredResourceIds=[];assert.deepEqual(deriveSaturatedResourceWindowBlocks(resources,resources.tasks,[]),[]);const windows=scenario();windows.tasks[0]!.availability=[{start:605,end:660}];assert.deepEqual(deriveSaturatedResourceWindowBlocks(windows,windows.tasks,[]),[]);const placed=scenario();assert.deepEqual(deriveSaturatedResourceWindowBlocks(placed,placed.tasks,[{...placed.tasks[0]!,start:600,end:620}]),[])});
test("budget exhaustion is atomic and publishes no partial candidates",()=>{const p=scenario(),block=deriveSaturatedResourceWindowBlocks(p,p.tasks,[])[0]!,result=constructSaturatedResourceWindowBlockCandidates(p,block,[],1);assert.equal(result.exhausted,true);assert.deepEqual(result.candidates,[]);const placed=placeAuxiliaryTasks(p,[],1);assert.equal(placed.tasks,null);assert.equal(placed.exhausted,true)});
