import assert from "node:assert/strict";import test from "node:test";
import {spaceMealScenario} from "./scenarios/spaceMealScenario";import {createScheduledSpaceMeal,spaceMealCandidateStarts,spaceMealPotentialStarts,spaceMealId,combineSpaceOccupations,internalGapMinutes,occupiedBlockCount} from "./spaceMeals";import {planMainFlowAndFeeders} from "./planMainFlowAndFeeders";import {canPlaceTask} from "./placement";import {preflight,validatePlan} from "./validate";import {assessFutureFeasibility} from "./futureFeasibility";
test("canonical meal helpers and sole candidate",()=>{const p=spaceMealScenario();assert.equal(spaceMealId("meal-room"),"space-meal:meal-room:1");assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[],[]),[620])});
test("meal is explicit, blocks only its space, and forms continuous occupation",()=>{const p=spaceMealScenario(),r=planMainFlowAndFeeders(p),m=r.scheduledSpaceMeals[0]!;assert.equal(r.complete,true);assert.deepEqual([m.start,m.end],[620,640]);const tasks=r.scheduledTasks.filter(t=>t.spaceId==="meal-room");assert.deepEqual(tasks.map(t=>[t.start,t.end]),[[600,620],[640,660]]);const o=combineSpaceOccupations("meal-room",tasks,[m]);assert.equal(internalGapMinutes(o),0);assert.equal(occupiedBlockCount(o),1);const own=p.tasks.find(t=>t.id==="meal-room-task-a")!;assert.equal(canPlaceTask(p,own,620,[],[m]),false);p.spaces.push({id:"other-meal-test",availability:[{start:600,end:660}]});assert.equal(canPlaceTask(p,{id:"other",kind:"technical",duration:20,spaceId:"other-meal-test",dependencies:[]},620,[],[m]),true)});
test("meal policy preflight is deterministic and crash safe",()=>{for(const mutate of [(p:any)=>p.spaces.at(-1).mealPolicy=null,(p:any)=>delete p.spaces.at(-1).mealPolicy.window,(p:any)=>p.spaces.at(-1).mealPolicy.window={start:640,end:620},(p:any)=>p.spaces.at(-1).mealPolicy.duration=0,(p:any)=>p.spaces.at(-1).mealPolicy.duration=-1,(p:any)=>p.spaces.at(-1).mealPolicy.duration=2.5,(p:any)=>p.spaces.at(-1).mealPolicy.duration=25]){const p:any=spaceMealScenario();mutate(p);assert(preflight(p).includes("INVALID_SPACE_MEAL_POLICY"))}});
test("structured and unsupported meal tasks fail preflight",()=>{for(const mutate of [(p:any)=>p.spaces.at(-1).secondaryContinuity="REQUIRED",(p:any)=>p.spaces.at(-1).setupPolicy={familyOrder:["x"],reentry:"FORBIDDEN"},(p:any)=>p.tasks.at(-1).dependencies=["meal-room-task-a"],(p:any)=>p.tasks.at(-1).jointGroupId="x",(p:any)=>p.tasks.at(-1).setupFamilyId="x"]){const p:any=spaceMealScenario();mutate(p);assert(preflight(p).some(x=>x.startsWith("SPACE_MEAL_")))}});
test("validator rejects absent, duplicate and unknown meals once per space",()=>{const p=spaceMealScenario(),r=planMainFlowAndFeeders(p),m=r.scheduledSpaceMeals[0]!;assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[]).spaceMealViolationCount,1);assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[m,m]).spaceMealViolationCount,1);assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[{...m,spaceId:"unknown"}]).spaceMealViolationCount,2);for(const bad of [{...m,id:"bad"},{...m,entryIndex:2},{...m,duration:15},{...m,start:615,end:635}])assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[bad]).spaceMealViolationCount,1)});
test("future feasibility publishes canonical meal blocker and exhaustion atomically",()=>{const p=spaceMealScenario(),blocking=[{...p.tasks.find(t=>t.id==="meal-room-task-a")!,start:620,end:640}];const a=assessFutureFeasibility(p,blocking,[],{remaining:100},()=>({count:0,exhausted:false}));assert.deepEqual(a.blockingWorkItemKeys,["meal:meal-room"]);const b=assessFutureFeasibility(p,[],[],{remaining:0},()=>({count:0,exhausted:false}));assert.equal(b.exhausted,true);assert.deepEqual(b.assessments,[])});
test("planner input remains immutable",()=>{const p=spaceMealScenario(),before=structuredClone(p);planMainFlowAndFeeders(p);assert.deepEqual(p,before)});
test("potential meal starts use global five-minute boundaries and hard filtering",()=>{const immutable=spaceMealScenario(),before=structuredClone(immutable);assert.deepEqual(requireStarts(immutable),[620]);assert.deepEqual(immutable,before);const p=spaceMealScenario(),space=p.spaces.find(s=>s.id==="meal-room")!;space.mealPolicy={window:{start:621,end:646},duration:20};assert.deepEqual(requireStarts(p),[625]);space.mealPolicy={window:{start:621,end:644},duration:20};assert.deepEqual(requireStarts(p),[]);space.mealPolicy={window:{start:620,end:650},duration:20};assert(requireStarts(p).every((x:number)=>x%5===0));assert.deepEqual(requireStarts(p),[620,625,630]);const own={...p.tasks.at(-1)!,start:620,end:625},other={...own,spaceId:"other"};assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[own],[]),[625,630]);assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[],[createScheduledSpaceMeal("meal-room",625,20)]),[]);assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[other],[]),[620,625,630]);p.protectedMeal={start:620,end:650};assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[],[]),[620,625,630]);});
function requireStarts(p:any){return spaceMealPotentialStarts(p,"meal-room")}
test("future meal feasibility charges invalid starts and exhausts atomically",()=>{const p=spaceMealScenario(),s=p.spaces.find(x=>x.id==="meal-room")!;s.mealPolicy={window:{start:620,end:650},duration:20};const task={...p.tasks.at(-1)!,start:620,end:630},budget={remaining:2},before=structuredClone(p),r=assessFutureFeasibility(p,[task],[],budget,()=>({count:0,exhausted:false}));assert.equal(r.exhausted,true);assert.equal(r.branchesConsumed,2);assert.equal(budget.remaining,0);assert.deepEqual(r.assessments,[]);assert.deepEqual(p,before);const full=assessFutureFeasibility(p,[{...task,end:650}],[],{remaining:3},()=>({count:0,exhausted:false}));assert.equal(full.branchesConsumed,3);assert.deepEqual(full.blockingWorkItemKeys,["meal:meal-room"]);p.budget.bestK=2;const best=assessFutureFeasibility(p,[],[],{remaining:10},()=>({count:0,exhausted:false}));assert.equal(best.assessments[0]?.alternativeCount,2);assert.equal(best.branchesConsumed,2)});
