import assert from "node:assert/strict";import test from "node:test";
import {spaceMealScenario} from "./scenarios/spaceMealScenario";import {requiredSpaceMealScenario} from "./scenarios/requiredSpaceMealScenario";import {createScheduledSpaceMeal,spaceMealCandidateStarts,spaceMealPotentialStarts,spaceMealId,combineSpaceOccupations,internalGapMinutes,occupiedBlockCount,independentSpaceMealIds,requiredBlockMealSpaceIds} from "./spaceMeals";import {planMainFlowAndFeeders} from "./planMainFlowAndFeeders";import {canPlaceTask} from "./placement";import {preflight,validatePlan} from "./validate";import {assessFutureFeasibility} from "./futureFeasibility";import {generateBlockCandidates} from "./placeAuxiliaryTasks";
test("canonical meal helpers and sole candidate",()=>{const p=spaceMealScenario();assert.equal(spaceMealId("meal-room"),"space-meal:meal-room:1");assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[],[]),[620])});
test("meal is explicit, blocks only its space, and forms continuous occupation",()=>{const p=spaceMealScenario(),r=planMainFlowAndFeeders(p),m=r.scheduledSpaceMeals[0]!;assert.equal(r.complete,true);assert.deepEqual([m.start,m.end],[620,640]);const tasks=r.scheduledTasks.filter(t=>t.spaceId==="meal-room");assert.deepEqual(tasks.map(t=>[t.start,t.end]),[[600,620],[640,660]]);const o=combineSpaceOccupations("meal-room",tasks,[m]);assert.equal(internalGapMinutes(o),0);assert.equal(occupiedBlockCount(o),1);const own=p.tasks.find(t=>t.id==="meal-room-task-a")!;assert.equal(canPlaceTask(p,own,620,[],[m]),false);p.spaces.push({id:"other-meal-test",availability:[{start:600,end:660}]});assert.equal(canPlaceTask(p,{id:"other",kind:"technical",duration:20,spaceId:"other-meal-test",dependencies:[]},620,[],[m]),true)});
test("meal policy preflight is deterministic and crash safe",()=>{for(const mutate of [(p:any)=>p.spaces.at(-1).mealPolicy=null,(p:any)=>delete p.spaces.at(-1).mealPolicy.window,(p:any)=>p.spaces.at(-1).mealPolicy.window={start:640,end:620},(p:any)=>p.spaces.at(-1).mealPolicy.duration=0,(p:any)=>p.spaces.at(-1).mealPolicy.duration=-1,(p:any)=>p.spaces.at(-1).mealPolicy.duration=2.5,(p:any)=>p.spaces.at(-1).mealPolicy.duration=25]){const p:any=spaceMealScenario();mutate(p);assert(preflight(p).includes("INVALID_SPACE_MEAL_POLICY"))}});
test("required meals are supported while setup and unsupported meal tasks fail preflight",()=>{const required=spaceMealScenario();required.spaces.at(-1)!.secondaryContinuity="REQUIRED";assert.equal(preflight(required).some(x=>x.startsWith("SPACE_MEAL_")),false);for(const mutate of [(p:any)=>p.spaces.at(-1).setupPolicy={familyOrder:["x"],reentry:"FORBIDDEN"},(p:any)=>p.tasks.at(-1).dependencies=["meal-room-task-a"],(p:any)=>p.tasks.at(-1).jointGroupId="x",(p:any)=>p.tasks.at(-1).setupFamilyId="x"]){const p:any=spaceMealScenario();mutate(p);assert(preflight(p).some(x=>x.startsWith("SPACE_MEAL_")))}});
test("validator rejects absent, duplicate and unknown meals once per space",()=>{const p=spaceMealScenario(),r=planMainFlowAndFeeders(p),m=r.scheduledSpaceMeals[0]!;assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[]).spaceMealViolationCount,1);assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[m,m]).spaceMealViolationCount,1);assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[{...m,spaceId:"unknown"}]).spaceMealViolationCount,2);for(const bad of [{...m,id:"bad"},{...m,entryIndex:2},{...m,duration:15},{...m,start:615,end:635}])assert.equal(validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,[bad]).spaceMealViolationCount,1)});
test("future feasibility publishes canonical meal blocker and exhaustion atomically",()=>{const p=spaceMealScenario(),blocking=[{...p.tasks.find(t=>t.id==="meal-room-task-a")!,start:620,end:640}];const a=assessFutureFeasibility(p,blocking,[],{remaining:100},()=>({count:0,exhausted:false}));assert.deepEqual(a.blockingWorkItemKeys,["meal:meal-room"]);const b=assessFutureFeasibility(p,[],[],{remaining:0},()=>({count:0,exhausted:false}));assert.equal(b.exhausted,true);assert.deepEqual(b.assessments,[])});
test("planner input remains immutable",()=>{const p=spaceMealScenario(),before=structuredClone(p);planMainFlowAndFeeders(p);assert.deepEqual(p,before)});
test("potential meal starts use global five-minute boundaries and hard filtering",()=>{const immutable=spaceMealScenario(),before=structuredClone(immutable);assert.deepEqual(requireStarts(immutable),[620]);assert.deepEqual(immutable,before);const p=spaceMealScenario(),space=p.spaces.find(s=>s.id==="meal-room")!;space.mealPolicy={window:{start:621,end:646},duration:20};assert.deepEqual(requireStarts(p),[625]);space.mealPolicy={window:{start:621,end:644},duration:20};assert.deepEqual(requireStarts(p),[]);space.mealPolicy={window:{start:620,end:650},duration:20};assert(requireStarts(p).every((x:number)=>x%5===0));assert.deepEqual(requireStarts(p),[620,625,630]);const own={...p.tasks.at(-1)!,start:620,end:625},other={...own,spaceId:"other"};assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[own],[]),[625,630]);assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[],[createScheduledSpaceMeal("meal-room",625,20)]),[]);assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[other],[]),[620,625,630]);p.protectedMeal={start:620,end:650};assert.deepEqual(spaceMealCandidateStarts(p,"meal-room",[],[]),[620,625,630]);});
test("required block meal PROBE stops immediately without changing SEARCH or publishing partials",()=>{
  const p=requiredSpaceMealScenario(),before=structuredClone(p),tasks=p.tasks.filter(t=>t.spaceId==="required-meal-room"),logical=(c:any)=>({tasks:c.tasks.map(({id,start,end}:any)=>({id,start,end})),meals:c.meals.map(({id,start,end}:any)=>({id,start,end})),cost:c.cost});
  const run=(mode:"SEARCH"|"PROBE",limit=p.budget.bestK,items=tasks,allowance=p.budget.maxBranchExpansions)=>generateBlockCandidates(p,items,[],allowance,0,mode,limit);
  const search=run("SEARCH"),searchAgain=run("SEARCH"),probeLimit1=run("PROBE",1),probeLimit1Again=run("PROBE",1),probeLimit2=run("PROBE",2),probeBestK=run("PROBE",p.budget.bestK),reversed=run("SEARCH",p.budget.bestK,[...tasks].reverse()),short=run("PROBE",1,tasks,3);
  assert.equal(search.consumed,51);assert.equal(search.candidates.length,5);assert.equal(search.diagnostics.completeCandidatesGenerated,5);assert.equal(search.diagnostics.maximumPartialStatesPerStart,5);assert.equal(search.diagnostics.mealAttemptsExplored,10);
  assert(search.candidates.every(c=>c.tasks.length===4&&c.meals.length===1&&c.meals[0]!.start===700));assert.deepEqual(search,searchAgain);assert.deepEqual(search,reversed);
  assert.equal(probeLimit1.exhausted,false);assert.equal(probeLimit1.candidates.length,1);assert.equal(probeLimit1.diagnostics.completeCandidatesGenerated,1);assert(probeLimit1.consumed<51);assert(probeLimit1.consumed<search.consumed);assert.deepEqual(logical(probeLimit1.candidates[0]),logical(search.candidates[0]));assert.deepEqual(probeLimit1,probeLimit1Again);
  assert.equal(probeLimit2.exhausted,false);assert.equal(probeLimit2.candidates.length,2);assert.equal(probeLimit2.diagnostics.completeCandidatesGenerated,2);assert(probeLimit2.consumed>=probeLimit1.consumed);assert(probeLimit2.consumed<=search.consumed);assert.deepEqual(probeLimit2.candidates.map(logical),search.candidates.slice(0,2).map(logical));
  assert.equal(probeBestK.candidates.length,5);assert.equal(probeBestK.diagnostics.completeCandidatesGenerated,5);assert(probeBestK.consumed<=search.consumed);assert.deepEqual(probeBestK.candidates.map(logical),search.candidates.map(logical));
  for(const result of [search,probeLimit1,probeLimit2,probeBestK]){assert(result.diagnostics.maximumPartialStatesPerStart<=p.budget.bestK);assert(result.candidates.every(c=>c.tasks.length===tasks.length&&c.meals.length===1));}
  assert.equal(short.exhausted,true);assert.equal(short.consumed,3);assert.deepEqual(short.candidates,[]);assert.equal(short.diagnostics.completeCandidatesGenerated,0);assert.deepEqual(p,before);
  assert.deepEqual(independentSpaceMealIds(p,[]),["meal-room"]);assert.deepEqual(requiredBlockMealSpaceIds(p,[]),["required-meal-room"]);
  const r=planMainFlowAndFeeders(p);assert.equal(r.complete,true);assert(r.metrics.auxiliaryWorkItemSelectionOrder.includes("space:required-meal-room"));assert(!r.metrics.auxiliaryWorkItemSelectionOrder.includes("meal:required-meal-room"));assert.deepEqual(r.scheduledTasks.filter(t=>t.spaceId==="required-meal-room").map(t=>[t.start,t.end]),[[660,680],[680,700],[720,740],[740,760]]);assert.deepEqual(r.scheduledSpaceMeals.find(m=>m.spaceId==="required-meal-room")&&[700,720],[700,720]);assert.equal(r.metrics.secondarySpaceGapMinutesById["required-meal-room"],0);assert.equal(r.metrics.secondarySpaceBlockCountById["required-meal-room"],1);
})
test("required meal validation reports meal and continuity independently and is order invariant",()=>{const p=requiredSpaceMealScenario(),r=planMainFlowAndFeeders(p),own=r.scheduledSpaceMeals.find(m=>m.spaceId==="required-meal-room")!,without=r.scheduledSpaceMeals.filter(m=>m!==own),a=validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,without);assert.equal(a.spaceMealViolationCount,1);assert.equal(a.secondaryContinuityViolationCount,1);const duplicate=validatePlan(p,[...r.scheduledTasks].reverse(),[...r.scheduledSetupPreparations].reverse(),[...r.scheduledSpaceMeals,own].reverse());assert.equal(duplicate.spaceMealViolationCount,1);assert.deepEqual(validatePlan(p,[...r.scheduledTasks].reverse(),[...r.scheduledSetupPreparations].reverse(),[...r.scheduledSpaceMeals].reverse()),validatePlan(p,r.scheduledTasks,r.scheduledSetupPreparations,r.scheduledSpaceMeals))});
test("an impossible required meal block publishes no part of the plan",()=>{const p=requiredSpaceMealScenario();p.spaces.find(s=>s.id==="required-meal-room")!.mealPolicy={window:{start:705,end:725},duration:20};const r=planMainFlowAndFeeders(p);assert.equal(r.complete,false);assert.deepEqual(r.scheduledTasks,[]);assert.deepEqual(r.scheduledSetupPreparations,[]);assert.deepEqual(r.scheduledSpaceMeals,[])});
function requireStarts(p:any){return spaceMealPotentialStarts(p,"meal-room")}
test("future meal feasibility charges invalid starts and exhausts atomically",()=>{const p=spaceMealScenario(),s=p.spaces.find(x=>x.id==="meal-room")!;s.mealPolicy={window:{start:620,end:650},duration:20};const task={...p.tasks.at(-1)!,start:620,end:630},budget={remaining:2},before=structuredClone(p),r=assessFutureFeasibility(p,[task],[],budget,()=>({count:0,exhausted:false}));assert.equal(r.exhausted,true);assert.equal(r.branchesConsumed,2);assert.equal(budget.remaining,0);assert.deepEqual(r.assessments,[]);assert.deepEqual(p,before);const full=assessFutureFeasibility(p,[{...task,end:650}],[],{remaining:3},()=>({count:0,exhausted:false}));assert.equal(full.branchesConsumed,3);assert.deepEqual(full.blockingWorkItemKeys,["meal:meal-room"]);p.budget.bestK=2;const best=assessFutureFeasibility(p,[],[],{remaining:10},()=>({count:0,exhausted:false}));assert.equal(best.assessments[0]?.alternativeCount,2);assert.equal(best.branchesConsumed,2)});
