import type { Candidate, Evidence, OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { resolveORCPlanningEntryOperationalRoleMetadata } from "../state/nonWorkTaskClassifier";
import { resolveORCSpaceOccupancy } from "../state/spaceOccupancyResolver";
import { resolveORCTransportContract } from "../state/transportContractResolver";

export const BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION = "BASELINE-OVERLAP-REPAIR-CONFLICT-CLOSURE-V1" as const;
export type BaselineRepairClosureDirection = "forward" | "backward";
export interface BaselineRepairConflictClosureLimits { maxClosureTasks: number; maxClosureDepth: number; maxBoundaryCandidatesPerRoot: number; maxGeneratedClosureCandidates: number; }
export const DEFAULT_BASELINE_REPAIR_CONFLICT_CLOSURE_LIMITS: BaselineRepairConflictClosureLimits = { maxClosureTasks: 3, maxClosureDepth: 3, maxBoundaryCandidatesPerRoot: 16, maxGeneratedClosureCandidates: 12 };
export type ClosureBlockReason = "contestant_overlap"|"itinerant_team_overlap"|"obvious_resource_overlap"|"obvious_space_overlap"|"direct_dependency_broken"|"template_dependency_broken"|"availability_violation"|"outside_workday"|"hard_break_overlap"|"meal_overlap"|"protected_task"|"locked_task"|"closure_limit_reached"|"no_boundary_available"|"duplicate_assignment";
export interface ClosureAssignment { taskId: number; startPlanned: string; endPlanned: string; spaceId: number | null; resourceIds: number[]; }
export interface BaselineRepairConflictClosureCandidate { id: string; assignments: ClosureAssignment[]; movedTaskIds: number[]; conflictsResolved: string[]; conflictsRemaining: string[]; residualConflictCount: number; residualConflictCodes: string[]; residualConflictTaskPairs: number[][]; dependenciesChecked: string[]; blockingReason: ClosureBlockReason | null; depthUsed: number; taskCount: number; totalDisplacementMinutes: number; maximumDisplacementMinutes: number; direction: BaselineRepairClosureDirection; rootTaskId: number; evidence: Record<string, unknown>; }
export interface BaselineRepairConflictClosureResult { candidates: BaselineRepairConflictClosureCandidate[]; rejected: { reason: ClosureBlockReason; taskIds: number[]; boundary?: string | null }[]; summary: { version: typeof BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION; originalConflictTaskIds: number[]; originalViolationCodes: string[]; rootVariantsEvaluated: number; boundaryCandidatesEvaluated: number; generatedCandidateCount: number; locallyRejectedCandidateCount: number; prefilterRejectedCandidateCount: number; canonicallyValidCandidateCount: number; selectedCandidateId: string | null; selectedRootTaskId: number | null; selectedDirection: BaselineRepairClosureDirection | null; selectedMovedTaskIds: number[]; selectedAssignmentCount: number; selectedClosureDepth: number; selectedTotalDisplacementMinutes: number; selectedMaximumDisplacementMinutes: number; selectedPlanningFingerprint: string | null; selectedCanonicalValidationResult: string | null; selectedContestantOverlapCount: number; selectedResourceOverlapCount: number; selectedSpaceOverlapCount: number; selectedDependencyViolationCount: number; selectedAvailabilityViolationCount: number; previewClosedCandidateCount: number; previewRejectedCandidateCount: number; executableCandidateCount: number; residualConflictReasonCounts: Record<string, number>; selectedResidualConflictCount: number | null; selectedResidualConflictCodes: string[]; noValidRepairReason: string | null; searchExhausted: boolean; rejectedReasonCounts: Record<string, number>; searchLimitReached: boolean; deterministic: true; readOnly: true; }; }

type Entry = OperationalState["planning"][number];
type Planned = Entry & { start: number; end: number; duration: number; task: OperationalState["tasks"][number] | undefined };
const toMinutes=(v:unknown):number|null=>{ if(typeof v!=="string"||!/^\d{2}:\d{2}$/.test(v)) return null; const [h,m]=v.split(":").map(Number); return h*60+m; };
const toTime=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const overlaps=(a:{start:number;end:number},b:{start:number;end:number})=>a.start<b.end&&b.start<a.end;
const resources=(p:Planned)=>[...(p.assignedResourceIds??(p.task as any)?.assignedResourceIds??[])].map(Number).filter(Number.isFinite).sort((a,b)=>a-b);
const hasLock=(s:OperationalState,id:number)=>(s.locks??[]).some(l=>l.taskId===id&&["full","time"].includes(String(l.lockType)));
const protectedTask=(p:Planned)=>["done","in_progress"].includes(String(p.task?.status??""));
function planned(state:OperationalState):Planned[]{const tasks=new Map((state.tasks??[]).map(t=>[t.id,t]));return (state.planning??[]).flatMap((e):Planned[]=>{const start=toMinutes(e.startPlanned),end=toMinutes(e.endPlanned);return start==null||end==null||end<=start?[]:[{...e,assignedResourceIds:[...(e.assignedResourceIds??[])],start,end,duration:end-start,task:tasks.get(e.taskId)}];}).sort((a,b)=>a.start-b.start||a.end-b.end||a.taskId-b.taskId)}
function spaceExclusive(state:OperationalState,p:Planned){const transportContract=(state.constraints as any)?.transportContract??resolveORCTransportContract(state as any);const role=resolveORCPlanningEntryOperationalRoleMetadata({entry:p,task:p.task,mealWindow:state.availability?.actualMeal??state.availability?.meal??state.availability?.mealWindow??null,transportContract});const occ=resolveORCSpaceOccupancy({entry:p,task:p.task,roleMetadata:role,spaceConfig:state.spaces,transportContract});return occ.blocksSpace&&occ.spaceOccupancyMode==="exclusive"&&!occ.allowsSpaceOverlap;}
function hardWindows(state:OperationalState){const c:any=state.constraints??{}; const av:any=state.availability??{}; const arr:any[]=[...(Array.isArray(c.hardBreaks)?c.hardBreaks:[]),...(Array.isArray(av.hardBreaks)?av.hardBreaks:[])]; const meal=av.actualMeal??av.meal??av.mealWindow; if(meal) arr.push(meal); return arr.map(w=>({start:toMinutes(w.start),end:toMinutes(w.end)})).filter((w):w is {start:number;end:number}=>w.start!=null&&w.end!=null&&w.end>w.start);}
function insideAvailability(state:OperationalState,start:number,end:number){const dayStart=toMinutes(state.workDay?.start??state.availability?.workDay?.start)??0, dayEnd=toMinutes(state.workDay?.end??state.availability?.workDay?.end)??1440; if(start<dayStart||end>dayEnd)return "outside_workday" as const; const av:any=state.availability??{}; const wins:any[]=Array.isArray(av.windows)?av.windows:Array.isArray(av.taskWindows)?av.taskWindows:[]; if(wins.length){const ok=wins.some(w=>{const s=toMinutes(w.start),e=toMinutes(w.end);return s!=null&&e!=null&&start>=s&&end<=e}); if(!ok)return "availability_violation" as const;} for(const w of hardWindows(state)) if(overlaps({start,end},w)) return "hard_break_overlap" as const; return null;}
function depReason(state:OperationalState, map:Map<number,{start:number;end:number}>):ClosureBlockReason|null{const deps:any[]=[...((state.constraints as any)?.dependencies??[]),...((state as any).dependencies??[])]; const byTemplate=new Map((state.tasks??[]).map(t=>[String((t as any).templateId??(t as any).template??""),t.id])); for(const d of deps){let a=Number(d.beforeTaskId??d.predecessorTaskId??d.fromTaskId), b=Number(d.afterTaskId??d.successorTaskId??d.toTaskId); let template=false; if(!Number.isFinite(a)&&d.beforeTemplateId!=null){a=Number(byTemplate.get(String(d.beforeTemplateId)));template=true} if(!Number.isFinite(b)&&d.afterTemplateId!=null){b=Number(byTemplate.get(String(d.afterTemplateId)));template=true} if(!Number.isFinite(a)||!Number.isFinite(b)) continue; const pa=map.get(a), pb=map.get(b); if(pa&&pb&&pa.end>pb.start) return template?"template_dependency_broken":"direct_dependency_broken";} return null;}

export interface BaselineRepairClosurePreviewConflict { code: ClosureBlockReason; taskIds: number[]; start: number; }
export function buildBaselineRepairClosurePreview(state: OperationalState, assignments: Map<number,{start:number;end:number}>): Planned[] {
  return planned(state).map((e) => {
    const a = assignments.get(e.taskId);
    return a ? { ...e, start: a.start, end: a.end, startPlanned: toTime(a.start), endPlanned: toTime(a.end) } : { ...e };
  }).sort((a,b)=>a.start-b.start||a.end-b.end||a.taskId-b.taskId);
}
const conflictPriority: Record<ClosureBlockReason, number> = { protected_task:0, locked_task:0, direct_dependency_broken:1, template_dependency_broken:1, contestant_overlap:2, itinerant_team_overlap:3, obvious_resource_overlap:4, obvious_space_overlap:5, availability_violation:6, outside_workday:6, hard_break_overlap:6, meal_overlap:6, closure_limit_reached:9, no_boundary_available:9, duplicate_assignment:9 };
function sortConflicts(conflicts: BaselineRepairClosurePreviewConflict[]): BaselineRepairClosurePreviewConflict[] {
  return [...conflicts].sort((a,b)=>(conflictPriority[a.code]??99)-(conflictPriority[b.code]??99)||a.start-b.start||Math.min(...a.taskIds)-Math.min(...b.taskIds)||Math.max(...a.taskIds)-Math.max(...b.taskIds)||a.code.localeCompare(b.code));
}
export function auditBaselineRepairClosurePreview(state: OperationalState, preview: Planned[], focusTaskIds: Set<number>): BaselineRepairClosurePreviewConflict[] {
  const out: BaselineRepairClosurePreviewConflict[] = [];
  for (const p of preview) if (focusTaskIds.has(p.taskId)) {
    const av=insideAvailability(state,p.start,p.end); if(av) out.push({code:av,taskIds:[p.taskId],start:p.start});
    if (protectedTask(p)) out.push({code:"protected_task",taskIds:[p.taskId],start:p.start});
    if (hasLock(state,p.taskId)) out.push({code:"locked_task",taskIds:[p.taskId],start:p.start});
  }
  for(let i=0;i<preview.length;i++) for(let j=i+1;j<preview.length;j++){
    const a=preview[i], b=preview[j]; if(!focusTaskIds.has(a.taskId)&&!focusTaskIds.has(b.taskId)) continue; if(!overlaps(a,b)) continue;
    if(a.task?.contestantId!=null&&a.task.contestantId===b.task?.contestantId) out.push({code:"contestant_overlap",taskIds:[a.taskId,b.taskId].sort((x,y)=>x-y),start:Math.min(a.start,b.start)});
    if(a.task?.itinerantTeamId!=null&&a.task.itinerantTeamId===b.task?.itinerantTeamId) out.push({code:"itinerant_team_overlap",taskIds:[a.taskId,b.taskId].sort((x,y)=>x-y),start:Math.min(a.start,b.start)});
    if(resources(a).some(id=>resources(b).includes(id))) out.push({code:"obvious_resource_overlap",taskIds:[a.taskId,b.taskId].sort((x,y)=>x-y),start:Math.min(a.start,b.start)});
    if((a.spaceId??null)!=null&&a.spaceId===b.spaceId&&spaceExclusive(state,a)&&spaceExclusive(state,b)) out.push({code:"obvious_space_overlap",taskIds:[a.taskId,b.taskId].sort((x,y)=>x-y),start:Math.min(a.start,b.start)});
  }
  const deps:any[]=[...((state.constraints as any)?.dependencies??[]),...((state as any).dependencies??[])];
  const byTemplate=new Map<string, number[]>(); for (const t of state.tasks??[]) { const k=String((t as any).templateId??(t as any).template??""); if(k) byTemplate.set(k,[...(byTemplate.get(k)??[]),t.id]); }
  const map=new Map(preview.map(e=>[e.taskId,e]));
  for(const d of deps){
    let beforeIds=[Number(d.beforeTaskId??d.predecessorTaskId??d.fromTaskId)].filter(Number.isFinite), afterIds=[Number(d.afterTaskId??d.successorTaskId??d.toTaskId)].filter(Number.isFinite); let template=false;
    if(beforeIds.length===0&&d.beforeTemplateId!=null){beforeIds=byTemplate.get(String(d.beforeTemplateId))??[];template=true}
    if(afterIds.length===0&&d.afterTemplateId!=null){afterIds=byTemplate.get(String(d.afterTemplateId))??[];template=true}
    for(const a of beforeIds) for(const b of afterIds){ const pa=map.get(a), pb=map.get(b); if(pa&&pb&&pa.end>pb.start&&(focusTaskIds.has(a)||focusTaskIds.has(b))) out.push({code:template?"template_dependency_broken":"direct_dependency_broken",taskIds:[a,b].sort((x,y)=>x-y),start:Math.min(pa.start,pb.start)}); }
  }
  const seen=new Set<string>(); return sortConflicts(out).filter(c=>{const k=`${c.code}:${c.taskIds.join('-')}:${c.start}`; if(seen.has(k)) return false; seen.add(k); return true;});
}
function boundaries(state:OperationalState,p:Planned,direction:BaselineRepairClosureDirection){const bs=new Set<number>(); const dayStart=toMinutes(state.workDay?.start??state.availability?.workDay?.start)??0, dayEnd=toMinutes(state.workDay?.end??state.availability?.workDay?.end)??1440; bs.add(dayStart); bs.add(dayEnd-p.duration); for(const e of planned(state)){bs.add(direction==="forward"?e.end:e.start-p.duration); if(p.task?.contestantId!=null&&p.task.contestantId===e.task?.contestantId){bs.add(e.end);bs.add(e.start-p.duration)} if((p.spaceId??null)!=null&&p.spaceId===e.spaceId){bs.add(e.end);bs.add(e.start-p.duration)} if(resources(p).some(id=>resources(e).includes(id))){bs.add(e.end);bs.add(e.start-p.duration)}} for(const w of hardWindows(state)){bs.add(w.end);bs.add(w.start-p.duration)} return [...bs].filter(Number.isFinite).sort((a,b)=>direction==="forward"?a-b:b-a);}
export function buildBaselineRepairConflictClosure(args:{ operationalState:OperationalState; originalConflictTaskIds:number[]; originalViolationCodes?:string[]; rootTaskId:number; direction:BaselineRepairClosureDirection; limits?:Partial<BaselineRepairConflictClosureLimits>; createdAt?:string|null }):BaselineRepairConflictClosureResult{
 const state=args.operationalState; const limits={...DEFAULT_BASELINE_REPAIR_CONFLICT_CLOSURE_LIMITS,...args.limits}; const entries=planned(state); const byId=new Map(entries.map(e=>[e.taskId,e])); const root=byId.get(args.rootTaskId); const rejected:BaselineRepairConflictClosureResult["rejected"]=[]; let evals=0, limit=false, closed=0, previewRejected=0; const out:BaselineRepairConflictClosureCandidate[]=[]; const residualCounts:Record<string,number>={};
 const reject=(reason:ClosureBlockReason,ids:number[],boundary?:string|null, conflicts: BaselineRepairClosurePreviewConflict[] = [])=>{rejected.push({reason,taskIds:ids,boundary}); previewRejected++; residualCounts[reason]=(residualCounts[reason]??0)+1; for(const c of conflicts) residualCounts[c.code]=(residualCounts[c.code]??0)+1; if(reason==="closure_limit_reached")limit=true;}; if(!root){reject("no_boundary_available",[args.rootTaskId]);}
 if(root) for(const start0 of boundaries(state,root,args.direction).filter(s=>args.direction==="forward"?s>=root.end:s+root.duration<=root.start).slice(0,limits.maxBoundaryCandidatesPerRoot)){
  evals++; const assigned=new Map<number,{start:number;end:number}>(); const movedIds=new Set<number>(); const focus=new Set<number>([...args.originalConflictTaskIds, root.taskId]); let block:ClosureBlockReason|null=null; let residual:BaselineRepairClosurePreviewConflict[]=[];
  assigned.set(root.taskId,{start:start0,end:start0+root.duration}); movedIds.add(root.taskId); focus.add(root.taskId);
  for(let depth=0;;depth++){
    const preview=buildBaselineRepairClosurePreview(state,assigned); residual=auditBaselineRepairClosurePreview(state,preview,focus);
    if(residual.length===0) break;
    if(movedIds.size>=limits.maxClosureTasks||depth>=limits.maxClosureDepth){block="closure_limit_reached";break;}
    const first=sortConflicts(residual)[0];
    const movableId=first.taskIds.map(id=>byId.get(id)).filter((p):p is Planned=>!!p&&!movedIds.has(p.taskId)).sort((a,b)=>a.start-b.start||a.taskId-b.taskId)[0];
    if(!movableId){block=first.code;break;}
    if(protectedTask(movableId)){block="protected_task";break} if(hasLock(state,movableId.taskId)){block="locked_task";break}
    const anchorIds=first.taskIds.filter(id=>id!==movableId.taskId); const anchors=anchorIds.map(id=>assigned.get(id)??byId.get(id)).filter(Boolean) as {start:number;end:number}[];
    const anchorEnd=args.direction==="forward"?Math.max(...anchors.map(a=>a.end)):Math.min(...anchors.map(a=>a.start));
    const candidates=args.direction==="forward"?[anchorEnd,...boundaries(state,movableId,args.direction)]:[anchorEnd-movableId.duration,...boundaries(state,movableId,args.direction)];
    const next=candidates.find(s=>args.direction==="forward"?s>=anchorEnd:s+movableId.duration<=anchorEnd);
    if(next==null){block="no_boundary_available";break}
    assigned.set(movableId.taskId,{start:next,end:next+movableId.duration}); movedIds.add(movableId.taskId); focus.add(movableId.taskId);
  }
  if(!block){ const dep=depReason(state,new Map(entries.map(e=>[e.taskId,assigned.get(e.taskId)??e]))); if(dep){block=dep; residual=[{code:dep,taskIds:[...movedIds].sort((a,b)=>a-b),start:start0}];} }
  if(block || residual.length>0){reject(block??residual[0]?.code??"no_boundary_available",[...movedIds].sort((a,b)=>a-b),toTime(start0),residual); continue}
  const moved=[...movedIds].map(id=>byId.get(id)).filter((x):x is Planned=>!!x).sort((a,b)=>a.taskId-b.taskId);
  const assignments=moved.map(m=>{const w=assigned.get(m.taskId)!;return {taskId:m.taskId,startPlanned:toTime(w.start),endPlanned:toTime(w.end),spaceId:m.spaceId??m.task?.spaceId??null,resourceIds:resources(m)}}); const disps=moved.map(m=>Math.abs((assigned.get(m.taskId)?.start??m.start)-m.start)); const id=`orc-see:baseline-overlap-repair:conflict-closure:${args.direction}:root-${root.taskId}:${assignments.map(a=>`${a.taskId}-${a.startPlanned}-${a.endPlanned}`).join("_")}`;
  closed++; out.push({id,assignments,movedTaskIds:[...movedIds].sort((a,b)=>a-b),conflictsResolved:["baseline_overlap"],conflictsRemaining:[],residualConflictCount:0,residualConflictCodes:[],residualConflictTaskPairs:[],dependenciesChecked:["direct","template"],blockingReason:null,depthUsed:Math.max(0,movedIds.size-1),taskCount:movedIds.size,totalDisplacementMinutes:disps.reduce((s,x)=>s+x,0),maximumDisplacementMinutes:Math.max(0,...disps),direction:args.direction,rootTaskId:root.taskId,evidence:{version:BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION,readOnly:true,residualConflictCount:0}});
  if(out.length>=limits.maxGeneratedClosureCandidates){limit=true;break}
 }
 out.sort((a,b)=>a.residualConflictCount-b.residualConflictCount||a.taskCount-b.taskCount||a.totalDisplacementMinutes-b.totalDisplacementMinutes||a.maximumDisplacementMinutes-b.maximumDisplacementMinutes||a.depthUsed-b.depthUsed||a.id.localeCompare(b.id)); const selected=out[0]??null; const counts:Record<string,number>={}; for(const r of rejected) counts[r.reason]=(counts[r.reason]??0)+1; return deepFreeze({candidates:out,rejected,summary:{version:BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION,originalConflictTaskIds:[...args.originalConflictTaskIds].sort((a,b)=>a-b),originalViolationCodes:args.originalViolationCodes??["SPACE_OVERLAP"],rootVariantsEvaluated:root?1:0,boundaryCandidatesEvaluated:evals,generatedCandidateCount:out.length,locallyRejectedCandidateCount:rejected.length,prefilterRejectedCandidateCount:0,canonicallyValidCandidateCount:0,selectedCandidateId:selected?.id??null,selectedRootTaskId:selected?.rootTaskId??null,selectedDirection:selected?.direction??null,selectedMovedTaskIds:selected?.movedTaskIds??[],selectedAssignmentCount:selected?.assignments.length??0,selectedClosureDepth:selected?.depthUsed??0,selectedTotalDisplacementMinutes:selected?.totalDisplacementMinutes??0,selectedMaximumDisplacementMinutes:selected?.maximumDisplacementMinutes??0,selectedPlanningFingerprint:null,selectedCanonicalValidationResult:null,selectedContestantOverlapCount:0,selectedResourceOverlapCount:0,selectedSpaceOverlapCount:0,selectedDependencyViolationCount:0,selectedAvailabilityViolationCount:0,previewClosedCandidateCount:closed,previewRejectedCandidateCount:previewRejected,executableCandidateCount:out.length,residualConflictReasonCounts:residualCounts,selectedResidualConflictCount:selected?.residualConflictCount??null,selectedResidualConflictCodes:selected?.residualConflictCodes??[],noValidRepairReason:out.length===0?(rejected[0]?.reason??"no_boundary_available"):null,searchExhausted:!limit, rejectedReasonCounts:counts,searchLimitReached:limit,deterministic:true,readOnly:true}}) as BaselineRepairConflictClosureResult;
}
export function closureCandidateToORCCandidate(c:BaselineRepairConflictClosureCandidate, conflictingTaskIds:number[], createdAt:string|null):{candidate:Candidate;evidence:Evidence}{const evidenceId=`evidence:${c.id}`; const metadata={strategy:"BASELINE_SPACE_OVERLAP_REPAIR",strategyFamily:"baseline-repair",strategyType:"repair_space_overlap",baselineRepairCandidate:true,baselineRepairType:"productive-space-overlap-conflict-closure",repairVariant:`closure-${c.direction}`,movedTaskId:c.rootTaskId,fixedTaskId:conflictingTaskIds.find(id=>id!==c.rootTaskId)??null,conflictingTaskIds,movedTaskIds:c.movedTaskIds,localFeasibility:{locallyFeasible:true,warnings:[],blockingReason:null,checkedConstraints:["closure"],readOnly:true},conflictClosure:c.evidence,generationReason:"conflict_closure",expectedImpact:"restore-hard-feasibility",planningInfluence:"candidate-assignments",executesTransformations:true,readOnly:false,repairedViolationCode:"SPACE_OVERLAP"}; return {candidate:{id:c.id,state:{status:"draft",evidenceIds:[evidenceId],metadata},assignments:c.assignments,operationalValues:[],evidenceIds:[evidenceId],metadata},evidence:deepFreeze({id:evidenceId,source:"orc-see",kind:"baseline-overlap-repair-conflict-closure-candidate-generated",subjectId:c.id,createdAt,data:{candidateId:c.id,conflictingTaskIds,movedTaskIds:c.movedTaskIds,assignments:c.assignments,conflictClosure:c.evidence,readOnly:true,mutatesOperationalState:false,commitsPlanning:false}}) as Evidence};}
