import type { Candidate, Evidence, OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { resolveORCPlanningEntryOperationalRoleMetadata } from "../state/nonWorkTaskClassifier";
import { resolveORCSpaceOccupancy } from "../state/spaceOccupancyResolver";
import { resolveORCTransportContract } from "../state/transportContractResolver";

export const BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION = "BASELINE-OVERLAP-REPAIR-CONFLICT-CLOSURE-V1" as const;
export type BaselineRepairClosureDirection = "forward" | "backward";
export interface BaselineRepairConflictClosureLimits { maxClosureTasks: number; maxClosureDepth: number; maxBoundaryCandidatesPerRoot: number; maxGeneratedClosureCandidates: number; }
export const DEFAULT_BASELINE_REPAIR_CONFLICT_CLOSURE_LIMITS: BaselineRepairConflictClosureLimits = { maxClosureTasks: 3, maxClosureDepth: 3, maxBoundaryCandidatesPerRoot: 16, maxGeneratedClosureCandidates: 12 };
export type ClosureBlockReason = "contestant_overlap"|"itinerant_team_overlap"|"obvious_resource_overlap"|"obvious_space_overlap"|"direct_dependency_broken"|"template_dependency_broken"|"availability_violation"|"outside_workday"|"hard_break_overlap"|"meal_overlap"|"protected_task"|"locked_task"|"closure_limit_reached"|"no_boundary_available"|"duplicate_assignment";
export interface ClosureAssignment { taskId: number; startPlanned: string; endPlanned: string; spaceId: number | null; resourceIds: number[]; }
export interface BaselineRepairConflictClosureCandidate { id: string; assignments: ClosureAssignment[]; movedTaskIds: number[]; conflictsResolved: string[]; conflictsRemaining: string[]; dependenciesChecked: string[]; blockingReason: ClosureBlockReason | null; depthUsed: number; taskCount: number; totalDisplacementMinutes: number; maximumDisplacementMinutes: number; direction: BaselineRepairClosureDirection; rootTaskId: number; evidence: Record<string, unknown>; }
export interface BaselineRepairConflictClosureResult { candidates: BaselineRepairConflictClosureCandidate[]; rejected: { reason: ClosureBlockReason; taskIds: number[]; boundary?: string | null }[]; summary: { version: typeof BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION; originalConflictTaskIds: number[]; originalViolationCodes: string[]; rootVariantsEvaluated: number; boundaryCandidatesEvaluated: number; generatedCandidateCount: number; locallyRejectedCandidateCount: number; prefilterRejectedCandidateCount: number; canonicallyValidCandidateCount: number; selectedCandidateId: string | null; selectedRootTaskId: number | null; selectedDirection: BaselineRepairClosureDirection | null; selectedMovedTaskIds: number[]; selectedAssignmentCount: number; selectedClosureDepth: number; selectedTotalDisplacementMinutes: number; selectedMaximumDisplacementMinutes: number; selectedPlanningFingerprint: string | null; selectedCanonicalValidationResult: string | null; selectedContestantOverlapCount: number; selectedResourceOverlapCount: number; selectedSpaceOverlapCount: number; selectedDependencyViolationCount: number; selectedAvailabilityViolationCount: number; rejectedReasonCounts: Record<string, number>; searchLimitReached: boolean; deterministic: true; readOnly: true; }; }

type Entry = OperationalState["planning"][number];
type Planned = Entry & { start: number; end: number; duration: number; task: OperationalState["tasks"][number] | undefined };
const toMinutes=(v:unknown):number|null=>{ if(typeof v!=="string"||!/^\d{2}:\d{2}$/.test(v)) return null; const [h,m]=v.split(":").map(Number); return h*60+m; };
const toTime=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const overlaps=(a:{start:number;end:number},b:{start:number;end:number})=>a.start<b.end&&b.start<a.end;
const resources=(p:Planned)=>[...(p.assignedResourceIds??(p.task as any)?.assignedResourceIds??[])].map(Number).filter(Number.isFinite).sort((a,b)=>a-b);
const hasLock=(s:OperationalState,id:number)=>(s.locks??[]).some(l=>l.taskId===id&&["full","time"].includes(String(l.lockType)));
const protectedTask=(p:Planned)=>["done","in_progress"].includes(String(p.task?.status??""));
function planned(state:OperationalState):Planned[]{const tasks=new Map((state.tasks??[]).map(t=>[t.id,t]));return (state.planning??[]).flatMap((e):Planned[]=>{const start=toMinutes(e.startPlanned),end=toMinutes(e.endPlanned);return start==null||end==null||end<=start?[]:[{...e,assignedResourceIds:[...(e.assignedResourceIds??[])],start,end,duration:end-start,task:tasks.get(e.taskId)}];}).sort((a,b)=>a.start-b.start||a.end-b.end||a.taskId-b.taskId)}
function spaceExclusive(state:OperationalState,p:Planned){const transportContract=(state.constraints as any)?.transportContract??resolveORCTransportContract(state as any);const role=resolveORCPlanningEntryOperationalRoleMetadata({entry:p,task:p.task,mealWindow:state.availability?.actualMeal??state.availability?.meal??state.availability?.mealWindow??null,transportContract});const occ=resolveORCSpaceOccupancy({entry:p,task:p.task,roleMetadata:role,spaceConfig:state.spaces,transportContract});return occ.blocksSpace&&occ.spaceOccupancyMode==="exclusive"&&!occ.allowsSpaceOverlap;}
function hardWindows(state:OperationalState){const c:any=state.constraints??{}; const av:any=state.availability??{}; const arr:any[]=[...(Array.isArray(c.hardBreaks)?c.hardBreaks:[]),...(Array.isArray(av.hardBreaks)?av.hardBreaks:[])]; const meal=av.actualMeal??av.meal??av.mealWindow; if(meal) arr.push(meal); return arr.map(w=>({start:toMinutes(w.start),end:toMinutes(w.end)})).filter((w):w is {start:number;end:number}=>w.start!=null&&w.end!=null&&w.end>w.start);}
function insideAvailability(state:OperationalState,start:number,end:number){const dayStart=toMinutes(state.workDay?.start??state.availability?.workDay?.start)??0, dayEnd=toMinutes(state.workDay?.end??state.availability?.workDay?.end)??1440; if(start<dayStart||end>dayEnd)return "outside_workday" as const; const av:any=state.availability??{}; const wins:any[]=Array.isArray(av.windows)?av.windows:Array.isArray(av.taskWindows)?av.taskWindows:[]; if(wins.length){const ok=wins.some(w=>{const s=toMinutes(w.start),e=toMinutes(w.end);return s!=null&&e!=null&&start>=s&&end<=e}); if(!ok)return "availability_violation" as const;} for(const w of hardWindows(state)) if(overlaps({start,end},w)) return "hard_break_overlap" as const; return null;}
function depReason(state:OperationalState, map:Map<number,{start:number;end:number}>):ClosureBlockReason|null{const deps:any[]=[...((state.constraints as any)?.dependencies??[]),...((state as any).dependencies??[])]; const byTemplate=new Map((state.tasks??[]).map(t=>[String((t as any).templateId??(t as any).template??""),t.id])); for(const d of deps){let a=Number(d.beforeTaskId??d.predecessorTaskId??d.fromTaskId), b=Number(d.afterTaskId??d.successorTaskId??d.toTaskId); let template=false; if(!Number.isFinite(a)&&d.beforeTemplateId!=null){a=Number(byTemplate.get(String(d.beforeTemplateId)));template=true} if(!Number.isFinite(b)&&d.afterTemplateId!=null){b=Number(byTemplate.get(String(d.afterTemplateId)));template=true} if(!Number.isFinite(a)||!Number.isFinite(b)) continue; const pa=map.get(a), pb=map.get(b); if(pa&&pb&&pa.end>pb.start) return template?"template_dependency_broken":"direct_dependency_broken";} return null;}
function conflictReason(state:OperationalState,p:Planned,start:number,end:number,entries:Planned[],assigned:Map<number,{start:number;end:number}>):{reason:ClosureBlockReason; other?:Planned}|null{const av=insideAvailability(state,start,end); if(av)return {reason:av}; const test={...p,start,end}; for(const other of entries){if(other.taskId===p.taskId)continue; const o=assigned.get(other.taskId)??other; if(!overlaps(test,o))continue; if(p.task?.contestantId!=null&&p.task.contestantId===other.task?.contestantId)return {reason:"contestant_overlap",other}; if(p.task?.itinerantTeamId!=null&&p.task.itinerantTeamId===other.task?.itinerantTeamId)return {reason:"itinerant_team_overlap",other}; if(resources(p).some(id=>resources(other).includes(id)))return {reason:"obvious_resource_overlap",other}; if((p.spaceId??null)!=null&&p.spaceId===other.spaceId&&spaceExclusive(state,p)&&spaceExclusive(state,other))return {reason:"obvious_space_overlap",other};} return null;}
function boundaries(state:OperationalState,p:Planned,direction:BaselineRepairClosureDirection){const bs=new Set<number>(); const dayStart=toMinutes(state.workDay?.start??state.availability?.workDay?.start)??0, dayEnd=toMinutes(state.workDay?.end??state.availability?.workDay?.end)??1440; bs.add(dayStart); bs.add(dayEnd-p.duration); for(const e of planned(state)){bs.add(direction==="forward"?e.end:e.start-p.duration); if(p.task?.contestantId!=null&&p.task.contestantId===e.task?.contestantId){bs.add(e.end);bs.add(e.start-p.duration)} if((p.spaceId??null)!=null&&p.spaceId===e.spaceId){bs.add(e.end);bs.add(e.start-p.duration)} if(resources(p).some(id=>resources(e).includes(id))){bs.add(e.end);bs.add(e.start-p.duration)}} for(const w of hardWindows(state)){bs.add(w.end);bs.add(w.start-p.duration)} return [...bs].filter(Number.isFinite).sort((a,b)=>direction==="forward"?a-b:b-a);}
export function buildBaselineRepairConflictClosure(args:{ operationalState:OperationalState; originalConflictTaskIds:number[]; originalViolationCodes?:string[]; rootTaskId:number; direction:BaselineRepairClosureDirection; limits?:Partial<BaselineRepairConflictClosureLimits>; createdAt?:string|null }):BaselineRepairConflictClosureResult{const state=args.operationalState; const limits={...DEFAULT_BASELINE_REPAIR_CONFLICT_CLOSURE_LIMITS,...args.limits}; const entries=planned(state); const byId=new Map(entries.map(e=>[e.taskId,e])); const root=byId.get(args.rootTaskId); const rejected:BaselineRepairConflictClosureResult["rejected"]=[]; let evals=0, limit=false; const out:BaselineRepairConflictClosureCandidate[]=[]; const reject=(reason:ClosureBlockReason,ids:number[],boundary?:string|null)=>{rejected.push({reason,taskIds:ids,boundary}); if(reason==="closure_limit_reached")limit=true;}; if(!root){reject("no_boundary_available",[args.rootTaskId]);}
 if(root) for(const start0 of boundaries(state,root,args.direction).filter(s=>args.direction==="forward"?s>=root.end:s+root.duration<=root.start).slice(0,limits.maxBoundaryCandidatesPerRoot)){evals++; const assigned=new Map<number,{start:number;end:number}>(); const moved:Planned[]=[]; let cur:Planned|undefined=root, start=start0, depth=0, block:ClosureBlockReason|null=null; while(cur){ if(protectedTask(cur)){block="protected_task";break} if(hasLock(state,cur.taskId)){block="locked_task";break} if(moved.length>=limits.maxClosureTasks||depth>=limits.maxClosureDepth){block="closure_limit_reached";break} const end=start+cur.duration; assigned.set(cur.taskId,{start,end}); moved.push(cur); const c=conflictReason(state,cur,start,end,entries,assigned); if(!c){cur=undefined;break} if(!c.other){block=c.reason;break} if(protectedTask(c.other)){block="protected_task";break} if(hasLock(state,c.other.taskId)){block="locked_task";break} cur=c.other; const nextCandidates = args.direction === "forward" ? [end, ...boundaries(state,cur,args.direction)] : [start - cur.duration, ...boundaries(state,cur,args.direction)]; const next=nextCandidates.find(s=>args.direction==="forward"?s>=end:s+cur!.duration<=start); if(next==null){block="no_boundary_available";break} start=next; depth++; }
 const dep=depReason(state,new Map(entries.map(e=>[e.taskId,assigned.get(e.taskId)??e]))); if(!block&&dep) block=dep; if(block){reject(block,moved.map(m=>m.taskId),toTime(start0));continue} const assignments=moved.map(m=>{const w=assigned.get(m.taskId)!;return {taskId:m.taskId,startPlanned:toTime(w.start),endPlanned:toTime(w.end),spaceId:m.spaceId??m.task?.spaceId??null,resourceIds:resources(m)}}); const disps=moved.map(m=>Math.abs((assigned.get(m.taskId)?.start??m.start)-m.start)); const id=`orc-see:baseline-overlap-repair:conflict-closure:${args.direction}:root-${root.taskId}:${assignments.map(a=>`${a.taskId}-${a.startPlanned}-${a.endPlanned}`).join("_")}`; out.push({id,assignments,movedTaskIds:moved.map(m=>m.taskId).sort((a,b)=>a-b),conflictsResolved:["baseline_overlap"],conflictsRemaining:[],dependenciesChecked:["direct","template"],blockingReason:null,depthUsed:Math.max(0,moved.length-1),taskCount:moved.length,totalDisplacementMinutes:disps.reduce((s,x)=>s+x,0),maximumDisplacementMinutes:Math.max(0,...disps),direction:args.direction,rootTaskId:root.taskId,evidence:{version:BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION,readOnly:true}}); if(out.length>=limits.maxGeneratedClosureCandidates){limit=true;break} }
 out.sort((a,b)=>a.taskCount-b.taskCount||a.totalDisplacementMinutes-b.totalDisplacementMinutes||a.maximumDisplacementMinutes-b.maximumDisplacementMinutes||a.id.localeCompare(b.id)); const selected=out[0]??null; const counts:Record<string,number>={}; for(const r of rejected) counts[r.reason]=(counts[r.reason]??0)+1; return deepFreeze({candidates:out,rejected,summary:{version:BASELINE_OVERLAP_REPAIR_CONFLICT_CLOSURE_VERSION,originalConflictTaskIds:[...args.originalConflictTaskIds].sort((a,b)=>a-b),originalViolationCodes:args.originalViolationCodes??["SPACE_OVERLAP"],rootVariantsEvaluated:root?1:0,boundaryCandidatesEvaluated:evals,generatedCandidateCount:out.length,locallyRejectedCandidateCount:rejected.length,prefilterRejectedCandidateCount:0,canonicallyValidCandidateCount:0,selectedCandidateId:selected?.id??null,selectedRootTaskId:selected?.rootTaskId??null,selectedDirection:selected?.direction??null,selectedMovedTaskIds:selected?.movedTaskIds??[],selectedAssignmentCount:selected?.assignments.length??0,selectedClosureDepth:selected?.depthUsed??0,selectedTotalDisplacementMinutes:selected?.totalDisplacementMinutes??0,selectedMaximumDisplacementMinutes:selected?.maximumDisplacementMinutes??0,selectedPlanningFingerprint:null,selectedCanonicalValidationResult:null,selectedContestantOverlapCount:0,selectedResourceOverlapCount:0,selectedSpaceOverlapCount:0,selectedDependencyViolationCount:0,selectedAvailabilityViolationCount:0,rejectedReasonCounts:counts,searchLimitReached:limit,deterministic:true,readOnly:true}}) as BaselineRepairConflictClosureResult;}
export function closureCandidateToORCCandidate(c:BaselineRepairConflictClosureCandidate, conflictingTaskIds:number[], createdAt:string|null):{candidate:Candidate;evidence:Evidence}{const evidenceId=`evidence:${c.id}`; const metadata={strategy:"BASELINE_SPACE_OVERLAP_REPAIR",strategyFamily:"baseline-repair",strategyType:"repair_space_overlap",baselineRepairCandidate:true,baselineRepairType:"productive-space-overlap-conflict-closure",repairVariant:`closure-${c.direction}`,movedTaskId:c.rootTaskId,fixedTaskId:conflictingTaskIds.find(id=>id!==c.rootTaskId)??null,conflictingTaskIds,movedTaskIds:c.movedTaskIds,localFeasibility:{locallyFeasible:true,warnings:[],blockingReason:null,checkedConstraints:["closure"],readOnly:true},conflictClosure:c.evidence,generationReason:"conflict_closure",expectedImpact:"restore-hard-feasibility",planningInfluence:"candidate-assignments",executesTransformations:true,readOnly:false,repairedViolationCode:"SPACE_OVERLAP"}; return {candidate:{id:c.id,state:{status:"draft",evidenceIds:[evidenceId],metadata},assignments:c.assignments,operationalValues:[],evidenceIds:[evidenceId],metadata},evidence:deepFreeze({id:evidenceId,source:"orc-see",kind:"baseline-overlap-repair-conflict-closure-candidate-generated",subjectId:c.id,createdAt,data:{candidateId:c.id,conflictingTaskIds,movedTaskIds:c.movedTaskIds,assignments:c.assignments,conflictClosure:c.evidence,readOnly:true,mutatesOperationalState:false,commitsPlanning:false}}) as Evidence};}
