import test from "node:test"; import assert from "node:assert/strict";
import { buildInitialConstructionBranches, buildInitialConstructionClosure, searchInitialConstructionClosureAssignments } from "./initialConstructionBranchBuilder";
const state:any={id:"s",planning:[],locks:[],cognitive:{}};
function stage(anchor=1, prereqs:number[]=[2,3], windows:any[]=[{start:"09:00",end:"10:30"}]):any{return {selectedAnchor:{anchorTaskId:anchor,contestantId:1,spaceId:1},searchSpaces:[{anchorTaskId:anchor,provisionalWindows:windows}],initialConstructionMap:{dependencyGraph:{nodes:[{taskId:anchor,directPrerequisiteTaskIds:prereqs},{taskId:2,directPrerequisiteTaskIds:[]},{taskId:3,directPrerequisiteTaskIds:[]}]}}};}
const base=(tasks:any[], resources:any[]=[]):any=>({planId:1,workDay:{start:"09:00",end:"12:00"},meal:{start:"13:00",end:"14:00"},contestantAvailabilityById:{1:{start:"09:00",end:"12:00"},2:{start:"09:00",end:"12:00"},3:{start:"09:00",end:"12:00"}},planResourceItems:resources,tasks});

test("buildInitialConstructionClosure returns deterministic transitive topological closure",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30},{id:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30},{id:3,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}]); const c=buildInitialConstructionClosure({input,stage1:stage(),anchorTaskId:1}); assert.deepEqual(c.closureTaskIds,[2,3,1]); });

test("recursive search performs real temporal backtracking before completing closure",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00"},{id:3,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30}]); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[3,2]),maxBranches:1}); const b=r.branches[0]; assert.equal(b.status,"candidate"); assert.equal(b.searchEvidence?.closureComplete,true); assert.ok((b.searchEvidence?.recursiveBacktrackCount??0)>0); assert.deepEqual(b.assignments.map(a=>[a.taskId,a.startPlanned,a.endPlanned]),[[3,"09:00","09:30"],[2,"09:30","10:00"],[1,"10:00","10:30"]]); });

test("recursive search performs real resource backtracking before completing closure",()=>{ const resources=[{id:201,resourceItemId:11,typeId:1,name:"R1",isAvailable:true},{id:202,resourceItemId:12,typeId:1,name:"R2",isAvailable:true}]; const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00",resourceRequirements:{byItem:{11:1}}},{id:3,status:"pending",contestantId:3,spaceId:3,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00",resourceRequirements:{anyOf:[{resourceItemIds:[11,12],quantity:1}]}}],resources); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[2,3]),maxBranches:1}); const b=r.branches[0]; assert.equal(b.status,"candidate"); assert.ok((b.searchEvidence?.recursiveBacktrackCount??0)>0); assert.equal(new Set(b.assignments.map(a=>a.taskId)).size,3); assert.deepEqual(b.assignments.find(a=>a.taskId===3)?.resourceIds,[202]); assert.deepEqual(b.assignments.find(a=>a.taskId===2)?.resourceIds,[201]); });

test("recursive search stops deterministically on exhausted budget with exact blocker",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}]); const anchor={taskId:1,startPlanned:"10:00",endPlanned:"10:30",spaceId:1,resourceIds:[]}; const r=searchInitialConstructionClosureAssignments({input,originOperationalState:state,stage1:stage(1,[2]),closureTopologicalTaskIds:[2,1],anchorAssignment:anchor,branchWindow:{start:"09:00",end:"10:30"},reasoningBudget:{maxDepth:3,maxSearchSpaceSize:0,explorationBudget:1} as any}); assert.equal(r.ok,false); assert.equal(r.evidence.budgetExhausted,true); assert.deepEqual(r.blockers.map(b=>b.code),["ASSIGNMENT_SEARCH_BUDGET_EXHAUSTED"]); });

test("linear closure completes without pretending backtracking was observed",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00"},{id:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}]); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[2],[{start:"09:00",end:"10:00"}]),maxBranches:1}); assert.equal(r.branches[0].status,"candidate"); assert.equal(r.branches[0].searchEvidence?.recursiveBacktrackCount,0); });

test("equivalent shuffled declarations produce same assignments, backtracks, and fingerprint",()=>{ const tasks=[{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00"},{id:3,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30}]; const a=buildInitialConstructionBranches({input:base(tasks),originOperationalState:state,stage1:stage(1,[3,2]),maxBranches:1}); const b=buildInitialConstructionBranches({input:base([tasks[2],tasks[0],tasks[1]]),originOperationalState:state,stage1:stage(1,[2,3]),maxBranches:1}); assert.deepEqual(a.branches[0].assignments,b.branches[0].assignments); assert.equal(a.branches[0].searchEvidence?.recursiveBacktrackCount,b.branches[0].searchEvidence?.recursiveBacktrackCount); assert.equal(a.branches[0].searchEvidence?.assignmentSearchFingerprint,b.branches[0].searchEvidence?.assignmentSearchFingerprint); });
