import type { EngineInput } from "../../types";
import { deepFreeze } from "../immutability";
import { resolveORCPlanningEntryOperationalRoleMetadata } from "../state/nonWorkTaskClassifier";
import { resolveORCTransportContract } from "../state/transportContractResolver";
const min=(s?:string|null)=>s&&/^\d{2}:\d{2}$/.test(s)?Number(s.slice(0,2))*60+Number(s.slice(3)):null; const hh=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const dur=(t:any)=>Number(t?.durationOverrideMin??t?.durationMin??t?.durationMinutes??t?.duration??0)||0;
const overlaps=(a:any,b:any)=>{ const as=min(a.start), ae=min(a.end), bs=min(b.start), be=min(b.end); return as!=null&&ae!=null&&bs!=null&&be!=null&&as<be&&bs<ae; };
export interface InitialConstructionProtectedInterval { start:string; end:string; scope:"global"|"contestant"|"space"; contestantId:number|null; spaceId:number|null; source:string; sourceTaskId?:number|null; readOnly:true }
export function resolveInitialConstructionProtectedIntervalsForAnchor(args:{input:EngineInput; anchor:any}):InitialConstructionProtectedInterval[]{ const {input,anchor}=args; const out:InitialConstructionProtectedInterval[]=[]; const add=(start:any,end:any,scope:any,source:string,extra:any={})=>{ if(min(start)!=null&&min(end)!=null&&min(start)!<min(end)!) out.push({start,end,scope,contestantId:extra.contestantId??null,spaceId:extra.spaceId??null,source,sourceTaskId:extra.sourceTaskId??null,readOnly:true}); };
  if(input.meal?.start&&input.meal?.end) add(input.meal.start,input.meal.end,"global","hard_meal_break");
  if(input.actualMeal?.start&&input.actualMeal?.end) add(input.actualMeal.start,input.actualMeal.end,"global","actual_meal_break");
  const transport=resolveORCTransportContract(input as any); const meal=(input.actualMeal??input.meal??null) as any;
  for(const t of (input.tasks??[]) as any[]){ const meta=resolveORCPlanningEntryOperationalRoleMetadata({task:t,mealWindow:meal,transportContract:transport}); const start=t.startPlanned??t.fixedWindowStart??t.start; const end=t.endPlanned??t.fixedWindowEnd??t.end; if(!start||!end) continue; const source=meta.role==="space_break_placeholder"?"space_break_task":meta.role==="meal_break_placeholder"?"actual_meal_task":meta.role.startsWith("transport_")&&meta.blocksSpace?"protected_transport_task":t.protected===true||t.blocksSpace===true?"protected_task":null; if(!source) continue; const sameContestant=t.contestantId!=null&&anchor.contestantId!=null&&Number(t.contestantId)===Number(anchor.contestantId); const sameSpace=t.spaceId!=null&&anchor.spaceId!=null&&Number(t.spaceId)===Number(anchor.spaceId); if(source==="actual_meal_task"&&sameContestant) add(start,end,"contestant",source,{contestantId:Number(t.contestantId),sourceTaskId:t.id}); else if((source==="space_break_task"||t.blocksSpace===true)&&sameSpace) add(start,end,"space",source,{spaceId:Number(t.spaceId),sourceTaskId:t.id}); else if(source==="protected_task"&&(sameContestant||sameSpace)) add(start,end,sameSpace?"space":"contestant",source,{contestantId:sameContestant?Number(t.contestantId):null,spaceId:sameSpace?Number(t.spaceId):null,sourceTaskId:t.id}); else if(source==="protected_transport_task"&&sameContestant) add(start,end,"contestant",source,{contestantId:Number(t.contestantId),sourceTaskId:t.id}); }
  return out.sort((a,b)=>min(a.start)!-min(b.start)!||min(a.end)!-min(b.end)!||a.source.localeCompare(b.source)); }
function splitWindow(w:any, intervals:any[], duration:number){ let segs=[{start:min(w.start)!,end:min(w.end)!}]; for(const it of intervals){ const s=min(it.start), e=min(it.end); if(s==null||e==null) continue; segs=segs.flatMap(g=>!(g.start<e&&s<g.end)?[g]:[{start:g.start,end:Math.min(g.end,s)},{start:Math.max(g.start,e),end:g.end}].filter(x=>x.end-x.start>=duration)); } return segs.filter(g=>g.end-g.start>=duration).map(g=>({start:hh(g.start),end:hh(g.end),source:w.source})); }
export function countProtectedIntervalCrossings(windows:any[], intervals:any[]){ return windows.reduce((n,w)=>n+intervals.filter(i=>overlaps(w,i)).length,0); }
export function buildInitialConstructionSearchSpaces(args:{input:EngineInput; anchors:any[]; initialConstructionMap:any; maxSearchSpaces?:number; maxWindowsPerAnchor?:number}){ const spaces:any[]=[]; const {input,anchors}=args; const wd=input.workDay; const base=[wd?.start, wd?.end, input.meal?.start, input.meal?.end, input.actualMeal?.start, input.actualMeal?.end].filter(Boolean) as string[]; for(const anchor of anchors){ const times=[...base]; const av=anchor.contestantId!=null?(input.contestantAvailabilityById??{})[anchor.contestantId]:null; if(av){times.push(av.start,av.end)} const task=(input.tasks??[]).find(t=>t.id===anchor.anchorTaskId) as any; if(task?.fixedWindowStart) times.push(task.fixedWindowStart); if(task?.fixedWindowEnd) times.push(task.fixedWindowEnd); const duration=dur(task)||1; const protectedIntervalsApplied=resolveInitialConstructionProtectedIntervalsForAnchor({input,anchor}); for(const it of protectedIntervalsApplied){ times.push(it.start,it.end); } const sorted=[...new Set(times.map(min).filter((v):v is number=>v!=null))].sort((a,b)=>a-b); const raw=[]; for(let i=0;i<sorted.length-1;i++){ if(sorted[i+1]-sorted[i] >= duration) raw.push({start:hh(sorted[i]),end:hh(sorted[i+1]),source:"bounded_frontier"}); } const windows=raw.flatMap(w=>splitWindow(w,protectedIntervalsApplied,duration)).slice(0,args.maxWindowsPerAnchor??3); const crossings=countProtectedIntervalCrossings(windows,protectedIntervalsApplied); spaces.push({id:`initial-construction-stage1:${anchor.anchorTaskId}`,initialConstructionStage:1,anchorTaskId:anchor.anchorTaskId,prerequisiteClosureTaskIds:anchor.transitivePrerequisiteTaskIds,provisionalWindows:windows,protectedIntervalsApplied,provisionalWindowsCrossingProtectedIntervals:crossings,excludedProtectedIntervalCount:raw.reduce((n,w)=>n+protectedIntervalsApplied.filter(i=>overlaps(w,i)).length,0),propagatedConstraints:{contestantId:anchor.contestantId,spaceId:anchor.spaceId,zoneId:anchor.zoneId},criticalEntities:{contestantIds:[anchor.contestantId].filter(Boolean),resourceIds:[],spaceIds:[anchor.spaceId].filter(Boolean)},futureFeasibility:{preliminary:true,hardRisk:anchor.futureFreedomRisk,readOnly:true},blockers:[],budgetConsumed:{windows:windows.length,closureSize:anchor.transitivePrerequisiteTaskIds.length},executesTransformations:false,commitsPlanning:false,readOnly:true}); if(spaces.length>=(args.maxSearchSpaces??8)) break; } return deepFreeze(spaces) as any; }
export function buildInitialConstructionCandidates(searchSpaces:any[]){ return deepFreeze(searchSpaces.map((s:any)=>({id:`candidate:${s.id}`,assignments:[],metadata:{initialConstructionStage:1,anchorTaskId:s.anchorTaskId,closureTaskIds:s.prerequisiteClosureTaskIds,provisionalWindows:s.provisionalWindows,executesTransformations:false,commitsPlanning:false,readOnly:true},state:{status:"draft",metadata:{readOnly:true}},evidenceIds:[],operationalValues:[]}))) as any; }
