import type { EngineInput } from "../../types";
import type { Candidate, CandidateAssignment, OperationalState } from "../contracts";
import { deepFreeze } from "../immutability";
import { stableStringify } from "../structuralEquality";
import { createHash } from "node:crypto";
import { resolveInitialConstructionProtectedIntervalsForAnchor } from "./initialConstructionSearchSpace";

const toMin=(s?:string|null)=>/^\d{2}:\d{2}$/.test(String(s??""))?Number(String(s).slice(0,2))*60+Number(String(s).slice(3)):null;
const hh=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const dur=(t:any)=>Number(t?.durationOverrideMin??t?.durationMin??t?.durationMinutes??t?.duration??0)||0;
const overlaps=(a:any,b:any)=>{const as=toMin(a.startPlanned??a.start),ae=toMin(a.endPlanned??a.end),bs=toMin(b.startPlanned??b.start),be=toMin(b.endPlanned??b.end);return as!=null&&ae!=null&&bs!=null&&be!=null&&as<be&&bs<ae};
const protectedStatus=new Set(["done","in_progress"]);

export type Stage2BranchStatus="candidate"|"closure-incomplete"|"unsupported";
export interface InitialConstructionBranch { branchId:string; status:Stage2BranchStatus; assignments:CandidateAssignment[]; rejectionReason?:string|null; blockers:any[]; unsupportedRequirementCodes:string[]; evidence:any[]; }
export interface InitialConstructionBranchBuilderResult { selectedAnchorTaskId:number|null; closureTaskIds:number[]; topologicalTaskOrder:number[]; branches:InitialConstructionBranch[]; structuralFingerprint:string; readOnly:true; }

function prereqMap(stage1:any):Map<number,number[]> { return new Map((stage1.initialConstructionMap?.dependencyGraph?.nodes??[]).map((n:any)=>[Number(n.taskId),(n.directPrerequisiteTaskIds??[]).map(Number).sort((a:number,b:number)=>a-b)])); }
function cycleSet(stage1:any):Set<number>{ return new Set((stage1.initialConstructionMap?.dependencyGraph?.nodes??[]).filter((n:any)=>n.inDependencyCycle).map((n:any)=>Number(n.taskId))); }
export function buildInitialConstructionClosure(args:{input:EngineInput; stage1:any; anchorTaskId:number}){ const tasks=new Map((args.input.tasks??[]).map((t:any)=>[Number(t.id),t])); const pre=prereqMap(args.stage1); const cycles=cycleSet(args.stage1); const seen=new Set<number>(), order:number[]=[], blockers:any[]=[]; const visit=(id:number, stack:number[])=>{ if(seen.has(id)||cycles.has(id)) return; const task=tasks.get(id); if(!task){blockers.push({code:"MISSING_PREREQUISITE_TASK",taskId:id,dependentTaskId:stack.at(-1)??null}); return;} if(task.status!=="pending"&&task.status!=="interrupted") { if(id!==args.anchorTaskId) blockers.push({code:"PROTECTED_PREREQUISITE_TASK",taskId:id}); return; } seen.add(id); for(const p of pre.get(id)??[]) visit(p,[...stack,id]); order.push(id); }; visit(args.anchorTaskId,[]); return {closureTaskIds:order, topologicalTaskOrder:order, blockers}; }
function resourceAlternatives(input:EngineInput, task:any, occupied:CandidateAssignment[], start:string, end:string):{ids:number[]; unsupported?:any}[]{ const req=task.resourceRequirements??{}; if(req.byType&&Object.values(req.byType).some((q:any)=>Number(q)>0)) return [{ids:[],unsupported:{code:"UNSUPPORTED_STAGE2_CONSTRUCTIVE_REQUIREMENT",contract:"byType",taskId:task.id,evidence:req.byType}}]; const fixed=Object.entries(req.byItem??{}); let base:number[]=[]; for(const [rid,q] of fixed){ if(Number(q)!==1) return [{ids:[],unsupported:{code:"UNSUPPORTED_STAGE2_CONSTRUCTIVE_REQUIREMENT",contract:"byItem.quantity",taskId:task.id,evidence:{resourceItemId:Number(rid),quantity:q}}}]; const item=(input.planResourceItems??[]).filter(x=>x.isAvailable!==false&&Number(x.resourceItemId)===Number(rid)).sort((a,b)=>a.id-b.id).find(pr=>!occupied.some(o=>o.resourceIds.includes(pr.id)&&overlaps(o,{start,end}))); if(!item) return [{ids:[],unsupported:{code:"REQUIRED_RESOURCE_UNAVAILABLE",contract:"byItem",taskId:task.id,evidence:{resourceItemId:Number(rid)}}}]; base.push(item.id); }
 const groups=req.anyOf??[]; if(groups.some((g:any)=>Number(g.quantity)!==1)) return [{ids:[],unsupported:{code:"UNSUPPORTED_STAGE2_CONSTRUCTIVE_REQUIREMENT",contract:"ANY_OF.quantity",taskId:task.id,evidence:groups}}]; let alts=[base]; for(const g of groups){ const opts=(g.resourceItemIds??[]).flatMap((rid:number)=>(input.planResourceItems??[]).filter(x=>x.isAvailable!==false&&Number(x.resourceItemId)===Number(rid))).sort((a:any,b:any)=>a.id-b.id); const usable=opts.filter((pr:any)=>!occupied.some(o=>o.resourceIds.includes(pr.id)&&overlaps(o,{start,end}))); if(!usable.length) return [{ids:[],unsupported:{code:"REQUIRED_RESOURCE_UNAVAILABLE",contract:"ANY_OF",taskId:task.id,evidence:g}}]; alts=alts.flatMap((a:number[])=>usable.map((u:any)=>[...a,u.id])); }
 return alts.map(ids=>({ids:[...new Set(ids)].sort((a,b)=>a-b)})); }
function canPlace(input:EngineInput, task:any, a:CandidateAssignment, occupied:CandidateAssignment[], protectedIntervals:any[]):boolean{ const s=toMin(a.startPlanned), e=toMin(a.endPlanned), ws=toMin(input.workDay?.start), we=toMin(input.workDay?.end); if(s==null||e==null||ws==null||we==null||s<ws||e>we||e-s!==dur(task)) return false; if(protectedIntervals.some(i=>overlaps(a,i))) return false; if(occupied.some(o=>overlaps(o,a)&&(o.spaceId===a.spaceId|| (task.contestantId!=null && (input.tasks??[]).find(t=>t.id===o.taskId)?.contestantId===task.contestantId) || o.resourceIds.some(r=>a.resourceIds.includes(r))))) return false; return true; }
export function buildInitialConstructionBranches(args:{input:EngineInput; originOperationalState:OperationalState; stage1:any; maxBranches?:number}):InitialConstructionBranchBuilderResult{ const anchorId=Number(args.stage1.selectedAnchor?.anchorTaskId); const closure=buildInitialConstructionClosure({input:args.input,stage1:args.stage1,anchorTaskId:anchorId}); const tasks=new Map((args.input.tasks??[]).map((t:any)=>[Number(t.id),t])); const search=(args.stage1.searchSpaces??[]).find((s:any)=>Number(s.anchorTaskId)===anchorId); const branches:InitialConstructionBranch[]=[]; const max=args.maxBranches??8; const baseOccupied:CandidateAssignment[]=(args.originOperationalState.planning??[]).map((p:any)=>({taskId:p.taskId,startPlanned:p.startPlanned,endPlanned:p.endPlanned,spaceId:p.spaceId??null,resourceIds:[...(p.assignedResourceIds??[])]})); let seq=0;
 for(const w of (search?.provisionalWindows??[])){ if(branches.length>=max) break; const anchor=tasks.get(anchorId); if(!anchor) continue; const anchorEnd=toMin(w.end)!; const anchorStart=anchorEnd-dur(anchor); const provisional:CandidateAssignment[]=[]; const blockers=[...closure.blockers]; const prot=resolveInitialConstructionProtectedIntervalsForAnchor({input:args.input,anchor:args.stage1.selectedAnchor}); const tryTask=(taskId:number, latestEnd:number):boolean=>{ const task=tasks.get(taskId); if(!task) return false; const candidates=[latestEnd-dur(task), toMin(w.start)!-dur(task), toMin(args.input.workDay.start)!].filter((v,i,a)=>Number.isFinite(v)&&a.indexOf(v)===i).sort((a,b)=>b-a); for(const st of candidates){ const ass0={taskId,startPlanned:hh(st),endPlanned:hh(st+dur(task)),spaceId:task.spaceId??null,resourceIds:[]}; const res=resourceAlternatives(args.input,task,[...baseOccupied,...provisional],ass0.startPlanned!,ass0.endPlanned!); for(const r of res){ if(r.unsupported){ blockers.push(r.unsupported); continue; } const ass={...ass0,resourceIds:r.ids}; if(canPlace(args.input,task,ass,[...baseOccupied,...provisional],prot)){ provisional.push(ass); return true; } } } return false; };
 const anchorRes=resourceAlternatives(args.input,anchor,baseOccupied,hh(anchorStart),hh(anchorEnd)); for(const r of anchorRes){ seq++; const bid=`stage2-branch:${String(seq).padStart(3,"0")}`; if(r.unsupported){branches.push({branchId:bid,status:r.unsupported.code==="UNSUPPORTED_STAGE2_CONSTRUCTIVE_REQUIREMENT"?"unsupported":"closure-incomplete",assignments:[],rejectionReason:r.unsupported.code,blockers:[r.unsupported],unsupportedRequirementCodes:[r.unsupported.code],evidence:[r.unsupported]}); continue;} provisional.length=0; const aa={taskId:anchorId,startPlanned:hh(anchorStart),endPlanned:hh(anchorEnd),spaceId:anchor.spaceId??null,resourceIds:r.ids}; if(!canPlace(args.input,anchor,aa,baseOccupied,prot)){branches.push({branchId:bid,status:"closure-incomplete",assignments:[],rejectionReason:"ANCHOR_WINDOW_INFEASIBLE",blockers,evidence:[],unsupportedRequirementCodes:[]}); continue;} provisional.push(aa); let ok=true; for(const taskId of [...closure.topologicalTaskOrder].reverse().filter(id=>id!==anchorId)){ const depStarts=provisional.filter(a=> (prereqMap(args.stage1).get(a.taskId)??[]).includes(taskId)).map(a=>toMin(a.startPlanned)!); if(!tryTask(taskId, Math.min(...depStarts, anchorStart))) {ok=false; blockers.push({code:"PREREQUISITE_PLACEMENT_FAILED",taskId}); break;} } branches.push({branchId:bid,status:ok&&blockers.length===0?"candidate":blockers.some(b=>b.code==="UNSUPPORTED_STAGE2_CONSTRUCTIVE_REQUIREMENT")?"unsupported":"closure-incomplete",assignments:[...provisional].sort((a,b)=>toMin(a.startPlanned)!-toMin(b.startPlanned)!||a.taskId-b.taskId),rejectionReason:ok&&blockers.length===0?null:(blockers.at(-1)?.code??"CLOSURE_INCOMPLETE"),blockers:blockers.slice(0,10),unsupportedRequirementCodes:[...new Set(blockers.filter(b=>b.code==="UNSUPPORTED_STAGE2_CONSTRUCTIVE_REQUIREMENT").map(b=>b.code))],evidence:blockers.slice(0,5)}); }
 }
 const fp=createHash("sha256").update(stableStringify({anchorId,closure:closure.closureTaskIds,branches:branches.map(b=>({id:b.branchId,s:b.status,a:b.assignments}))})).digest("hex"); return deepFreeze({selectedAnchorTaskId:anchorId||null,closureTaskIds:closure.closureTaskIds,topologicalTaskOrder:closure.topologicalTaskOrder,branches,structuralFingerprint:fp,readOnly:true}) as any; }
export function branchToCandidate(branch:InitialConstructionBranch):Candidate{ return {id:`candidate:${branch.branchId}`,assignments:branch.assignments,state:{status:"draft",evidenceIds:[],metadata:{readOnly:true}},metadata:{strategy:"SCHEDULE_PENDING_TASKS",initialConstructionStage:2,branchId:branch.branchId,taskIds:branch.assignments.map(a=>a.taskId),executesTransformations:false,readOnly:true},evidenceIds:[],operationalValues:[]}; }
