import test from "node:test"; import assert from "node:assert/strict";
import { generateInitialConstructionAnchorTemporalCandidates } from "./initialConstructionAnchorTemporalCandidates";
const input:any={workDay:{start:"08:00",end:"18:00"},contestantAvailabilityById:{1:{start:"09:00",end:"17:00"}},tasks:[],planResourceItems:[]};

test("historical end-aligned candidate is first and no minute sweep is used",()=>{ const task:any={id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}; const c=generateInitialConstructionAnchorTemporalCandidates({input,anchorTask:task,provisionalWindow:{start:"09:00",end:"17:00"},maxCandidates:20}); assert.equal(c[0].startPlanned,"16:30"); assert.ok(c.length<10); });

test("fixed windows generate a single exact candidate",()=>{ const task:any={id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"}; const c=generateInitialConstructionAnchorTemporalCandidates({input,anchorTask:task,provisionalWindow:{start:"09:00",end:"17:00"},maxCandidates:20}); assert.deepEqual(c.map(x=>[x.startPlanned,x.endPlanned,x.sourceKinds]),[["10:00","10:30",["fixed-window"]]]); });

test("provisional assignment and protected interval borders seed bounded candidates without crossing",()=>{ const task:any={id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}; const local={...input,protectedBreaks:[{start:"12:00",end:"13:00",spaceId:1}],tasks:[]}; const c=generateInitialConstructionAnchorTemporalCandidates({input:local,anchorTask:task,provisionalWindow:{start:"09:00",end:"14:00"},provisionalAssignments:[{taskId:99,startPlanned:"10:00",endPlanned:"10:30",spaceId:1,resourceIds:[]}],maxCandidates:20}); const starts=c.map(x=>x.startPlanned); assert.ok(starts.includes("09:30")); assert.ok(starts.includes("10:30")); assert.ok(starts.includes("11:30")); assert.ok(starts.includes("13:00")); assert.equal(c.some(x=>x.startPlanned<"13:00"&&x.endPlanned>"12:00"),false); });

test("input order does not change candidates",()=>{ const task:any={id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}; const a=generateInitialConstructionAnchorTemporalCandidates({input,anchorTask:task,provisionalWindow:{start:"09:00",end:"17:00"},provisionalAssignments:[{taskId:2,startPlanned:"11:00",endPlanned:"11:30",spaceId:1,resourceIds:[]},{taskId:3,startPlanned:"10:00",endPlanned:"10:30",spaceId:1,resourceIds:[]}],maxCandidates:20}); const b=generateInitialConstructionAnchorTemporalCandidates({input,anchorTask:task,provisionalWindow:{start:"09:00",end:"17:00"},provisionalAssignments:[{taskId:3,startPlanned:"10:00",endPlanned:"10:30",spaceId:1,resourceIds:[]},{taskId:2,startPlanned:"11:00",endPlanned:"11:30",spaceId:1,resourceIds:[]}],maxCandidates:20}); assert.deepEqual(a,b); });

test("partial fixed windows generate exactly one preserved candidate",()=>{ const startTask:any={id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00"}; const endTask:any={...startTask,fixedWindowStart:undefined,fixedWindowEnd:"11:00"}; assert.deepEqual(generateInitialConstructionAnchorTemporalCandidates({input,anchorTask:startTask,provisionalWindow:{start:"09:00",end:"17:00"},maxCandidates:20}).map(x=>[x.startPlanned,x.endPlanned]),[["10:00","10:30"]]); assert.deepEqual(generateInitialConstructionAnchorTemporalCandidates({input,anchorTask:endTask,provisionalWindow:{start:"09:00",end:"17:00"},maxCandidates:20}).map(x=>[x.startPlanned,x.endPlanned]),[["10:30","11:00"]]); });

test("same contestant in another space and logical resource assignments seed boundaries while nonblocking placeholder does not",()=>{ const local:any={...input,tasks:[{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,resourceRequirements:{byItem:{70:1}}},{id:2,status:"pending",contestantId:1,spaceId:2,durationOverrideMin:30},{id:3,status:"pending",contestantId:1,spaceId:3,durationOverrideMin:30,type:"meal"},{id:4,status:"pending",contestantId:4,spaceId:4,durationOverrideMin:30}],planResourceItems:[{id:7,resourceItemId:70,isAvailable:true}]}; const c=generateInitialConstructionAnchorTemporalCandidates({input:local,anchorTask:local.tasks[0],provisionalWindow:{start:"09:00",end:"13:00"},provisionalAssignments:[{taskId:2,startPlanned:"10:00",endPlanned:"10:30",spaceId:2,resourceIds:[]},{taskId:3,startPlanned:"11:00",endPlanned:"11:30",spaceId:3,resourceIds:[]},{taskId:4,startPlanned:"12:00",endPlanned:"12:30",spaceId:4,resourceIds:[7]}],maxCandidates:20}); const starts=c.map(x=>x.startPlanned); assert.ok(starts.includes("09:30")); assert.ok(starts.includes("10:30")); assert.ok(starts.includes("11:30")); assert.equal(starts.includes("11:00"),false); });
