import test from "node:test"; import assert from "node:assert/strict";
import { buildInitialConstructionBranches, buildInitialConstructionClosure, searchInitialConstructionClosureAssignments } from "./initialConstructionBranchBuilder";
const state:any={id:"s",planning:[],locks:[],cognitive:{}};
function stage(anchor=1, prereqs:number[]=[2,3], windows:any[]=[{start:"09:00",end:"10:30"}]):any{return {selectedAnchor:{anchorTaskId:anchor,contestantId:1,spaceId:1},searchSpaces:[{anchorTaskId:anchor,provisionalWindows:windows}],initialConstructionMap:{dependencyGraph:{nodes:[{taskId:anchor,directPrerequisiteTaskIds:prereqs},{taskId:2,directPrerequisiteTaskIds:[]},{taskId:3,directPrerequisiteTaskIds:[]}]}}};}
const base=(tasks:any[], resources:any[]=[], workDay:any={start:"09:00",end:"12:00"}):any=>({planId:1,workDay,meal:{start:"13:00",end:"14:00"},contestantAvailabilityById:{1:{start:workDay.start,end:workDay.end},2:{start:workDay.start,end:workDay.end},3:{start:workDay.start,end:workDay.end}},planResourceItems:resources,tasks});

test("buildInitialConstructionClosure returns deterministic transitive topological closure",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30},{id:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30},{id:3,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}]); const c=buildInitialConstructionClosure({input,stage1:stage(),anchorTaskId:1}); assert.deepEqual(c.closureTaskIds,[2,3,1]); });

test("recursive search undoes an accepted temporal decision before completing closure",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:30",fixedWindowEnd:"11:00"},{id:2,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:3,status:"pending",contestantId:3,spaceId:2,durationOverrideMin:30}],[],{start:"09:00",end:"11:00"}); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[2,3],[{start:"09:30",end:"11:00"}]),maxBranches:1}); const b=r.branches[0]; assert.equal(b.status,"candidate"); assert.equal(b.searchEvidence?.closureComplete,true); assert.equal(b.searchEvidence?.temporalDecisionBacktrackCount,1); assert.equal(b.searchEvidence?.resourceDecisionBacktrackCount,0); assert.equal(b.searchEvidence?.recursiveBacktrackCount,1); assert.deepEqual(b.searchEvidence?.backtrackEventsSample,[{depth:0,taskId:3,startPlanned:"10:00",endPlanned:"10:30",resourceIds:[],failedDeeperTaskId:2,kind:"TEMPORAL_DECISION_UNDONE",nextAlternativeAvailable:true,readOnly:true}]); assert.deepEqual(b.assignments.map(a=>[a.taskId,a.startPlanned,a.endPlanned,a.resourceIds]),[[3,"09:30","10:00",[]],[2,"10:00","10:30",[]],[1,"10:30","11:00",[]]]); });

test("recursive search performs real resource backtracking before completing closure",()=>{ const resources=[{id:201,resourceItemId:11,typeId:1,name:"R1",isAvailable:true},{id:202,resourceItemId:12,typeId:1,name:"R2",isAvailable:true}]; const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00",resourceRequirements:{byItem:{11:1}}},{id:3,status:"pending",contestantId:3,spaceId:3,durationOverrideMin:30,fixedWindowStart:"09:30",fixedWindowEnd:"10:00",resourceRequirements:{anyOf:[{resourceItemIds:[11,12],quantity:1}]}}],resources); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[2,3]),maxBranches:1}); const b=r.branches[0]; assert.equal(b.status,"candidate"); assert.ok((b.searchEvidence?.resourceDecisionBacktrackCount??0)>0); assert.equal(b.searchEvidence?.recursiveBacktrackCount,(b.searchEvidence?.temporalDecisionBacktrackCount??0)+(b.searchEvidence?.resourceDecisionBacktrackCount??0)); assert.equal(b.searchEvidence?.backtrackEventsSample[0]?.kind,"RESOURCE_DECISION_UNDONE"); assert.equal(new Set(b.assignments.map(a=>a.taskId)).size,3); assert.deepEqual(b.assignments.find(a=>a.taskId===3)?.resourceIds,[202]); assert.deepEqual(b.assignments.find(a=>a.taskId===2)?.resourceIds,[201]); });

test("recursive search stops deterministically on exhausted budget with exact blocker",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30}]); const anchor={taskId:1,startPlanned:"10:00",endPlanned:"10:30",spaceId:1,resourceIds:[]}; const r=searchInitialConstructionClosureAssignments({input,originOperationalState:state,stage1:stage(1,[2]),closureTopologicalTaskIds:[2,1],anchorAssignment:anchor,branchWindow:{start:"09:00",end:"10:30"},reasoningBudget:{maxDepth:3,maxSearchSpaceSize:0,explorationBudget:1} as any}); assert.equal(r.ok,false); assert.equal(r.evidence.budgetExhausted,true); assert.deepEqual(r.evidence.backtrackEventsSample,[]); assert.deepEqual(r.blockers.map(b=>b.code),["ASSIGNMENT_SEARCH_BUDGET_EXHAUSTED"]); });

test("local rejected position completes without recursive backtracking evidence",()=>{ const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:00",fixedWindowEnd:"10:30"},{id:2,status:"pending",contestantId:1,spaceId:2,durationOverrideMin:30}]); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[2],[{start:"09:00",end:"10:30"}]),maxBranches:1}); assert.equal(r.branches[0].status,"candidate"); assert.equal(r.branches[0].searchEvidence?.recursiveBacktrackCount,0); assert.equal(r.branches[0].searchEvidence?.temporalDecisionBacktrackCount,0); assert.equal(r.branches[0].searchEvidence?.resourceDecisionBacktrackCount,0); assert.deepEqual(r.branches[0].searchEvidence?.backtrackEventsSample,[]); });

test("equivalent declarations produce same assignments, events, backtracks, and fingerprint",()=>{ const resources=[{id:201,resourceItemId:11,typeId:1,name:"R1",isAvailable:true}]; const tasks=[{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,fixedWindowStart:"10:30",fixedWindowEnd:"11:00"},{id:2,status:"pending",contestantId:2,spaceId:2,durationOverrideMin:30,resourceRequirements:{byItem:{11:1}}},{id:3,status:"pending",contestantId:3,spaceId:3,durationOverrideMin:30,resourceRequirements:{byItem:{11:1}}}]; const inputA=base(tasks,resources,{start:"09:00",end:"11:00"}); inputA.contestantAvailabilityById[3]={start:"10:00",end:"10:30"}; const inputB=base([tasks[2],tasks[0],tasks[1]],resources,{start:"09:00",end:"11:00"}); inputB.contestantAvailabilityById[3]={start:"10:00",end:"10:30"}; const a=buildInitialConstructionBranches({input:inputA,originOperationalState:state,stage1:stage(1,[3,2],[{start:"09:00",end:"11:00"}]),maxBranches:1}); const b=buildInitialConstructionBranches({input:inputB,originOperationalState:state,stage1:stage(1,[3,2],[{start:"09:00",end:"11:00"}]),maxBranches:1}); assert.deepEqual(a.branches[0].assignments,b.branches[0].assignments); assert.deepEqual(a.branches[0].searchEvidence?.backtrackEventsSample,b.branches[0].searchEvidence?.backtrackEventsSample); assert.equal(a.branches[0].searchEvidence?.recursiveBacktrackCount,b.branches[0].searchEvidence?.recursiveBacktrackCount); assert.equal(a.branches[0].searchEvidence?.assignmentSearchFingerprint,b.branches[0].searchEvidence?.assignmentSearchFingerprint); });

test("anchor resource alternatives are evaluated round-robin across temporal candidates",()=>{ const resources=[{id:201,resourceItemId:11,typeId:1,name:"R1",isAvailable:true},{id:202,resourceItemId:12,typeId:1,name:"R2",isAvailable:true}]; const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,resourceRequirements:{anyOf:[{resourceItemIds:[11,12],quantity:1}]}}],resources,{start:"09:00",end:"12:00"}); const r=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[],[{start:"09:00",end:"12:00"}]),maxBranches:4,reasoningBudget:{maxTemporalCandidatesPerAnchor:4,initialTemporalCandidateBatchSize:4,maxSearchSpaceSize:10} as any}); assert.ok(r.branches.length>=4); assert.deepEqual(r.branches.slice(0,4).map((b:any)=>[b.anchorPlacementEvidence?.candidateRankWithinWindow,b.anchorPlacementEvidence?.resourceAlternativeIds]),[[0,[[201]]],[1,[[201]]],[0,[[202]]],[1,[[202]]]]); });

test("branch identifiers and exploration fingerprint are independent of batch size",()=>{ const resources=[{id:201,resourceItemId:11,typeId:1,name:"R1",isAvailable:true}]; const input=base([{id:1,status:"pending",contestantId:1,spaceId:1,durationOverrideMin:30,resourceRequirements:{byItem:{11:1}}}],resources,{start:"09:00",end:"12:00"}); const a=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[],[{start:"09:00",end:"12:00"}]),maxBranches:2,reasoningBudget:{initialTemporalCandidateBatchSize:1,maxTemporalCandidatesPerAnchor:4,maxSearchSpaceSize:10} as any}); const b=buildInitialConstructionBranches({input,originOperationalState:state,stage1:stage(1,[],[{start:"09:00",end:"12:00"}]),maxBranches:2,reasoningBudget:{initialTemporalCandidateBatchSize:4,maxTemporalCandidatesPerAnchor:4,maxSearchSpaceSize:10} as any}); assert.equal(a.branches[0].branchId,b.branches[0].branchId); assert.equal((a.branches[0] as any).anchorPlacementEvidence?.temporalCandidateFingerprint,(b.branches[0] as any).anchorPlacementEvidence?.temporalCandidateFingerprint); });
