import type { Candidate, Evidence, OperationalState } from "../contracts";
import { classifyORCPlanningEntryOperationalRole, isORCProductiveRole } from "../state/nonWorkTaskClassifier";
import { configuredHardBreaks } from "../validation/protectedBreakScope";
import { ORC_MAIN_ZONE_RESOLUTION_CONTRACT_VERSION_ID228, resolveORCMainZoneTarget, type ORCMainZoneTargetResolution } from "../state/mainZoneTargetResolver";

export interface MainZoneGapResourceBlockSwapSummary {
  readonly executed: boolean; readonly generatedCandidateCount: number; readonly candidateIds: string[]; readonly selectedAsBest: boolean; readonly selectedAsCommit: boolean;
  readonly movedMainZoneTaskIds: number[]; readonly movedBlockingTaskIds: number[]; readonly sharedResourceIds: number[]; readonly gapMinutesBefore: number | null; readonly expectedGapMinutesAfter: number | null;
  readonly candidateStateCount: number; readonly simulatedStateCount: number; readonly validSimulationCount: number; readonly invalidSimulationCount: number; readonly prefilterDiscardReasons: Record<string, number>; readonly acceptedBeforePrefilter?: number; readonly discardedByPrefilter?: number; readonly prefilterDiscardDetails: ReadonlyArray<Record<string, unknown>>; readonly skippedReason: string | null; readonly candidateGenerationReason?: string | null; readonly candidateGenerationBlockers?: string[]; readonly readOnly: true;
}
export interface MainZoneContinuitySummary { readonly mainZoneConfigured: boolean; readonly mainZoneId: number | null; readonly mainZoneSource: string | null; readonly configured?: boolean; readonly rawMainZoneId?: number | null; readonly targetKind?: "space" | "zone" | "unknown"; readonly mainSpaceIds?: number[]; readonly mainZoneIds?: number[]; readonly dominantMainSpaceId?: number | null; readonly mainEntryCount?: number; readonly mainProductiveEntryCount?: number; readonly resolutionWarnings?: string[]; readonly mainZoneResolutionContractVersion?: "ORC-MAIN-ZONE-RESOLUTION-ID228"; readonly mainZoneGapCount: number; readonly largestMainZoneGapMinutes: number; readonly mainZoneGapCandidatesAvailable: boolean; readonly mainZoneContinuityContractVersion: "ORC-MAIN-ZONE-CONTINUITY-ID226"; readonly gaps: ReadonlyArray<Record<string, unknown>>; readonly readOnly: true; }
export interface MainZoneGapResourceBlockSwapResult { readonly candidates: Candidate[]; readonly evidence: Evidence[]; readonly summary: MainZoneGapResourceBlockSwapSummary; readonly mainZoneContinuity: MainZoneContinuitySummary; }
interface Opts { minGapMinutes?: number; maxMainZoneBlockTasks?: number; maxBlockingBlockTasks?: number; maxCandidatesPerGap?: number; maxCandidates?: number; blockToleranceMinutes?: number; }
type Entry = OperationalState["planning"][number] & { start: number; end: number; task: OperationalState["tasks"][number] | undefined; resources: number[] };
const DEF = { minGapMinutes: 10, maxMainZoneBlockTasks: 4, maxBlockingBlockTasks: 4, maxCandidatesPerGap: 3, maxCandidates: 6, blockToleranceMinutes: 5 };
const tm=(v:unknown)=>{ if(typeof v!=="string"||!/^[0-2]\d:[0-5]\d$/.test(v)) return null; const [h,m]=v.split(":").map(Number); return h<24?h*60+m:null; };
const tt=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const num=(v:unknown)=> typeof v==="number"&&Number.isFinite(v)?v: typeof v==="string"&&/^\d+$/.test(v)?Number(v):null;
const overlap=(a:number,b:number,c:number,d:number)=>a<d&&c<b;
function isMainEntry(e: Entry, rz: ORCMainZoneTargetResolution): boolean { const sp = e.spaceId ?? e.task?.spaceId ?? null; const ez = (e as any).zoneId ?? e.task?.zoneId ?? null; return (sp != null && rz.mainSpaceIds.includes(Number(sp))) || (ez != null && rz.mainZoneIds.includes(Number(ez))); }
function empty(reason:string|null, cont:MainZoneContinuitySummary): MainZoneGapResourceBlockSwapResult { return { candidates:[], evidence:[], mainZoneContinuity:cont, summary:{executed:reason!=="main_zone_not_configured", generatedCandidateCount:0, candidateIds:[], selectedAsBest:false, selectedAsCommit:false, movedMainZoneTaskIds:[], movedBlockingTaskIds:[], sharedResourceIds:[], gapMinutesBefore:null, expectedGapMinutesAfter:null, candidateStateCount:0, simulatedStateCount:0, validSimulationCount:0, invalidSimulationCount:0, prefilterDiscardReasons:{}, prefilterDiscardDetails:[], skippedReason:reason, candidateGenerationReason: reason, candidateGenerationBlockers: reason?[reason]:[], readOnly:true}}; }
function protectedTask(state:OperationalState,e:Entry){ return ["done","in_progress"].includes(String(e.task?.status??"")) || (state.locks??[]).some(l=>l.taskId===e.taskId && ["full","time","space","resource"].includes(String(l.lockType))); }
function entries(state:OperationalState): Entry[] { const tasks=new Map((state.tasks??[]).map(t=>[t.id,t])); return (state.planning??[]).flatMap((p):Entry[]=>{ const s=tm(p.startPlanned), e=tm(p.endPlanned); if(s==null||e==null||e<=s)return[]; const task=tasks.get(p.taskId); return [{...p,start:s,end:e,task,resources:[...(p.assignedResourceIds??task?.assignedResourceIds??[])].sort((a,b)=>a-b)}];}).sort((a,b)=>a.start-b.start||a.end-b.end||a.taskId-b.taskId); }
function crossesHardBreak(state:OperationalState,s:number,e:number){ return configuredHardBreaks(state).some(b=>{ const bs=tm(b.start), be=tm(b.end); return bs!=null&&be!=null&&overlap(s,e,bs,be); }); }
export function buildMainZoneGapResourceBlockSwapCandidates(state: OperationalState | null | undefined, createdAt: string | null = null, options: Opts = {}): MainZoneGapResourceBlockSwapResult {
  const opts={...DEF,...options}; const rz=state?resolveORCMainZoneTarget(state):resolveORCMainZoneTarget({}); let mainEntryCount=0, mainProductiveEntryCount=0; const baseCont=(gaps:ReadonlyArray<Record<string,unknown>>=[]):MainZoneContinuitySummary=>({mainZoneConfigured:rz.configured,mainZoneId:rz.rawMainZoneId,mainZoneSource:rz.source,configured:rz.configured,rawMainZoneId:rz.rawMainZoneId,targetKind:rz.targetKind,mainSpaceIds:[...rz.mainSpaceIds],mainZoneIds:[...rz.mainZoneIds],dominantMainSpaceId:rz.dominantMainSpaceId,mainEntryCount,mainProductiveEntryCount,resolutionWarnings:[...rz.warnings],mainZoneResolutionContractVersion:ORC_MAIN_ZONE_RESOLUTION_CONTRACT_VERSION_ID228,mainZoneGapCount:gaps.length,largestMainZoneGapMinutes:gaps.reduce((m,g)=>Math.max(m,Number(g.gapMinutes??0)),0),mainZoneGapCandidatesAvailable:false,mainZoneContinuityContractVersion:"ORC-MAIN-ZONE-CONTINUITY-ID226",gaps,readOnly:true}); if(!state) return empty("operational_state_unavailable", baseCont()); if(!rz.configured) return empty("main_zone_not_configured", baseCont());
  const all=entries(state); const mainCandidates=all.filter(e=> isMainEntry(e, rz)); mainEntryCount=mainCandidates.length; const main=mainCandidates.filter(e=> isORCProductiveRole(classifyORCPlanningEntryOperationalRole({entry:e,task:e.task,mealWindow:state.availability?.actualMeal??state.availability?.meal??state.availability?.mealWindow??null}))); mainProductiveEntryCount=main.length; if(mainCandidates.length===0) return empty("main_zone_configured_but_no_matching_entries", baseCont()); const gaps:any[]=[]; const candidates:Candidate[]=[]; const evidence:Evidence[]=[]; const reasons:Record<string,number>={}; const addReason=(r:string)=>{reasons[r]=(reasons[r]??0)+1;};
  for(let i=0;i<main.length-1;i++){ const prev=main[i], next=main[i+1]; const gm=next.start-prev.end; if(gm<opts.minGapMinutes||crossesHardBreak(state,prev.end,next.start)) continue; const blocking=all.filter(e=>!isMainEntry(e, rz) && overlap(prev.end,next.start,e.start,e.end)); const blockingResources=[...new Set(blocking.flatMap(b=>b.resources).filter(r=>next.resources.includes(r)))].sort((a,b)=>a-b); gaps.push({gapStart:tt(prev.end),gapEnd:tt(next.start),gapMinutes:gm,previousTaskId:prev.taskId,nextTaskId:next.taskId,mainZoneId:rz.rawMainZoneId,targetKind:rz.targetKind,mainSpaceIds:[...rz.mainSpaceIds],mainZoneIds:[...rz.mainZoneIds],blockingResources,candidateReason:blockingResources.length?"shared-resource-blocking-main-zone-gap":"no-shared-resource"}); if(candidates.length>=opts.maxCandidates) continue;
    const mainBlock:Entry[]=[next]; for(const e of main.slice(i+2)){ if(e.start-mainBlock[mainBlock.length-1].end>opts.blockToleranceMinutes) break; mainBlock.push(e); if(mainBlock.length>opts.maxMainZoneBlockTasks) break; }
    if(mainBlock.length>opts.maxMainZoneBlockTasks){addReason("main-zone-gap-swap-block-too-large"); continue;} const shared=[...new Set(blocking.flatMap(b=>b.resources).filter(r=>mainBlock.some(m=>m.resources.includes(r))))].sort((a,b)=>a-b); if(shared.length===0){addReason("main-zone-gap-swap-no-shared-resource"); continue;} const block=blocking.filter(b=>b.resources.some(r=>shared.includes(r))).sort((a,b)=>a.start-b.start||a.taskId-b.taskId); if(block.length===0){addReason("main-zone-gap-swap-no-shared-resource"); continue;} if(block.length>opts.maxBlockingBlockTasks){addReason("main-zone-gap-swap-block-too-large"); continue;} if([...mainBlock,...block].some(e=>protectedTask(state,e))){addReason("main-zone-gap-swap-protected-task"); continue;}
    const mainDur=mainBlock[mainBlock.length-1].end-mainBlock[0].start; const blockDur=block[block.length-1].end-block[0].start; const newMainStart=prev.end, newBlockStart=mainBlock[0].start; const newMainEnd=newMainStart+mainDur, newBlockEnd=newBlockStart+blockDur; const wd=state.workDay??state.availability?.workDay; const ds=tm(wd?.start)??0,de=tm(wd?.end)??1440; if(newMainEnd>next.start || newBlockEnd>de || newMainStart<ds || crossesHardBreak(state,newMainStart,newMainEnd)||crossesHardBreak(state,newBlockStart,newBlockEnd)){addReason(newBlockEnd>de?"main-zone-gap-swap-outside-workday":"main-zone-gap-swap-crosses-hard-break"); continue;}
    const assigns=[...mainBlock.map(e=>({e,delta:newMainStart-mainBlock[0].start})),...block.map(e=>({e,delta:newBlockStart-block[0].start}))].map(x=>({taskId:x.e.taskId,startPlanned:tt(x.e.start+x.delta),endPlanned:tt(x.e.end+x.delta),spaceId:x.e.spaceId??x.e.task?.spaceId??null,resourceIds:[...x.e.resources]})); const id=`orc-see:main-zone-gap-resource-block-swap:${rz.rawMainZoneId}:${prev.taskId}-${next.taskId}:${block.map(b=>b.taskId).join("-")}`; const ev=`evidence:${id}`; const movedMainZoneTaskIds=mainBlock.map(e=>e.taskId), movedBlockingTaskIds=block.map(e=>e.taskId);
    candidates.push({id,state:{status:"draft",reason:"Executable main-zone resource block swap candidate",evidenceIds:[ev],metadata:{readOnly:true}},assignments:assigns,operationalValues:[],evidenceIds:[ev],metadata:{strategy:"MAIN_ZONE_GAP_RESOURCE_BLOCK_SWAP",strategyId:"MAIN_ZONE_GAP_RESOURCE_BLOCK_SWAP",family:"main-zone-continuity",type:"resource-block-swap",strategyFamily:"main-zone-continuity",strategyType:"resource-block-swap",mainZoneId:rz.rawMainZoneId,rawMainZoneId:rz.rawMainZoneId,targetKind:rz.targetKind,mainSpaceIds:[...rz.mainSpaceIds],mainZoneIds:[...rz.mainZoneIds],dominantMainSpaceId:rz.dominantMainSpaceId,gapStart:tt(prev.end),gapEnd:tt(next.start),gapMinutesBefore:gm,expectedGapMinutesAfter:Math.max(0,next.start-newMainEnd),movedMainZoneTaskIds,movedBlockingTaskIds,sharedResourceIds:shared,blockingReason:"shared-resource-blocks-main-zone-gap",executesTransformations:true,planningInfluence:"candidate-transformations",readOnly:true,assignmentDetails:assigns.map((a,j)=>({taskId:a.taskId,fromStart:[...mainBlock,...block][j].startPlanned,fromEnd:[...mainBlock,...block][j].endPlanned,toStart:a.startPlanned,toEnd:a.endPlanned,assignedSpace:a.spaceId,assignedResources:a.resourceIds}))}}); evidence.push({id:ev,source:"orc-see",kind:"main-zone-gap-resource-block-swap-candidate-generated",subjectId:id,createdAt,data:{candidateId:id,mainZoneId:rz.rawMainZoneId,rawMainZoneId:rz.rawMainZoneId,targetKind:rz.targetKind,movedMainZoneTaskIds,movedBlockingTaskIds,sharedResourceIds:shared,readOnly:true,planningInfluence:"candidate-generation-diagnostics-only"}}); if(candidates.length>=opts.maxCandidatesPerGap) break;
  }
  const cont={...baseCont(gaps),mainZoneGapCandidatesAvailable:candidates.length>0}; const first=candidates[0]; return {candidates,evidence,mainZoneContinuity:cont,summary:{executed:true,generatedCandidateCount:candidates.length,candidateIds:candidates.map(c=>c.id),selectedAsBest:false,selectedAsCommit:false,movedMainZoneTaskIds:(first?.metadata.movedMainZoneTaskIds as number[])??[],movedBlockingTaskIds:(first?.metadata.movedBlockingTaskIds as number[])??[],sharedResourceIds:(first?.metadata.sharedResourceIds as number[])??[],gapMinutesBefore:(first?.metadata.gapMinutesBefore as number)??null,expectedGapMinutesAfter:(first?.metadata.expectedGapMinutesAfter as number)??null,candidateStateCount:0,simulatedStateCount:0,validSimulationCount:0,invalidSimulationCount:0,prefilterDiscardReasons:reasons,prefilterDiscardDetails:[],skippedReason:candidates.length?null:(gaps.length===0?"main_zone_has_no_relevant_gap":Object.keys(reasons)[0]?.replace("main-zone-gap-swap-no-shared-resource","main_zone_gap_has_no_shared_resource_blocker").replace("main-zone-gap-swap-block-too-large","main_zone_gap_block_too_large")??"main_zone_gap_candidate_rejected_by_prefilter"),candidateGenerationReason:candidates.length?"candidate_generated":(gaps.length===0?"main_zone_has_no_relevant_gap":Object.keys(reasons)[0]??null),candidateGenerationBlockers:Object.keys(reasons),readOnly:true}};
}
