import test from "node:test";
import assert from "node:assert/strict";
import { buildMainZoneGapResourceBlockSwapCandidates } from "./mainZoneGapResourceBlockSwapCandidateBuilder";
const st=(over:any={})=>({tasks:[{id:1,status:"pending",spaceId:48},{id:2,status:"pending",spaceId:48},{id:3,status:"pending",spaceId:7}],planning:[{taskId:1,startPlanned:"10:20",endPlanned:"11:20",spaceId:48,assignedResourceIds:[1]},{taskId:3,startPlanned:"11:20",endPlanned:"12:05",spaceId:7,assignedResourceIds:[336]},{taskId:2,startPlanned:"12:05",endPlanned:"12:45",spaceId:48,assignedResourceIds:[336]}],dependencies:[],locks:[],constraints:{optimizer:{mainZoneId:48}},availability:{workDay:{start:"09:00",end:"18:00"}},workDay:{start:"09:00",end:"18:00"},spaces:{exclusiveById:{48:true,7:true},capacityById:{},concurrencyById:{},parentById:{},nameById:{},priorityById:{},zoneIdBySpaceId:{48:1,7:2},spaceIdsByZoneId:{1:[48],2:[7]}},operationalMetrics:{},...over} as any);
test("generates candidate for a main-zone gap blocked by resource",()=>{const r=buildMainZoneGapResourceBlockSwapCandidates(st()); assert.equal(r.summary.generatedCandidateCount,1); const c=r.candidates[0]; assert.equal(c.metadata.strategy,"MAIN_ZONE_GAP_RESOURCE_BLOCK_SWAP"); assert.deepEqual(c.metadata.movedMainZoneTaskIds,[2]); assert.deepEqual(c.metadata.movedBlockingTaskIds,[3]); assert.deepEqual(c.metadata.sharedResourceIds,[336]); assert.equal(c.assignments.find(a=>a.taskId===2)?.startPlanned,"11:20"); assert.equal(c.assignments.find(a=>a.taskId===3)?.startPlanned,"12:05"); assert.equal(c.assignments.find(a=>a.taskId===2)?.spaceId,48); assert.deepEqual(c.assignments.find(a=>a.taskId===2)?.resourceIds,[336]);});
test("does not generate without mainZoneId",()=>{const r=buildMainZoneGapResourceBlockSwapCandidates(st({constraints:{optimizer:{}}})); assert.equal(r.summary.skippedReason,"main_zone_not_configured");});
test("does not generate when moved block is protected",()=>{const r=buildMainZoneGapResourceBlockSwapCandidates(st({tasks:[{id:1,status:"pending",spaceId:48},{id:2,status:"done",spaceId:48},{id:3,status:"pending",spaceId:7}]})); assert.equal(r.summary.generatedCandidateCount,0); assert.equal(r.summary.skippedReason,"main-zone-gap-swap-protected-task");});
test("does not generate without shared resource",()=>{const s=st(); s.planning[1].assignedResourceIds=[9]; const r=buildMainZoneGapResourceBlockSwapCandidates(s); assert.equal(r.summary.skippedReason,"main_zone_gap_has_no_shared_resource_blocker");});
test("enforces block size limit",()=>{const s=st(); for(let i=4;i<9;i++){s.tasks.push({id:i,status:"pending",spaceId:7}); s.planning.push({taskId:i,startPlanned:"11:25",endPlanned:"11:35",spaceId:7,assignedResourceIds:[336]});} const r=buildMainZoneGapResourceBlockSwapCandidates(s); assert.equal(r.summary.skippedReason,"main_zone_gap_block_too_large");});
test("does not cross explicit hard break",()=>{const s=st({availability:{workDay:{start:"09:00",end:"18:00"},globalHardBreaks:[{start:"11:30",end:"11:45",kind:"global",code:"HARD"}]}}); const r=buildMainZoneGapResourceBlockSwapCandidates(s); assert.equal(r.summary.generatedCandidateCount,0);});

test("detects V4-34-like gap by zone id and generates resource block swap",()=>{const s=st({tasks:[{id:504,status:"pending",spaceId:48,zoneId:1},{id:285,status:"pending",spaceId:48,zoneId:1},{id:295,status:"pending",spaceId:48,zoneId:1},{id:305,status:"pending",spaceId:48,zoneId:1},{id:376,status:"pending",spaceId:7,zoneId:2},{id:386,status:"pending",spaceId:7,zoneId:2},{id:396,status:"pending",spaceId:7,zoneId:2}],planning:[{taskId:504,startPlanned:"10:35",endPlanned:"11:20",spaceId:48,zoneId:1,assignedResourceIds:[1]},{taskId:376,startPlanned:"11:20",endPlanned:"11:35",spaceId:7,zoneId:2,assignedResourceIds:[336]},{taskId:386,startPlanned:"11:35",endPlanned:"11:50",spaceId:7,zoneId:2,assignedResourceIds:[336]},{taskId:396,startPlanned:"11:50",endPlanned:"12:05",spaceId:7,zoneId:2,assignedResourceIds:[336]},{taskId:285,startPlanned:"12:05",endPlanned:"12:20",spaceId:48,zoneId:1,assignedResourceIds:[336]},{taskId:295,startPlanned:"12:20",endPlanned:"12:35",spaceId:48,zoneId:1,assignedResourceIds:[336]},{taskId:305,startPlanned:"12:35",endPlanned:"12:50",spaceId:48,zoneId:1,assignedResourceIds:[336]}],constraints:{optimizer:{mainZoneId:1}}}); const r=buildMainZoneGapResourceBlockSwapCandidates(s); assert.equal(r.mainZoneContinuity.targetKind,"zone"); assert.ok(r.mainZoneContinuity.mainSpaceIds?.includes(48)); assert.ok(r.mainZoneContinuity.gaps.some((g:any)=>g.gapStart==="11:20"&&g.gapEnd==="12:05"&&g.previousTaskId===504&&g.nextTaskId===285&&g.gapMinutes===45)); assert.ok(r.summary.generatedCandidateCount>0); assert.equal(r.candidates[0].metadata.strategy,"MAIN_ZONE_GAP_RESOURCE_BLOCK_SWAP");});
